{
  "build": {
    "artifacts": {
      "expire_in": "4 weeks",
      "name": "reports",
      "paths": [
        "core/target/surefire-reports/",
        "export/target/surefire-reports/",
        "mw/OCTOPUS/core/target/surefire-reports/",
        "mw/OCTOPUS/ext-beans/target/surefire-reports/",
        "mw/tarentcommons/target/surefire-reports/",
        "shared/target/surefire-reports/",
        "vwor/target/surefire-reports/",
        "systemtest/target/failsafe-reports",
        "systemtest/target/geb-reports"
      ],
      "when": "on_failure"
    },
    "only": [
      "master@veraweb-int/veraweb"
    ],
    "script": [
      "xvfb-run mvn -B -Psystemtest clean verify"
    ],
    "stage": "build",
    "tags": [
      "veraweb"
    ]
  },
  "stages": [
    "test",
    "build"
  ],
  "test": {
    "artifacts": {
      "expire_in": "4 weeks",
      "name": "reports",
      "paths": [
        "core/target/surefire-reports/",
        "export/target/surefire-reports/",
        "mw/OCTOPUS/core/target/surefire-reports/",
        "mw/OCTOPUS/ext-beans/target/surefire-reports/",
        "mw/tarentcommons/target/surefire-reports/",
        "shared/target/surefire-reports/",
        "vwor/target/surefire-reports/",
        "systemtest/target/failsafe-reports",
        "systemtest/target/geb-reports"
      ],
      "when": "on_failure"
    },
    "except": [
      "master@veraweb-int/veraweb"
    ],
    "only": [
      "branches"
    ],
    "script": [
      "xvfb-run mvn -B -Psystemtest -Dsonar.host.url=https://ci-busyapps.lan.tarent.de/sonar/ -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME clean verify sonar:sonar"
    ],
    "stage": "test",
    "tags": [
      "veraweb"
    ]
  },
  "variables": {
    "MAVEN_OPTS": "-Xmx2048m -XX:+UseG1GC -XX:+UseCompressedOops"
  }
}
