 

select
    g.pk as g_pk,
    g.fk_person as g_fk_person,
    g.fk_event as g_fk_event,
    g.fk_category as g_fk_category,
    g.fk_color as g_fk_color,
    g.invitationtype as g_invitationtype,
    g.invitationstatus as g_invitationstatus,
    g.ishost as g_ishost,
    g.diplodate as g_diplodate,
    g.rank as g_rank,
    g.reserve as g_reserve,
    g.tableno as g_tableno,
    g.seatno as g_seatno,
    g.orderno as g_orderno,
    g.notehost as g_notehost,
    g.noteorga as g_noteorga,
    g.language as g_language,
    g.gender as g_gender,
    g.nationality as g_nationality,
    g.domestic_a as g_domestic_a,
    g.invitationstatus_p as g_invitationstatus_p,
    g.tableno_p as g_tableno_p,
    g.seatno_p as g_seatno_p,
    g.orderno_p as g_orderno_p,
    g.notehost_p as g_notehost_p,
    g.noteorga_p as g_noteorga_p,
    g.language_p as g_language_p,
    g.gender_p as g_gender_p,
    g.nationality_p as g_nationality_p,
    g.domestic_b as g_domestic_b,
    g.fk_color_p as g_fk_color_p,
    g.createdby as g_createdby,
    g.changedby as g_changedby,
    g.created as g_created,
    g.changed as g_changed,
    g.delegation as g_delegation,
    g.osiam_login as g_osiam_login,
    g.login_required_uuid as g_login_required_uuid,
    g.image_uuid as g_image_uuid,
    g.image_uuid_p as g_image_uuid_p,
    g.keywords as g_keywords,
    p.pk as p_pk,
    p.internal_id as p_internal_id,
    p.firstname_a_e1 as p_firstname_a_e1,
    p.lastname_a_e1 as p_lastname_a_e1,
    p.mail_a_e1 as p_mail_a_e1,
    -- ofdc.value as (select string_agg(label, ',') FROM (select * from veraweb.toptional_fields f where f.fk_event=1 group by f.pk order by f.pk) orif)
    string_agg(ofdc.value, ';') as g_optional_field_content
  from veraweb.tguest g
  inner join veraweb.tperson p on (g.fk_person = p.pk)
  left outer join veraweb.link_uuid l on l.personid = p.pk
  left join veraweb.toptional_fields_delegation_content ofdc on ofdc.fk_guest = g.pk
  where g.fk_event = 1
  group by g.pk, p.pk
  ;