#!/bin/sh
# DJB Daemontools startup script for VerA.web Online-Anmeldung

cd "$(dirname "$0")"
if test -d log && test -x log/run && test -d log/supervise; then
	echo restarting
	# for example with DJB daemontools:
	# #!/bin/sh
	# exec setuidgid vwoalog multilog t ./main
	# log/main/ is then 2770 vwoalog:adm
	exec 2>&1
else
	exec >&2
fi
mkdir -p /var/log/vwoa
chown vwoa:adm /var/log/vwoa
chmod 2770 /var/log/vwoa
#XXX TODO investigate why port reuse does not work without 3s sleep
sleep 2
date -u +'INFO  [%F %T,000] starting up VWOA' >>/var/log/vwoa/vwoa.log
chown vwoa:adm /var/log/vwoa/vwoa.log
chmod 0640 /var/log/vwoa/vwoa.log
date -u +'INFO  [%F %T,000] Note: log timestamps are in UTC!' >>/var/log/vwoa/vwoa.log
sleep 1
exec setuidgid vwoa java \
    -Dfile.encoding=UTF-8 -Djava.awt.headless=true \
    -Djava.security.egd=file:/dev/./urandom -Xmx128m \
    -jar vwoa.jar server config.jsn
