freeform::CKEditor 4.6.2 ok
javascript::Bacon 0.7.73 ok
javascript::WCH 3.10 (incompatible licence) FAIL
javascript::jquery 1.10.1 ok
javascript::jquery.form 3.51 ok
javascript::jquery.gotop ba42aef4cf38558d6585db21096592ed50b52a4c ok
javascript::jquery.multifile 2.2.0 ok
javascript::jquery.tagsinput 1.3.3 ok
javascript::jquery:sizzle 1.10.1 ok
javascript::unknown:clipboard 0 FAIL
javascript::unknown:dhtml 0 FAIL
javascript::unknown:utils 0 FAIL
javascript::unknown:vex 3.0.0 ok
javascript::unknown:vex-dialog 1.0.6 ok
sourceforge::jscalendar 2006-02-11T12:32:59Z ok
