% VerA.web (public) Installationsanleitungstextteil
%
% Copyright © 2015
%	Thorsten „mirabilos“ Glaser <t.glaser@tarent.de>
%
% Provided that these terms and disclaimer and all copyright notices
% are retained or reproduced in an accompanying document, permission
% is granted to deal in this work without restriction, including un‐
% limited rights to use, publicly perform, distribute, sell, modify,
% merge, give away, or sublicence.
%
% This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
% the utmost extent permitted by applicable law, neither express nor
% implied; without malicious intent or gross negligence. In no event
% may a licensor, author or contributor be held liable for indirect,
% direct, other damage, loss, or other issues arising in any way out
% of dealing in the work, even if advised of the possibility of such
% damage or existence of a defect, except proven that it results out
% of said person’s immediate fault when using the work as intended.
%-
% Textabschnitt 2.1: Systemvoraussetzungen VerA.web-core

\subsection{Interne Veranstaltungs- und Adreßverwaltung}\label{subsec:req-core}

Eine VM mit mindestens 512 MiB RAM und 512 MiB Swap wird empfohlen.
Als Betriebssystem legen wir Debian 7 „wheezy“ nahe; die Software
\emph{kann} jedoch auch mit einer anderen Debian-basierten Distribution
(z.B. Ubuntu 14.04 „trusty“) oder einer anderen Java/Tomcat-Umgebung
betrieben werden.
