#!/bin/sh
case $(locale charmap) in
(UTF-8) ;;
(*) LC_ALL=C.UTF-8; export LC_ALL ;;
esac
case $(locale charmap) in
(UTF-8) ;;
(*) echo >&2 "E: fix your locale!"; exit 1 ;;
esac
cd "$(dirname "$0")"
test -n "$1" || set -- *.resource
echo >&2 I: $# files to convert
perl -C -pi -e 's/\\u([0-9A-Fa-f]{4})/chr(hex($1))/eg' "$@"
printf >&2 '%s' 'I: all done, checking for specials…'
if x=$(grep -l '[-	-"&'\''<>\]' "$@"); then
	echo >&2
	echo >&2 "E: invalid characters found in:" $x
	echo >&2 "N: use ./find_invalid -v for details and fix them!"
	exit 1
fi
echo >&2 " done"
exit 0
