#!/bin/sh
case $(locale charmap) in
(UTF-8) ;;
(*) LC_ALL=C.UTF-8; export LC_ALL ;;
esac
case $(locale charmap) in
(UTF-8) ;;
(*) echo >&2 "E: fix your locale!"; exit 1 ;;
esac
cd "$(dirname "$0")"
test -n "$1" || set -- *.resource
echo >&2 I: $# files to convert
perl -C -pi -e 's/\\u([0-9A-Fa-f]{4})/chr(hex($1))/eg' "$@"
echo >&2 I: all done.
