#!/bin/sh
case $(locale charmap) in
(UTF-8) ;;
(*) LC_ALL=C.UTF-8; export LC_ALL ;;
esac
case $(locale charmap) in
(UTF-8) ;;
(*) echo >&2 "E: fix your locale!"; exit 1 ;;
esac
cd "$(dirname "$0")"
perl -C -pi -e 's/[^\n -~]/"\\u" . sprintf("%04X", ord($&))/eg' *.resource
