language=Espa\u00F1ol

# BROWSER TAB-TITLE
BROWSER_TITLE_CATEGORY=Categor\u00EDas
BROWSER_TITLE_CLEANUP=Limpiar
BROWSER_TITLE_COLOURS=Colores
BROWSER_TITLE_GENERAL_CONFIGS=Configuraci\u00F3n general
BROWSER_TITLE_TASKS=Tareas
BROWSER_TITLE_DOCUMENT_TYPES=Tipos de documento
BROWSER_TITLE_IMPORT_DUPLICATE_ACCEPT=Estado de la importaci\u00F3n - Importar duplicados
BROWSER_TITLE_ERROR_OCCURS=Ha ocurrido un error
BROWSER_TITLE_EVENT_EDIT=Editar evento
BROWSER_TITLE_EVENT_CREATE=Crear nuevo evento
BROWSER_TITLE_EVENT_SELECT=Seleccionar evento
BROWSER_TITLE_PERSON_ASSIGN=Asignar persona
BROWSER_TITLE_EVENT_SEARCH=Buscar evento
BROWSER_TITLE_TASKS_EDIT=Editar tarea
BROWSER_TITLE_TASKS_CREATE=Crear nueva tarea
BROWSER_TITLE_EXPORT_PERSONDATA=Exportar datos de personas
BROWSER_TITLE_IMPORT_PERSONDATA=Importar datos de personas
BROWSER_TITLE_EVENT_GUESTLIST=Lista de invitados al evento
BROWSER_TITLE_EVENT_EXPORT_DATA=Generar archivo de control
BROWSER_TITLE_IMPORT_STATUS=Estado del proceso de importaci\u00F3n
BROWSER_TITLE_HELP=Ayuda
BROWSER_TITLE_INFO_VERAWEB=Acerca de VerA.web
BROWSER_TITLE_EVENT_LOCATION_EDIT=Editar localizaci\u00F3n del evento
BROWSER_TITLE_EVENT_LOCATION_CREATE=Crear nueva localizaci\u00F3n para el evento
BROWSER_TITLE_EVENT_LOCATION=Localizaciones del evento
BROWSER_TITLE_EMAIL_SUBMISSION_CREATE=Crear nueva plantilla de correo electr\u00F3nico
BROWSER_TITLE_EMAIL_SUBMISSION_EDIT=Editar plantilla de correo electr\u00F3nico
BROWSER_TITLE_EMAIL_SUBMISSION=Plantillas de correo electr\u00F3nico
BROWSER_TITLE_DISTRIBUTOR_CREATE=Crear distribuidor
BROWSER_TITLE_DISTRIBUTOR_LIST=Lista de distribuidores
BROWSER_TITLE_EMAIL_WRITE_DISTRIBUTOR=Escribir E-mail a distribuidor
BROWSER_TITLE_EMAIL_EDIT=Editar E-mail
BROWSER_TITLE_EMAIL_CREATE=Redactar E-mail
BROWSER_TITLE_EMAIL_OUTBOX=Bandeja de salida
BROWSER_TITLE_ROLE_WITH=con el rol
BROWSER_TITLE_ROLE_AVAILABLE=con el rol disponible
BROWSER_TITLE_ROLE_WITHOUT_INFO=ohne Rolleninformationen   *********************************
BROWSER_TITLE_SUCCESSFUL_LOGIN_ONE=Acceso satisfactorio
BROWSER_TITLE_SUCCESSFUL_LOGIN_TWO=al identificarse en el sistema
BROWSER_TITLE_PERSON_EDIT=Editar persona
BROWSER_TITLE_PERSON_CREATE=Crear nueva persona
BROWSER_TITLE_GUEST_ADD_EVENT=A\u00F1adir invitado al
BROWSER_TITLE_GUEST_HOST_ADD_EVENT=Seleccionar anfitri\u00F3n para
BROWSER_TITLE_GUEST_SELECT=Seleccionar invitado
BROWSER_TITLE_GUEST_HOST_SELECT=Seleccionar anfitri\u00F3n
BROWSER_TITLE_SEARCH_REPLACE_PERSONDATA=Buscar y reemplazar persona
BROWSER_TITLE_DUPLICATE_SEARCH=B\u00FAsqueda de duplicados
BROWSER_TITLE_TASK_ADD_RESPONSIBLE=Seleccionar responsable de la tarea
BROWSER_TITLE_PERSON_DELETE=Eliminar persona
BROWSER_TITLE_PERSON_LIST=Lista de personas
BROWSER_TITLE_SEARCH_REPLACE=Buscar y reemplazar
BROWSER_TITLE_GUEST_HOST_SEARCH=Buscar anfitri\u00F3n
BROWSER_TITLE_PERSON_SEARCH=Buscar persona
BROWSER_TITLE_PERSON_DATA_SALUTATION=Datos maestros - Denominaci\u00F3n
BROWSER_TITLE_LOGIN_REPRESENTATIVE=Acceder como representante
BROWSER_TITLE_STATISTIC_CREATE=Generar estad\u00EDsticas
BROWSER_TITLE_USER_CONFIGS=Configuraci\u00F3n de usuario
BROWSER_TITLE_WORK_AREAS=\u00C1reas de trabajo
BROWSER_TITLE_OVERVIEW_EVENTS_YEAR=Resumen del n\u00FAmero de eventos anual
BROWSER_TITLE_OVERVIEW_EVENTS_MONTH=Resumen del n\u00FAmero de eventos mensual
BROWSER_TITLE_OVERVIEW_GUEST_HOST_EVENTS=Resumen de eventos por anfitri\u00F3n
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST_HOST=Resumen de eventos, agrupados por anfitri\u00F3n
BROWSER_TITLE_OVERVIEW_GUEST_EVENTS=Resumen de eventos por invitado
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST=Resumen de eventos, agrupados por invitados
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_PLACE=Resumen de eventos por localizaci\u00F3n
BROWSER_TITLE_OVERVIEW_EVENTS_UNKNOWN_STATISTIC=ESTAD\u00CDSTICA DESCONOCIDA

# YOU MUST SET THESE PLACEHOLDERS WITH THE GENDER TYPE OF YOUR LANGUAGE FOR EACH OBJECT AS MALE OR FEMALE
GENDER_TYPE_CATEGORY=Mujer
GENDER_TYPE_CLIENT=Hombre
GENDER_TYPE_COLOR=Mujer
GENDER_TYPE_DELEGATION_FIELD=Mujer
GENDER_TYPE_DISTRIBUTOR=Hombre
GENDER_TYPE_DOCUMENT_TYPE=Hombre
GENDER_TYPE_EMAIL=Mujer
GENDER_TYPE_EVENT=Mujer
GENDER_TYPE_EVENT_LOCATION=Hombre
GENDER_TYPE_FUNCTION_OFFICIAL_TITLE=Mujer
GENDER_TYPE_GUEST=Hombre
GENDER_TYPE_MAIL_DRAFT=Mujer
GENDER_TYPE_PERSON=Mujer
GENDER_TYPE_REPRESENTATIVE=Mujer
GENDER_TYPE_SALUTATION=Mujer
GENDER_TYPE_TASK=Mujer
GENDER_TYPE_USER=Hombre
GENDER_TYPE_WORKAREA=Hombre

# REPETITIVE OBJECTS IN THER SINGULAR- AND PLURAL-TYPE
GENERIC_ADDRESS_DATA_PLURAL=Datos de la direcci\u00F3n
GENERIC_CATEGORY_SINGULAR=Categor\u00EDa
GENERIC_CATEGORY_PLURAL=Categor\u00EDas
GENERIC_CLIENT_SINGULAR=Mandante
GENERIC_CLIENT_PLURAL=Mandantes
GENERIC_COLOR_SINGULAR=Color
GENERIC_COLOR_PLURAL=Colores
GENERIC_COMPANY_SINGULAR=Empresa
GENERIC_COMPANY_PLURAL=Empresas
GENERIC_DELEGATION_FIELD_SINGULAR=Campo adicional
GENERIC_DELEGATION_FIELD_PLURAL=Campos adicionales
GENERIC_DISTRIBUTOR_SINGULAR=Distribuidor
GENERIC_DISTRIBUTOR_PLURAL=Distribuidores
GENERIC_DOCUMENT_TYPE_SINGULAR=Tipo de documento
GENERIC_DOCUMENT_TYPE_PLURAL=Tipos de documento
GENERIC_EMAIL_SINGULAR=E-Mail
GENERIC_EMAIL_PLURAL=E-Mails
GENERIC_EVENT_SINGULAR=Evento
GENERIC_EVENT_PLURAL=Eventos
GENERIC_EVENT_LOCATION_SINGULAR=Localizaci\u00F3n del evento
GENERIC_EVENT_LOCATION_PLURAL=Localizaciones del evento
GENERIC_FUNCTION_SINGULAR=Funci\u00F3n
GENERIC_FUNCTION_PLURAL=Funciones
GENERIC_GUEST_SINGULAR=Invitado
GENERIC_GUEST_PLURAL=Invitados
GENERIC_INSTITUTION_SINGULAR=Instituci\u00F3n
GENERIC_INSTITUTION_PLURAL=Instituciones
GENERIC_MAIL_DRAFT_SINGULAR=Presentaci\u00F3n
GENERIC_MAIL_DRAFT_PLURAL=Presentaciones
GENERIC_OFFICIAL_TITLE_SINGULAR=T\u00EDtulo
GENERIC_OFFICIAL_TITLE_PLURAL=T\u00EDtulos
GENERIC_PERSON_SINGULAR=Persona
GENERIC_PERSON_PLURAL=Personas
GENERIC_REPRESENTATIVE_SINGULAR=Representante
GENERIC_REPRESENTATIVE_PLURAL=Representantes
GENERIC_SALUTATION_SINGULAR=Denominaci\u00F3n
GENERIC_SALUTATION_PLURAL=Denominaciones
GENERIC_STATUS_OPEN=Abierto
GENERIC_STATUS_ACCEPT=Confirmado
GENERIC_STATUS_DECLINE=Rechazado
GENERIC_STATUS_PARTICIPATED=Participante
GENERIC_TASK_SINGULAR=Tarea
GENERIC_TASK_PLURAL=Tareas
GENERIC_USER_SINGULAR=Usuario
GENERIC_USER_PLURAL=Usuarios
GENERIC_WORKAREA_SINGULAR=\u00C1rea de trabajo
GENERIC_WORKAREA_PLURAL=\u00C1reas de trabajo

# HEADER MESSAGES
HEADER_REPRESENTATION_FOR=En representaci\u00F3n de
HEADER_COUNT_INSERT_ZERO_PART_ONE=Se ha
HEADER_COUNT_INSERT_ONE_PART_ONE=Se ha
HEADER_COUNT_INSERT_ELSE_PART_ONE=Se han
HEADER_COUNT_INSERT_ZERO_PART_TWO=creado
HEADER_COUNT_INSERT_ONE_PART_TWO=creado
HEADER_COUNT_INSERT_ELSE_PART_TWO=creado
HEADER_COUNT_REMOVE_ZERO_PART_ONE=Se ha
HEADER_COUNT_REMOVE_ONE_PART_ONE=Se ha
HEADER_COUNT_REMOVE_ELSE_PART_ONE=Se han
HEADER_COUNT_REMOVE_ZERO_PART_TWO=eliminado
HEADER_COUNT_REMOVE_ONE_PART_TWO=eliminado
HEADER_COUNT_REMOVE_ELSE_PART_TWO=eliminado
HEADER_COUNT_UPDATE_ZERO_PART_ONE=Se ha
HEADER_COUNT_UPDATE_ONE_PART_ONE =Se ha
HEADER_COUNT_UPDATE_ELSE_PART_ONE=Se han
HEADER_COUNT_UPDATE_ZERO_PART_TWO=modificado
HEADER_COUNT_UPDATE_ONE_PART_TWO=modificado
HEADER_COUNT_UPDATE_ELSE_PART_TWO=modificado
HEADER_ELEMENT_FEMALE_NO=ninguna
HEADER_ELEMENT_FEMALE_ONE=una
HEADER_ELEMENT_FEMALE_NEW=nueva
HEADER_ELEMENT_MALE_NO=ning\u00FAn
HEADER_ELEMENT_MALE_ONE=un
HEADER_ELEMENT_MALE_NEW=nuevo
HEADER_ELEMENT_NO_RECORD_SINGULAR=ning\u00FAn registro
HEADER_ELEMENT_NO_NEW_RECORD_SINGULAR=ning\u00FAn nuevo registro
HEADER_ELEMENT_ONE_RECORD_SINGULAR=un registro
HEADER_ELEMENT_ONE_NEW_RECORD_SINGULAR=un nuevo registro
HEADER_ELEMENT_PLURAL=Registros
HEADER_ELEMENT_NEW_PLURAL=nuevos registros

# FIXES
GENERIC_EDIT=Editar
GENERIC_OFFICIAL_TITLE_SHORT=T\u00EDtulo
LETTER_COMMERCIAL=(G)
GENERIC_WRITE_EMAIL=Redactar E-mail
GENERIC_SEARCH_FOR_PERSON=Buscar persona
GENERIC_CHOOSE_ROLE=Seleccionar rol
GENERIC_EVENT=Evento
GENERIC_EVENTS=Eventos
SHOW_ALL_RECORDS=Mostrar todos los registros
SHOW_RECORDS=Mostrar registros

# GENERALLY USED
GENERIC_EMAIL_ADDRESS=Direcci\u00F3n de correo electr\u00F3nico
GENERIC_FROM=De
GENERIC_LANGUAGE=Idioma
GENERIC_LOGOUT=Cerrar sesi\u00F3n
GENERIC_ON=En
GENERIC_PAGE=P\u00E1gina
GENERIC_PLACE=plaza

# MENU
MENU_PERSONS=Personas
MENU_EVENTS=Eventos
MENU_MANAGEMENT=Gesti\u00F3n
MENU_ADMINISTRATION=Administraci\u00F3n

# ANMELDUNG
LOGIN_ERROR=El nombre de usuario y contrase\u00F1a son incorrectos. Por favor, vuelva a introducir los datos de acceso.
GENERIC_PASSWORD=Contrase\u00F1a
LOGIN_REPRESENTATION=Acceder como representante
GENERIC_LOGIN=Acceder
GENERIC_CLEAR_FIELDS=Reiniciar
HINT_LOGIN_ORGANISATION_ONE=Por favor, utilice el nombre de su organizaci\u00F3n o
HINT_LOGIN_ORGANISATION_TWO=nombre.apellido
HINT_LOGIN_ORGANISATION_THREE=como nombre de usuario

# WELCOME SITE: FIRST PAGE AFTER LOGIN
administration=Administraci\u00F3n
bittewaehlensieeineamtsbezeichnungfunktionaus=Por favor, seleccione una funci\u00F3n/t\u00EDtulo
eskannzuunerwartetenfehlernkommenbittewendensiesichanihrenadministrator=Pueden ocurrir errores inesperados. Por favor, contacte con su administrador.
willkommenbeiveraweb=Bienvenido a VerA.web
WELCOME_TEXT_GRANT_READ_STANDARD_FIELDS=Usted tiene la posibilidad de visualizar y exportar los datos maestros de personas y eventos.
WELCOME_TEXT_GRANT_READ_REMARK_FIELDS=Usted tiene la posibilidad de visualizar y exportar los datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_EXPORT_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar la informaci\u00F3n
WELCOME_TEXT_GRANT_WRITE_FULL=y observaciones
WELCOME_TEXT_GRANT_EXPORT_PART_TWO=de personas y eventos.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_TWO=Tambi\u00E9n puede visualizar y editar la configuraci\u00F3n del mandante.
WELCOME_TEXT_GRANT_ADMIN_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar los datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_ADMIN_PART_TWO=Tambi\u00E9n puede visualizar y editar la configuraci\u00F3n global y por mandante.
WELCOME_TEXT_HELP=Si necesita m\u00C3\u00A1s informaci\u00C3\u00B3n, por favor visite la p\u00C3\u00A1gina \u00E2\u0080\u009EAyuda\u00E2\u0080\u009C.
WELCOME_TEXT_NO_ROLE=Su acceso no dispone de rol para utilizar VerA.web. Por favor, cierre su sesi\u00F3n y vuelva a intentarlo con una cuenta de usuario habilitada en VerA.web.
GENERIC_AVAILABLE_DUPLICATES=Duplicados existentes

# ADMINISTRATION/ANREDEN
GENERIC_SALUTATIONS=Denominaciones
GENERIC_SALUTATIONS_MARKED=Denominaciones seleccionadas
GENERIC_ID=ID
GENERIC_MAIN_FORM=Descripci\u00F3n
GENERIC_GENDER=G\u00E9nero
GENERIC_GENDER_FEMALE=Mujer
GENERIC_GENDER_MALE=Hombre
GENERIC_PAGING=Punto de entrada directa
MESSAGE_SUCCESS_INSERT_SALUTATION=Denominaci\u00F3n creada satisfactoriamente
QUESTION_DELETE=\u00BFRealmente desea eliminar su selecci\u00F3n?
GENERIC_NEW_PLURAL=nuevas
GENERIC_YES=S\u00ED
GENERIC_NO=No
MESSAGE_SUCCESS_DELETE_SALUTATION=Denominaci\u00F3n eliminada satisfactoriamente
MESSAGE_EXIST_MASTER_DATA_ENTRY=Ya existe una denominaci\u00F3n con el nombre
GENERIC_NAME=Nombre
GENERIC_NEW=Nueva

# ADMINISTRATION/ARBEITSBEREICHE
GENERIC_WORK_FIELDS=\u00C1reas de trabajo
GENERIC_WORK_FIELDS_MARKED=\u00C1rea(s) de trabajo seleccionada(s)
MESSAGE_MISSING_DATA=No se han encontrado datos
MESSAGE_INSERT_WORK_FIELD=Nuevo \u00E1rea de trabajo creado satisfactoriamente
MESSAGE_FAIL_DELETE_WORK_FIELD=No se ha eliminado ning\u00FAn \u00E1rea de trabajo
MESSAGE_SUCCESS_DELETE_WORK_FIELD=Se ha eliminado un \u00E1rea de trabajo

# ADMINISTRATION/BENUTZER
GENERIC_USER=Usuario
GENERIC_USER_MARKED=Usuario(s) seleccionado(s)
GENERIC_USERNAME=Nombre de usuario
GENERIC_USER_RIGHTS=Permisos de usuario
MESSAGE_SUCCESS_INSERT_USER=Se ha creado un nuevo usuario
MESSAGE_SUCCESS_DELETE_USER=Se ha eliminado un usuario
MESSAGE_FILL_USER_ROLE=Debe introducir una descripci\u00F3n para el rol de usuario

# ADMINISTRATION/DOKUMENTTYPEN
GENERIC_TOOLTIP=Aviso
HINT_FORMAT_INFO=OOo 1.1 para OpenOffice 1.1 (Archivo-sxc) y OOo 2.0 para OpenOffice 2.0 (Archivo-ods), xls para Microsoft Office: los signos distintivos 50 y 99 ser\u00E1n autom\u00E1ticamente aderidos a un nuevo evento. En caso del signo 50 no habr\u00E1 posibilidad de texto libre.(Archivo-xls) y CSV para Archivo-CSV.
HINT_EVENT_MARK=Los signos distintivos 50 y 99 ser\u00E1n autom\u00E1ticamente aderidos a un nuevo evento. En caso del signo 50 no habr\u00E1 posibilidad de texto libre.
GENERIC_DOCUMENT_TYPES_MARKED=Tipo(s) de documento seleccionado(s)
GENERIC_LABELLING=Descripci\u00F3n
GENERIC_ADRESS_TYPE=Tipo de direcci\u00F3n
GENERIC_CHARSET=Conjunto de caracteres
GENERIC_FORMAT=Formato
GENERIC_PARTNER_DOCUMENT=Documento para partner
GENERIC_SORT=Selecc.
GENERIC_SIGN=Signo
GENERIC_GA=GA
GENERIC_SD=SD
GENERIC_BUSINESS=Negocio
GENERIC_PRIVATE=Privado
GENERIC_MORE=Adicionales
GENERIC_LATIN=Lat\u00EDn
kyrillisch=Cir\u00EDlico
chinesisch=Chino
eswurdeeindokumenttypgeloscht=Se ha eliminado un tipo de documento.
eswurdeeinneuerdokumenttypangelegt=Nuevo tipo de documento creado satisfactoriamente.

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Estado
GENERIC_TO=Para
GENERIC_SUBJECT=Asunto
GENERIC_ERROR=Error
e-mails=E-Mails
GENERIC_BLEND_IN_TECHNICAL_ERROR_MESSAGE=Combinar error t\u00E9cnicoTechnische Fehlermeldung einblenden
GENERIC_ERROR_DESCRIPTION=Descripci\u00F3n del error

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=Plantillas de correo electr\u00F3nico
GENERIC_MARKED_TEMPLATES_PP=Plantilla(s) seleccionada(s)
GENERIC_INSERT_NEW_TEMPLATES=Crear nueva plantilla
GENERIC_TEMPLATE_NAME=Nombre de la plantilla
eswurdeeineneuevorlageangelegt=Nueva plantilla creada satisfactoriamente.
GENERIC_TEXT=Texto
GENERIC_PLACEHOLDER=Identificador
GENERIC_ADD=A\u00F1adir
GENERIC_BACK_TO_TEMPLATES_LIST=Volver al listado de plantillas

# ADMINISTRATION/FARBEN
GENERIC_COLOR_PLURAL=Colores
GENERIC_CHROMATICITY=Cromaticidad
LETTERS_CHROMATICITY=R G B

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=Denominaciones seleccionadas
GENERIC_LABELLING=Denominaci\u00F3n
eswurdeeineneuefunktion/amtsbezeichnungangelegt=Se ha creado una nueva funci\u00F3n/denominaci\u00F3n.
eswurdeeinefunktion/amtsbezeichnunggeloscht=Se ha eliminado una funci\u00F3n/denominaci\u00F3n.

# ADMINISTRATION/KATEGORIEN
GENERIC_CATEGORY_PLURAL=Categor\u00EDas
markiertekategorie=Categor\u00EDa(s) seleccionada(s)
GENERIC_MARK_LONG=Clase
GENERIC_RANK=Rango
GENERIC_EVENTS_PP=Evento(s)
GENERIC_CATEGORY_SINGULAR=Categor\u00EDa
GENERIC_OCCASION=Suceso

# ADMINISTRATION/MANDANTEN
GENERIC_CLIENT_PLURAL=Mandantes
markierte(n)mandanten=Mandante(s) seleccionado(s)
GENERIC_DATA_NOT_ASSIGNED_TO_CLIENTS=Datos de mandantes no asociados
personen=Personas
GENERIC_IMPORT_PROCEDURES=Importar procesos
veranstaltungorte=Localizaci\u00F3n del evento
GENERIC_IMPORT_PERSONS=Importar personas
GENERIC_DISTRIBUTOR_SINGULAR=Distribuidor
GENERIC_USER=Usuario
GENERIC_ASSIGN_CLIENTS=Asignar mandantes
GENERIC_CLIENT_SINGULAR=Mandante

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=Configuraci\u00F3n del sistema
GENERIC_STANDARD_TABULATOR_CHOICE=Elecci\u00F3n est\u00E1ndar mediante tabulaciones
GENERIC_MAIN_TABS=Pesta\u00F1as principales
GENERIC_PERSONS_DATA=Datos de personas
GENERIC_MAILING_ADDRESSES=Direcciones
GENERIC_SUBTABS_OF_PERSONS_DATA=Subpesta\u00F1as de \u00E2\u0080\u009EDatos de personas\u00E2\u0080\u009C
GENERIC_MAIN_PERSON=Persona principal
GENERIC_PARTNER=Partner
GENERIC_SUBTABS_OF_MAILING_ADDRESSES=Subpesta\u00F1as de \u00E2\u0080\u009EDirecciones\u00E2\u0080\u009C
GENERIC_BUSINESS=Negocio
GENERIC_STANDARD_CHOICE_OF_SELECTED_BOX=Elecci\u00F3n est\u00E1ndar sobre el selector de \u00E2\u0080\u009Echarset\u00E2\u0080\u009C
GENERIC_CHARSET=Conjunto de caracteres
GENERIC_STANDARD_SALUTATIONS_AND_FREE_TEXT_FIELDS=Denominaciones est\u00E1ndar y campos de texto libre
GENERIC_STANDARD_SALUTATION=Denominaci\u00F3n est\u00E1ndar
GENERIC_STANDARD_SALUTATION_PARTNER=Demoninaci\u00F3n est\u00E1ndar del partner
GENERIC_FREE_TEXT_FIELD=Campo de texto libre
GENERIC_FREE_TEXT_FIELDS=Campos de texto libre
GENERIC_FREE_TEXT_FIELD_CONNECTOR=Conexi\u00F3n de campo de texto libre
GENERIC_SHOW=Visualizaci\u00F3n
GENERIC_HELP=Ayuda
GENERIC_HELP_LINK=Enlace de ayuda
GENERIC_HELP_WINDOW=Ventana de ayuda
OPTION_HELP_WINDOW_1=Utilizar ventana de ayuda actual
OPTION_HELP_WINDOW_2=Abrir una nueva ventana navegador por llamada
OPTION_HELP_WINDOW_3=La misma ventana de ayuda por llamada (no la actual)
GENERIC_MISCELLANEOUS=Otros
GENERIC_FAX_CONFIG_FIELD=Fax-DN (@fax.aa)
GENERIC_PROTOCOL_TIME_CHANGE=Historial de cambios
GENERIC_PROTOCOL_COMMISIONING_TIME=Intervalo del registro de datos
HINT_GIVE_THE_RETENTION_PERIOD=Indique el per\u00EDodo de retenci\u00F3n
GENERIC_YEARS=A\u00F1os
GENERIC_MONTHS=Meses
GENERIC_DAYS=D\u00EDas
GENERIC_MAILING_ADDRESS_BUSINESS=Direcci\u00F3n de trabajo
GENERIC_MAILING_ADDRESS_PRIVATE=Direcci\u00F3n privada
GENERIC_MAILING_ADDRESS_OTHERS=Otras direcciones
GENERIC_LABELLING_LATIN=Conjunto de caracteres latinos
GENERIC_LABELLING_ALTERNATIVE=Conjunto de caracteres alternativo
GENERIC_ADDRESS_ADDITIONAL=Direcci\u00F3n adicional

# ADMINISTRATION/REPORTS
GENERIC_REPORTS=Res\u00FAmenes
MESSAGE_WAITING_MESSAGE_LOG_REPORT=Dependiendo del per\u00EDodo de tiempo seleccionado y la cantidad de datos, la generaci\u00F3n del informe puede tardar m\u00E1s tiempo de lo normal. Por favor, mantenga la paciencia hasta el final del proceso.
GENERIC_DATE_BEGIN=Fecha de inicio
GENERIC_DATE_END=Fecha de fin
GENERIC_BACKUP_FIEDS=Reiniciar campos
GENERIC_GENERATE_REPORT=Generar resumen

# ADMINISTRATION/STELLVERTRETUNGEN
GENERIC_REPRESENTATIVES=Delegados
GENERIC_AVAILABILITY_FILTER=Filtro de disponibilidad
GENERIC_REPRESENTATIVES_ALL=Todos los delegados
GENERIC_NO_REPRESENTATION_EXPIRED=Ninguna representaci\u00F3n pasada
GENERIC_ONLY_CURRENT_REPRESENTATIONS=S\u00F3lo representaciones actuales
GENERIC_ROLE=Rol
GENERIC_REPRESENTATIVE=Representante
gultigab=Disponible a partir de
GENERIC_VALID_TILL=Disponible hasta
GENERIC_NO_DATA_FOUND=No se han encontrado datos

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Localizaciones de eventos seleccionadas
GENERIC_ADD_NEW_EVENT_LOCATIONS=Crear nueva localizaci\u00F3n para evento
GENERIC_ID=ID
GENERIC_CONTACT_PERSON=Persona de contacto
GENERIC_TELEFON=Tel\u00E9fono
GENERIC_FAX=Fax
e-mail=E-Mail
GENERIC_REMARK=Observaciones
GENERIC_URL=Enlace
gps-daten=Datos de localizaci\u00F3n (GPS)
GENERIC_ROOM_NUMBER=N\u00FAmero de sala
EVENT_PLACES_CONFIRM_DELETE=Por favor, confirme la eliminaci\u00F3n de las localizaciones del evento

# VERWALTUNG/EINSTELLUNGEN
GENERIC_MANAGEMENT=Gesti\u00F3n
GENERIC_OPTIONS=Ajustes
GENERIC_SUBTABS_OF=Subpesta\u00F1as de
GENERIC_PERSONAL_DETAILED_VIEW=Vista detalle de personas
GENERIC_LIST_OF_GUESTS=Lista de invitados
zusatzlichefelder=Campos adicionales
GENERIC_FUNCTION_SINGULAR=Funci\u00F3n
GENERIC_POSTNUMBER_AND_CITY=C\u00F3digo postal / Ciudad
GENERIC_LIST_OF_PERSONS=Lista de personas
GENERIC_FEDERAL_STATE=Provincia
MESSAGE_OPTIONS_WERE_SUCCESSFULLY_SAVED=La configuraci\u00F3n se ha guardado satisfactoriamente.

# VERWALTUNG/VERTRETUNGEN
GENERIC_REPRESENTATIVE_PLURAL=Representaciones
markiertevertretung=Representaciones seleccionadas
GENERIC_DELETE=Eliminar
GENERIC_NEW=Nuevo
eswurdeeineneuevertretungangelegt=Se ha creado una nueva representaci\u00F3n
eswurdeeinevertretunggeloscht=Se ha eliminado una representaci\u00F3n
siemuseneinevertretereingeben=Debe seleccionar un representante
derbeginndervertretungmusvordemendeliegen=La fecha de inicio debe ser anterior a la fecha final
MESSAGE_REPORT_NUMBER_PART_1=Se han eliminado
vertretungengeloscht=representaciones
# VERWALTUNG/INFO
GENERIC_INFO=Informaci\u00F3n
GENERIC_INFORMATION_ABOUT_VERAWEB=Acerca de VerA.web
veraweb=VerA.web
GENERIC_VERSION=Versi\u00F3n
build=Compilaci\u00F3n
GENERIC_BUILD_NUMBER=N\u00FAmero de compilaci\u00F3n
GENERIC_BUILD_TIME=Tiempo de compilaci\u00F3n
GENERIC_DATABASE=Base de datos
GENERIC_LOGIN=Login
GENERIC_GROUPS=Grupos
GENERIC_NOT_AVAILABLE=No disponible

# ALLGEMEIN
GENERIC_YOU_ARE_HERE=Usted se encuentra aqu\u00ED
GENERIC_HOME=Inicio

# TABELLEN
GENERIC_DATE=Fecha
GENERIC_WORKAREA_SINGULAR=\u00C1rea de trabajo
GENERIC_LASTNAME=Apellido
GENERIC_FIRSTNAME=Nombre
akwritemtsbezeichnung=T\u00EDtulo
GENERIC_COMPANY_INSTITUTION=Empresa / Instituci\u00F3n
GENERIC_STREET=Calle
GENERIC_POST_NUMBER=C\u00F3digo postal
GENERIC_CITY=Ciudad
GENERIC_MARKED_PERSONS_PP=Persona(s) seleccionada(s)
expotieren=Exportar
GENERIC_ASSIGN_CATEGORIES=Asignar categor\u00EDas
GENERIC_REMOVE_CATEGORIES=Eliminar categor\u00EDas
GENERIC_ASSING_WORKAREA=Asignar \u00E1reas de trabajo
GENERIC_REMOVE_WORKAREA=Eliminar \u00E1reas de trabajo
GENERIC_EXECUTE=Aplicar
personenanzahlproseite=Personas | Personen | Total por p\u00E1gina
GENERIC_ALL=Todas
seite=P\u00E1gina
GENERIC_PAGE=Fecha de nacimiento
GENERIC_PLACE_OF_BIRTH=Lugar de nacimiento
GENERIC_NATIONALITY=Nacionalidad
GENERIC_CITIZENSHIP=Ciudadan\u00EDa
GENERIC_LANGUAGES=Idiomas
GENERIC_HINT_FOR_HOST=Aviso para el anfitri\u00F3n
GENERIC_ACCOUNT_OPENING_DATE=Fecha de acreditaci\u00F3n
GENERIC_AT=a las
GENERIC_OCLOCK=horas
GENERIC_ORIGIN_DATA=Origen de los datos
GENERIC_PERSON_SINGULAR=Persona

# DATEITYP
csv=CSV (Comma-Separated-Values)
xml=XML (VerA.web-XML)
zkm=ZKM (VerA.web-XML sobre el m\u00F3dulo central de comunicaci\u00F3n)
madlan-personen=MAdLAN-Personas (MAdLAN-Importar-Personas)
madlan-firmen=MAdLAN-Empresas (MAdLAN-Importar-Empresas)
x-manage-csv=X-Manage-CSV (X-Manage Contactos)
csvpersdatanschriftdoktyp=CSVPersdat+Anschrift+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp=CSVPersdat+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp10=CSVPersdat+Doktyp 1.0 (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Categor\u00EDas (Comma-Separated-Values)
csviso885915=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)

# PERSONEN/PERSONENUEBERSICHT
GENERIC_PERSON_SUMMARY=Lista de personas
GENERIC_SEARCH_PERSONS=Buscar personas
GENERIC_CREATE_PERSON=Crear nueva persona
GENERIC_PERSONS_DELETED=Personas eliminadas

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
GENERIC_EDIT_PERSON=Editar persona
GENERIC_DOCUMENTED_ON=Documentado el 
GENERIC_LAST_EDITED_ON=\u00DAltima edici\u00F3n el 
GENERIC_PERSONS_ID=Identificador de personas
GENERIC_OA_USERNAME=Nombre de usuario para aplicaci\u00F3n en l\u00EDnea
freifeld-vorschaufuretikett="Campo de vista previa para \u00E2\u0080\u009EEtiqueta\u00E2\u0080\u009C"
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=Para esta persona, la vista previa correspondiente no ha sido generada.
GENERIC_COPY_PERSON=Copiar persona
GENERIC_CREATE_TAG=Crear etiqueta
GENERIC_ASSIGN_AN_EVENT=Asignar un evento
GENERIC_DELETE_PERSON=Eliminar persona
GENERIC_STATISTIC=Estad\u00EDsticas
ausstammdatenhinzufugen=Obtener de los datos maestros

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPE_SINGULAR=Tipo de documento
GENERIC_GENERATE_ALL=Generar todos

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
GENERIC_CATEGORIES_AND_OCCASIONS=Categor\u00EDas y sucesos

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=Lista de todos los eventos por invitado
GENERIC_VIEW_OVER_GUEST_EVENT=Desde
statistikfurgast=Estad\u00EDsticas para invitado
GENERIC_EVENT=Evento
GENERIC_BEGIN=Comienzo

# PERSONEN/PERSONENSUCHE
GENERIC_SEARCH_PERSON=B\u00FAsqueda de personas 
GENERIC_SEARCH=B\u00FAsqueda
GENERIC_VALIDITY_DATE=Fecha de disponibilidad
GENERIC_ADVANCED_SEARCH=B\u00FAsqueda avanzada
HINT_PLACEHOLDER=Aviso: Puede utilizar comodines para su b\u00FAsqueda. El asterisco (*) se utilizar\u00E1 para representar n\u00FAmeros, as\u00ED como el s\u00EDmbolo de interrogaci\u00F3n(?) para caracteres individuales. La b\u00FAsqueda se realizar\u00E1 mediante nombre, apellido, ciudad, c\u00F3digo postal, calle, Empresa/Instituci\u00F3n, tel\u00E9fono, fax, tel\u00E9fono m\u00F3vil, correo electr\u00F3nico, observaciones, categor\u00EDas, \u00E1rea de trabajo y funci\u00F3n/t\u00EDtulo.

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=Datos de acceso guardados satisfactoriamente.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Ya existen datos de acceso para esta persona.

# PERSONEN/NEUE PERSON ANLEGEN
GENERIC_IS_COMPANY=Empresa
GENERIC_SALUTATION_SINGULAR=Denominaci\u00F3n
frau=Sra.
herr=D.
lady=Srta.
sir=Sr.
GENERIC_PLEASE_CHOOSE=Por favor, seleccione
GENERIC_ACAD_TITLE=T\u00EDtulo acad\u00E9mico
GENERIC_IN_COUNTRY=En el pa\u00EDs
GENERIC_HINT_FOR_ORGA=Aviso para la organizaci\u00F3n
GENERIC_COMPANY_SINGULAR=Empresa
GENERIC_COUNTRY=Pa\u00EDs
plz/postfach=C\u00F3digo postal/apartado de correos
GENERIC_POST_OFFICE_BOX=Apartado de correos
iban=IBAN
bic=BIC
GENERIC_MOBILE=M\u00F3vil
LETTERS_WWW=WWW
dublettenprufungdurchfuhren=Examinar duplicados
zurpersonenubersicht=Listado de personas

# PERSONEN/SUCHEN & ERSETZEN IN PERSONENDATEN
suchen&ersetzeninpersonendaten=Buscar y reemplazar datos de personas
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=Aviso: al utilizar el comod\u00EDn '*', ser\u00E1n reemplazadas todas las que contengan las secciones del texto de b\u00FAsqueda (orden inclu\u00EDdo), si no se reemplazar\u00E1n aquellas que coincidan ex\u00E1ctamente con el texto de b\u00FAsqueda.
GENERIC_SEARCH_V=Buscar
GENERIC_REPLACE=Reemplazar
GENERIC_IN_THE_FOLLOWING_FIELDS=En los pr\u00F3ximos campos
anrede/titel=Denominaci\u00F3n / T\u00EDtulo
GENERIC_EMPLOYMENT_TITLE_SHORT=Cargo
GENERIC_INSTITUTION_SINGULAR=Instituci\u00F3n
GENERIC_ADDRESSES=Direcci\u00F3n
telefon/fax=Tel\u00E9fono / fax
GENERIC_REPLACE_INDIVIDUALLY=Reemplazar individualmente
GENERIC_REPLACE_ALL=Reemplazar todas

# PERSONEN/DUBLETTENSUCHE
GENERIC_DUPLICATE_SEARCH=B\u00FAsqueda de duplicados

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Exportar desde los datos de personas
HINT_EXPORT_MANDANT_PERSON=Mediante esta funci\u00F3n, usted exporta s\u00F3lo las personas correspondientes a los mandantes actuales.
GENERIC_WITHOUT=Sin
botschaften=Embajadas
finanzamtsprecher=Portavoz financiero
journalisten=Periodistas
lieferant=Proveedor
nogs=ONGs
politik=Pol\u00EDtico
pressevertreter=Representante de prensa
wirtschaft=Econom\u00EDa
GENERIC_START_EXPORT=Iniciar exportaci\u00F3n
ENCODING_TYPE_CYRILLIC=Cir\u00EDlico
ENCODING_TYPE_WEST=Del oeste
ENCODING_TYPE_BALTIC=B\u00E1ltico
ENCODING_TYPE_EAST=Del este
ENCODING_TYPE_TURKISH=Turco
EXPORT_DATA_TYPE_CSV=CSV (Comma-Separated-Values)
EXPORT_DATA_TYPE_XML=XML (VerA.web-XML)
EXPORT_DATA_TYPE_ZKM=ZKM (VerA.web-XML mediante el m\u00F3dulo de comunicaci\u00F3n central)
EXPORT_DATA_TYPE_MADLAN_PERSON=MAdLAN-Personas (MAdLAN-Importar-Personas)
EXPORT_DATA_TYPE_MADLAN_COMPANY=MAdLAN-Empresas (MAdLAN-Importar-Empresas)
EXPORT_DATA_TYPE_X_MANAGE_CSV=X-Manage-CSV (X-Manage Kontakte)
EXPORT_DATA_TYPE_CSVPERSDATA_ADDRESS_DOCTYPE=CSVPersdat+Direcci\u00F3n+TipoDocumento (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_DOCTYPE=CSVPersdat+TipoDocumento (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_DOCTYPE_1_0=CSVPersdat+TipoDocumento 1.0 (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_CATEGORY=CSVPersdat+Categor\u00EDas (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSV_ISO_8859_15=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)
EXPORT_TITLE_CSV=CSV
EXPORT_TITLE_XML=XML
EXPORT_TITLE_ZKM=ZKM
EXPORT_TITLE_MADLAN_PERSON=MAdLAN-Personas
EXPORT_TITLE_MADLAN_COMPANY=MAdLAN-Empresas
EXPORT_TITLE_X_MANAGE_CSV=X-Manage-CSV
EXPORT_TITLE_CSVPERSDATA_ADDRESS_DOCTYPE=CSV DatosPersonas+Direcciones+TiposDocumentos
EXPORT_TITLE_CSVPERSDATA_DOCTYPE=CSV DatosPersonas+TiposDocumentos
EXPORT_TITLE_CSVPERSDATA_DOCTYPE_1_0=CSV DatosPersonas+TiposDocumentos 1.0
EXPORT_TITLE_CSVPERSDATA_CATEGORY=CSV DatosPersonas+Categor\u00EDas
EXPORT_TITLE_CSV_ISO_8859_15=CSV ISO-8859-15
LABEL_EXPORT_ZKM=Ziel (ZKM-Abreviatura)
LABEL_EXPORT_MADLAN_ENCODING=Codificaci\u00F3n
LABEL_EXPORT_MADLAN_ENCODING_CYRILLIC=Codificaci\u00F3n (Cir\u00EDlica)
HINT_EXPORT_CSV=Dependiendo de la cantidad de datos exportados (mediante el n\u00FAmero de categor\u00EDas y tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_ZKM=El archivo de exportaci\u00F3n ser\u00E1 almacenado en la carpeta de salida ZKM como se podr\u00E1 gestionar un control sobre la descarga. La descarga se podr\u00E1 abortar de forma segura.
HINT_EXPORT_CSVPERSDATA_ADDRESS_DOCTYPE=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as "Datos de personas", "Direcciones", "Tipos de documento" y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_DOCTYPE=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as "Datos de personas", "Tipos de documento" y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_DOCTYPE_1_0=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as "Datos de personas", "Tipos de documento" y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_CATEGORY=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as "Datos de personas", "Tipos de documento" y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de categor\u00EDas), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSV_ISO_8859_15=Este formato es adecuado para la importaci\u00F3n/exportaci\u00F3n sobre aplicaciones como MS Office, las cuales utilizan el juego de caracteres ISO-8859-15. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de categor\u00EDas y tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.

# PERSONEN/IMPORT VON PERSONENDATEN
GENERIC_IMPORT_FROM_PERSONS_DATA=Importaci\u00F3n de datos de personas
HINT_IMPORT_SHORT_CONTENT=Aviso: Al importar los datos, es posible que los datos de mayor longitud sean acortados para su visualizaci\u00F3n en VerA.web.
GENERIC_TARGET_CLIENT=Mandante objetivo
GENERIC_IMPORT_DATA=Importar-Archivo
GENERIC_DATA_TYPE=Tipo de archivo
dateiauswahlen=Seleccionar archivo
keineausgewahlt=Ning\u00FAn seleccionado
GENERIC_START_IMPORT=Comenzar importaci\u00F3n

# PERSONENDROPDOWN
GENERIC_NEW_PERSON=Nueva persona
suchen&ersetzen=Buscar y reemplazar
GENERIC_EXPORT_PERSONS=Exportaci\u00F3n de personas
GENERIC_IMPORT_PERSONS=Importaci\u00F3n de personas

# VERANSTALTUNGENDROPDOWN
GENERIC_EVENT_VIEW=Lista de eventos
veranstaltunguuche=B\u00FAsqueda de eventos
GENERIC_NEW_EVENT=Nuevo evento
GENERIC_STATISTICS=Estad\u00EDsticas

# ADMINISTRATIONDROPDOWN
GENERIC_SALUTATIONS=Denominaciones
GENERIC_WORKAREA_PLURAL=\u00C1rea de trabajo
GENERIC_DOCUMENT_TYPE_PLURAL=Tipos de documento
e-mail-postausgang=E-Mail-Buz\u00F3n de salida
GENERIC_PROGRAM_PERFERENCES=Preferencias de programa
GENERIC_EVENT_LOCATION_PLURAL=Localizaciones de eventos

# VERANSTALTUNGSUEBERSICHT
GENERIC_END=Fin
GENERIC_HOST=Anfitri\u00F3n
GENERIC_EVENT_LOCATION_SINGULAR=Localizaci\u00F3n del evento
GENERIC_EVENT_SEARCH=Buscar eventos
GENERIC_CREATE_NEW_EVENT=Crear nuevo evento
GENERIC_NUMBER_PER_PAGE=Total por p\u00E1gina
seitexvony=P\u00E1gina x de y

# EVENT HEADER
EVENT_ID=ID-Evento
EVENT_NAME=Nombre del evento
EVENT_URL=Enlace al evento
EVENT_URL_MEDIA_REPRESENTATIVE=Enlace para representates de prensa
EVENT_MAX_GUEST=N\u00FAmero m\u00E1ximo de invitados
EVENT_MAX_RESERVE=N\u00FAmero m\u00E1ximo en lista de espera
EVENT_INVITATION_TYPE=Tipo de invitaci\u00F3n
EVENT_INVITATION_TYPE_WITHOUT_PARTNER=Sin partner
EVENT_INVITATION_TYPE_ONLY_PARTNER=S\u00F3lo partner
EVENT_INVITATION_TYPE_WITH_PARTNER=Con partner

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
GENERIC_EDIT_EVENT=Editar evento
GENERIC_TO_GUEST_MANAGEMENT=Gesti\u00F3n de invitados
GENERIC_GENERAL=General
GENERIC_TASK_PLURAL=Tareas
GENERIC_ADDITIONAL_PERSONS_DATA=Datos adicionales
kurzbereichnung=Abreviatura
GENERIC_OPEN_EVENT=Evento abierto
umxuhr=A las x horas
veranstalgungsort=Localizaci\u00F3n del evento
GENERIC_SEARCH_FOR_HOST=Buscar anfitri\u00F3n
GENERIC_DELETE_HOST=Eliminar anfitri\u00F3n
GENERIC_HOST_PARTNER=Anfitri\u00F3n-Partner
GENERIC_LOGIN_REQUIRED=Login necesario
GENERIC_SUBSCRIPTION_OF_PRESS_REPRESENTATIVES_POSSIBLE=Acceso habilitado a representantes de prensa
GENERIC_SAVE_EVENT=Guardar evento
GENERIC_TO_EVENT_VIEW=Lista de eventos

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPES_MARKED_DELETE=Eliminar tipo(s) de documento seleccionado(s)
GENERIC_DELETE=Eliminar
GENERIC_ADD_NEW_DOCUMENT_TYPE=A\u00F1adir nuevo tipo de documento
xvonydokumenttypen=x de y tipos de documento

# VERANSTALTUNG BEARBEITEN/AUFGABEN
GENERIC_ADD_NEW_TASK=Crear nueva tarea
MESSAGE_NO_TASKS_FOR_THIS_EVENT=No existe ninguna tarea asignada a este evento
GENERIC_SELECTED_ENTRIES=Entradas seleccionadas
GENERIC_TITLE=T\u00EDtulo
GENERIC_RESPONSIBLE=Responsable

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
GENERIC_TASKS_ID=ID-Tarea
GENERIC_COMPLETION=Finalizaci\u00F3n
GENERIC_PRIORITY=Prioridad
GENERIC_DESCRIPTION=Descripci\u00F3n
GENERIC_ADD_RESPONSIBLES=A\u00F1adir responsables
verantwortlichenentfernen=Eliminar responsables
GENERIC_SAVE_TASK=Guardar tarea
GENERIC_BACK_TO_TASKS_VIEW=Lista de tareas

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
GENERIC_ADD_NEW_EMPLOYMENT_TITLE=A\u00F1adir nuevo t\u00EDtulo
MESSAGE_NO_EMPLOYMENT_TITLES_FOUND=No se han encontrado t\u00EDtulos

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
GENERIC_ADD_NEW_KATEGORIES=A\u00F1adir nueva categor\u00EDa

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
GENERIC_PRECONDITION_PLURAL=Precondiciones
EVENT_PRECONDITION_MARKED=Precondiciones seleccionadas
EVENT_PRECONDITION_ADD=A\u00F1adir precondiciones
EVENT_PRECONDITION_INVITATIONSTATUS=Estado de invitaci\u00F3n
EVENT_PRECONDITION_STARTDATE=Fecha de inicio
EVENT_PRECONDITION_NOT_FOUND=No se han encontrado precondiciones

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Buscar s\u00F3lo en eventos futuros
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=Puede utilizar comodines en su b\u00FAsqueda: asterisco (*) para b\u00FAsqueda plurar y el s\u00EDmbolo de interrogaci\u00F3n para b\u00FAsqueda individual.

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=Con partner
eswurdeeineneueveranstaltungangelegt=Se ha creado un nuevo evento.

# VERTEILER
angelegtvon=Creado por
angelegtam=Creado el
erzeugtausveranstaltung=Generado por evento

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=Restringir estad\u00EDsticas para el pr\u00F3ximo intervalo temporal
statistiktypauswahlen=Seleccionar tipo de estad\u00EDsticas
zeitrahmenbeginn=Inicio-Intervalo
zeitrahmenende=Final-Intervalo
STATISTIC_RADIO_PER_YEAR=Total de eventos por a\u00F1o
STATISTIC_RADIO_PER_MONTH=Total de eventos por mes
STATISTIC_RADIO_GROUPED_BY_HOST=Total de eventos, agrupados por anfitri\u00F3n
STATISTIC_RADIO_PER_HOST=Listado de eventos de un anfitri\u00F3n (con b\u00FAsqueda)
STATISTIC_RADIO_PER_GUEST=Listado de eventos de un invitado (con b\u00FAsqueda)
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=Listado de eventos ordenados por localizaci\u00F3n
statistikerstellen=Generar estad\u00EDsticas

# GAESTEVERWALTUNG DER VERANSTALTUNG
gasteverwaltungderveranstaltung=Gesti\u00F3n de invitados del evento
maxanzahlgaste=Total de invitados
gastedetails=Detalles de invitados
offen=Abierto
zusagen=Aceptado
absagen=Rechazado
teilnahmen=Participaciones
aufplatz=Con plaza
aufreserve=En reserva
filter=Filtro
platzwahl=Selecci\u00F3n de plaza
lfdnr=N\u00B0 Serie
nichteingeladen=No invitado
laufendenummerberechnen=Calcular n\u00FAmero de serie
allestammdatenneuladen=Cargar datos maestros de nuevo
HINT_ENTRY_POINT=Direkteinsprung: s\u00F3lo es posible mediante ordenaci\u00F3n por nombre, apellido o correo electr\u00F3nico..
HINT_GUEST_MANAGEMENT_FILTER=Para la generaci\u00F3n del archivo de control o listado de invitados se considerara el criterio establecido en el filtro superior.
HINT_GUEST_MANAGEMENT_MARKED=Si selecciona un s\u00F3lo invitado, ser\u00E1 el \u00FAnico en ser exportado. De lo contrario, se exportar\u00E1 el listado completo.
TABLE_BEFORE_GUEST=Invitado anterior
TABLE_FIRST_GUEST=Primer invitado
TABLE_LAST_GUEST=\u00DAltimo invitado
TABLE_NEXT_GUEST=Invitado siguiente

# GAESTELISTE
GUEST_LIST_ALL_GUEST=Todos los invitados
GUEST_LIST_ALL_GUEST_ON_PLACE=Todos los invitados con plaza
GUEST_LIST_ALL_GUEST_ON_RESERVE=Todos los invitados en reserva
GUEST_LIST_APPLY_GUEST_FROM_EVENT=Aplicar invitados desde evento
GUEST_LIST_CATEGORY_ASSIGN=Asignar categor\u00EDas
GUEST_LIST_CATEGORY_REMOVE=Eliminar categor\u00EDas
GUEST_LIST_DISTRIBUTOR_CREATE=Crear distribuidor
GUEST_LIST_DATA_EXPORT=Exportar archivo de control
GUEST_LIST_CONFIRM_ACTION=Por favor, confirme la siguiente acci\u00F3n
GUEST_LIST_DIDNT_CHANGE=No se ha modificado la lista de invitados
GUEST_LIST_EXPAND_ONE=Se ha a\u00F1adido un invitado a la lista
GUEST_LIST_EXPAND_MULTIPLE_PART_ONE=Se han a\u00F1adido 
GUEST_LIST_EXPAND_MULTIPLE_PART_TWO=invitados a la lista
GUEST_LIST_HINT_EXPORT_GUEST=Si selecciona un s\u00F3lo invitado, ser\u00E1 el \u00FAnico en ser exportado. De lo contrario, se exportar\u00E1 el listado completo
GUEST_LIST_HINT_FILTER=Para la generaci\u00F3n del archivo de control o listado de invitados se considerara el criterio establecido en el filtro superior.
GUEST_LIST_HINT_RED_PERSON=Las personas con fondo de color rojo ser\u00E1n marcadas como personas "a borrar"
GUEST_LIST_CREATED_NO_PERSON=creado sin personas
GUEST_LIST_CREATED_ONE_PERSON=creado con una persona
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_ONE=creado con 
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_TWO=personas
GUEST_LIST_NO_GUEST_INVITED=A\u00FAn no se han a\u00F1adido invitadoseingeladen
GUEST_LIST_NUMBER_CALCULATE=Calcular n\u00FAmero de serie
GUEST_LIST_NUMBER_CALCULATED_SAVED=El "n\u00FAmero de serie" ser\u00E1 recalculado y guardado para todos los invitados
GUEST_LIST_ONLY_OPEN=s\u00F3lo pendientes
GUEST_LIST_ONLY_ACCEPT=s\u00F3lo aceptados
GUEST_LIST_ONLY_DECLINED=s\u00F3lo rechazados
GUEST_LIST_ONLY_PARTICIPATE=s\u00F3lo participantes
GUEST_LIST_PERSON_DATA_RELOAD=Recargar todos los datos maestros
GUEST_LIST_RESERVE=R
GUEST_LIST_SEARCH_PERSON_ADD=Buscar personas y a\u00F1adirlas a la lista de invitados

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=Generar lista de invitados
SELECT_OUTPUT_FORMAT=Seleccionar formato de salida
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=Lista agrupada por categor\u00EDa - con Partner
LIST_GROUP_BY_CATEGORY_WITH_TEL=Lista agrupada por categor\u00EDa - con n\u00FAmero de tel\u00E9fono y m\u00F3vil
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=Lista agrupada por categor\u00EDa - con partner y fax
LIST_SORT_PARTNER_TEL=Lista agrupada -con partner, n\u00FAmero de tel\u00E9fono y m\u00F3vil
SORT_CRITERIA=Criterios de filtraci\u00F3n
SORT_AFTER=Filtrar por
CONTINUAL_NUMBER=N\u00FAmero de serie
anschliesendnach=Despu\u00E9s de
zusatzlichesortierungnach=Filtro adicional por

# GASTDETAILS
GUEST_DETAIL_HINT_GUEST_HOST=Aviso para el anfitri\u00F3n
GUEST_DETAIL_HINT_ORGANISATION_TEAM=Aviso para la organizaci\u00F3n
GUEST_DETAIL_INVITATION_STATUS=Estado de la invitaci\u00F3n
GUEST_DETAIL_SEAT_NUMBER=Plaza
GUEST_DETAIL_TABLE_NUMBER=Mesa
gastdetails=Detalles del invitado
HINT_GUEST_LIST_EDIT_PERSONDATA=\u00DAnicamente modificar\u00E1 los datos de la persona correspondientes al evento actual, no produci\u00E9ndose cambios sobre los datos maestros.
istgastgeber=Anfitri\u00F3n
reserve=Reserva
aufstammdatenzurucksetzen=Restablecer desde los datos maestros
stammdatenbearbeiten=Editar datos maestros

# DOKUMENTTYPEN
dokumenttypwahlen=Seleccionar tipos de documento
mitgliedsausweis=Tarjeta de membres\u00EDa
etikett=Etiqueta
tischkarte=Tarjeta de mesa
adresstypundzeichensatzwahlen=Seleccionar tipo de direcci\u00F3n y conjunto de caracteres
adresstyp=Tipo de direcci\u00F3n
datenbearbeiten=Editar datos
verbinder=Interconexiones
freitextfeldpartner=Campo de texto libre (partner)
akatitel=T\u00EDtulo acad\u00E9mico (partner)
kontaktdaten=Datos de contacto
strase=Calle
postfachplz=C\u00F3digo postal
nummer=N\u00FAmero
zuruckzudenveranstaltungsdetails=Volver a detalles del evento

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Editar tipo de documento
dokument-id=ID-Documento
dokument-name=Nombre-Documento
dokumenttypspeichern=Guardar tipo de documento
zuruckzurdokumenttypenliste=Volver a tipos de documento
anmeldedatenerzeugen=Generar datos de acceso
esliegenkeinekategorienundereignissevor=No se presentan categor\u00EDas y sucesos
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=En verde se resaltan las entradas de sucesos repetidos.

# SUCHEN & ERSETZEN IN PERSONENDATEN

# VERTEILERDETAILS
verteilerdetails=Detalles de la distribuci\u00F3n
verteilerversenden=Enviar distribuci\u00F3n
e-mail-clientaufrufen=Redactar E-Mail a cliente

# FEHLEND
zurstartseite=Inicio
solldieneuekategorie=\u00BFDeber\u00EDa filtrarse 
einsortiertwerden=la nueva categor\u00EDa?
pflichtfelder=Campos obligatorios
markiertekategorien=Categor\u00EDas seleccionadas
markiertekategorienloschen=Eliminar las categor\u00EDas seleccionadas
alledemarkieren=Eliminar selecci\u00F3n
furalleveranstaltungen=Para todos los eventos
speichern=Guardar
anderungsprotokollfurdenzeitraum=Historial de cambios para el per\u00EDodo de tiempo
objekt=Objeto
objektid=ID-Objeto
artderanderung=Tipo de cambio
geandertefelder=Campos modificados
datumauswahlen=Seleccionar fechaDatum ausw\u00E4hlen
folgendeaktionen=Acciones siguientes
wurden=ser
durchgefuhrt=realizadas
konnen=podr\u00E1n
aktuallisieren=Actualizar
cleanupjetztunwiderruflichdurchfuhren=Realizar cleanup definitivo
essindderzeitkeinecleanupsmoglichnotig=No es posible/necesario realizar un cleanup.
nochkeineauswahlgetroffen=A\u00FAn no se dispone de selecci\u00F3n
oberflachenbeschriftungen=Oberfl\u00E4chenbeschriftungen
zusatzfelder=Campos adicionales
eswurdeeinzusatzfeld=Se ha creado 
angelegt=un campo adicional
geandert=modificado
geloscht=eliminado
feldbezeichnung=Descripci\u00F3n del campo
eingabetyp=Tipo de entrada
erfolgreichgespeichert=\u00A1Guardado satisfactoriamente!
markiertendokumenttypen=Tipo(s) de documento seleccionado(s)
eigenesdokumentfurpartner=Documento para partners
sortierreihenfolge=Orden de clasificaci\u00F3n
gastgebermitausgeben=Anfitri\u00F3n con distribuci\u00F3n
iststandardfursteuerdatei=Est\u00E1ndar para el archivo de control
format=Formato
HINT_EXPORT_FORMAT=OOo 1.1 para OpenOffice 1.1 (Archivo-sxc) y OOo 2.0 para OpenOffice 2.0 (Archivo-ods),xls para Microsoft Office (Archivo-xls) y CSV para formato-CSV.
HINT_EVENT_IDENTIFICATION=Las marcas 50 y 99 ser\u00E1n a\u00F1adidas autom\u00E1ticamente al evento. Para la marca 50 no se dispondr\u00E1 de ning\u00FAn campo de texto libre.
wirklichloschen=Eliminar realmente
zumpersonenimport=Volver a Importar-Personas
importstatus=Estado de la importaci\u00F3n
importstatusvorhandenedublettenbearbeiten=Estado de la importaci\u00F3n: editar duplicados existentes
bittemarkierensiediezuimportierendenpersonen=Por favor, realice su selecci\u00F3n para importar personas.
dublettendiedurchden=Duplicados, los cuales ser\u00E1n a\u00F1adidos 
importhinzugefugtwerdenwurden=a trav\u00E9s de la importaci\u00F3n
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=, se encuentra remarados mediante un checkbox. Seguidamente se muestran los datos ya almacenados dentro del sistema.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=Deber\u00E1 escoger los duplicados para integrarlos en la importaci\u00F3n.
alsdubletteubernehmen=Aceptar como duplicados
markiertepersonenalsdubletteubernehmen=Persona(s) seleccionada(s) como duplicado(s)
anzahlzuspeicherndedubletten=Recuento de duplicados a almacenar
eswurdenkeineeintragegefunden=No se han encontrado entradas
zuruckzumpersonenimport=Volver a importaci\u00F3n
fehlermeldung=Mensaje de error
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=Durante la ejecuci\u00F3n del proceso ha ocurrido un error. Por favor, contacte con su administrador.
unbekannterfehler=Error desconocido.
markiertenkategorien=Categor\u00EDas seleccionadas
markiertenkategorienentfernen=Eliminar categor\u00EDas seleccionadas
bitteauswahlen=Por favor, realice su selecci\u00F3n
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=El evento actual ha sido eliminado por otro usuario. Puede crear un nuevo evento si as\u00ED lo desea, o simplemente continuar trabajando sobre VerA.web.
bittebestatigensiedasspeicherndieserveranstaltung=Por favor, confirme la actualizaci\u00F3n del evento actual
keingastgeberausgewahlt=Anfitri\u00F3n no seleccionado
kurzbezeichnung=Descripci\u00F3n corta
maximalelangederwarteliste=Longitud m\u00E1xima de la lista de espera
sollendiestammdatenumdiesenorterweitertwerden=Los datos maestros deben ser modificados en relaci\u00F3n a la localizaci\u00F3n actual
markiertendokumenttypenentfernen=Eliminar tipo(s) de documento seleccionado(s)
eswurdenkeinedokumenttypengefunden=No se han encontrado tipos de documento.
markiertenamtsbezeichnungen=T\u00EDtulo(s) seleccionado(s)
markiertenamtsbezeichnungenentfernen=Eliminar t\u00EDtulo(s) seleccionado(s)
zurveranstaltungssuche=B\u00FAsqueda de eventos
veranstaltungssuche=B\u00FAsqueda de eventos
suchergebnis=Resultado de la b\u00FAsqueda
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=Por favor, para obtener la lista de invitados, seleccione un evento dentro del listado.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=Por favor, para asignar la persona de un evento, seleccione un evento dentro del listado.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=Por favor, seleccione una persona de la lista para establecerla como anfitri\u00F3n.
loschenvonveranstaltungenistnichtmoglich=No es posible eliminar eventos
weiteremeldungen=mensajes adicionales.
bittebestatigensiedasloschendermarkiertenveranstaltungen=Por favor, \u00A1confirme la eliminaci\u00F3n de los eventos seleccionados!
markierteveranstaltungloschen=Eliminar los eventos seleccionados
abbrechen=Cancelar
markierteveranstaltungen=Evento(s) seleccionado(s)
markierteveranstaltungenloschen=Eliminar evento(s) seleccionado(s)
zuruckzurgasteverwaltung=Volver a gesti\u00F3n de invitados
zuruckzurgasteliste=Volver a lista de invitados
zuruckzurveranstaltungsdetails=Volver a detalles de evento
zuruckzurveranstaltungsstatistiken=Volver a estad\u00EDsticas del evento
zuruckzurveranstaltungsaufgabe=Volver a tareas del evento
zuruckzurpersonensuche=Volver a b\u00FAsqueda de personas
zuruckzusuchenundersetzen=Buscar y reemplazar
zuruckzurveranstaltungssuche=B\u00FAsqueda de eventos
wahlensiebittezunachsteineodermehrereveranstaltungenaus=Por favor, comience por seleccionar uno o m\u00E1s eventos.
nurinzuunftigenveranstaltungensuchen=Buscar s\u00F3lo en eventos futuros
zuruck=Volver
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=Puede utilizar comodines en la b\u00FAsqueda. Al utilizar el comod\u00EDn '*', ser\u00E1n seleccionadas todas las que contengan las secciones del texto de b\u00FAsqueda (orden inclu\u00EDdo), as\u00ED como podr\u00E1 realizar b\u00FAsquedas individuales mediante el comod\u00EDn '?'.
bittebestatigensiedasspeicherndieseraufgabe=Por favor, confirme la actualizaci\u00F3n sobre la tarea actual
verantworlichenhinzufugen=A\u00F1adir responsables
verantworlichenentfernen=Eliminar responsables
loschenvonaufgabenistnichtmoglich=No se puede eliminar tareas
bittebestatigensiedasloschenvonaufgaben=Por favor, confirme la eliminaci\u00F3n de las tareas
ausgewahlteeintrageloschen=Elminar entradas seleccionadas
start=Comenzar
zursuche=Buscar
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=Se ha conectado como administrador y le es permitido exportar todos los mandantes.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=Mediante esta funci\u00F3n, puede exportar exclusivamente personas pertenecientes a mandantes.
event=Evento
keine=Ning\u00FAn
category=Categor\u00EDa
weitereoptionen=Opciones adicionales
anmerkung=Nota
anmerkungen=Notas
markiertebezeichnunge=Denominaciones seleccionadas
markierteeintrageentfernen=Eliminar denominaciones seleccionadas
eswurdenkeinedatengefunden=No se han encontrado datos

eswurdenkeinedatengefunden=No se han encontrado datos
siehabenkeinedatenherkunftangegeben=Los datos de origen no han sido especificados.
HINT_EXPORT_NOT_POSSIBLE_OPENOFFICE=Ha intentado importar un archivo de OpenOffice. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_EXPORT_NOT_POSSIBLE_STAROFFICE=Ha intentado importar un archivo de StarOffice. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_EXPORT_NOT_POSSIBLE_EXCEL=Ha intentado importar un archivo Excel. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_IMPORT_NOT_POSSIBLE_PDF=Ha intentado importar un archivo PDF. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_ZIP=Ha intentado importar un archivo ZIP. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_EXE=Ha intentado importar un archivo EXE. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
siehabenversuchteinedateimitderendung=Ha intentado importar un archivo con la extensi\u00F3n 
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=Eso no es posible en la versi\u00F3n actual de VerA.web.
siehabenkeinedateiausgewahltoderdiesewarleer=No ha selecionado ning\u00FAn archivo o el archivo seleccionado est\u00E1 vac\u00EDo.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=Ha ocurrido un error inesperado al importar un archivo.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Presumiblemente, el archivo a importar no posee el formato esperado por el sistema.
detailsanzeigen=Mostrar detalles
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=Al importar datos con gran longitud, es posible que sean acortados para ser visualizados en VerA.web.
alledokumenttypenderzuimportierendenpersonenmussenimsystemvorhandenseinsollderimportjetztgestartetwerden=Todos los tipos de documento para la importaci\u00F3n de personas deber\u00E1n estar habilitados en el sistema. \u00BFComenzar proceso de importaci\u00F3n?
umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=Para hacer a un duplicado almacenable, deber\u00E1 seleccionarlos como almacenables mediante la opci\u00F3n "duplicados existentes".
HINT_UMLAUT_COMPARISON=Tenga en cuenta, que los caracteres \u00E4, \u00F6, \u00FC y \u00DF ser\u00E1n tratados como ae, oe, ue y ss, respectivamente.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=La importaci\u00F3n terminar\u00E1 una vez pulse sobre el bot\u00F3n "Finalizar exportaci\u00F3n".
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=El proceso puede ser finalizado en caso de que los registros almacenables se hayan guardado.
vorhandenedubletten=Duplicados existentes
vorhandenedublettenbearbeiten=Editar duplicados existentes
zuimportierendedatensatzeinsgesamt=Importar total de registros
davondubletten=De duplicados
davonspeicherbar=De almacenables
ignoriertefehlerdatensatze=Datos err\u00F3neos ignorados
importabschlieszen=Finalizar exportaci\u00F3n
siehabenkeinendatensatzimportiert=No se han importado registros.
siehabeneinendatensatzimportiert=Se ha importado un registro.
siehaben=Se han importado
datensatzeimportiert=registros.
informationennichtverfugbar=Informaci\u00F3n no disponible
nichtgewahlt=No seleccionado
verfugbarerollen=Roles disponibles
passowrt=Contrase\u00F1a
inverteretunganmelden=Acceder como representante
vornamenachname=Nombre.Apellido
alsbenutzernamen=Como nombre de usuario
emailvorlage=Modelo E-Mail
amtsbezfunktion=T\u00EDtulo/Funci\u00F3n
postfachnummer=C\u00F3digo postal
email=E-Mail
verteileranlegen=Crear distribuci\u00F3n
sielegeneinenneuenverteilerausderveranstaltung=Se crea un nuevo distribuidor para el evento
mit=con
einerperson=una persona
verteilername=nombre del representante
verteilerspeichern=Guardar representante
markierteadressen=Direcciones seleccionadas
markierteadressenausdemverteilerloschen=Eliminar direcciones seleccionadas
analleadressenversenden=Enviar a todas las direcciones
emailclientaufrufen=Redactar E-mail para cliente
esliegenkeineadressdatenfurdiesenverteilervor=No existen datos de direcci\u00F3n para el representante.
esliegenkeineadressenfurdiesenverteilervor=No existen direcciones para el representante.
esliegenkeinevorlagenvor=No existen plantillas.
zuruckzurverteilerubersicht=Gesti\u00F3n de representantes
eswurdekeineemailzumversendengespeichert=No existe ning\u00FAn E-Mail para enviar
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=Se almacenar\u00E1 autom\u00E1ticamente un E-Mail. Ser\u00E1 env\u00EDado directamente.
emailszumversendengespeichertdiesewerdennunautomatischversendet=E-Mails a enviar guardados autom\u00E1ticamente. Ser\u00E1n env\u00EDados directamente.
markiertenverteiler=Representante(s) seleccionado(s)
markierteverteilerloschen=Eliminar representante(s) seleccionado(s)
persondendaten=Datos de personas
solldiesergastaufplatzgesetztwerden=\u00BFDebe el invitado actual obtener una plaza?
solldiepartnerinderpartnermiteingeladenwerden=\u00BFDebe el partner ser invitado?
aktuellepersonwirklichentfernen=\u00BFDesea realmente eliminar la persona actual?
personspeichern=Guardar persona
zurpersonenliste=Volver a personas
zurpersonenuebersicht=Lista de personas
zurueckzurveranstaltung=Volver a eventos
zurdublettensuche=B\u00FAsqueda de duplicados
zurckzumsuchergebnis=Resultados de b\u00FAsqueda
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=La persona ha sido invitada satisfactoriamente
hinzugefuegt=al evento
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=La persona no ser\u00E1 invitada, puesto que ya se encuentra en la lista de invitados.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=La persona actual ser\u00E1 marcada como borrada. Por tanto, no ser\u00E1 posible acceder a ella mediante la b\u00FAsqueda de personas.
personanlegen\u2243Crear persona
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=No se han encontrado duplicados. Usted podr\u00E1 ahora rellenar la informaci\u00F3n para almacenarla.
bittegebensiezunaechstden=Por favor, primero indique 
vorundnachnamen= nombre y apellidos 
anundfuhrendiedublettenprufungdurch=e inicie la b\u00FAsqueda de duplicados.
beifirmenwaehlensiediecheckbox=Para empresas, seleccione el check correspondiente
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=e introduzca el nombre de la empresa. El sistema comprobar\u00E1 la existencia de duplicados.
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=No existen duplicados, ahora puede introducir m\u00E1s informaci\u00F3n y despu\u00E9s guardarla.
geschaeftlich=Negocio
privat=Privado
zurueckzurpersonensuche=Buscar personas
zurueck=Volver
dublettenpruefungdurchfuehren=Iniciar b\u00FAsqueda de duplicados
zurueckzumsuchergebnis=Resultados de b\u00FAsqueda
personspeicherndublettenpruefung=Guardar persona - B\u00FAsqueda-duplicados
neueneintraganlegen=Crear nueva entrada
existierendeneintragbearbeiten=Editar entradas existentes
eswurdenkeinedublettengefunden=No se han encontrado duplicados.
hinzufuegen=A\u00F1adir
ausgewaehltepersonenzurveranstaltunghinzufuegen=Invitar al evento a las personas seleccionadas.
personerfassen=Capturar persona
dublettenanlegen=Crear duplicados
abbrechenundzurueck=Cancelar y volver
gastsuchenveranstaltung=Buscar invitado - Evento
gastsuchen=Buscar invitado
verantwortlichenfueraufgabesuchen=Buscar responsable para tarea
verantwortlichenfueraufgabehinzufugen=Invitar responsable para tarea
gastgeberhinzufuegen=Invitar anfitri\u00F3n
personensuchegastgeberhinzufugen=B\u00FAsqueda de personas: invitar anfitri\u00F3n
gasthinzufuegen=A\u00F1adir invitado
personensuchegasthinzufugen=B\u00FAsqueda de personas: a\u00F1adir invitado
personfirma=Persona/Empresa
weitereangaben=Informaci\u00F3n adicional
keinekategoriezugeordnet=Sin categor\u00EDa asignada
keinarbeitsbereichzugeordnet=Sin \u00E1rea de trabajo asignada
keinarbeitsbereich=Sin \u00E1rea de trabajo
gueltigkeitsdatum=Fecha de disponibilidad
biszudiesemdatum=Hasta la fecha
abdiesemdatum=Desde la fecha
angenaudiesemdatum=Exactamente en la fecha
datumauswaehlen=Seleccionar fecha
HINT_SEARCH_MULTIPLE=La b\u00FAsqueda tambi\u00E9n es compatible con la b\u00FAsqueda m\u00FAltiple por categor\u00EDa. Por favor, seleccione varias categor\u00EDas, mantenga presionado el bot\u00F3n del rat\u00F3n y arrastre su selecci\u00F3n hacia la b\u00FAsqueda de categor\u00EDas. Como alternativa, puede hacer clic mientras mantiene pulsada la tecla "Ctrl" con el bot\u00F3n izquierdo del rat\u00F3n. Tenga en cuenta que las pseudocategor\u00EDas "Todas" y "Ninguna" no son seleccionables.
waehlensiebittezunaechsteinekategorieaus=Por favor, seleccione una categor\u00EDa.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=Desea asignar la categor\u00EDa asignada a la persona/invitado
eswurdekeinekategoriezugeordnet=No se han asignado categor\u00EDas
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=Desea asignar la categor\u00EDa asignada a ${count} personas/invitados
eswurdenkeinekategorienzugeordnet=No se han asignado categor\u00EDas
eswurdenkeinekategoriengefunden=No se han encontrado categor\u00EDas
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Desea desasignar la categor\u00EDa seleccionada a la persona actual
eswurdekeinekategorieentfernt=No se han eliminado categor\u00EDas
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Desea desasignar la categor\u00EDa seleccionada a ${count} personas/invitados
eswurdenkeinekategorienentfernt=No se han eliminado categor\u00EDas.
zuweisen=Asignar
waehlensieeinekategorieauswelchesie=Seleccione una categor\u00EDa, la que 
moechten=desee
alleentfernen=Eliminar todas
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=No ha configurado categor\u00EDas. Mediante el apartado "Administraci\u00F3n" es posible 
definieren=definirlas.
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=Ha seleccionado ${count} personas. Dependiendo del n\u00FAmero de personas seleccionadas, el proceso puede durar un poco m\u00E1s.
waehlensiebittezunaechsteinenarbeitsbereichaus=Seleccione un \u00E1rea de trabajo.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a la persona/invitado actual
eswurdekeinarbeitsbereichzugeordnet=No se han asignado \u00E1reas de trabajo
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a estas personas/invitados
eswurdenkeinearbeitsbereichzugeordnet=No se han asignado \u00E1reas de trabajo
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Desea desasignar del \u00E1rea de trabajo seleccionada a la persona/invitado actual
eswurdekeinarbeitsbereichaufgehoben=No se han eliminado \u00E1reas de trabajo
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Desea desasignar del \u00E1rea de trabajo seleccionada a estas personas/invitados
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a la persona/invitado actual
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a ${count} personas/invitados
waehlensieeinenarbeitsbereichauswelchensie=Seleccione un \u00E1rea de trabajo, el que 
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=No ha configurado \u00E1reas de trabajo. Mediante el apartado "Administraci\u00F3n" es posible 
administrationallestellvertretungenimmandanten=Administraci\u00F3n - todos los delegados del mandante
administrationallestellvertretungen=Administraci\u00F3n - todos los delegados
verwaltungpersoenlichevertretungen=Gesti\u00F3n - delegados personales
vertretung=Delegado
markiertevertretungen=Delegado(s) seleccionado(s)
loeschen=Eliminar
markiertevertretungenloeschen=Eliminar delegado(s) seleccionado(s)
gueltigab=V\u00E1lido desde
gueltigbis=V\u00E1lido hasta
bitteauswaehlen=Por favor, seleccione
gaestelisteerstellenfuerveranstaltungeventshortname=Gestionar lista de invitados para el evento: $!event.shortname
gaesteverwaltungderveranstaltung=Lista de invitados del evento
gaestelisteerstellen=Gestionar lista de invitados
ausgabeformatwaehlen=Seleccionar formato de las tareas
listenachkategoriengruppiertmitpartner=Lista agrupada por categor\u00EDa - con Partner
listenachkategoriengruppiertmittelundmobiltelefon=Lista agrupada por categor\u00EDa - con tel\u00E9fono y m\u00F3vil
listenachkategoriengruppiertmitpartnerundfax=Lista agrupada por categor\u00EDa - con partner y fax
listenachsortierungmitpartnertelundmobiltelefon=Lista agrupada - con partner, tel\u00E9fono y m\u00F3vil
tisch=Mesa
zusaetzlichesortierungnach=Filtrado adicional porZus\u00E4tzliche Sortierung nach
zurueckzurgaesteverwaltung=Volver a gesti\u00F3n de invitados
verwaltungallebenutzerimmandanten=Gesti\u00F3n - usuarios en mandantes
verwaltungallebenutzer=Gesti\u00F3n - todos los usuarios
markiertenbenutzer=Usuario(s) seleccionado(s)
markiertenbenutzerloeschen=Eliminar usuario(s) seleccionado(s)
leseneingeschraenkt=Lectura restringida
lesenuneingeschraenkt=Lectura permitida
lesenundschreibeneingeschraenkt=Lectura y escritura restringidas
lesenundschreibenuneingeschraenkt=Lectura y escritura permitidas
mandantadministrieren=Administrar mandantes
administrieren=Administrar
stellvertretung=Declaraci\u00F3n
bittewahlensiedierolleausdiesievertretenmochten=Por favor, seleccione los roles que desee representar
benutzerrolle=Rol de usuario
vertreten=Representar
statistikfurgastgeber=Estad\u00EDsticas para el anfitri\u00F3n
imzeitraumvom=En el per\u00EDodo comprendido entre 
biszum=a
bis=hasta
auswartigesamtintranetstil=Ausw\u00E4rtiges Amt Intranet-Stil
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Klicken Sie eine der aufgelisteten Personen an, um sie der Aufgabe hinzuzuf\u00FCgen
eswurdeeinepersongeloscht=Es wurde eine Person gel\u00F6scht
eswurdekeinepersongeloscht=Es wurde keine Person gel\u00F6scht
personengelouscht=Personen gel\u00F6scht.
derarbeitsbereichwurdeerfolgreichhinzugefugt=Der Arbeitsbereich wurde erfolgreich hinzugef\u00FCgt.
diearbeitsbereichewurdenerfolgreichentfernt=Die Arbeitsbereiche wurden erfolgreich entfernt.
diekategoriewurdeerfolgreichhinzugefugt=Die Kategorie wurde erfolgreich hinzugef\u00FCgt.
diekategorienwurdenerfolgreichentfernt=Die Kategorien wurden erfolgreich entfernt.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=Sie haben keine ausreichende Berechtigung um Personen zu entfernen.
wauhlensiebittezunauchsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=Bei den folgenden Personen liegt das G\u00FCltigkeitsdatum in der Zukunft
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=Folgende Personen sind mindestens einer laufenden oder zuk\u00FCnftigen Veranstaltung
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=zugeordnet. Detailinformationen k\u00F6nnen Sie \u00FCber die G\u00E4stelisten der
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=jeweiligen Veranstaltungen abrufen. Die Personen werden aus allen G\u00E4stelisten
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=Folgende Personen sind mindestens einer Aufgabe in mindestens einer laufenden oder
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=zuk\u00FCnftigen Veranstaltung zugeordnet. Detailinformationen rufen Sie bitte \u00FCber die
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=Aufgabenlisten der jeweiligen Veranstaltungen auf. Die Personen werden aus allen
aufgabenentfernt=Aufgaben entfernt
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=Wenn Sie Ihre Auswahl anpassen wollen, brechen Sie bitte das L\u00F6schen ab.
sollenallemarkiertenpersonengeloeschtwerden=Sollen alle markierten Personen gel\u00F6scht werden?
dieseaktionkannnichtrueckgaungiggemachtwerden=Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.
bittebestaetigensiedasloeschendermarkiertenpersonen=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Personen!
loeschenvonpersonenistnichtmoeglich=L\u00F6schen von Personen ist nicht m\u00F6glich
markiertepersonenzurveranstaltunghinzufuegen=Markierte Person(en) zur Veranstaltung hinzuf\u00FCgen
zudieserpersonistkeinehauptpersoneingetragen=Zu dieser Person ist keine Hauptperson eingetragen.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=Diese Person kann nicht auf Reserve gesetzt werden, da die notwendigen Daten
nichtvollstaendigerfasstwurden=nicht vollst\u00E4ndig erfasst wurden.
waehlensiebittezunaechsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
exportieren=Exportieren
einladen=Einladen
aufreservesetzen=Auf Reserve setzen
delegationanmelden=Delegation anmelden
alledemarkiereninklpartnerwenneingeladen=Alle (de)markieren (inkl. Partner, wenn eingeladen)
arbeitsshybereich=Arbeits\u00ADbereich
amtsbeshyzeichnung=Amtsbe\u00ADzeichnung
eswurdenkeineeintraegegefunden=Es wurden keine Eintr\u00E4ge gefunden.
suchenersetzen=Suchen & Ersetzen
suchenersetzeninpersonendaten=Suchen & Ersetzen in Personendaten
vornamederhauptpersonunddespartners=Vorname der Hauptperson und des Partners
nachnamederhauptpersonunddespartners=Nachname der Hauptperson und des Partners
anredetitel=Anrede / Titel
anredeundtitel=Anrede und Titel
straszligeadresszusatzundland=Stra\u00DFe, Adresszusatz und Land
plzortundplzpostfach=PLZ / Ort und PLZ / Postfach
telefontelefaxundmobiltelefon=Telefon, Telefax und Mobiltelefon
telefonfax=Telefon / Fax
emailadresse=E-Mail Adresse
internetadresse=Internet-Adresse
ihresuchemussausmindestenseinembuchstabenbestehen=Ihre Suche muss aus mindestens einem Buchstaben bestehen.
siemuessenmindestenseinfeldausgewhlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersonersetzt=Es wurde keine Person ersetzt.
eswurdeeinepersonersetzt=Es wurde eine Person ersetzt.
personenersetzt=Personen ersetzt.
siemuessenmindestenseinfeldausgewaehlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersongefunden=Es wurde keine Person gefunden.
eswurdeeinepersongefunden=Es wurde eine Person gefunden.
personengefunden=Personen gefunden.
einzelneeinzraegezumersetzenselektieren=Einzelne Einzr\u00E4ge zum Ersetzen selektieren
allesofortersetzen=Alle sofort ersetzen
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=Wenn Sie den Platzhalter * verwenden, werden auch Teilst\u00FCcke ersetzt, sonst nur vollst\u00E4ndige Datenfelder.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=Sie m\u00FCssen das Datum des Zeitrahmens im Format TT.MM.JJJJ angeben
markierteanredenloschen=Markierte Anrede(n) l\u00F6schen
markiertendokumenttypenloschen=Markierte Dokumenttyp(en) l\u00F6schen
markierteveranstaltungsorteloschen=Markierte Veranstaltungsorte l\u00F6schen
markiertevorlagenloschen=Markierte Vorlagen l\u00F6schen
# ----------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Status
CAP_TO=An
GENERIC_SUBJECT=Betreff
GENERIC_ERROR=Fehler
e-mails=E-Mails
technischefehlermeldungeinblenden=Technische Fehlermeldung einblenden
fehlerbeschreibung=Fehlerbeschreibung

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=E-Mail-Vorlagen
markiertevorlage=Markierte Vorlage(n)
neuevorlageanlegen=Neue Vorlage anlegen
namedervorlage=Name der Vorlage
eswurdeeineneuevorlageangelegt=Es wurde eine neue Vorlage angelegt.
text=Text
platzhalter=Platzhalter
hinzufugen=Hinzuf\u00FCgen
zuruckzurvorlagenliste=Zur\u00FCck zur Vorlagenliste

# ADMINISTRATION/FARBEN
farben=Farben
farbwert=Farbwert
LETTERS_RED_GREEN_BLUE=R G B
inlandjageschlechtweiblich=Inland: Ja - Geschlecht: Weiblich
inlandjageschlechtmannlich=Inland: Ja - Geschlecht: M\u00E4nnlich
inlandneingeschlechtweiblich=Inland: Nein - Geschlecht: Weiblich
inlandneingeschlechtmannlich=Inland: Nein - Geschlecht: M\u00E4nnlich

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=Markierte Bezeichnung(en)
bezeichnung=Bezeichnung
eswurdeeineneuefunktion/amtsbezeichnungangelegt=Es wurde eine neue Funktion/Amtsbezeichnung angelegt.
eswurdeeinefunktion/amtsbezeichnunggeloscht=Es wurde eine Funktion/Amtsbezeichnung gel\u00F6scht.

# ADMINISTRATION/KATEGORIEN
kategorien=Kategorien
markiertekategorie=Markierte Kategorie(n)
kennzeichen=Kennzeichen
rang=Rang
veranstaltungen=Veranstaltung(en)
kategorie=Kategorie
ereignis=Ereignis

# ADMINISTRATION/MANDANTEN
mandanten=Mandanten
markierte(n)mandanten=Markierte(n) Mandanten
nichtmandantenzugeordnetedaten=Nicht Mandanten zugeordnete Daten
personen=Personen
importvorgange=Import Vorg\u00E4nge
veranstaltungorte=Veranstaltungorte
importpersonen=Import Personen
verteiler=Verteiler
benutzer=Benutzer
mandantenzuordnen=Mandanten zuordnen
mandant=Mandant

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=Programeinstellungen
standardauswahlvontabulatoren=Standard Auswahl von Tabulatoren
haupttabs=Haupttabs
personendaten=Personendaten
anschriften=Anschriften
subtabsvonpersonendaten=Subtabs von \u00E2\u0080\u009EPersonendaten\u00E2\u0080\u009C
hauptperson=Hauptperson
partner=Partner
subtabsvonanschriften=Subtabs von \u00E2\u0080\u009EAnschriften\u00E2\u0080\u009C
geschaftlich=Gesch\u00E4ftlich
standardauswahlderselectboxzeichensatz=Standard Auswahl der Selectbox \u00E2\u0080\u009EZeichensatz\u00E2\u0080\u009C
zeichensatz=Zeichensatz
standardanredenundfreitextfelder=Standard-Anreden und Freitextfelder
standardanrede=Standard-Anrede
standardanredepartner=Standard-Anrede Partner
freitextfeldverbinder=Freitextfeld-Verbinder
freitextfeldanzeige=Freitextfeld (Anzeige)
freitextfeldgasteliste=Freitextfeld (G\u00E4steliste)
hilfe=Hilfe
hilfelink=Hilfe-Link
hilfefenster=Hilfe-Fenster
aktuellesbrowserfensterverwenden=Aktuelles Browser-Fenster verwenden
proaufrufeinneuesbrowserfensteroffnen=Pro Aufruf ein neues Browser-Fenster \u00F6ffnen
beijedemaufrufdasselbebrowserfensternichtdasaktuelle=Bei jedem Aufruf das selbe Browser-Fenster (nicht das aktuelle)
sonstiges=Sonstiges
faxdnfaxaa=Fax-DN (@fax.aa)
anderungsprotokoll=\u00E4nderungsprotokoll
vorhaltezeitderprotokolldaten=Vorhaltezeit der Protokolldaten
gebensiedieaufbewahrungsfristein=Geben Sie die Aufbewahrungsfrist ein
GENERIC_YEARS=Jahre
GENERIC_MONTHS=Monate
GENERIC_DAYS=Tage
anschriftgeschaftlich=Anschrift Gesch\u00E4ftlich
anschriftprivat=Anschrift Privat
anschriftweitere=Anschrift Weitere
zeichensatzlatein=Zeichensatz Latein
zeichensatzalternative1=Zeichensatz Alternative 1
zeichensatzalternative2=Zeichensatz Alternative 2
adresszusatz1=Adresszusatz 1
adresszusatz2=Adresszusatz 2

# ADMINISTRATION/REPORTS
reports=Reports
abhangigvomausgewahltenzeitraumundderdarausresultierendenanzahldatenkanndieerzeugungdesberichtsrelativlangedauernhabensiebitteeinweniggeduld=Abh\u00E4ngig vom ausgew\u00E4hlten Zeitraum und der daraus resultierenden Anzahl von Daten, kann die Erzeugung des Berichts relativ lange dauern. Haben Sie bitte ein wenig Geduld.
datumbeginn=Datum Beginn
datumende=Datum Ende
felderzurucksetzen=Felder zur\u00FCcksetzen
reporterzeugen=Report erzeugen

# ADMINISTRATION/STELLVERTRETUNGEN
stellvertretungen=Stellvertretungen
gultigkeitsfilter=G\u00FCltigkeitsfilter
allevertretungen=Alle Vertretungen
keineabgelaufenenvertretungen=Keine abgelaufenen Vertretungen
nuraktuellevertretungen=Nur aktuelle Vertretungen
rolle=Rolle
vertreter=Vertreter
gultigab=G\u00FCltig ab
gultigbis=G\u00FCltig bis
keinedatengefunden=Keine Daten gefunden.

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Markierte(n) Veranstaltungsort(e)
neuenveranstaltungsorthinzufugen=Neuen Veranstaltungsort hinzuf\u00FCgen
id=ID
ansprechpartner=Ansprechpartner
telefon=Telefon
fax=Fax
e-mail=E-Mail
bemerkung=Bemerkung
url=URL
gps-daten=GPS-Daten
raumnummer=Raumnummer
EVENT_PLACES_CONFIRM_DELETE=Bitte best\u00E4tigen Sie das L\u00F6schen von Veranstaltungsorten

# VERWALTUNG/EINSTELLUNGEN
verwaltung=Verwaltung
einstellungen=Einstellungen
personendetailansicht=Personendetailansicht
gasteliste=G\u00E4steliste
zusatzlichefelder=Zus\u00E4tzliche Felder
funktion=Funktion
plz/ort=PLZ / Ort
personenliste=Personenliste
bundesland=Bundesland
einstellungenwurdenerfolgreichgespeichert=Einstellungen wurden erfolgreich gespeichert.

# VERWALTUNG/VERTRETUNGEN
vertretungen=Vertretungen
markiertevertretung=Markierte Vertretung(en)
loschen=L\u00F6schen
neu=Neu
eswurdeeineneuevertretungangelegt=Es wurde eine neue Vertretung angelegt
eswurdeeinevertretunggeloscht=Es wurde eine Vertretung gel\u00E4scht
siemuseneinevertretereingeben=Sie m\u00FCssen eine Vertreter eingeben
derbeginndervertretungmusvordemendeliegen=Der Beginn der Vertretung muss vor dem Ende liegen
eswurden=Es wurden
vertretungengeloscht=Vertretungen gel\u00E4scht
# VERWALTUNG/INFO
info=Info
informationenzuveraweb=Informationen zu VerA.web
veraweb=VerA.web
version=Version
build=Build
datenbank=Datenbank
login=Login
gruppen=Gruppen
nichtverfugbar=Nicht verf\u00FCgbar

# ALLGEMEIN
siesindhier=Sie sind hier
home=Home

# TABELLEN
datum=Datum
arbeitsbereich=Arbeits&shy;bereich
nachname=Nachname
vorname=Vorname
amtsbezeichnung=Amtsbe&shy;zeichnung
firmainstitution=Firma / Institution
strasse=Stra\u00DFe
plz=PLZ
ort=Ort
markiertepersonen=Markierte Person(en)
expotieren=Expotieren
kategorienzuordnen=Kategorien zuordnen
kategorienentfernen=Kategorien entfernen
arbeitsbereichzuordnen=Arbeitsbereich zuordnen
arbeitsbereichentfernen=Arbeitsbereich entfernen
durchfuhren=Durchf\u00FChren
personenanzahlproseite=Personen | Anzahl pro Seite
alle=Alle
seite=Seite
geburtsdatum=Geburtsdatum
geburtsort=Geburtsort
nationalitat=Nationalit\u00E4t
staatsangehorigkeit=Staatsangeh\u00E4rigkeit
sprachen=Sprachen
hinweisfurgastgeber=Hinweis f\u00FCr Gastgeber
akkreditierungsdatum=Akkreditierungsdatum
um=Um
uhr=Uhr
datenherkunft=Datenherkunft
person=Person

# DATEITYP
csv=CSV (Comma-Separated-Values)
xml=XML (VerA.web-XML)
zkm=ZKM (VerA.web-XML \u00FCber das Zentrale Kommunikationsmodul)
madlan-personen=MAdLAN-Personen (MAdLAN-Personen-Import)
madlan-firmen=MAdLAN-Firmen (MAdLAN-Firmen-Import)
x-manage-csv=X-Manage-CSV (X-Manage Kontakte)
csvpersdatanschriftdoktyp=CSVPersdat+Anschrift+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp=CSVPersdat+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp10=CSVPersdat+Doktyp 1.0 (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Kategorien (Comma-Separated-Values)
csviso885915=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)

# PERSONEN/PERSONENUEBERSICHT
personenubersicht=Personen\u00FCbersicht
personensuchen=Personen suchen
neuepersonanlegen=Neue Person anlegen
personengeloscht=Personen gel\u00F6scht

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
personbearbeiten=Person bearbeiten
erfasstam=Erfasst am
zuletztgeandertam=Zuletzt ge\u00E4ndert am
personen-id=Personen-ID
online-anmeldungbenutzername=Online-Anmeldung Benutzername
freifeld-vorschaufuretikett="Freifeld-Vorschau f\u00C3\u00BCr \u00E2\u0080\u009EEtikett\u00E2\u0080\u009C"
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=Zu dieser Person wurde das entsprechende Vorschaufeld noch nicht erzeugt.
personkopieren=Person kopieren
etiketterzeugen=Etikett erzeugen
einerveranstaltungzuordnen=Einer Veranstaltung zuordnen
personloschen=Person l\u00E4schen
statistik=Statistik
ausstammdatenhinzufugen=Aus Stammdaten hinzuf\u00FCgen

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
dokumenttyp=Dokumenttyp
alleerzeugen=Alle erzeugen

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
kategorienundereignisse=Kategorien und Ereignisse

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=\u00FCbersicht \u00FCber alle Veranstaltungen eines Gastes.
ab=Ab
statistikfurgast=Statistik f\u00FCr Gast
veranstaltung=Veranstaltung
beginn=Beginn

# PERSONEN/PERSONENSUCHE
personensuche=Personensuche
suche=Suche
gultigkeitsdatum=G\u00FCltigkeitsdatum
erweitertesuche=Erweiterte Suche
HINT_PLACEHOLDER=Hinweis Sie k\u00E4nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen. Die Suche erfolgt im Vornamen, Nachnamen, Ort, PLZ, Stra\u00DFe, Firma/Institution, Telefon, Fax, Mobil, E-Mail, Bemerkungen, Kategorien, Arbeitsbereiche und Amtsbezeichnung/Funktion.

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=Die Anmeldedaten wurden erfolgreich erzeugt.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Anmeldedaten f\u00FCr diese Person sind bereits vorhanden.

# PERSONEN/NEUE PERSON ANLEGEN
istfirma=Ist Firma
anrede=Anrede
frau=Frau
herr=Herr
lady=Lady
sir=Sir
bittewahlensie=Bitte w\u00E4hlen Sie
akadtitel=Akad. Titel
inland=Inland
hinweisfurorga=Hinweis f\u00FCr Orga
firma=Firma
land=Land
plz/postfach=PLZ / Postfach
iban=IBAN
bic=BIC
mobil=Mobil
www=WWW
dublettenprufungdurchfuhren=Dublettenpr\u00FCfung durchf\u00FChren
zurpersonenubersicht=Zur Personen\u00FCbersicht

# PERSONEN/SUCHEN & ERSETZEN IN PERSONENDATEN
suchen&ersetzeninpersonendaten=Suchen & Ersetzen in Personendaten
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=Hinweis Wenn Sie den Platzhalter * verwenden, werden auch Teilst\u00FCcke ersetzt, sonst nur vollst\u00E4ndige Datenfelder.
suchen=Suchen
ersetzen=Ersetzen
infolgendenfeldern=In folgenden Feldern
anrede/titel=Anrede / Titel
freitextfelder=Freitextfelder
amtsbezeichn=Amtsbezeichn.
institution=Institution
adresse=Adresse
telefon/fax=Telefon / Fax
einzelnersetzen=Einzeln ersetzen
alleersetzen=Alle ersetzen

# PERSONEN/DUBLETTENSUCHE
dublettensuche=Dublettensuche

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Export von Personendaten
HINT_EXPORT_MANDANT_PERSON=Sie exportieren mit dieser Funktion ausschlie\u00DFlich Personen aus Ihrem aktuellen Mandanten.
ohne=Ohne
botschaften=Botschaften
finanzamtsprecher=Finanzamtsprecher
journalisten=Journalisten
lieferant=Lieferant
nogs=NOGs
politik=Politik
pressevertreter=Pressevertreter
wirtschaft=Wirtschaft
HINT_EXPORT_OPEN_DATA=Je nach Menge der exportierten Felder (insbesondere ist dies von der Anzahl exportierter Dokumenttypen und Kategorien abh\u00E4ngig) kann es passieren, dass MS Excel und OO Calc die exportierten Daten nicht vollst\u00E4ndig lesen k\u00E4nnen.
exportstarten=Export starten

# PERSONEN/IMPORT VON PERSONENDATEN
importvonpersonendaten=Import von Personendaten
HINT_IMPORT_SHORT_CONTENT=Hinweis Beim Import k\u00E4nnen Feldinhalte, die l\u00E4nger als bei VerA.web vorgesehen sind, gek\u00FCrzt \u00FCbernommen werden.
zielmandant=Zielmandant
importdatei=Import-Datei
dateityp=Dateityp
dateiauswahlen=Datei ausw\u00E4hlen
keineausgewahlt=Keine ausgew\u00E4hlt
importstarten=Import starten

# PERSONENDROPDOWN
neueperson=Neue person
suchen&ersetzen=Suchen & ersetzen
personenexport=Personenexport
personenimport=Personenimport

# VERANSTALTUNGENDROPDOWN
veranstaltungsubersicht=Veranstaltungs\u00FCbersicht
veranstaltunguuche=Veranstaltungssuche
neueveranstaltung=Neue Veranstaltung
statistiken=Statistiken

# ADMINISTRATIONDROPDOWN
anreden=Anreden
arbeitsbereiche=Arbeitsbereiche
dokumenttypen=Dokumenttypen
e-mail-postausgang=E-Mail-Postausgang
programmeinstellungen=Programmeinstellungen
veranstaltungsorte=Veranstaltungsorte

# VERANSTALTUNGSUEBERSICHT
ende=Ende
gastgeber=Gastgeber
veranstaltungsort=Veranstaltungsort
veranstaltungsuchen=Veranstaltung suchen
neueveranstaltunganlegen=Neue Veranstaltung anlegen
anzahlproseite=Anzahl pro seite
seitexvony=Seite x von y

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
veranstaltungbearbeiten=Veranstaltung bearbeiten
veranstaltungs-id=Veranstaltungs-id
veranstaltungsname=Veranstaltungsname
veranstaltungsurl=Veranstaltungs-URL
urlfurpressevertreter=URl f\u00FCr pressevertreter
zurgasteverwaltung=Zur G\u00E4steverwaltung
allgemein=Allgemein
aufgaben=Aufgaben
zusatzlichepersonendaten=Zus\u00E4tzliche Personendaten
kurzbereichnung=Kurzbereichnung
einladungsart=Einladungsart
offeneveranstaltung=Offene Veranstaltung
umxuhr=Um x uhr
maximalanzahlgaste=Maximal Anzahl G\u00E4ste
veranstalgungsort=Veranstalgungsort
gastgebersuchen=Gastgeber suchen
gastgeberentfernen=Gastgeber entfernen
gastgeberpartner=Gastgeber-Partner
loginnotwendig=Login notwendig
anmeldungvonpressevertreternmoglich=Anmeldung von Pressevertretern m\u00F6glich
veranstaltungspeichern=Veranstaltung speichern
zurveranstaltungsubersicht=Zur Veranstaltungs\u00FCbersicht

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
markiertedokumenttypen=Markierte Dokumenttypen
entfernen=Entfernen
neuendokumenttyphinzufugen=Neuen Dokumenttyp hinzuf\u00FCgen
xvonydokumenttypen=x von y Dokumenttypen

# VERANSTALTUNG BEARBEITEN/AUFGABEN
neueaufgabeanlegen=Neue Aufgabe anlegen
esliegenkeineaufgabenfurdieseveranstaltungvor=Es liegen keine Aufgaben f\u00FCr diese Veranstaltung vor
ausgewahlteeintrage=Ausgew\u00E4hlte Eintr\u00E4ge
titel=Titel
verantwortlicher=Verantwortlicher

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
aufgabenid=Aufgaben-ID
fertigstellung=Fertigstellung
prioritat=Priorit\u00E4t
beschreibung=Beschreibung
verantwortlichenhinzufugen=Verantwortlichen hinzuf\u00FCgen
verantwortlichenentfernen=Verantwortlichen entfernen
aufgabespeichern=Aufgabe Speichern
zuruckzuraufgabenubersicht=Zur\u00FCck zur Aufgaben\u00FCbersicht

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
neueamtsbezeichnunghinzufugen=Neue Amtsbezeichnung Hinzuf\u00FCgen
eswurdenkeineamtsbezeichnungengefunden=Es wurden keine Amtsbezeichnungen gefunden.

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
neuekategoriehinzufugen=Neue Kategorie hinzuf\u00FCgen

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
GENERIC_PRECONDITION_PLURAL=Vorbedingungen
EVENT_PRECONDITION_MARKED=Markierte Vorbendingung(en)
EVENT_PRECONDITION_ADD=Vorbedingung hinzuf\u00FCgen
EVENT_PRECONDITION_INVITATIONSTATUS=Teilnahmestatus
EVENT_PRECONDITION_STARTDATE=Startdatum
EVENT_PRECONDITION_NOT_FOUND=Es wurden keine Vorbedingungen gefunden

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Nur in zuk\u00FCnftigen Veranstaltungen suchen
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere das ? f\u00FCr einzelne

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=Mit Partner
eswurdeeineneueveranstaltungangelegt=Es wurde eine neue Veranstaltung angelegt.

# VERTEILER
angelegtvon=Angelegt von
angelegtam=Angelegt am
erzeugtausveranstaltung=Erzeugt aus Veranstaltung

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=Statistik auf folgenden Zeitrahmen einschr\u00E4nken
statistiktypauswahlen=Statistiktyp ausw\u00E4hlen
zeitrahmenbeginn=Zeitrahmen-beginn
zeitrahmenende=Zeitrahmen-ende
STATISTIC_RADIO_PER_YEAR=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Jahr
STATISTIC_RADIO_PER_MONTH=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Monat
STATISTIC_RADIO_GROUPED_BY_HOST=Gesamt\u00FCbersicht \u00FCber alle Veranstaltungen, gruppiert nach Gastgeber
STATISTIC_RADIO_PER_HOST=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastgebers (mit Suche)
STATISTIC_RADIO_PER_GUEST=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastes (mit Suche)
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=\u00DCbersicht \u00FCber alle Veranstaltungen sortiert nach Veranstaltungsort
statistikerstellen=Statistik erstellen

# GAESTEVERWALTUNG DER VERANSTALTUNG
gasteverwaltungderveranstaltung=G\u00E4steverwaltung der Veranstaltung
maxanzahlgaste=Max. Anzahl G\u00E4ste
gastedetails=G\u00E4stedetails
offen=Offen
zusagen=Zusagen
absagen=Absagen
teilnahmen=Teilnahmen
aufplatz=Auf Platz
aufreserve=Auf Reserve
filter=Filter
platzwahl=Platzwahl
lfdnr=Lfd.-nr.
nichteingeladen=Nicht eingeladen
laufendenummerberechnen=Laufende Nummer berechnen
allestammdatenneuladen=Alle Stammdaten neu laden
HINT_ENTRY_POINT=Direkteinsprung: ist nur bei einer Sortierung nach Name, Vorname oder E-Mail m\u00F6glich.
HINT_GUEST_MANAGEMENT_FILTER=Beim Erstellen von Steuerdateien oder G\u00E4stelisten wird Ihr oben ausgew\u00E4hlter Filter ber\u00FCcksichtigt.
HINT_GUEST_MANAGEMENT_MARKED=Wenn Sie einzelne G\u00E4ste markieren, werden nur diese exportiert, ansonsten die vollst\u00E4ndige Liste.

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=G\u00E4steliste erstellen
SELECT_OUTPUT_FORMAT=Ausgabeformat w\u00E4hlen
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=Liste nach Kategorien gruppiert - mit Partner
LIST_GROUP_BY_CATEGORY_WITH_TEL=Liste nach Kategorien gruppiert - mit Tel. und Mobiltelefon
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=Liste nach Kategorien gruppiert - mit Partner und Fax
LIST_SORT_PARTNER_TEL=Liste nach sortierung -mit Partner, Tel. und Mobiltelefon
SORT_CRITERIA=Sortierkriterien
SORT_AFTER=Sortieren nach
CONTINUAL_NUMBER=Laufende nummer
anschliesendnach=Anschlie\u00DFend nach
zusatzlichesortierungnach=Zus\u00E4tzliche sortierung nach

# GASTDETAILS
gastdetails=Gastdetails
HINT_GUEST_LIST_EDIT_PERSONDATA=Sie bearbeiten hier ausschlie\u00DFlich Personendaten im Rahmen der aktuellen Veranstaltung, keine grundlegenden Stammdaten.
istgastgeber=Ist Gastgeber
reserve=Reserve
aufstammdatenzurucksetzen=Auf Stammdaten zur\u00FCcksetzen
stammdatenbearbeiten=Stammdaten bearbeiten

# DOKUMENTTYPEN
dokumenttypwahlen=Dokumenttyp w\u00E4hlen
mitgliedsausweis=Mitgliedsausweis
etikett=Etikett
tischkarte=Tischkarte
adresstypundzeichensatzwahlen=Adresstyp und Zeichensatz w\u00E4hlen
adresstyp=Adresstyp
datenbearbeiten=Daten bearbeiten
verbinder=Verbinder
freitextfeld=Freitextfeld
freitextfeldpartner=Freitextfeld (Partner)
akatitel=Aka. Titel (Partner)
kontaktdaten=Kontaktdaten
strase=Stra\u00DFe
postfachplz=Postfach PLZ
nummer=Nummer
zuruckzudenveranstaltungsdetails=Zur\u00FCck zu den Veranstaltungsdetails

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Dokumenttyp bearbeiten
dokument-id=Dokument-ID
dokument-name=Dokument-Name
dokumenttypspeichern=Dokumenttyp speichern
zuruckzurdokumenttypenliste=Zur\u00FCck zur Dokumenttypenliste
anmeldedatenerzeugen=Anmeldedaten erzeugen
esliegenkeinekategorienundereignissevor=Es liegen keine Kategorien und Ereignisse vor
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=Bei gr\u00FCn hinterlegten Eintr\u00E4gen handelt es sich um wiederkehrende Ereignisse.

# SUCHEN & ERSETZEN IN PERSONENDATEN

# VERTEILERDETAILS
verteilerdetails=Verteilerdetails
verteilerversenden=Verteiler versenden
e-mail-clientaufrufen=E-Mail-Client aufrufen

# FEHLEND
zurstartseite=Zur Startseite
solldieneuekategorie=Soll die neue Kategorie
einsortiertwerden=einsortiert werden?
pflichtfelder=Pflichtfelder
markiertekategorienloschen=Markierte Kategorien l\u00F6schen
alledemarkieren=Alle (de)markieren
furalleveranstaltungen=F\u00FCr alle Veranstaltungen
speichern=Speichern
anderungsprotokollfurdenzeitraum=\u00C4nderungsprotokoll f\u00FCr den Zeitraum
objekt=Objekt
objektid=Objekt-Id
artderanderung=Art der \u00C4nderung
geandertefelder=Ge\u00E4nderte Felder
datumauswahlen=Datum ausw\u00E4hlen
folgendeaktionen=Folgende Aktionen
wurden=WURDEN
durchgefuhrt=durchgef\u00FChrt
konnen=K\u00D6NNEN
aktuallisieren=Aktuallisieren
cleanupjetztunwiderruflichdurchfuhren=Cleanup jetzt unwiderruflich durchf\u00FChren.
essindderzeitkeinecleanupsmoglichnotig=Es sind derzeit keine Cleanups m\u00F6glich / n\u00F6tig.
nochkeineauswahlgetroffen=Noch keine Auswahl getroffen
oberflachenbeschriftungen=Oberfl\u00E4chenbeschriftungen
zusatzfelder=Zusatzfelder
eswurdeeinzusatzfeld=Es wurde ein Zusatzfeld
angelegt=angelegt
geandert=ge\u00E4ndert
geloscht=gel\u00F6scht
feldbezeichnung=Feldbezeichnung
eingabetyp=Eingabetyp
erfolgreichgespeichert=Erfolgreich gespeichert!
markiertendokumenttypen=Markierte(n) Dokumenttyp(en)
eigenesdokumentfurpartner=Eigenes Dokument f\u00FCr Partner
sortierreihenfolge=Sortierreihenfolge
gastgebermitausgeben=Gastgeber mit Ausgeben
iststandardfursteuerdatei=Ist Standard f\u00FCr Steuerdatei
format=Format
HINT_EXPORT_FORMAT=OOo 1.1 steht f\u00FCr OpenOffice 1.1 (sxc-Datei) und OOo 2.0 f\u00FCr OpenOffice 2.0 (ods-Datei),xls steht f\u00FCr Microsoft Office (xls-Datei) und CSV steht f\u00FCr CSV-Dateiformat.
HINT_EVENT_IDENTIFICATION=Kennz. 50 und 99 werden autom. neuen Veranstaltungen hinzugef\u00FCgt. Beim Kennz. 50 wird kein Freitextfeld erzeugt.
wirklichloschen=Wirklich l\u00E4schen
zumpersonenimport=Zum Personen-Import
importstatus=Importstatus
importstatusvorhandenedublettenbearbeiten=Importstatus: vorhandene Dubletten bearbeiten
bittemarkierensiediezuimportierendenpersonen=Bitte markieren Sie die zu importierenden Personen.
dublettendiedurchden=Dubletten, die durch den
importhinzugefugtwerdenwurden=Import hinzugef\u00FCgt werden w\u00FCrden
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=, sind mit einer Checkbox gekennzeichnet.Darunter befinden sich die bereits im System vorhandenen, entsprechenden Datens\u00E4tze.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=Um eine Dublette in den Import zu integrieren, m\u00FCssen Sie sie \u00FCbernehmen.
alsdubletteubernehmen=Als Dublette \u00FCbernehmen
markiertepersonenalsdubletteubernehmen=Markierte Person(en) als Dublette \u00FCbernehmen
anzahlzuspeicherndedubletten=Anzahl zu speichernde Dubletten
eswurdenkeineeintragegefunden=Es wurden keine Eintr\u00E4ge gefunden.
zuruckzumpersonenimport=Zur\u00FCck zum Personenimport
fehlermeldung=Fehlermeldung
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=Bei der Bearbeitung Ihrer Anfrage ist ein Fehler aufgetreten.Bitte melden Sie dies Ihrem Administrator.
unbekannterfehler=Unbekannter Fehler.
markiertenkategorien=Markierte(n) Kategorie(n)
markiertenkategorienentfernen=Markierte(n) Kategorie(n) entfernen
bitteauswahlen=Bitte ausw\u00E4hlen
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=Die Veranstaltung, an der Sie gerade gearbeitet haben, wurde von einem anderen Anwender gel\u00F6scht.Sie k\u00F6nnen nun eine neue Veranstaltung anlegen oder anderweitig mit VerA.web arbeiten.
bittebestatigensiedasspeicherndieserveranstaltung=Bitte best\u00E4tigen Sie das Speichern dieser Veranstaltung
keingastgeberausgewahlt=Kein Gastgeber ausgew\u00E4hlt
kurzbezeichnung=Kurzbezeichnung
maximalelangederwarteliste=Maximale L\u00E4nge der Warteliste
sollendiestammdatenumdiesenorterweitertwerden=Sollen die Stammdaten um diesen Ort erweitert werden
markiertendokumenttypenentfernen=Markierte(n) Dokumenttyp(en) entfernen
eswurdenkeinedokumenttypengefunden=Es wurden keine Dokumenttypen gefunden.
markiertenamtsbezeichnungen=Markierte(n) Amtsbezeichnung(en)
markiertenamtsbezeichnungenentfernen=Markierte(n) Amtsbezeichnung(en) entfernen
zurveranstaltungssuche=Zur Veranstaltungssuche
veranstaltungssuche=Veranstaltungssuche
suchergebnis=Suchergebnis
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=Bitte klicken Sie eine der aufgelisteten Veranstaltungen an, um die G\u00E4ste zu \u00FCbernehmen.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=Bitte klicken Sie eine der aufgelisteten Veranstaltungen an, um die Person dieser Veranstaltung zuzuordnen.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=Bitte klicken Sie eine der aufgelisteten Personen an um diese als Gastgeber zu \u00E4bernehmen.
loschenvonveranstaltungenistnichtmoglich=L\u00F6schen von Veranstaltungen ist nicht m\u00F6glich
weiteremeldungen=weitere Meldungen.
bittebestatigensiedasloschendermarkiertenveranstaltungen=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Veranstaltungen!
markierteveranstaltungloschen=Markierte Veranstaltung l\u00F6schen
abbrechen=Abbrechen
markierteveranstaltungen=Markierte Veranstaltung(en)
markierteveranstaltungenloschen=Markierte Veranstaltungen l\u00F6schen
zuruckzurgasteverwaltung=Zur\u00FCck zur G\u00E4steverwaltung
zuruckzurveranstaltungssuche=Zur\u00FCck zur Veranstaltungssuche
wahlensiebittezunachsteineodermehrereveranstaltungenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Veranstaltungen aus.
nurinzuunftigenveranstaltungensuchen=Nur in zuk\u00FCnftigen Veranstaltungen suchen
zuruck=Zur\u00FCck
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen.
bittebestatigensiedasspeicherndieseraufgabe=Bitte best\u00E4tigen Sie das Speichern dieser Aufgabe
verantworlichenhinzufugen=Verantworlichen hinzuf\u00FCgen
verantworlichenentfernen=Verantworlichen entfernen
loschenvonaufgabenistnichtmoglich=L\u00F6schen von Aufgaben ist nicht m\u00F6glich
bittebestatigensiedasloschenvonaufgaben=Bitte best\u00E4tigen Sie das L\u00F6schen von Aufgaben
ausgewahlteeintrageloschen=Ausgew\u00E4hlte Eintr\u00E4ge l\u00F6schen
start=Start
zursuche=Zur Suche
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=Sie sind als "Voll-Administrator" angemeldet und exportieren hiermit Mandanten\u00FCbergreifend.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=Sie exportieren mit dieser Funktion ausschlie\u00DFlich Personen aus Ihrem aktuellen Mandanten.
event=Veranstaltung
keine=Keine
category=Kategorie
weitereoptionen=Weitere Optionen
anmerkung=Anmerkung
anmerkungen=Anmerkungen
markiertebezeichnunge=Markierte Bezeichnung(e)
markierteeintrageentfernen=Markierte Eintr\u00E4ge entfernen
eswurdenkeinedatengefunden=Es wurden keine Daten gefunden
siehabenkeinedatenherkunftangegeben=Sie haben keine Datenherkunft angegeben.
HINT_EXPORT_NOT_POSSIBLE_OPENOFFICE=Sie haben versucht eine OpenOffice-Datei zu importieren.Der direkte Import ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_EXPORT_NOT_POSSIBLE_STAROFFICE=Sie haben versucht eine StarOffice-Datei zu importieren.Der direkte Import ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_EXPORT_NOT_POSSIBLE_EXCEL=Sie haben versucht eine Microsoft Excel-Datei zu importieren.Der direkte Import von Excel-Dokumenten ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_IMPORT_NOT_POSSIBLE_PDF=Sie haben versucht eine PDF-Datei zu importieren.Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
HINT_IMPORT_NOT_POSSIBLE_ZIP=Sie haben versucht eine ZIP-Datei zu importieren.Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
HINT_IMPORT_NOT_POSSIBLE_EXE=Sie haben versucht eine EXE-Datei zu importieren.Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
siehabenversuchteinedateimitderendung=Sie haben versucht eine Datei mit der Endung
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=zu importieren. Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
siehabenkeinedateiausgewahltoderdiesewarleer=Sie haben keine Datei ausgew\u00E4hlt oder diese war leer.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=Es ist ein unerwarteter Fehler beim importieren einer Datei aufgetreten.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Vermutlich befindet sich die Import-Datei nicht im vom System erwartem Format.
detailsanzeigen=Details anzeigen
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=Beim Import k\u00F6nnen Feldinhalte, die l\u00E4nger als bei VerA.web vorgesehen sind, gek\u00FCrzt \u00FCbernommen werden.
alledokumenttypenderzuimportierendenpersonenmussenimsystemvorhandenseinsollderimportjetztgestartetwerden=Alle Dokumenttypen der zu importierenden Personen m\u00FCssen im System vorhanden sein. Soll der Import jetzt gestartet werden?
umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=Um Dubletten speicherbar zu machen, m\u00C3\u00BCssen sie zun\u00C3\u00A4chst im Bereich \u00E2\u0080\u009Evorhandene Dubletten\u00E2\u0080\u009C \u00C3\u00BCbernommen werden.
HINT_UMLAUT_COMPARISON=Beachten Sie, dass \u00E4 mit ae, \u00F6 mit oe, \u00FC mit ue und \u00DF mit ss verglichen wird.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=Der Import ist erst beendet, wenn der Button \u00E2\u0080\u009EImport abschlie\u00C3\u009Fen\u00E2\u0080\u009C geklickt wurde.
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=Der Import kann erst abgeschlossen werden, wenn speicherbare Datens\u00E4tze vorhanden sind.
vorhandenedubletten=Vorhandene Dubletten
vorhandenedublettenbearbeiten=Vorhandene Dubletten bearbeiten
zuimportierendedatensatzeinsgesamt=Zu importierende Datens\u00E4tze insgesamt
davondubletten=Davon Dubletten
davonspeicherbar=Davon speicherbar
ignoriertefehlerdatensatze=Ignorierte Fehlerdatens\u00E4tze
importabschlieszen=Import abschlie\u00DFen
siehabenkeinendatensatzimportiert=Sie haben keinen Datensatz importiert.
siehabeneinendatensatzimportiert=Sie haben einen Datensatz importiert.
siehaben=Sie haben
datensatzeimportiert=Datens\u00E4tze importiert.
informationennichtverfugbar=Informationen nicht verf\u00FCgbar
nichtgewahlt=Nicht gew\u00E4hlt
verfugbarerollen=Verf\u00FCgbare Rollen
passowrt=Passwort
inverteretunganmelden=In Vertretung anmelden
vornamenachname=Vorname.Nachname
alsbenutzernamen=Als Benutzernamen
emailvorlage=E-Mail-Vorlage
amtsbezfunktion=Amtsbez./Funktion
postfachnummer=Postfach Nummer
email=E-Mail
verteileranlegen=Verteileranlegen
sielegeneinenneuenverteilerausderveranstaltung=Sie legen einen neuen Verteiler aus der Veranstaltung
mit=mit
einerperson=einer Person
verteilername=Verteilername
verteilerspeichern=Verteiler speichern
markierteadressen=Markierte Adresse(n)
markierteadressenausdemverteilerloschen=Markierte Adresse(n) loschen
analleadressenversenden=An alle Adressen versenden
emailclientaufrufen=E-Mail-Client aufrufen
esliegenkeineadressdatenfurdiesenverteilervor=Es liegen keine Adressdaten f\u00FCr diesen Verteiler vor.
esliegenkeineadressenfurdiesenverteilervor=Es liegen keine Adressen f\u00FCr diesen Verteiler vor.
esliegenkeinevorlagenvor=Es liegen keine Vorlagen vor.
zuruckzurverteilerubersicht=Zur\u00FCck zur Verteiler\u00FCbersicht
eswurdekeineemailzumversendengespeichert=Es wurde keine E-Mail zum Versenden gespeichert
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=Es wurde eine E-Mail automatisch gespeichert. Diese wird nun automatisch versendet.
emailszumversendengespeichertdiesewerdennunautomatischversendet=E-Mails zum Versenden automatisch gespeichert. Diese werden nun automatisch versendet.
markiertenverteiler=Markierte(n) Verteiler
markierteverteilerloschen=Markierte Verteiler l\u00F6schen
persondendaten=Persondendaten
solldiesergastaufplatzgesetztwerden=Soll dieser Gast auf Platz gesetzt werden?
solldiepartnerinderpartnermiteingeladenwerden=Soll die Partnerin / der Partner mit eingeladen werden?
aktuellepersonwirklichentfernen=Aktuelle Person wirklich entfernen?
personspeichern=Person speichern
zurpersonenliste=Zur Personenliste
zurpersonenuebersicht=Zur Personen\u00FCbersicht
zurueckzurveranstaltung=Zur\u00FCck zur Veranstaltung
zurdublettensuche=Zur Dublettensuche
zurckzumsuchergebnis=Zur\u00FCck zum Suchergebnis
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=Diese Person wurde erfolgreich zur G\u00E4steliste der Veranstaltung
hinzugefuegt=hinzugef\u00FCgt
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=Diese Person wurde nicht hinzugef\u00FCgt, da Sie bereits auf der G\u00E4steliste steht.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=Diese Person wurde bereits als gel\u00F6scht markiert und wird beim Suchen nicht mehr angezeigt.
personanlegen=Person anlegen
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=Es wurden keine Dubletten gefunden. Sie k\u00F6nnen jetzt weitere Daten eingeben und die Daten speichern.
bittegebensiezunaechstden=Bitte geben Sie zun\u00E4chst den
vorundnachnamen=Vor- und Nachnamen
anundfuhrendiedublettenprufungdurch=an und f\u00FChren die Dublettenpr\u00FCfung durch.
beifirmenwaehlensiediecheckbox=Bei Firmen w\u00E4hlen Sie die Checkbox
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=und tragen dann den Firmennamen ein. Das System pr\u00FCft Ihre Angaben daraufhin auf Dubletten.
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=Liegt keine Dublette vor, k\u00F6nnen Sie weitere Daten eingeben und die Daten speichern.
geschaeftlich=Gesch\u00E4ftlich
privat=Privat
zurueckzurpersonensuche=Zur\u00FCck zur Personensuche
zurueck=Zur\u00FCck
dublettenpruefungdurchfuehren=Dublettenpr\u00FCfung durchf\u00FChren
zurueckzumsuchergebnis=Zurueck zum Suchergebnis
personspeicherndublettenpruefung=Person speichern - Dubletten-Pr\u00FCfung
neueneintraganlegen=Neuen Eintrag anlegen
existierendeneintragbearbeiten=Existierenden Eintrag bearbeiten
eswurdenkeinedublettengefunden=Es wurden keine Dubletten gefunden.
hinzufuegen=Hinzuf\u00FCgen
ausgewaehltepersonenzurveranstaltunghinzufuegen=Ausgew\u00E4hlte Personen zur Veranstaltung hinzuf\u00FCgen.
personerfassen=Person erfassen
dublettenanlegen=Dubletten anlegen
abbrechenundzurueck=Abbrechen und zur\u00FCck
gastsuchenveranstaltung=Gast suchen - Veranstaltung
gastsuchen=Gast suchen
verantwortlichenfueraufgabesuchen=Verantwortlichen f\u00FCr Aufgabe suchen
verantwortlichenfueraufgabehinzufugen=Verantwortlichen f\u00FCr Aufgabe hinzuf\u00FCgen
gastgeberhinzufuegen=Gastgeber hinzuf\u00FCgen
personensuchegastgeberhinzufugen=Personensuche: Gastgeber hinzuf\u00FCgen
gasthinzufuegen=Gast hinzuf\u00FCgen
personensuchegasthinzufugen=Personensuche: Gast hinzuf\u00FCgen
personfirma=Person/Firma
weitereangaben=Weitere Angaben
keinekategoriezugeordnet=Keine Kategorie zugeordnet
keinarbeitsbereichzugeordnet=Kein Arbeitsbereich zugeordnet
keinarbeitsbereich=Kein Arbeitsbereich
gueltigkeitsdatum=G\u00FCltigkeitsdatum
biszudiesemdatum=Bis zu diesem Datum
abdiesemdatum=Ab diesem Datum
angenaudiesemdatum=An genau diesem Datum
datumauswaehlen=Datum ausw\u00E4hlen
HINT_SEARCH_MULTIPLE=Die Suche unterst\u00FCtzt auch die Mehrfachsuche nach Kategorien. Um mehrere Kategorien auszuw\u00E4hlen, halten Sie bitte die Maustaste gedr\u00FCckt und ziehen Sie den Mauszeiger \u00FCber die in der Suche zu ber\u00FCcksichtigenden Kategorien. Alternativ k\u00F6nnen Sie bei gedr\u00FCckter STRG-Taste mit der linken Maustaste auf die zu ber\u00FCcksichtigenden Kategorien klicken. Beachten Sie bitte, dass die beiden Pseudokategorien "Alle" und "Keine" nicht zusammen mit anderen Kategorien ausgew\u00E4hlt werden k\u00F6nnen.
waehlensiebittezunaechsteinekategorieaus=W\u00E4hlen Sie bitte zun\u00E4chst eine Kategorie aus.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=Wollen Sie diese Person bzw. diesen Gast der ausgew\u00E4hlten Kategorie zuordnen
eswurdekeinekategoriezugeordnet=Es wurde keine Kategorie zugeordnet
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=Wollen Sie ${count} Personen bzw. G\u00E4ste der ausgew\u00E4hlten Kategorie zuordnen
eswurdenkeinekategorienzugeordnet=Es wurden keine Kategorien zugeordnet
eswurdenkeinekategoriengefunden=Es wurden keine Kategorien gefunden
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Wollen Sie diese Personen bzw. diesen Gast aus der ausgew\u00E4hlten Kategorie entfernen
eswurdekeinekategorieentfernt=Es wurde keine Kategorie entfernt
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Wollen Sie ${count} Personen bzw. G\u00E4ste aus der ausgew\u00E4hlten Kategorie entfernen
eswurdenkeinekategorienentfernt=Es wurden keine Kategorien entfernt.
zuweisen=Zuweisen
waehlensieeinekategorieauswelchesie=W\u00E4hlen Sie eine Kategorie aus, welche Sie
moechten=m\u00F6chten
alleentfernen=Alle entfernen
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Sie haben keine Kategorien konfiguriert. Diese k\u00F6nnen Sie im Administrationsbereich unter dem Punkt
definieren=definieren.
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=Sie haben ${count} Person(en) ausgew\u00E4hlt. Abh\u00E4ngig von der Anzahl der ausgew\u00E4hlten Personen kann die Aktion eine gewisse Zeit in Anspruch nehmen.
waehlensiebittezunaechsteinenarbeitsbereichaus=W\u00E4hlen Sie bitte zun\u00E4chst einen Arbeitsbereich aus.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=Wollen Sie diese Person bzw. diesen Gast den ausgew\u00E4hlten Arbeitsbereich zuordnen
eswurdekeinarbeitsbereichzugeordnet=Es wurde kein Arbeitsbereich zugeordnet
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=Wollen Sie diesen Personen bzw. diesen G\u00E4ste den ausgew\u00E4hlten Arbeitsbereich zuordnen
eswurdenkeinearbeitsbereichzugeordnet=Es wurden keine Arbeitsbereich zugeordnet
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Wollen Sie die Zuordnung dieser Person bzw. diesem Gast zum ausgew\u00E4hlten Arbeitsbereich aufheben
eswurdekeinarbeitsbereichaufgehoben=Es wurde kein Arbeitsbereich aufgehoben
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Wollen Sie die Zuordnung von ${count} Personen bzw. G\u00E4sten zum ausgew\u00E4hlten Arbeitsbereich aufheben
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Wollen Sie diese Person bzw. diesen Gast dem ausgew\u00E4hlten Arbeitsbereich zuordnen
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=Wollen Sie ${count} Personen bzw. G\u00E4ste dem ausgew\u00E4hlten Arbeitsbereich zuordnen
waehlensieeinenarbeitsbereichauswelchensie=W\u00E4hlen Sie einen Arbeitsbereich aus, welchen Sie
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Sie haben keine Arbeitsbereiche konfiguriert. Diese k\u00F6nnen Sie im Administrationsbereich unter dem Punkt
administrationallestellvertretungenimmandanten=Administration - alle Stellvertretungen im Mandanten
administrationallestellvertretungen=Administration - alle Stellvertretungen
verwaltungpersoenlichevertretungen=Verwaltung - pers\u00F6nliche Vertretungen
vertretung=Vertretung
markiertevertretungen=Markierte Vertretung(en)
loeschen=L\u00F6schen
markiertevertretungenloeschen=Markierte Vertretung(en) l\u00F6schen
gueltigab=G\u00FCltig ab
gueltigbis=G\u00FCltig bis
bitteauswaehlen=Bitte ausw\u00E4hlen
gaestelisteerstellenfuerveranstaltungeventshortname=G\u00E4steliste erstellen f\u00FCr Veranstaltung: $!event.shortname
gaesteverwaltungderveranstaltung=G\u00E4steverwaltung der Veranstaltung
gaestelisteerstellen=G\u00E4steliste erstellen
ausgabeformatwaehlen=Ausgabeformat w\u00E4hlen
listenachkategoriengruppiertmitpartner=Liste nach Kategorien gruppiert - mit Partner
listenachkategoriengruppiertmittelundmobiltelefon=Liste nach Kategorien gruppiert - mit Tel. und Mobiltelefon
listenachkategoriengruppiertmitpartnerundfax=Liste nach Kategorien gruppiert - mit Partner und Fax
listenachsortierungmitpartnertelundmobiltelefon=Liste nach Sortierung - mit Partner, Tel. und Mobiltelefon
tisch=Tisch
zusaetzlichesortierungnach=Zus\u00E4tzliche Sortierung nach
zurueckzurgaesteverwaltung=Zur\u00FCck zur G\u00E4steverwaltung
verwaltungallebenutzerimmandanten=Verwaltung - alle Benutzer im Mandanten
verwaltungallebenutzer=Verwaltung - alle Benutzer
markiertenbenutzer=Markierte(n) Benutzer
markiertenbenutzerloeschen=Markierte(n) Benutzer l\u00D6schen
leseneingeschraenkt=Lesen eingeschr\u00E4nkt
lesenuneingeschraenkt=Lesen uneingeschr\u00E4nkt
lesenundschreibeneingeschraenkt=Lesen und Schreiben eingeschr\u00E4nkt
lesenundschreibenuneingeschraenkt=Lesen und Schreiben uneingeschr\u00E4nkt
mandantadministrieren=Mandant Administrieren
administrieren=Administrieren
stellvertretung=Stellvertretung
bittewahlensiedierolleausdiesievertretenmochten=Bitte w\u00E4hlen Sie die Rolle aus die Sie vertreten m\u00F6chten
benutzerrolle=Benutzerrolle
vertreten=Vertreten
statistikfurgastgeber=Statistik f\u00FCr Gastgeber
imzeitraumvom=Im Zeitraum vom
biszum=Bis zum
bis=Bis
auswartigesamtintranetstil=Ausw\u00E4rtiges Amt Intranet-Stil
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Klicken Sie eine der aufgelisteten Personen an, um sie der Aufgabe hinzuzuf\u00FCgen
eswurdeeinepersongeloscht=Es wurde eine Person gel\u00F6scht
eswurdekeinepersongeloscht=Es wurde keine Person gel\u00F6scht
personengelouscht=Personen gel\u00F6scht.
derarbeitsbereichwurdeerfolgreichhinzugefugt=Der Arbeitsbereich wurde erfolgreich hinzugef\u00FCgt.
diearbeitsbereichewurdenerfolgreichentfernt=Die Arbeitsbereiche wurden erfolgreich entfernt.
diekategoriewurdeerfolgreichhinzugefugt=Die Kategorie wurde erfolgreich hinzugef\u00FCgt.
diekategorienwurdenerfolgreichentfernt=Die Kategorien wurden erfolgreich entfernt.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=Sie haben keine ausreichende Berechtigung um Personen zu entfernen.
wauhlensiebittezunauchsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=Bei den folgenden Personen liegt das G\u00FCltigkeitsdatum in der Zukunft
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=Folgende Personen sind mindestens einer laufenden oder zuk\u00FCnftigen Veranstaltung
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=zugeordnet. Detailinformationen k\u00F6nnen Sie \u00FCber die G\u00E4stelisten der
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=jeweiligen Veranstaltungen abrufen. Die Personen werden aus allen G\u00E4stelisten
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=Folgende Personen sind mindestens einer Aufgabe in mindestens einer laufenden oder
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=zuk\u00FCnftigen Veranstaltung zugeordnet. Detailinformationen rufen Sie bitte \u00FCber die
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=Aufgabenlisten der jeweiligen Veranstaltungen auf. Die Personen werden aus allen
aufgabenentfernt=Aufgaben entfernt
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=Wenn Sie Ihre Auswahl anpassen wollen, brechen Sie bitte das L\u00F6schen ab.
sollenallemarkiertenpersonengeloeschtwerden=Sollen alle markierten Personen gel\u00F6scht werden?
dieseaktionkannnichtrueckgaungiggemachtwerden=Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.
bittebestaetigensiedasloeschendermarkiertenpersonen=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Personen!
loeschenvonpersonenistnichtmoeglich=L\u00F6schen von Personen ist nicht m\u00F6glich
markiertepersonenzurveranstaltunghinzufuegen=Markierte Person(en) zur Veranstaltung hinzuf\u00FCgen
zudieserpersonistkeinehauptpersoneingetragen=Zu dieser Person ist keine Hauptperson eingetragen.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=Diese Person kann nicht auf Reserve gesetzt werden, da die notwendigen Daten
nichtvollstaendigerfasstwurden=nicht vollst\u00E4ndig erfasst wurden.
waehlensiebittezunaechsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
exportieren=Exportieren
einladen=Einladen
aufreservesetzen=Auf Reserve setzen
delegationanmelden=Delegation anmelden
alledemarkiereninklpartnerwenneingeladen=Alle (de)markieren (inkl. Partner, wenn eingeladen)
arbeitsshybereich=Arbeits&shy;bereich
eswurdenkeineeintraegegefunden=Es wurden keine Eintr\u00E4ge gefunden.
suchenersetzen=Suchen & Ersetzen
suchenersetzeninpersonendaten=Suchen & Ersetzen in Personendaten
vornamederhauptpersonunddespartners=Vorname der Hauptperson und des Partners
nachnamederhauptpersonunddespartners=Nachname der Hauptperson und des Partners
anredetitel=Anrede / Titel
anredeundtitel=Anrede und Titel
straszligeadresszusatzundland=Stra\u00DFe, Adresszusatz und Land
plzortundplzpostfach=PLZ / Ort und PLZ / Postfach
telefontelefaxundmobiltelefon=Telefon, Telefax und Mobiltelefon
telefonfax=Telefon / Fax
emailadresse=E-Mail Adresse
internetadresse=Internet-Adresse
ihresuchemussausmindestenseinembuchstabenbestehen=Ihre Suche muss aus mindestens einem Buchstaben bestehen.
siemuessenmindestenseinfeldausgewhlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersonersetzt=Es wurde keine Person ersetzt.
eswurdeeinepersonersetzt=Es wurde eine Person ersetzt.
personenersetzt=Personen ersetzt.
siemuessenmindestenseinfeldausgewaehlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersongefunden=Es wurde keine Person gefunden.
eswurdeeinepersongefunden=Es wurde eine Person gefunden.
personengefunden=Personen gefunden.
einzelneeinzraegezumersetzenselektieren=Einzelne Einzr\u00E4ge zum Ersetzen selektieren
allesofortersetzen=Alle sofort ersetzen
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=Wenn Sie den Platzhalter * verwenden, werden auch Teilst\u00FCcke ersetzt, sonst nur vollst\u00E4ndige Datenfelder.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=Sie m\u00FCssen das Datum des Zeitrahmens im Format TT.MM.JJJJ angeben
markierteanredenloschen=Markierte Anrede(n) l\u00F6schen
markiertendokumenttypenloschen=Markierte Dokumenttyp(en) l\u00F6schen
markierteveranstaltungsorteloschen=Markierte Veranstaltungsorte l\u00F6schen
markiertevorlagenloschen=Markierte Vorlagen l\u00F6schen
keinedateigefunden=Keine Datei gefunden.
standardauswahlderselectboxbdquozeichensatzrdquo=Standard Auswahl der Selectbox \u00E2\u0080\u009EZeichensatz\u00E2\u0080\u009C
zusaetzlichefelder=Zus\u00E4tzliche Felder
postausgang=Postausgang
beimversendendieseremailisteinfehleraufgetreten=Beim Versenden dieser E-Mail ist ein Fehler aufgetreten.
siekonnendiesejetztbearbeitenunderneutsenden=Sie k\u00F6nnen diese jetzt bearbeiten und erneut senden.
dieseemailwartetaufihrefertigstellungdurcheinenbenutzer=Diese E-Mail wartet auf ihre Fertigstellung durch einen Benutzer.
dieseemailwartetaufihreversendung=Diese E-Mail wartet auf ihre Versendung.
dieseemailwirdgeradeversendetundsollte=Diese E-Mail wird gerade versendet und sollte
nichtbearbeitet=nicht bearbeitet
werden=werden.
dieseemailwurdebereitsversendetundsollte=Diese E-Mail wurde bereits versendet und sollte
nichtmehrbearbeitet=nicht mehr bearbeitet
technischefehlermeldungausblenden=Technische Fehlermeldung ausblenden
markiertenmandanten=Markierte(n) Mandanten
alledatensatzewurdenerfolgreichmandantenzugeordnet=Alle Datens\u00E4tze wurden erfolgreich einem Mandanten zugeordnet.
esexistiertnochkeinmandant=Es existiert noch kein Mandant.
zuordnen=Zuordnen
markierteanreden=Markierte Anrede(n)
markierteanredenloeschen=Markierte Anreden l\u00F6schen
markiertenarbeitsbereiche=Markierte(n) Arbeitsbereich(e)
markierteeintraegeentfernen=Markierte Eintr\u00E4ge entfernen
emailpostausgang=E-Mail-Postausgang
markierteemailsloeschen=Markierte E-Mail(s) l\u00F6schen
markierteemails=Markierte E-Mail(s)
wartet=Wartet
wirdversendet=Wird versendet
gesendet=Gesendet
unbekannt=Unbekannt
firmainstitutionauswaehlen=Firma/Institution ausw\u00E4hlen
bittewaehlensieeinefirmainstitutionaus=Bitte w\u00E4hlen Sie eine Firma / Institution aus
schliessen=Schlie\u00DFen
verawebuebersicht=VerA.web :: \u00DCbersicht
uebersichtanzeigen=\u00DCbersicht anzeigen
neuendatensatzanlegen=Neuen Datensatz anlegen
openofficedateiherrunterladen=OpenOffice-Datei herrunterladen
keinedatensaetzegefunden=Keine Datens\u00E4tze gefunden
einendatensatzgefunden=Einen Datensatz gefunden
datensaetzegefunden=Datens\u00E4tze gefunden
anzeigen=anzeigen
wollensiediesendatensatzunwiderruflichentfernen=Wollen Sie diesen Datensatz unwiderruflich entfernen
verawebdetailansicht=VerA.web :: Detailansicht
datensatzbearbeiten=Datensatz bearbeiten
zuruecksetzen=Zur\u00FCcksetzen
datensatzloeschen=Datensatzl\u00F6schen
siekoennenbeidersuchesogenannteplatzhalterverwendenderstehtfuermehrereunddasfuereinzelnezeichen=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen
undamtsbezeichnungfunktion=und Amtsbezeichnung/Funktion
HINT_SEARCH_WHERE=Die Suche erfolgt im Vornamen, Nachnamen, Ort, PLZ, Stra\u00DFe, Firma/Institution, Telefon, Fax, Mobil, E-Mail, Bemerkungen, Kategorien, Arbeitsbereiche
neuenorteingeben=Neuen Ort eingeben
bittegebensieeinenneuenorteinundklickensieaufhinzufuegen=Bitte geben Sie einen neuen Ort ein und klicken Sie auf "Hinzuf\u00FCgen"
neuerveranstaltungsort=Neuer Veranstaltungsort
markierenundkopierensiefolgendesadressetikett=Markieren und kopieren Sie folgendes Adress-Etikett
personenetikett=Personen-Etikett
zuruckzurubersicht=Zuruck zur \u00DCbersicht
gpsdaten=GPS-Daten
platzhalterintexteinfuegen=Platzhalter in Text einf\u00FCgen
intexteinfuegen=In Text einf\u00FCgen
emailvorlagen=E-Mail Vorlagen
vorhandenevorlagen=Vorhandene Vorlagen
bitteauswhaelengt=Bitte ausw\u00E4hlen
vorlageladen=Vorlage laden
neuevorlagename=Neue Vorlage (Name)
neuevorlagespeichern=Neue Vorlage speichern
neuevorlagenmuessensowohleinenbetreffalsauchtextenthalten=Neue Vorlagen m\u00FCssen sowohl einen Betreff als auch Text enthalten
zurueckzumverteiler=Zur\u00FCck zum Verteiler
markiertenveranstaltungsorte=Markierte(n) Veranstaltungsorte
hinweis=Hinweis
