#!/bin/sh

. /etc/vw-selfreg/deamon_options

echo `date` 'starting vw-selfreg service' >> $STARTUP_LOG_FILE

exec setuidgid nobody sh -c '
 cd /etc/vw-selfreg
 exec $JAVA_CMD -Xmx$JAVA_HEAP_SPACE -jar /usr/share/vw-selfreg/self-registration-1.0-SNAPSHOT.jar  server config.yaml  >> $STARTUP_LOG_FILE 2>&1

'
