com.lowagie:itext 4.2.0 TODO illegal:https://developers.itextpdf.com/question/versions-older-than-5
github::HubSpot/vex 3.0.0 ok
github::baconjs/bacon.js 0.7.73 ok
github::bbatliner/vex-dialog 1.0.6 ok
github::ckeditor/ckeditor-dev 4.6.2 ok
github::fyneworks/multifile 2.2.2 ok
github::jquery-form/form 3.51 ok
github::jquery/jquery 1.10.1 ok
github::jquery/sizzle 1.10.1 ok
github::tomsime/Scroll-to-Top 1.0.4 ok
github::xoxco/jQuery-Tags-Input 1.3.3 ok
javascript::unknown:clipboard 0 FAIL
javascript::unknown:dhtml 0 FAIL
javascript::unknown:utils 0 FAIL
sourceforge::jscalendar 2006-02-11T12:32:59Z ok
