freeform::CKEditor 4.6.2 (source missing) FAIL
freeform::dynarch.com:DHTML-Calendar 1.0 ok
javascript::Bacon 0.7.3 (licence missing) FAIL
javascript::WCH 3.10 (incompatible licence) FAIL
javascript::jquery 1.10.1 (minified) FAIL
javascript::jquery.form 3.51.0-2014.06.20 (minified) FAIL
javascript::jquery.gotop 1.0 ok
javascript::jquery.multifile 2.2.1 (minified, bogus source) FAIL
javascript::jquery.tagsinput 1.3.3 ok
javascript::unknown:ac 0 (minified) FAIL
javascript::unknown:clipboard 0 FAIL
javascript::unknown:complete 0 (minified) FAIL
javascript::unknown:dhtml 0 FAIL
javascript::unknown:utils 0 FAIL
javascript::unknown:vex 3.0.0 (minified) FAIL
javascript::unknown:vex-dialog 1.0.6 (minified) FAIL
