github::ForbesLindesay/umd 2.1.0 compile ok
github::HubSpot/vex 3.0.0 compile ok
github::JamesMGreene/qunit-assert-step 1.0.2 compile ok
github::baconjs/bacon.js 0.7.73 compile ok
github::bbatliner/vex-dialog 1.0.6 compile ok
github::browserify/browser-pack 3.2.0 compile ok
github::ckeditor/ckeditor-dev 4.6.2 compile ok
github::fyneworks/multifile 2.2.2 compile ok
github::getify/native-promise-only 0.7.8-a compile ok
github::jquery-form/form 3.51 compile ok
github::jquery/jquery 1.12.4 compile ok
github::jquery/sizzle 2.2.1 compile TODO
github::qunitjs/qunit 1.17.1 compile ok
github::requirejs/requirejs2.1.14 compile TODO
github::sinonjs/formatio 1.1.1 compile ok
github::sinonjs/lolex 1.1.0 compile ok
github::sinonjs/samsam 1.1.3 compile ok
github::sinonjs/sinon 1.14.1 compile ok
github::xoxco/jQuery-Tags-Input 1.3.3 compile ok
https::johnresig.com/files/jsdiff.js md5:74197a6d248d807a24791dcc17b3f389 ok
sourceforge::jscalendar 2006-02-11T12:32:59Z compile ok
