#!/bin/sh
# postinst script for selfreg

## ensure the daemontools scan service is running
pgrep svscan || initctl reload-configuration
pgrep svscan || initctl start svscan


update-service --add /etc/vw-selfreg/selfreg selfreg

# current testserver has no upstart yet...
#initctl reload svscan

#DEBHELPER#

exit 0
