language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"

before_install: npm conf set strict-ssl false

after_install:
  - sudo npm install -g phantomjs grunt-cli

before_script:
  - phantomjs --version

script:
  - npm test
  - grunt readme && git diff --exit-code README.md

notifications:
  flowdock: 3853ef33f6943539cbbed913648575be

branches:
  only:
    - master
