language=English
language_short=en

# BROWSER TAB-TITLE
BROWSER_TITLE_CATEGORY=Categories
BROWSER_TITLE_CLEANUP=Cleanup
BROWSER_TITLE_COLOURS=Colours
BROWSER_TITLE_GENERAL_CONFIGS=General Configuration
BROWSER_TITLE_TASKS=Tasks
BROWSER_TITLE_DOCUMENT_TYPES=Document Types
BROWSER_TITLE_IMPORT_DUPLICATE_ACCEPT=Import Status - Apply Doublets
BROWSER_TITLE_ERROR_OCCURS=An error occured
BROWSER_TITLE_EVENT_EDIT=Edit event
BROWSER_TITLE_EVENT_CREATE=Create new event
BROWSER_TITLE_EVENT_SELECT=Select event
BROWSER_TITLE_PERSON_ASSIGN=Assign person
BROWSER_TITLE_EVENT_SEARCH=Event search
BROWSER_TITLE_TASKS_EDIT=Edit task
BROWSER_TITLE_TASKS_CREATE=Create new task
BROWSER_TITLE_EXPORT_PERSONDATA=Personal data export
BROWSER_TITLE_IMPORT_PERSONDATA=Personal data import
BROWSER_TITLE_EVENT_GUESTLIST=Guest list for event
BROWSER_TITLE_EVENT_EXPORT_DATA=Create control file for event
BROWSER_TITLE_IMPORT_STATUS=Import process status
BROWSER_TITLE_HELP=Help
BROWSER_TITLE_INFO_VERAWEB=Learn more about VerA.web
BROWSER_TITLE_EVENT_LOCATION_EDIT=Edit venue
BROWSER_TITLE_EVENT_LOCATION_CREATE=Create new venue
BROWSER_TITLE_EVENT_LOCATION=Venues
BROWSER_TITLE_EMAIL_SUBMISSION_CREATE=Create new e-mail submission
BROWSER_TITLE_EMAIL_SUBMISSION_EDIT=Edit e-mail submission
BROWSER_TITLE_EMAIL_SUBMISSION=E-Mail submissions
BROWSER_TITLE_PDF_TEMPLATE=PDF templates
BROWSER_TITLE_DISTRIBUTOR_CREATE=Create distribution
BROWSER_TITLE_DISTRIBUTOR_LIST=Distribution list
BROWSER_TITLE_EMAIL_WRITE_DISTRIBUTOR=Write e-mail to distribution
BROWSER_TITLE_EMAIL_EDIT=Edit e-mail
BROWSER_TITLE_EMAIL_CREATE=Create new e-mail
BROWSER_TITLE_EMAIL_OUTBOX=E-mail outbox
BROWSER_TITLE_ROLE_WITH=With role
BROWSER_TITLE_ROLE_AVAILABLE=With available roles
BROWSER_TITLE_ROLE_WITHOUT_INFO=Without role information
BROWSER_TITLE_SUCCESSFUL_LOGIN_ONE=You were successfully
BROWSER_TITLE_SUCCESSFUL_LOGIN_TWO=logged into the system
BROWSER_TITLE_PERSON_EDIT=Edit person
BROWSER_TITLE_PERSON_CREATE=Create new person
BROWSER_TITLE_GUEST_ADD_EVENT=Add guest to
BROWSER_TITLE_GUEST_HOST_ADD_EVENT=Choose host for
BROWSER_TITLE_GUEST_SELECT=Select guest
BROWSER_TITLE_GUEST_HOST_SELECT=Select host
BROWSER_TITLE_SEARCH_REPLACE_PERSONDATA=Search and replace in personal data
BROWSER_TITLE_DUPLICATE_SEARCH=Duplicate search
BROWSER_TITLE_TASK_ADD_RESPONSIBLE=Add responsible for task
BROWSER_TITLE_PERSON_DELETE=Delete person
BROWSER_TITLE_PERSON_LIST=Person summary
BROWSER_TITLE_SEARCH_REPLACE=Search and replace
BROWSER_TITLE_GUEST_HOST_SEARCH=Search host
BROWSER_TITLE_PERSON_SEARCH=Search person
BROWSER_TITLE_PERSON_DATA_SALUTATION=Master data - salutation
BROWSER_TITLE_LOGIN_REPRESENTATIVE=Login as representative
BROWSER_TITLE_STATISTIC_CREATE=Create statistic
BROWSER_TITLE_USER_CONFIGS=User settings
BROWSER_TITLE_WORK_AREAS=Working areas
BROWSER_TITLE_OVERVIEW_EVENTS_YEAR=Complete summary of the number of events per year
BROWSER_TITLE_OVERVIEW_EVENTS_MONTH=Complete summary of the number of events per month
BROWSER_TITLE_OVERVIEW_GUEST_HOST_EVENTS=Summary of all events from one host
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST_HOST=Complete summary of all events, grouped by hosts
BROWSER_TITLE_OVERVIEW_GUEST_EVENTS=Summary of all events from one guest
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST=Complete summary of all events, grouped by guests
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_PLACE=Summary of all events, sorted by venue
BROWSER_TITLE_OVERVIEW_EVENTS_UNKNOWN_STATISTIC=UNKNOWN STATISTIC

# YOU MUST SET THESE PLACEHOLDERS WITH THE GENDER TYPE OF YOUR LANGUAGE FOR EACH OBJECT AS MALE OR FEMALE
GENDER_TYPE_CATEGORY=Female
GENDER_TYPE_CLIENT=Male
GENDER_TYPE_COLOR=Female
GENDER_TYPE_DELEGATION_FIELD=Female
GENDER_TYPE_DISTRIBUTOR=Male
GENDER_TYPE_DOCUMENT_TYPE=Male
GENDER_TYPE_EMAIL=Female
GENDER_TYPE_EVENT=Female
GENDER_TYPE_EVENT_LOCATION=Male
GENDER_TYPE_FUNCTION_OFFICIAL_TITLE=Female
GENDER_TYPE_GUEST=Male
GENDER_TYPE_MAIL_DRAFT=Female
GENDER_TYPE_PDF_TEMPLATE=Female
GENDER_TYPE_PERSON=Female
GENDER_TYPE_REPRESENTATIVE=Female
GENDER_TYPE_SALUTATION=Female
GENDER_TYPE_TASK=Female
GENDER_TYPE_USER=Male
GENDER_TYPE_WORKAREA=Male


# REPETITIVE OBJECTS IN THER SINGULAR- AND PLURAL-TYPE
GENERIC_ADDRESS_DATA_PLURAL=Address data
GENERIC_CATEGORY_SINGULAR=Category
GENERIC_KEYWORDS=Keywords
GENERIC_CATEGORY_PLURAL=Categories
GENERIC_CLIENT_SINGULAR=Client
GENERIC_CLIENT_PLURAL=Clients
GENERIC_COLOR_SINGULAR=Colour
GENERIC_COLOR_PLURAL=Colours
GENERIC_COMPANY_SINGULAR=Company
GENERIC_COMPANY_PLURAL=Companies
GENERIC_DELEGATION_FIELD_SINGULAR=Additional field
GENERIC_DELEGATION_FIELD_PLURAL=Additional fields
GENERIC_DISTRIBUTOR_SINGULAR=Distribution list
GENERIC_DISTRIBUTOR_PLURAL=Distribution lists
GENERIC_EMAIL_SINGULAR=E-Mail
GENERIC_EMAIL_PLURAL=E-Mails
GENERIC_EVENT_SINGULAR=Event
GENERIC_EVENT_PLURAL=events
GENERIC_EVENT_LOCATION_SINGULAR=Venue
GENERIC_EVENT_LOCATION_PLURAL=Venues
GENERIC_FUNCTION_SINGULAR=Function
GENERIC_FUNCTION_PLURAL=Functions
GENERIC_GUEST_SINGULAR=Guest
GENERIC_GUEST_PLURAL=Guests
GENERIC_GUEST_NONE=No guests
GENERIC_INSTITUTION_SINGULAR=Institution
GENERIC_INSTITUTION_PLURAL=Institutions
GENERIC_MAIL_DRAFT_SINGULAR=template
GENERIC_MAIL_DRAFT_PLURAL=templates
GENERIC_PDF_TEMPLATE_SINGULAR=PDF template
GENERIC_PDF_TEMPLATE_PLURAL=PDF templates
GENERIC_PDF_TEMPLATE_S_P=PDF template(s)
GENERIC_PDF_FILE=PDF File
GENERIC_OFFICIAL_TITLE_SINGULAR=Official title
GENERIC_OFFICIAL_TITLE_PLURAL=Official titles
GENERIC_PERSON_SINGULAR=Person
GENERIC_PERSON_PLURAL=people
GENERIC_REPRESENTATIVE_SINGULAR=Representative
GENERIC_REPRESENTATIVE_PLURAL=Representatives
GENERIC_SALUTATION_SINGULAR=Salutation
GENERIC_SALUTATION_PLURAL=Salutations
GENERIC_STATUS_OPEN=Open
GENERIC_STATUS_ACCEPT=Commitment
GENERIC_STATUS_DECLINE=declined
GENERIC_STATUS_PARTICIPATED=Participated
GENERIC_TASK_SINGULAR=Task
GENERIC_TASK_PLURAL=Tasks
GENERIC_USER_SINGULAR=User
GENERIC_USER_PLURAL=Users
GENERIC_WORKAREA_SINGULAR=Working area
GENERIC_WORKAREA_PLURAL=Working areas
GENERIC_SELECT_ALL=Select all

# HEADER MESSAGES
HEADER_REPRESENTATION_FOR=As representative of
HEADER_COUNT_INSERT_ZERO_PART_ONE=Has been
HEADER_COUNT_INSERT_ONE_PART_ONE=Has been
HEADER_COUNT_INSERT_ELSE_PART_ONE=Have been
HEADER_COUNT_INSERT_ZERO_PART_TWO=created
HEADER_COUNT_INSERT_ONE_PART_TWO=created
HEADER_COUNT_INSERT_ELSE_PART_TWO=created
HEADER_COUNT_REMOVE_ZERO_PART_ONE=Has been
HEADER_COUNT_REMOVE_ONE_PART_ONE=Has been
HEADER_COUNT_REMOVE_ELSE_PART_ONE=Have been
HEADER_COUNT_REMOVE_ZERO_PART_TWO=deleted
HEADER_COUNT_REMOVE_ONE_PART_TWO=deleted
HEADER_COUNT_REMOVE_ELSE_PART_TWO=deleted
HEADER_COUNT_UPDATE_ZERO_PART_ONE=Has been
HEADER_COUNT_UPDATE_ONE_PART_ONE =Has been
HEADER_COUNT_UPDATE_ELSE_PART_ONE=Have been
HEADER_COUNT_UPDATE_ZERO_PART_TWO=changed
HEADER_COUNT_UPDATE_ONE_PART_TWO=changed
HEADER_COUNT_UPDATE_ELSE_PART_TWO=changed
HEADER_ELEMENT_FEMALE_NO=none
HEADER_ELEMENT_FEMALE_ONE=one
HEADER_ELEMENT_FEMALE_NEW=new
HEADER_ELEMENT_MALE_NO=none
HEADER_ELEMENT_MALE_ONE=one
HEADER_ELEMENT_MALE_NEW=new
HEADER_ELEMENT_NO_RECORD_SINGULAR=no data record
HEADER_ELEMENT_NO_NEW_RECORD_SINGULAR=no new data record
HEADER_ELEMENT_ONE_RECORD_SINGULAR=one data record
HEADER_ELEMENT_ONE_NEW_RECORD_SINGULAR=one new data record
HEADER_ELEMENT_PLURAL=data records
HEADER_ELEMENT_NEW_PLURAL=new data records

# FIXES
GENERIC_EDIT=Edit
GENERIC_OFFICIAL_TITLE_SHORT=Off. Title
LETTER_COMMERCIAL=(C)
GENERIC_WRITE_EMAIL=Write e-mail
GENERIC_SEARCH_FOR_PERSON=Search for person
GENERIC_CHOOSE_ROLE=Choose role
GENERIC_EVENT=Event
GENERIC_EVENTS=Events
SHOW_ALL_RECORDS=Show all data records
SHOW_RECORDS_1=show
SHOW_RECORDS_2=data records
GENERIC_NO_WORKAREA_TEXT=None

# GENERALLY USED
GENERIC_EMAIL_ADDRESS=E-mail address
GENERIC_FROM=From
GENERIC_LANGUAGE=Language
GENERIC_LOGOUT=Logout
GENERIC_ON=On
GENERIC_ON_LOWERCASE=on
GENERIC_PAGE=Page
GENERIC_PAGES=Pages
GENERIC_PLACE=Place
GENERIC_ALTERNATIVE=Alternative

# MENU
MENU_PERSONS=people
MENU_EVENTS=Events
MENU_MANAGEMENT=Management
MENU_ADMINISTRATION=Administration

# ANMELDUNG
LOGIN_ERROR=An error occurred during the login process. Please check your username and password.
GENERIC_PASSWORD=Password
LOGIN_REPRESENTATION=Login as representative
GENERIC_LOGIN=Login
GENERIC_CLEAR_FIELDS=Clear fields
HINT_LOGIN_ORGANISATION_ONE=Please use your organizational ID or
HINT_LOGIN_ORGANISATION_TWO=firstname.lastname
HINT_LOGIN_ORGANISATION_THREE=as username

# WELCOME SITE: FIRST PAGE AFTER LOGIN
administration=Administration
bittewaehlensieeineamtsbezeichnungfunktionaus=Please choose an official title / role
eskannzuunerwartetenfehlernkommenbittewendensiesichanihrenadministrator=Unexpected errors may occur. Please contact your admin.
willkommenbeiveraweb=Welcome to VerA.web
WELCOME_TEXT_GRANT_READ_STANDARD_FIELDS=Here you\u2019ve got the possibility to show and export master data of persons and events.
WELCOME_TEXT_GRANT_READ_REMARK_FIELDS=Here you\u2019ve got the possibility to show and export master data of - and comments about - persons and events.
WELCOME_TEXT_GRANT_EXPORT_PART_ONE=Here you\u2019ve got the possibility to show, change, delete and to ex- or import
WELCOME_TEXT_GRANT_WRITE_FULL=master data of - and comments about -
WELCOME_TEXT_GRANT_EXPORT_PART_TWO=persons and events.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_ONE=Here you\u2019ve got the possibility to show, change, delete and to ex- or import master data of - and comments about - persons and events.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_TWO=Furthermore client-specific settings can be inspected and edited.
WELCOME_TEXT_GRANT_ADMIN_PART_ONE=Here you\u2019ve got the possibility to show, change, delete and to ex- or import master data of - and comments about - persons and events.
WELCOME_TEXT_GRANT_ADMIN_PART_TWO=Furthermore client-specific and global settings can be inspected and edited.
WELCOME_TEXT_HELP=For further information please go to the \u201CHelp\u201D page.
WELCOME_TEXT_NO_ROLE=There are no existing roles for you login with which you can operate in VerA.web. Please relog with a user- or rolename that is suitable for VerA.web.
GENERIC_AVAILABLE_DUPLICATES=Available duplicates

# ADMINISTRATION/ANREDEN
GENERIC_SALUTATIONS=Salutations
GENERIC_SALUTATIONS_MARKED=Selected salutation(s)
GENERIC_ID=ID
GENERIC_MAIN_FORM=Base form
GENERIC_GENDER=Gender
GENERIC_GENDER_FEMALE=Female
GENERIC_GENDER_MALE=Male
GENERIC_PAGING=Paging
MESSAGE_SUCCESS_INSERT_SALUTATION=A new salutation has been created
QUESTION_DELETE=Do you really want to delete?
GENERIC_NEW_PLURAL=new
GENERIC_YES=Yes
GENERIC_NO=No
MESSAGE_SUCCESS_DELETE_SALUTATION=An salutation has been deleted
MESSAGE_EXIST_MASTER_DATA_ENTRY=A master data record with the same name allready exists
GENERIC_NAME=Name
GENERIC_NEW=New

# ADMINISTRATION/ARBEITSBEREICHE
GENERIC_WORK_FIELDS=Working areas
GENERIC_WORK_FIELDS_MARKED=Selected work area(s)
MESSAGE_MISSING_DATA=No data was found
MESSAGE_INSERT_WORK_FIELD=A new work area has been created
MESSAGE_FAIL_DELETE_WORK_FIELD=No work area has been deleted
MESSAGE_SUCCESS_DELETE_WORK_FIELD=A work area has been deleted

# ADMINISTRATION/BENUTZER
GENERIC_USER=User
GENERIC_USER_MARKED=Selected user(s)
GENERIC_USERNAME=Username
GENERIC_USER_RIGHTS=User permissions
MESSAGE_SUCCESS_INSERT_USER=A new user has been created
MESSAGE_SUCCESS_DELETE_USER=A user has been deleted
MESSAGE_FILL_USER_ROLE=You need to enter a user role designation

# ADMINISTRATION/DOKUMENTTYPEN
GENERIC_TOOLTIP=Tooltip
HINT_FORMAT_INFO=OOo 1.1 stands for OpenOffice 1.1 (.sxc file), OOo 2.0 for OpenOffice 2.0 (.ods file), xls stands for Microsoft Office registration mark: marks 50 and 99 are automatically added to new events. Using mark 50 won\u2019t create a free text field (.xls file). CSV stands for CSV file format.
HINT_EVENT_MARK=Marks 50 and 99 will automatically be addedto new events. Using mark 50 won\u2019t create a free text field.
GENERIC_DOCUMENT_TYPES_MARKED=Selected document type(s)
GENERIC_LABELLING=Label
GENERIC_ADRESS_TYPE=Address type
GENERIC_CHARSET=Charset
GENERIC_FORMAT=Format
GENERIC_PARTNER_DOCUMENT=Document for partner
GENERIC_SORT=Sort
GENERIC_SIGN=Reg. mark
GENERIC_GA=GA
GENERIC_SD=SD
GENERIC_PRIVATE=Private
GENERIC_MORE=More
GENERIC_LATIN=Latin
kyrillisch=Cyrillic
chinesisch=Chinese
eswurdeeindokumenttypgeloscht=A document type has been deleted.
eswurdeeinneuerdokumenttypangelegt=A new document type has been created.

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Status
GENERIC_TO=To
GENERIC_SUBJECT=Subject
GENERIC_ERROR=Error
e-mails=E-mails
GENERIC_BLEND_IN_TECHNICAL_ERROR_MESSAGE=Blend in technical error message
GENERIC_ERROR_DESCRIPTION=Error description

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=E-Mail template
GENERIC_MARKED_TEMPLATES_PP=Selected template(s)
GENERIC_INSERT_NEW_TEMPLATES=Create new template
GENERIC_TEMPLATE_NAME=Name of template
eswurdeeineneuevorlageangelegt=A new template has been created
GENERIC_TEXT=Text
GENERIC_PLACEHOLDER=Placeholder
GENERIC_ADD=Add
GENERIC_BACK_TO_TEMPLATES_LIST=Back to list of templates

# ADMINISTRATION/FARBEN
GENERIC_COLOR_PLURAL=Colours
GENERIC_CHROMATICITY=Chromatic value
LETTERS_CHROMATICITY=R G B

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=Selected title(s)
GENERIC_LABELLING=Title
eswurdeeineneuefunktion/amtsbezeichnungangelegt=A new function/official title has been created
eswurdeeinefunktion/amtsbezeichnunggeloscht=A function/offical title has been deleted

# ADMINISTRATION/KATEGORIEN
GENERIC_CATEGORY_PLURAL=Categories
markiertekategorie=Selected categorie(s)
GENERIC_MARK_LONG=Mark
GENERIC_RANK=Rank
GENERIC_EVENTS_PP=Event(s)
GENERIC_CATEGORY_SINGULAR=Category
GENERIC_OCCASION=Occasion

# ADMINISTRATION/MANDANTEN
GENERIC_CLIENT_PLURAL=Clients
markierte(n)mandanten=Selected client(s)
GENERIC_DATA_NOT_ASSIGNED_TO_CLIENTS=Data not assigned to clients
personen=people
GENERIC_IMPORT_PROCEDURES=Import procedures
veranstaltungorte=Venues
GENERIC_IMPORT_PERSONS=Import persons
GENERIC_DISTRIBUTOR_SINGULAR=Distribution list
GENERIC_USER=User
GENERIC_ASSIGN_CLIENTS=Assign clients
GENERIC_CLIENT_SINGULAR=Client

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=Settings
GENERIC_STANDARD_TABULATOR_CHOICE=Standard choice of tabulators
GENERIC_MAIN_TABS=Main tabs
GENERIC_PERSONS_DATA=Personal data
GENERIC_MAILING_ADDRESSES=Addresses
GENERIC_SUBTABS_OF_PERSONS_DATA=Subtabs of \u201Cpersonal data\u201D
GENERIC_MAIN_PERSON=Main person
GENERIC_PARTNER=Partner
GENERIC_SUBTABS_OF_MAILING_ADDRESSES=Subtabs of \u201Caddresses\u201D
GENERIC_BUSINESS=Business
GENERIC_STANDARD_CHOICE_OF_SELECTED_BOX=Standard choice of selectbox \u201Ccharset\u201D
GENERIC_CHARSET=Charset
GENERIC_STANDARD_SALUTATIONS_AND_FREE_TEXT_FIELDS=Standard salutations and free text fields
GENERIC_STANDARD_SALUTATION=Standard salutations
GENERIC_STANDARD_SALUTATION_PARTNER=Standard form of address: partner
GENERIC_FREE_TEXT_FIELD=Free text field
GENERIC_FREE_TEXT_FIELD_CONNECTOR=Free text field connector
GENERIC_SHOW=Show
GENERIC_HELP=Help
GENERIC_HELP_LINK=Help link
GENERIC_HELP_WINDOW=Help window
OPTION_HELP_WINDOW_1=Use current browser window
OPTION_HELP_WINDOW_2=Open new browser window per request
OPTION_HELP_WINDOW_3=Same browser window for each request (not the current one)
GENERIC_MISCELLANEOUS=Miscellaneous
GENERIC_FAX_CONFIG_FIELD=Fax-DN (@fax.aa)
GENERIC_PROTOCOL_TIME_CHANGE=Protocol of amendment
GENERIC_PROTOCOL_COMMISIONING_TIME=Derivative time of protocol data
HINT_GIVE_THE_RETENTION_PERIOD=Please enter the retention period
GENERIC_YEARS=Years
GENERIC_MONTHS=Months
GENERIC_DAYS=Days
GENERIC_MAILING_ADDRESS_BUSINESS=Business address
GENERIC_MAILING_ADDRESS_PRIVATE=Private address
GENERIC_MAILING_ADDRESS_OTHERS=Address (others)
GENERIC_LABELLING_LATIN=Charset latin
GENERIC_LABELLING_ALTERNATIVE=Charset alternative
GENERIC_ADDRESS_ADDITIONAL=Addition to address

# ADMINISTRATION/REPORTS
GENERIC_REPORTS=Reports
MESSAGE_WAITING_MESSAGE_LOG_REPORT=Depending on the chosen period of time and the amount of data resulting from that, the report creation may take a while. Please be patient.
GENERIC_DATE_BEGIN=Start date
GENERIC_DATE_END=End date
GENERIC_BACKUP_FIEDS=Reset fields
GENERIC_GENERATE_REPORT=Create report

# ADMINISTRATION/STELLVERTRETUNGEN
GENERIC_REPRESENTATIVES=Representations
GENERIC_AVAILABILITY_FILTER=Availability filter
GENERIC_REPRESENTATIVES_ALL=All representations
GENERIC_NO_REPRESENTATION_EXPIRED=No expired representation
GENERIC_ONLY_CURRENT_REPRESENTATIONS=Current representations only
GENERIC_ROLE=Role
GENERIC_REPRESENTATIVE=Representative
gultigab=valid from
GENERIC_VALID_TILL=valid until
GENERIC_NO_DATA_FOUND=No data found

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Selected venue(s)
GENERIC_ADD_NEW_EVENT_LOCATIONS=Add new venue
GENERIC_ID=ID
GENERIC_CONTACT_PERSON=Contact
GENERIC_TELEFON=Phone
GENERIC_FAX=Fax
e-mail=E-mail
GENERIC_REMARK=Comment
GENERIC_URL=URL
gps-daten=GPS data
GENERIC_ROOM_NUMBER=Room number
EVENT_PLACES_CONFIRM_DELETE=Please confirm the deletion of venues

# VERWALTUNG/EINSTELLUNGEN
GENERIC_MANAGEMENT=Management
GENERIC_OPTIONS=Options
GENERIC_SUBTABS_OF=Subtabs of
GENERIC_PERSONAL_DETAILED_VIEW=Personal detailed view
GENERIC_LIST_OF_GUESTS=Guest list
zusatzlichefelder=Additional fields
GENERIC_FUNCTION_SINGULAR=Function
GENERIC_POSTNUMBER_AND_CITY=Postal code / City
GENERIC_LIST_OF_PERSONS=List of persons
GENERIC_FEDERAL_STATE=State
MESSAGE_OPTIONS_WERE_SUCCESSFULLY_SAVED=Options were saved successfully.

# VERWALTUNG/VERTRETUNGEN
GENERIC_REPRESENTATIVE_PLURAL=Representations
markiertevertretung=Selected representation(s)
GENERIC_DELETE=Delete
GENERIC_NEW=New
eswurdeeineneuevertretungangelegt=A new representation has been created
eswurdeeinevertretunggeloscht=One representation has been deleted
siemuseneinevertretereingeben=You need to enter a representation
derbeginndervertretungmusvordemendeliegen=The start date of the representation has to be before the end date
MESSAGE_REPORT_NUMBER_PART_1=There were
vertretungengeloscht=Representations deleted
# VERWALTUNG/INFO
GENERIC_INFO=Info
GENERIC_INFORMATION_ABOUT_VERAWEB=Informations about VerA.web
veraweb=VerA.web
GENERIC_VERSION=Version
build=Build
GENERIC_BUILD_NUMBER=Build number
GENERIC_BUILD_TIME=Build time (UTC)
GENERIC_REST_API=REST API
INFO_LIC_LIC=Licence
INFO_LIC_INFOS=Terms of Use
INFO_LIC_DOCS=further documents
GENERIC_DATABASE=Database
GENERIC_LOGIN=Login
GENERIC_GROUPS=Groups
GENERIC_NOT_AVAILABLE=Not available

# ALLGEMEIN
GENERIC_YOU_ARE_HERE=You are here
GENERIC_HOME=Home
GENERIC_DISCARD_CHANGES=Discard changes?

# TABELLEN
GENERIC_DATE=Date
GENERIC_WORKAREA_SINGULAR=work area
GENERIC_LASTNAME=last name
GENERIC_FIRSTNAME=first name
akwritemtsbezeichnung=Official title
GENERIC_COMPANY_INSTITUTION=Company / Institution
GENERIC_STREET=Street
GENERIC_POST_NUMBER=Postal code
GENERIC_CITY=City
GENERIC_MARKED_PERSONS_PP=Selected person(s)
expotieren=Export
GENERIC_ASSIGN_CATEGORIES=Assign category
GENERIC_REMOVE_CATEGORIES=Remove category
GENERIC_ASSING_WORKAREA=Assign work area
GENERIC_REMOVE_WORKAREA=Remove work area
GENERIC_EXECUTE=Execute
personenanzahlproseite=people | Number per site
GENERIC_ALL=All
seite=Site
GENERIC_DATE_OF_BIRTH=Date of birth
GENERIC_PLACE_OF_BIRTH=Place of birth
GENERIC_NATIONALITY_CITIZENSHIP=Nationality/Citizenship
GENERIC_LANGUAGES=Languages
GENERIC_HINT_FOR_HOST=Hint for host
GENERIC_ACCOUNT_OPENING_DATE=Account opening date
GENERIC_AT=at
GENERIC_OCLOCK=oclock
GENERIC_ORIGIN_DATA=Data origin
GENERIC_PERSON_SINGULAR=Person

# DATEITYP
csv=CSV (Comma-Separated-Values)
x-manage-csv=X-Manage-CSV (X-Manage Contacts)
csvpersdatanschrift=CSVPersdat+Anschrift (Comma-Separated-Values)
csvpersdat=CSVPersdat (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Kategorien (Comma-Separated-Values)
csviso885915=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)

# PERSONEN/PERSONENUEBERSICHT
GENERIC_PERSON_SUMMARY=people summary
GENERIC_SEARCH_PERSONS=Search for persons
GENERIC_CREATE_PERSON=Create person
GENERIC_PERSONS_DELETED=people deleted

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
GENERIC_EDIT_PERSON=Edit person
GENERIC_DOCUMENTED_ON=Documented on
GENERIC_LAST_EDITED_ON=Last edited on
GENERIC_PERSONS_ID=people-ID
GENERIC_OA=Online-registration
GENERIC_OA_USERNAME=Online-registration username
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=There is no preview-field created for this person.
GENERIC_COPY_PERSON=Copy person
GENERIC_CREATE_TAG=Create tag
GENERIC_ASSIGN_TO_EVENT=Assign to event
GENERIC_DELETE_PERSON=Delete person
GENERIC_STATISTIC=Statistics
ausstammdatenhinzufugen=Add from main data

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
GENERIC_GENERATE_ALL=Generate all

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
GENERIC_CATEGORIES_AND_OCCASIONS=Categories and occasions

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=Summary of all events for one guest.
GENERIC_VIEW_OVER_GUEST_EVENT=From
statistikfurgast=Statistics for guest
GENERIC_EVENT=Event
GENERIC_BEGIN=Start

# PERSONEN/PERSONENSUCHE
GENERIC_SEARCH_PERSON=Search for person
GENERIC_SEARCH=Search
GENERIC_VALIDITY_DATE=Validity date
GENERIC_ADVANCED_SEARCH=Advanced search
HINT_PLACEHOLDER=Hint With the Search, you can use Placeholder, where * stands for several and the Question mark ? for singular. This search could be used in Surnames, Last names, City, Zip code, Street, Company/Institution, telefon, fax, mobile, E-mail, remarks, categories, work areas and employment title/function.

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=The login credentials have been created successfully.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Login credentials for this person already exist.

# PERSONEN/NEUE PERSON ANLEGEN
GENERIC_IS_COMPANY=current company
GENERIC_SALUTATION_SINGULAR=Salutation
frau=Frau
herr=Herr
lady=Lady
sir=Sir
GENERIC_PLEASE_CHOOSE=Please choose
GENERIC_ACAD_TITLE=Acad. title
GENERIC_IN_COUNTRY=home country
GENERIC_HINT_FOR_ORGA=Hint for Orga
GENERIC_COMPANY_SINGULAR=Company
GENERIC_COUNTRY=Country
plz/postfach=Zip code/ post office box
GENERIC_POST_OFFICE_BOX=Post office box
iban=IBAN
bic=BIC
GENERIC_MOBILE=Mobile
LETTERS_WWW=WWW
dublettenprufungdurchfuhren=Execute search for duplicates
zurpersonenubersicht=To Person view

# PERSONEN/SUCHEN UND ERSETZEN IN PERSONENDATEN
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=If you use the placeholder *, sections will also be replaced, otherwise only complete datafields.
GENERIC_SEARCH_V=Search
GENERIC_REPLACE=Replace
GENERIC_IN_THE_FOLLOWING_FIELDS=In the following fields
anrede/titel=Salutations / title
GENERIC_EMPLOYMENT_TITLE_SHORT=Empl. title
GENERIC_INSTITUTION_SINGULAR=Institution
GENERIC_ADDRESSES=Addresses
telefon/fax=Phone / Fax
GENERIC_REPLACE_INDIVIDUALLY=Replace individually
GENERIC_REPLACE_ALL=Replace all

# PERSONEN/DUBLETTENSUCHE
GENERIC_DUPLICATE_SEARCH=Search for duplicates

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Export person data
HINT_EXPORT_MANDANT_PERSON=You export with this function only persons from the current client.
GENERIC_WITHOUT=Without
botschaften=embassy
finanzamtsprecher=financial officer
journalisten=journalists
lieferant=supplier
nogs=NOGs
politik=politics
pressevertreter=press representatives
wirtschaft=economy
GENERIC_EXPORT=Export
EXPORT_AS_CSV=Guest list complete
EXPORT_AS_CSV_SHORT=Guest list short
GENERIC_START_EXPORT=Start export
ENCODING_TYPE_CYRILLIC=Cyrillic
ENCODING_TYPE_WEST=Westerly
ENCODING_TYPE_BALTIC=Baltic
ENCODING_TYPE_EAST=Eastly
ENCODING_TYPE_TURKISH=Turkish
EXPORT_DATA_TYPE_CSV=CSV (Comma-Separated-Values)
EXPORT_DATA_TYPE_X_MANAGE_CSV=X-Manage-CSV (X-Manage contacts)
EXPORT_DATA_TYPE_CSVPERSDATA_ADDRESS=CSVPersdat+Mailing box (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA=CSVPersdat (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_CATEGORY=CSVPersdat+Categories (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSV_ISO_8859_15=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)
EXPORT_TITLE_CSV=CSV
EXPORT_TITLE_X_MANAGE_CSV=X-Manage-CSV
EXPORT_TITLE_CSVPERSDATA_ADDRESS=CSV people data+mailing boxes
EXPORT_TITLE_CSVPERSDATA=CSV people data
EXPORT_TITLE_CSVPERSDATA_CATEGORY=CSV people data+Categories
EXPORT_TITLE_CSV_ISO_8859_15=CSV ISO-8859-15
HINT_EXPORT_CSV=Depending on the amount of the exported fields (especially the amount of categories), MS Excel and OO Calc may not be able to read the exported data entirely.
HINT_EXPORT_CSVPERSDATA_ADDRESS=Only the fields from the \u201CPersonal data\u201D and \u201CAddresses\u201D tabs with their subtabs will be exported. Depending on the amount of the exported fields, MS Excel and OO Calc may not be able to read the exported data entirely.
HINT_EXPORT_CSVPERSDATA=Only the fields from the \u201CPersonal data\u201D tab with its' subtabs will be exported. Depending on the amount of the exported fields, MS Excel and OO Calc may not be able to read the exported data entirely.
HINT_EXPORT_CSVPERSDATA_CATEGORY=Only the fields from the \u201CPersonal data\u201D and \u201CCategories\u201D tabs with their subtabs will be exported. Depending on the amount of the exported fields, MS Excel and OO Calc may not be able to read the exported data entirely.
HINT_EXPORT_CSV_ISO_8859_15=This format is Im-/Export compatible with MS Office Applications, which use a Character set of ISO-8859-15. Depending on the amount of the exported fields, MS Excel and OO Calc may not be able to read the exported data entirely.

# PERSONEN/IMPORT VON PERSONENDATEN
GENERIC_IMPORT_FROM_PERSONS_DATA=Import of persons data
HINT_IMPORT_SHORT_CONTENT=Hint With the Import, the input fields which are longer than VerA.web expects, will be shortened.
GENERIC_TARGET_CLIENT=Target client
GENERIC_IMPORT_DATA=Import data
GENERIC_DATA_TYPE=Data type
dateiauswahlen=Select file
keineausgewahlt=None selected
GENERIC_START_IMPORT=Start import

# PERSONENDROPDOWN
GENERIC_NEW_PERSON=New person
GENERIC_EXPORT_PERSONS=Export persons
GENERIC_IMPORT_PERSONS=Import persons

# VERANSTALTUNGENDROPDOWN
GENERIC_EVENT_VIEW=Events summary
veranstaltunguuche=Veranstaltungssuche
GENERIC_NEW_EVENT=New event
GENERIC_STATISTICS=Statistics

# ADMINISTRATIONDROPDOWN
GENERIC_SALUTATIONS=Salutations
GENERIC_WORKAREA_PLURAL=Work areas
e-mail-postausgang=E-Mail outbox
GENERIC_PROGRAM_PERFERENCES=Program settings
GENERIC_EVENT_LOCATION_PLURAL=Venues

# VERANSTALTUNGSUEBERSICHT
GENERIC_END=End
GENERIC_HOST=Host
GENERIC_EVENT_LOCATION_SINGULAR=Venue
GENERIC_EVENT_SEARCH=Search for event
GENERIC_CREATE_NEW_EVENT=Create new event
GENERIC_NUMBER_PER_PAGE=Count per page
seitexvony=Seite x von y

# EVENT HEADER
EVENT_ID=Event-ID
EVENT_NAME=Event name
EVENT_URL=Event-URL
EVENT_URL_MEDIA_REPRESENTATIVE=URL for press representatives
EVENT_MAX_GUEST=maximal number of Guests
EVENT_MAX_RESERVE=maximum number on the waiting list
EVENT_INVITATION_TYPE=Invitation type
EVENT_INVITATION_TYPE_WITHOUT_PARTNER=Without partner
EVENT_INVITATION_TYPE_ONLY_PARTNER=Only partner
EVENT_INVITATION_TYPE_WITH_PARTNER=With Partner

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
GENERIC_EDIT_EVENT=Edit event
GENERIC_TO_GUEST_MANAGEMENT=To guest management
GENERIC_GENERAL=General
GENERIC_TASK_PLURAL=Tasks
GENERIC_ADDITIONAL_PERSONS_DATA=Additional persons data
kurzbereichnung=Abbreviated designation 
GENERIC_OPEN_EVENT=Open event
umxuhr=At x o'clock
veranstalgungsort=Venue
GENERIC_SEARCH_FOR_HOST=Search for host
GENERIC_DELETE_HOST=Delete host
GENERIC_HOST_PARTNER=Host-partner
GENERIC_LOGIN_REQUIRED=Login required
GENERIC_SUBSCRIPTION_OF_PRESS_REPRESENTATIVES_POSSIBLE=Subscription of press representatives possible
GENERIC_SAVE_EVENT=Save event
GENERIC_TO_EVENT_VIEW=To event view

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPES_MARKED_DELETE=Delete selected document type(s)
GENERIC_REMOVE=Remove
GENERIC_ADD_NEW_DOCUMENT_TYPE=Add new document type
xvonydokumenttypen=x of y documenttypes

# VERANSTALTUNG BEARBEITEN/AUFGABEN
GENERIC_ADD_NEW_TASK=create new task
MESSAGE_NO_TASKS_FOR_THIS_EVENT=No tasks are assigned to this event
GENERIC_SELECTED_ENTRIES=Selected entries
GENERIC_TITLE=Title
GENERIC_RESPONSIBLE=Responsible

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
GENERIC_TASKS_ID=Task-ID
GENERIC_COMPLETION=Completion
GENERIC_PRIORITY=Priority
GENERIC_DESCRIPTION=Description
GENERIC_ADD_RESPONSIBLES=Add responsibles
verantwortlichenentfernen=Delete responsibles
GENERIC_SAVE_TASK=Save task
GENERIC_BACK_TO_TASKS_VIEW=Back to task summary

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
GENERIC_ADD_NEW_EMPLOYMENT_TITLE=Add new employment title
MESSAGE_NO_EMPLOYMENT_TITLES_FOUND=No employment titles were found

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
GENERIC_ADD_NEW_KATEGORIES=Add new categorie

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
#GENERIC_PRECONDITION_PLURAL=Preconditions
#EVENT_PRECONDITION_MARKED=Selected precondition(s)
#EVENT_PRECONDITION_ADD=Add precondition
#EVENT_PRECONDITION_INVITATIONSTATUS=Teilnahmestatus
#EVENT_PRECONDITION_STARTDATE=Startdatum
#EVENT_PRECONDITION_NOT_FOUND=Es wurden keine Vorbedingungen gefunden

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Only search future events
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=When searching you can use placeholders. The * stands for multiple and the ? for single characters.

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=With Partner
eswurdeeineneueveranstaltungangelegt=One new event successfully created.

# VERTEILER
angelegtvon=applied by
angelegtam=applied on
erzeugtausveranstaltung=created from event

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=delimit statistics to following timeframe
statistiktypauswahlen=choose statistics type
zeitrahmenbeginn=timeframe-begin
zeitrahmenende=timeframe-end
STATISTIC_RADIO_PER_YEAR=overall view of events per year
STATISTIC_RADIO_PER_MONTH=overall view of events per month
STATISTIC_RADIO_GROUPED_BY_HOST=overall view of events, grouped by host
STATISTIC_RADIO_PER_HOST=overall view of one host\u2019s events(with search)
STATISTIC_RADIO_PER_GUEST=overall view of one guest\u2019s events(with search)
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=overall view of events ordered by venue
statistikerstellen=create statistics

# GAESTEVERWALTUNG DER VERANSTALTUNG
gasteverwaltungderveranstaltung=Guest Management of the Event
maxanzahlgaste=Max Number of guests
gastedetails=Guest details
offen=open
zusagen=accept
absagen=decline
teilnahmen=participations
aufplatz=on place
aufreserve=on reserve
filter=filter
platzwahl=seating
lfdnr=serial number
nichteingeladen=not invited
laufendenummerberechnen=calculate serial number
allestammdatenneuladen=reload core data
HINT_ENTRY_POINT=Indexing: only possible when ordered by name, first name or email
HINT_GUEST_MANAGEMENT_FILTER=When creating guestlists, the filter selected above will be included
HINT_GUEST_MANAGEMENT_MARKED=select guests to be exported, otherwise the whole list will be exported
TABLE_BEFORE_GUEST=previous guest
TABLE_FIRST_GUEST=first guest
TABLE_LAST_GUEST=last guest
TABLE_NEXT_GUEST=next guest

# GAESTELISTE
GUEST_LIST_ALL_GUEST=all guests
GUEST_LIST_ALL_GUEST_ON_PLACE=all guests on place
GUEST_LIST_ALL_GUEST_ON_RESERVE=all guests on reserve
GUEST_LIST_APPLY_GUEST_FROM_EVENT=apply guests from event
GUEST_LIST_CATEGORY_ASSIGN=assign categories
GUEST_LIST_CATEGORY_REMOVE=remove categories
GUEST_LIST_DISTRIBUTOR_CREATE=create distribution list
GUEST_LIST_CONFIRM_ACTION=Please confirm the following action
GUEST_LIST_DIDNT_CHANGE=The guest list did not change
GUEST_LIST_EXPAND_ONE=The guestlist has been expanded by one guest
GUEST_LIST_EXPAND_MULTIPLE_PART_ONE=The guestlist has been expanded by
GUEST_LIST_EXPAND_MULTIPLE_PART_TWO=guests
GUEST_LIST_HINT_EXPORT_GUEST=select guests to be exported, otherwise the whole list will be exported
GUEST_LIST_HINT_FILTER=When creating guestlists, the filter selected above will be included
GUEST_LIST_HINT_RED_PERSON=people highlighted in red were already selected \u201Cto be delete\u201Dd
GUEST_LIST_CREATED_NO_PERSON=has been created without persons
GUEST_LIST_CREATED_ONE_PERSON=has been created with one person
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_ONE=has been created with
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_TWO=persons
GUEST_LIST_NO_GUEST_INVITED=No guests were invited yet or your filter settings do not show any result
GUEST_LIST_NUMBER_CALCULATE=calculate serial number
GUEST_LIST_NUMBER_CALCULATED_SAVED=The \u201Cserial number\u201D has been recalculated and saved for all guests
GUEST_LIST_ONLY_OPEN=open only
GUEST_LIST_ONLY_ACCEPT=accepted only
GUEST_LIST_ONLY_DECLINED=declined only
GUEST_LIST_ONLY_PARTICIPATE=participations only
GUEST_LIST_PERSON_DATA_RELOAD=reload all core data
GUEST_LIST_RESERVE=R
GUEST_LIST_SEARCH_PERSON_ADD=Search and add people to guest list

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=create guest list
SELECT_OUTPUT_FORMAT=select output format
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=list grouped by category - with partner
LIST_GROUP_BY_CATEGORY_WITH_TEL=list grouped by category - with phone and mobile numbers
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=list grouped by category- with partner and fax
LIST_SORT_PARTNER_TEL=list ordered - with partner, phone and mobile numbers
SORT_CRITERIA=sort criteria
SORT_AFTER=sort by
CONTINUAL_NUMBER=serial number
anschliesendnach=afterwards sort by
zusatzlichesortierungnach=furthermore ordered by

# GASTDETAILS
GUEST_DETAIL_HINT_GUEST_HOST=Hint host
GUEST_DETAIL_HINT_ORGANISATION_TEAM=Hint organisation team
GUEST_DETAIL_INVITATION_STATUS=invitation status
GUEST_DETAIL_SEAT_NUMBER=seat number
GUEST_DETAIL_TABLE_NUMBER=table number
gastdetails=guest details
HINT_GUEST_LIST_EDIT_PERSONDATA=Here you are only editing personal data within the current event, not general core data
istgastgeber=is host
reserve=reserve
aufstammdatenzurucksetzen=Reset to core data
stammdatenbearbeiten=edit core data

# DOKUMENTTYPEN
dokumenttypwahlen=choose document type
mitgliedsausweis=membership card
etikett=label
tischkarte=place card
adresstypundzeichensatzwahlen=choose address type and charset
adresstyp=address type
datenbearbeiten=edit data
verbinder=Connector
freitextfeldpartner=free text field(partner)
akatitel=aka title (partner)
kontaktdaten=contact data
strase=Street
postfachplz=PO Box Postcode
nummer=number
zuruckzudenveranstaltungsdetails=Back to event details

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Edit document type
dokument-id=Document-id
dokument-name=Document-name
dokumenttypspeichern=Save document type
zuruckzurdokumenttypenliste=Back to document type list
anmeldedatenerzeugen=Create login data
esliegenkeinekategorienundereignissevor=there are no categories and occasions
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=green highlighted entried are recuring occasions

# VERTEILERDETAILS
verteilerdetails=distribution details
verteilerversenden=dispatch contributor
e-mail-clientaufrufen=open e-mail client
mailclient_other=Other Mailclient
mailclient_msoutlook=Microsoft Outlook
verteilerverschickt=The distribution was successfully sent
verteilerfehler=The distribution was not sent successfully, try again later.

# FEHLEND
zurstartseite=Home
solldieneuekategorie=should the new category
einsortiertwerden=be sorted?
pflichtfelder=mandatory field
markiertekategorien=Selected categorie(s)
markiertekategorienloschen=delete selected categorie(s)
alledemarkieren=check all
furalleveranstaltungen=for all events
speichern=Save
anderungsprotokollfurdenzeitraum=changelog for period
objekt=object
objektid=object-id
artderanderung=kind of changes
geandertefelder=changed fields
datumauswahlen=choose date
folgendeaktionen=following action
wurden=were
durchgefuhrt=performed
konnen=can
aktuallisieren=update
cleanupjetztunwiderruflichdurchfuhren=run cleanup now irreversible
essindderzeitkeinecleanupsmoglichnotig=There are no cleanups possible/necessary at the moment
nochkeineauswahlgetroffen=nothing selected yet
oberflachenbeschriftungen=surface-label
zusatzfelder=additional fields
eswurdeeinzusatzfeld=An additional field has been
angelegt=created
geandert=changed
geloscht=deleted
feldbezeichnung=field identifier
eingabetyp=input type
erfolgreichgespeichert=saved successfully!
markiertendokumenttypen=selected document type(s)
eigenesdokumentfurpartner=own document for partner
sortierreihenfolge=sort sequence
gastgebermitausgeben=display host
iststandardfursteuerdatei=is standard for control file
format=format
HINT_EXPORT_FORMAT=OOo 1.1 stands for OpenOffice 1.1(sxc-file) and OOo 2.0 for OpenOffice 2.0(ods-file), xls stands for Microsoft Office(xls-file) and CSV for CSV-fileformat.
HINT_EVENT_IDENTIFICATION=indicators 50 and 99 are added automaticly to new events. No free text field is will be created for indicator 50.
wirklichloschen=delete
zumpersonenimport=to person import
importstatus=Import status
importstatusvorhandenedublettenbearbeiten=import status: edit existing duplicates
bittemarkierensiediezuimportierendenpersonen=Please select the people to import
dublettendiedurchden=Duplicates which
importhinzugefugtwerdenwurden=have been added by the import
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=, are marked with a checkbox. They contain the correspondant data sets already existing in the system.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=In order to integrate a duplicate into the import, you need to apply it first.
alsdubletteubernehmen=Apply as duplicate
markiertepersonenalsdubletteubernehmen=apply selected people as duplicates
anzahlzuspeicherndedubletten=Count of duplicates to save
eswurdenkeineeintragegefunden=No entries found.
zuruckzumpersonenimport=Back to import persons
fehlermeldung=Errormessage
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=An Error occured while processing your request. Please report this to your administrator.
unbekannterfehler=unknown error.
markiertenkategorien=Selected categorie(s)
markiertenkategorienentfernen=Remove selected categorie(s)
bitteauswahlen=please select
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=The event you just edited has just been removed by another user. You can now create a new event or continue working with VerA.web ulterior.
bittebestatigensiedasspeicherndieserveranstaltung=Please confirm saving the event
keingastgeberausgewahlt=No host selected
kurzbezeichnung=Abbreviated designation
maximalelangederwarteliste=Maximum length of the waitlist
sollendiestammdatenumdiesenorterweitertwerden=Shall the core data be expanded by this location
markiertendokumenttypenentfernen=remove selected document types
eswurdenkeinedokumenttypengefunden=No document types found.
markiertenamtsbezeichnungen=selected employment titles
markiertenamtsbezeichnungenentfernen=remove selected employment titles
zurveranstaltungssuche=To event search
veranstaltungssuche=Event search
suchergebnis=search result
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=Please click one of the listed events to apply the guestlist.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=Please click one of the listed events to assign the person.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=Please click one of the listed People to apply it as host.
loschenvonveranstaltungenistnichtmoglich=It is not possible to delete events
weiteremeldungen=more notifications.
bittebestatigensiedasloschendermarkiertenveranstaltungen=Please confirm to delete the selected events!
markierteveranstaltungloschen=delete selected event
abbrechen=Cancel
markierteveranstaltungen=Selected event(s)
markierteveranstaltungenloschen=Delete selected event(s)
zuruckzurgasteverwaltung=Back to guest management
zuruckzurgasteliste=Back to guestlist
zuruckzurveranstaltungsdetails=Back to event details
zuruckzurveranstaltungsstatistiken=Back to event statistics
zuruckzurveranstaltungsaufgabe=Back to event task
zuruckzurpersonensuche=Back to people search
zuruckzusuchenundersetzen=Back to search and replace
zuruckzurveranstaltungssuche=Back to event search
wahlensiebittezunachsteineodermehrereveranstaltungenaus=Please select one or more events first
nurinzuunftigenveranstaltungensuchen=Only search future events
zuruck=Back
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=When searching you can use placeholders. The * stands for multiple and the ? for single characters.
bittebestatigensiedasspeicherndieseraufgabe=Please confirm saving this task
verantworlichenhinzufugen=add person in charge
verantworlichenentfernen=remove person in charge
loschenvonaufgabenistnichtmoglich=Deleting tasks is not possible
bittebestatigensiedasloschenvonaufgaben=Please confirm removing tasks
ausgewahlteeintrageloschen=delete selected entries
start=start
zursuche=To search
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=You are logged in as \u201Cfull-administrator\u201D and about to export across clients.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=With this function you exclusively export People from your current client.
event=event
keine=none
category=category
weitereoptionen=more options
anmerkung=note
anmerkungen=notes
markiertebezeichnunge=Selected description(s)
markierteeintrageentfernen=Delete selected entries
eswurdenkeinedatengefunden=No data found
siehabenkeinedatenherkunftangegeben=You have not inserted any data origin.
HINT_IMPORT_NOT_POSSIBLE_OPENOFFICE=You are trying to import an OpenOffice file. The direct import is in the current version of VerA.web unfortunately not possible. Please save the file with your table calculation program as a .csv file.
HINT_IMPORT_NOT_POSSIBLE_STAROFFICE=You are trying to import a StarOffice file. The direct import is in the current version of VerA.web unfortunately not possible. Please save the file with your table calculation program as a .csv file.
HINT_IMPORT_NOT_POSSIBLE_EXCEL=You are trying to import a Microsoft Excel file. The direct import is in the current version of VerA.web unfortunately not possible. Please save the file with your table calculation program as a .csv file.
HINT_IMPORT_NOT_POSSIBLE_PDF=You are trying to import a PDF file. This import is unfortunately in the current version of VerA.web not possible.
HINT_IMPORT_NOT_POSSIBLE_ZIP=You are trying to import a ZIP file. This import is unfortunately in the current version of VerA.web not possible.
HINT_IMPORT_NOT_POSSIBLE_EXE=You are trying to import a EXE file. This import is unfortunately in the current version of VerA.web not possible.
siehabenversuchteinedateimitderendung=You are trying to import  a data with the extension
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=.This is unfortunately in the cuurent version of VerA.web not available.
siehabenkeinedateiausgewahltoderdiesewarleer=You have either selected an empty file or have not selected any at all.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=An error has occured while importing the file.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Probably the import file is not in the expected format.
detailsanzeigen=Show details
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=While importing, the input fields content might be shortened.

umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=In order to be able save duplicates, they first have to be applied in the available duplicates.
HINT_UMLAUT_COMPARISON=Please note, that the special characters \u00E4, \u00F6, \u00FC and \u00DF will be compared with ae,oe,ue and ss.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=In order to complete the import process, please click on \u201CComplete import\u201D.
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=The import will be completed only when storable datasets are available.
vorhandenedubletten=Available duplicates
vorhandenedublettenbearbeiten=Edit available duplicates
zuimportierendedatensatzeinsgesamt=To import all datasets
davondubletten=Duplicates
davonspeicherbar=Storable
ignoriertefehlerdatensatze=Ignored datasets errors
importabschlieszen=Complete import
siehabenkeinendatensatzimportiert=You have not imported any dataset.
siehabeneinendatensatzimportiert=You have imorted one dataset.
siehaben=You have imported
datensatzeimportiert=datasets.
informationennichtverfugbar=Information not available
nichtgewahlt=Not selected
verfugbarerollen=Available roles
passowrt=Password
inverteretunganmelden=Login as representative
vornamenachname=First name.Last name
alsbenutzernamen=As Username
emailvorlage=E-mail template
amtsbezfunktion=Empl. Title/funktion
postfachnummer=Post office number
email=E-mail
verteileranlegen=Create distribution list
sielegeneinenneuenverteilerausderpersonensuche=You are creating a new distribution list from the Person Search
sielegeneinenneuenverteilerausderveranstaltung=You are creating a new distribution list from the Event
mit=with
einerperson=a person
verteilername=Name of the distribution list
verteilerspeichern=Save distribution list
markierteadressen=selected Address(es)
markierteadressenausdemverteilerloschen=Delete selected address(es)
analleadressenversenden=Send to all addresses
emailclientaufrufen=open e-mail client
esliegenkeineadressdatenfurdiesenverteilervor=No addresses exist for this distribution list
esliegenkeineadressenfurdiesenverteilervor=No addresses exist for this distribution list
esliegenkeinevorlagenvor=There are no templates.
zuruckzurverteilerubersicht=back to distribution list summary
eswurdekeineemailzumversendengespeichert=No E-mails to be sent were saved
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=An E-mail was saved automatically. This will be sent automatically.
emailszumversendengespeichertdiesewerdennunautomatischversendet=E-mails to be sent are automatically saved. These will be automatially sent.
markiertenverteiler=Selected distribution list(s)
markierteverteilerloschen=Delete selected distribution lists
persondendaten=Person data
solldiesergastaufplatzgesetztwerden=Should this guest get a seat?
solldiepartnerinderpartnermiteingeladenwerden=Should the partner be invited?
aktuellepersonwirklichentfernen=Delete updated person?
personspeichern=Save person
zurpersonenliste=To persons List
zurpersonenuebersicht=To persons summary
zurueckzurveranstaltung=Back to Event
zurdublettensuche=To duplicates
zurckzumsuchergebnis=Back to search results
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=This person was successfully added to the event
hinzugefuegt=
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=This person was not added, since he/she is already on the guest list.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=This person is already selected as deleted and will not be shown in search anymore.
personanlegen=Create person
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=No duplicates were found. You can now input more data and save.
bittegebensiezunaechstden=Please enter
vorundnachnamen=first and last name
sowieunteranschriftendie=as well as
anundfuhrendiedublettenprufungdurch=and search for duplicates.
beifirmenwaehlensiediecheckbox=For companies, choose the checkbox
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=and input the company name. The system checks your input for duplicates.
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=If there are no duplicates, you can input more data and save.
geschaeftlich=Business
privat=Private
zurueckzurpersonensuche=Back to person search
zurueckzurpersonenuebersicht=Back to person summary
zurueck=Back
dublettenpruefungdurchfuehren=Execute search for duplicates
zurueckzumsuchergebnis=Back to search results
personspeicherndublettenpruefung=Save person - Search for duplicates
neueneintraganlegen=Create new entry
existierendeneintragbearbeiten=Edit existing entry
eswurdenkeinedublettengefunden=No duplicates were found.
hinzufuegen=Add
ausgewaehltepersonenzurveranstaltunghinzufuegen=Add selected persons to event.
personerfassen=Record person
dublettenanlegen=Create duplicates
abbrechenundzurueck=Cancel and back
gastsuchenveranstaltung=Search guest - Event
gastsuchen=Search guest
verantwortlichenfueraufgabesuchen=Search tasks for responsibles
verantwortlichenfueraufgabehinzufugen=Add tasks to responsibles
gastgeberhinzufuegen=Add host
personensuchegastgeberhinzufugen=Search person: Add person
gasthinzufuegen=Add guest
personensuchegasthinzufugen=Search person: Add guest
personfirma=Person/Company
weitereangaben=More Tasks
keinekategoriezugeordnet=No Category was assigned
keinarbeitsbereichzugeordnet=No work area assigned
keinarbeitsbereich=No work area
gueltigkeitsdatum=Validity date
biszudiesemdatum=Till this date
abdiesemdatum=From this date
angenaudiesemdatum=On this date
datumauswaehlen=Select date
HINT_SEARCH_MULTIPLE=You can search also for multiple categories. To select multiple categories, please click and hold with your mouse and drag it over the categories. Alternatively, you can press the Ctrl button and hold while choosing the desired categories. Please note that both pseudocategories \u201CAll\u201D and \u201CNone\u201D cannot be selected with other categories.
waehlensiebittezunaechsteinekategorieaus=Please choose a categorie.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=Would you like to assign this category to this person (i.e. guest)
eswurdekeinekategoriezugeordnet=No categories were assigned
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=Would you like to assign this category to %s persons (i.e. guests)
eswurdenkeinekategorienzugeordnet=No category assigned
eswurdenkeinekategoriengefunden=No categories were found
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Would you like to delete this person (i.e. guest) from the categorie
eswurdekeinekategorieentfernt=No category was deleted
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Would you like to delete %s persons (i.e. guests) from the categorie
eswurdenkeinekategorienentfernt=No categories were deleted
zuweisen=Assign
waehlensieeinekategorieauswelchesie=Choose a categorie, which you wish to
moechten=
alleentfernen=Delete all
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=you have no configured category. These you can define under Administrationsarea
definieren=.
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=You have chosen %s person(s). Depending on the amount of persons, this action could take a while.
waehlensiebittezunaechsteinenarbeitsbereichaus=Please, choose a work area.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=Would you like to assign the chosen work area to this person (i.e guest)
eswurdekeinarbeitsbereichzugeordnet=No work area was assigned
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=Would you like to assign the chosen work area to %s persons (i.e. guests)
eswurdenkeinearbeitsbereichzugeordnet=no work areas were assigned
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Would you like to revoke the work area assignment of this person (i.e. guest)
eswurdekeinarbeitsbereichaufgehoben=No work area revoked
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Would you like to revoke the selected work area assignment of %s persons (i.e. guests)
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Would you like to assign the selected work area to this person (i.e. guest)
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=Would you like assign the selected work area to %s persons (i.e. guests)
waehlensieeinenarbeitsbereichauswelchensie=Choose a work area, which you want to
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=You haven\u2019t configured any work area. You can these under Administrationsarea
administrationallestellvertretungenimmandanten=Administration - all representations in clients
administrationallestellvertretungen=Administration - all representations
verwaltungpersoenlichevertretungen=Administration - personal representation
vertretung=Representation
markiertevertretungen=Selected substitutions
loeschen=Delete
markiertevertretungenloeschen=Delete selected substitute(s)
gueltigab=valid from
gueltigbis=valid until
bitteauswaehlen=Please choose
gaestelisteerstellenfuerveranstaltungeventshortname=Create guest list for event
gaesteverwaltungderveranstaltung=Guests management of the event
gaestelisteerstellen=Create guest list
ausgabeformatwaehlen=Choose output format
listenachkategoriengruppiertmitpartner=List grouped by categories - with partner
listenachkategoriengruppiertmittelundmobiltelefon=List grouped by kategories - with phone and mobile
listenachkategoriengruppiertmitpartnerundfax=List grouped by categories - with partner and fax
listenachsortierungmitpartnertelundmobiltelefon=Sorted list - with partner, phone and mobile
tisch=Table
zusaetzlichesortierungnach=Additionaly sorted by
zurueckzurgaesteverwaltung=Back to guest management
verwaltungallebenutzerimmandanten=Management - all users in Clients
verwaltungallebenutzer=Management - all users
markiertenbenutzer=Selected user(s)
markiertenbenutzerloeschen=Delete selected user(s)
leseneingeschraenkt=Read only
lesenuneingeschraenkt=Read only unrestrained
lesenundschreibeneingeschraenkt=Read and write only
lesenundschreibenuneingeschraenkt=Read and write unrestrained
mandantadministrieren=Administrate client
administrieren=Administrate
stellvertretung=substitution
bittewahlensiedierolleausdiesievertretenmochten=Please choose a role you would like to represent
benutzerrolle=User roles
vertreten=represent
statistikfurgastgeber=Statistics for host
imzeitraumvom=In time frame of
biszum=Until
bis=Till
auswartigesamtintranetstil=Foreigners office Intranet-style
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Klick on a listed person, to add a Task to him.
eswurdeeinepersongeloscht=A person was deleted.
eswurdekeinepersongeloscht=No person was deleted.
personengelouscht=person deleted.
derarbeitsbereichwurdeerfolgreichhinzugefugt=The work area was added successfully.
diearbeitsbereichewurdenerfolgreichentfernt=The work areas were deleted successfully.
diekategoriewurdeerfolgreichhinzugefugt=The category was added successfully.
diekategorienwurdenerfolgreichentfernt=The categories were added successfully.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=You have no permission to delete a person.
wauhlensiebittezunauchsteineodermehrerepersonenaus=Please, choose one or more persons.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=The Expiry date of these persons is in the future
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=The following persons are assigned at least for one current or upcoming event.
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=For more detailed information, you can check the respective guest list.
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=The persons will be deleted
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=The following persons are assigned at least a task in at least on current or
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=upcoming event. For more detailed information, please check the
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=correspondant guest list. The tasks of these persons will otherwise
aufgabenentfernt=be deleted
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=If you want to adjust your selection, please stop the deletion.
sollenallemarkiertenpersonengeloeschtwerden=Should all persons be deleted?
dieseaktionkannnichtrueckgaungiggemachtwerden=This action cannot be undone.
bittebestaetigensiedasloeschendermarkiertenpersonen=Please confirm the deletion request of the selected persons!
loeschenvonpersonenistnichtmoeglich=Deletion of persons is not possible
markiertepersonenzurveranstaltunghinzufuegen=Add selected person(s) to event
zudieserpersonistkeinehauptpersoneingetragen=No main person ist added to this person.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=This person cannot be set to reserve, since the essential data
nichtvollstaendigerfasstwurden=were not thoroughly entered.
waehlensiebittezunaechsteineodermehrerepersonenaus=Please, choose one or more persons.
exportieren=Export
einladen=Invite
aufreservesetzen=Set as reserve
delegationanmelden=Register delegation
alledemarkiereninklpartnerwenneingeladen=All (de)selected (incl. Partner, if invited)
arbeitsshybereich=Work area
eswurdenkeineeintraegegefunden=No entries were found.
suchenersetzen=Search and replace
suchenersetzeninpersonendaten=Search and replace in persons data
vornamederhauptpersonunddespartners=First name of the main person and his/her partner
nachnamederhauptpersonunddespartners=Family name of the main person and his/her parnter
anredetitel=Salutation / Title
anredeundtitel=Salutation and title
straszligeadresszusatzundland=Street, additional address and country
plzortundplzpostfach=Zip code / City and Zip code / Post office box
telefontelefaxundmobiltelefon=Phone, telefax and mobile
telefonfax=Phone / Fax
emailadresse=E-mail Address
internetadresse=Internet-Addresses
ihresuchemussausmindestenseinembuchstabenbestehen=Your search fileds must include at least a letter.
siemuessenmindestenseinfeldausgewhlthaben=You should select a field at least.
eswurdekeinepersonersetzt=No person was replaced.
eswurdeeinepersonersetzt=One person was replaced.
personenersetzt=people replaced.
siemuessenmindestenseinfeldausgewaehlthaben=You should select at least one field.
eswurdekeinepersongefunden=No persons were found.
eswurdeeinepersongefunden=One person was found.
personengefunden=people found.
einzelneeinzraegezumersetzenselektieren=Singular entries were selected for replacing
allesofortersetzen=Replace all immediately
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=If you use the placeholder *, sections will also be replaced, otherwise only complete datafields.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=You should input a date in the DD.MM.JJJJ format
markierteanredenloschen=Delete selected salutation(s)
markiertendokumenttypenloschen=Delete selected document type(s)
markierteveranstaltungsorteloschen=Delete selected Venue(s)
markiertevorlagenloschen=Delete selected templates
keinedateigefunden=No file found.
standardauswahlderselectboxbdquozeichensatzrdquo=Default selection \u201Ccharacter set\u201D
zusaetzlichefelder=additional fields
postausgang=outbox
beimversendendieseremailisteinfehleraufgetreten=An error occured while sending the email.
siekonnendiesejetztbearbeitenunderneutsenden=You can now edit and send it again.
dieseemailwartetaufihrefertigstellungdurcheinenbenutzer=This email is waiting to be finished by a user.
dieseemailwartetaufihreversendung=This email is waiting to be sent.
dieseemailwirdgeradeversendetundsollte=This email is beeing sent now and should
nichtbearbeitet=not be edited.
werden=
dieseemailwurdebereitsversendetundsollte=This email has already been sent and should
nichtmehrbearbeitet=not be edited anymore
technischefehlermeldungausblenden=Hide technical error message
markiertenmandanten=Selected client(s)
markiertenmandantenwirklichloschen=delete selected client(s)
alledatensatzewurdenerfolgreichmandantenzugeordnet=All datasets were succesfully assigned to a client
esexistiertnochkeinmandant=No client existing yet.
zuordnen=Assign
zuordnen_klein=assign
markierteanreden=selected salutations
markierteanredenloeschen=delete selected salutations
markiertenarbeitsbereiche=Selected work area(s)
markierteeintraegeentfernen=Delete selected entries
emailpostausgang=E-mail outbox
markierteemailsloeschen=remove selecte e-mails
markierteemails=selected e-mail(s)
wartet=waits
wirdversendet=beeing sent
gesendet=sent
unbekannt=unknown
firmainstitutionauswaehlen=select company/institution
bittewaehlensieeinefirmainstitutionaus=Please choose a company/institution
schliessen=close
verawebuebersicht=VerA.web :: Summary
uebersichtanzeigen=show summary
neuendatensatzanlegen=apply new dataset
openofficedateiherrunterladen=Download OpenOffice-file
keinedatensaetzegefunden=No datasets found
einendatensatzgefunden=One dataset found
datensaetzegefunden=datasets found
anzeigen=show
wollensiediesendatensatzunwiderruflichentfernen=Do you wnat to remove this dataset irrevocably
verawebdetailansicht=VerA.web :: Details
datensatzbearbeiten=edit dataset
zuruecksetzen=reset
datensatzloeschen=remove dataset
siekoennenbeidersuchesogenannteplatzhalterverwendenderstehtfuermehrereunddasfuereinzelnezeichen= For searching purposes you can use so-called placeholders: * is used to replace more than one character and ? for exactly one character
undamtsbezeichnungfunktion=and employment title/function
HINT_SEARCH_WHERE=Searching in first name, last name, city, zip, street, company/institution, telephone, fax, mobile, e-mail,notes, categories, work areas
neuenorteingeben=enter new city
bittegebensieeinenneuenorteinundklickensieaufhinzufuegen=Please enter a new city and click on \u201Cadd\u201D
neuerveranstaltungsort=new venue
personenetikett=Person label
zuruckzurubersicht=Back to summary
gpsdaten=GPS-data
platzhalterintexteinfuegen=insert placeholder into text
intexteinfuegen=insert into text
emailvorlagen=E-mail template
pdfvorlagen=PDF templates
pdfvorlage=PDF template
vorhandenevorlagen=existing templates
bitteauswhaelengt=please choose
vorlageladen=load template
neuevorlagename=new template (name)
neuevorlagespeichern=save new template
neuevorlagenmuessensowohleinenbetreffalsauchtextenthalten=New templates must contain a subject and text (attachments will not be saved)
zurueckzumverteiler=Back to contributor
markiertenveranstaltungsorte=selected venue(s)
hinweis=note
aktiv=active
inaktiv=inactive
aktionen=Actions
anschrift=Address
anderungenspeichern=Save changes
senden=Send

# GENERIC
GENERIC_UPLOAD_BUTTON=Select file
GENERIC_FEDERAL_STATE=Federal state
GENERIC_PERSONAL_DATA=Personal data
GENERIC_NUMBER_OF_GUESTS=Number of guests
GENERIC_TELEFON=Telephone

# MESSAGES
MESSAGE_INVITATION_WITHOUT_MAIN_PERSON=This guest has been invited without main person
MESSAGE_INVITATION_WITHOUT_PARTNER=This guest has been invited without partner
MESSAGE_INVITATION_WITHOUT_PERSON_PART1=Do you want to
MESSAGE_INVITATION_WITHOUT_PERSON_PART2_BUTTON=invite these subsequently
MESSAGE_END_AND_START_DATE=The event\u2019s end-date needs to be after the beginning-date chronologically
MESSAGE_EVENT_MISSING_SHORT_DESCRIPTION=The event can not be saved, please give a short description
MESSAGE_EVENT_WRING_DATE_FORMAT=You need to state the event-beginn formatted like dd.mm.yyyy
MESSAGE_GENERIC_MISSING_DESCRIPTION=You need to provide a description.
MESSAGE_EVENTDOCTYPE_ASSIGNMENT_WRONG=A document type is incorrectly assigned to an event.
MESSAGE_EVENT_LOCATION_TITLE_EMPTY=The venue can not be saved. Please provide a title.
MESSAGE_EVENT_LOCATION_MAX_REMARK_REACHED=The remark-field is restricted to 1000 characters.
MESSAGE_EMAIL_DRAFT_NAME_MISSING=You need to provide a name for the e-mail template.
MESSAGE_EMAIL_DRAFT_SUBJECT_MISSING=You did not provide a subject for the e-mail template.
MESSAGE_EMAIL_DRAFT_TEXT_MISSING=You did not enter a text for this e-mail template.
MESSAGE_EMAIL_LIST_NAME_EMPTY=Please provide a name for the contributor.
MESSAGE_TASK_TIME_WITHOUT_DATE=Entering a time without an associated date is not allowed.
MESSAGE_TASK_END_DATE_NOT_FUTURE=The task can not be saved. The end-date needs to be in the future.
MESSAGE_TASK_END_DATE_WITHOUT_BEGIN_DATE=The tast can not be saved. Please provide a begin-date as well.
MESSAGE_TASK_BEGIN_DATE_BEFORE_END_DATE=The tast can not be saved. The begin-date needs to be before the end-date chronologically.
MESSAGE_TASK_NO_SHORTNAME=Tha task can not be saved. Please provide a short description.
MESSAGE_TASK_MAX_REMARK_REACHED=The task can not be saved. The description-field is restricted to 1000 characters.
MESSAGE_TASK_EMAIL_WITHOUT_SENDER=The e-mail can not be sent without a sender\u2019s address.
MESSAGE_TASK_EMAIL_WITHOUT_RECEIVER=The e-mail can not be sent without a recipient.
MESSAGE_TASK_EMAIL_WITHOUT_SUBJECT=The e-mail can not be sent without a subject.
MESSAGE_ORG_UNIT_NO_NAME=You need to provide a name.
MESSAGE_PERSON_MAX_COMPANY_REACHED=Company/institution is restricted to 100 characters.
MESSAGE_PERSON_MAX_NAME_REACHED=The main person\u2019s first name is restricted to 100 characters.
MESSAGE_PERSON_MAX_LASTNAME_REACHED=The main person\u2019s last name is restricted to 100 characters.
MESSAGE_PERSON_NO_MAIL=You need to provide an email-address.
MESSAGE_PERSON_NO_COMPANY_NAME=You need to provide a name for the company/institution.
MESSAGE_PERSON_NO_NAME_LAST_NAME=You need to provide a first- and last name.
MESSAGE_PERSON_NO_NAME=You need to provide a first name.
MESSAGE_PERSON_NO_LASTNAME=You need to provide a last name.
MESSAGE_PERSON_CATEGORY_NO_CONNECTION_PERSON_CATEGORY=Connection between person and category can not be saved.
MESSAGE_DOCTYPE_MAX_CONNECTOR_REACHED=The connector is limited to 50 characters.
MESSAGE_PROXY_NO_REPRESENTATIVE=You need to assign a representative.
MESSAGE_PROXY_NO_ROLE=You need to provide a role.
MESSAGE_PROXY_MISSING_BOTH=You need to provide a role and representative.
MESSAGE_PROXY_REPRESENTATIVE_BEGIN_BEFORE_END=The representative\u2019s begin needs to be before the end chronologically.
MESSAGE_FUNCTION_MISSING_NAME=You need to provide a name for the function.
MESSAGE_USER_MISSING_ROLE=You need to provide a description for a user role.
MESSAGE_ORGUNIT_BUSY=While the client is still assigned users it cannot be deleted.

# EVENT LIST TEXTS
EVENT_LIST_WARNING_EVENTS_IN_FUTURE=At least one of the selected events is in process or in the future.
EVENT_LIST_WARNING_SELECTION_CHANGING=If you want to edit your selection, please cancel the delete-process.
EVENT_LIST_DELETE_CONFIRMATION_MESSAGE=Remove all selected events? This action can not be undone.

# PERSON LIST TEXTS
PERSON_LIST_WARNING_NO_PERMISSION_TO_DELETE=You do not have permission to delete people.
PERSON_LIST_WARNING_ONLY_DELETE_ONE_PERSON=You are only allowed to delete one person at a time. Please select only one entry or contact your administrator.
PERSON_LIST_QUESTION_DELETE_CONFIRMATION=Delete all selected people?

# EVENT DETAIL SITE TEXTS
EVENT_DETAIL_ALREADY_EXISTS_ONE=An event with the name \u201C
EVENT_DETAIL_ALREADY_EXISTS_TWO=\u201D already exists. Do you wish to save the new event anyway?

# CATEGORY TEXTS
CATEGORY_DETAIL_ALREADY_EXISTS=A core-data entry with this name already exists

# CHANGELOG REPORTS TEXTS
CHANGELOG_NO_PROTOCOL_AVAILABLE=No log data available.

# BROWSER TITLES
BROWSER_TITLE_REPORTS=Reports


#NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GUEST_LIST_RESET_ALL_TO_MASTER_DATA=Reset all values to core data
GUEST_LIST_EDIT_MASTER_DATA=edit person core data
GUEST=guest
GENERIC_OF=of


TOOLTIP_EDIT_HEADLINES=You can still edit the headlines before printing by clicking the \u201Cedit\u201D button. Please save before printing.
GENERIC_APPLY_TO_GUESTLIST=Apply to guestlist
GENERIC_APPLY_GUEST_TO_GUESTLIST=Apply guest directly to guestlist
GENERIC_APPLY=apply
GENERIC_APPLY_PERSON_AS_HOST=Apply person directly as host
etikettfuraktuellepersonerzeugen=create label for current person

aktuellepersonloschenundzurpersonenlistezuruckkehren=Remove current person and go back to personlist
freifeldvorschaufur=Free field preview for
zudieserpersonwurdedasentsprechendevorschaufeldnochncihterzeugt=The according preview-field for this person has not been created yet
siemussendierolleangebenunterdersieverawebnutzenmochten=You need to state the role u wish to use VerA.web as.
GENERIC_CHOOSE=choose
GENERIC_RESET=reset
siehabenkeineausreichendeberechtigungumdiegastelistezuentfernen=You do not have sufficient permissions to remove guests
wahlensiebittezunachsteinenodermehreregasteaus=Please choose one or more guests first
bittebestatigensiedasloschendermarkiertengasteliste=Please confirm removing the selected guests!
GENERIC_NO_GUESTLIST_DELETED=No guests have been removed.


EVENT_DOCTYPE_RESET_INFO=Please check if there already are document types assigned to this event. If so you have to recreate the document types for this guest by clicking \u201Creset to core data\u201D.

diesistuberdenmenupunktadministrationprogrammeinstellungenmoglich=To do so, navigate to the menu administration \u2192 program settings.

GENERIC_CHOSEN_GUESTLIST=Selected guest list
exportierfahigegasteliste=exportable guest list
unvollstandigegasteliste=incomplete guest list

GUESTLIST_FILTER_EXPORT_INFO=In case you filtered the guest list, only the selected guests will be exported.

GUEST_CANNOT_BE_EXPORTED_1=A guest
GUEST_CANNOT_BE_EXPORTED_2=could
GUEST_CANNOT_BE_EXPORTED_3=not be
GUEST_CANNOT_BE_EXPORTED_4=exported
PERSON_MISSING_DOCTYPE_SPECIFIC_DATA=because no according document-type-specific data has been saved for this person

GUESTS_CANNOT_BE_EXPORTED_1=Guests
GUESTS_CANNOT_BE_EXPORTED_2=could
GUESTS_CANNOT_BE_EXPORTED_3=not be
GUESTS_CANNOT_BE_EXPORTED_4=exported
PERSONS_MISSING_DOCTYPE_SPECIFIC_DATA=because according document-type-specific data has not been saved for every person
GENERIC_TO_EVENTDETAIL=To event details
GENERIC_INSERT_CURRENT_MONTH=insert current month
GENERIC_SELECT_FUNCTION=select function
diestammdatendiesesgasteswurdengeloschtsiekonnennurdatenimrahmendieserveranstaltungbearbeiten=This guest\u2019s core data has been deleted. You can only edit the data for the purposes of this event
DELETE_SELECTED_MANDATOR=Delete selected client(s)
PROMPT_APPLY_CATEGORY_RANK_FROM_MASTERDATA=Shall the category\u2019s rank be applied from the core data?


# NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GENERIC_OF_CAPITAL=Of
GENERIC_ASSIGN=assign
GENERIC_CANCEL=Cancel
GENERIC_CONNECTOR=Connector
GENERIC_VIEW_DOCUMENT_TYPE=View Document type
GENERIC_GENERATE_DOCUMENT_TYPE=generate document type

# GUEST DETAIL TEXTS
GUEST_DETAIL_PARTNER=the partner
GUEST_DETAIL_PARTNER_GENITIV=of the partner
GUEST_DETAIL_MAINPERSON=of the main person

GUEST_DETAIL_DUP_SEAT_ERROR_ONE=Please first change the seat at
GUEST_DETAIL_DUP_SEAT_ERROR_TWO=from
GUEST_DETAIL_DUP_SEAT_ERROR_THREE=vie the guest list. This person currently sits at
GUEST_DETAIL_DUP_SEAT_ERROR_FOUR=on seat
GUEST_DETAIL_DUP_SEAT_ERROR_FIVE=. Changes have not been saved.

# GUEST TEXTS
GUEST_CALC_SERIALNO=This event is in the past already. Do you wish to recalculate the serial number anyway?

# MAILING LIST TEXTS
MAILING_LIST_NO_ADDRESSES=Failed to apply a new contributor, due to selected person\u2019s missing address-data
MAILING_LIST_SELECTED_FILE=Selected file
MAILING_LIST_ALREADY_SELECTED_FILE=This file has already been selected
MAILING_LIST_SELECTED_TOO_MANY=Too many files selected
MAILING_LIST_SELECTED_TOO_BIG=File is too big
MAILING_LIST_SIZE_NOTICE=The max size of all attachments together must not excede 1 MB.

# ORG UNIT LIST TEXTS
ORG_UNIT_NO_MANDANT_ID=Client to be inserted must not have an id
ORG_UNIT_MANDANT_ALREADY_EXISTS_ONE=Client to be inserted
ORG_UNIT_MANDANT_ALREADY_EXISTS_TWO=already exists.
ORG_UNIT_MANDANT_ID_COMPULSORY_ONE=Client to be updated
ORG_UNIT_MANDANT_ID_COMPULSORY_TWO= must have an id
ORG_UNIT_MANDANT_EXISTS_ONE=A client with the name
ORG_UNIT_MANDANT_EXISTS_TWO=already exists.

# PERSON CATEGORIES TEXTS
PERSON_CATEGORIES_SELECT_WARNING=In order to add a category, please choose a category. (You only entered a rank.)

# EXPORT FILE HEADERS
EXPORT_HEADER_DOCUMENT_TYPE=document_type
EXPORT_HEADER_FREETEXT_FIELD=free_text_field
EXPORT_HEADER_PARTNER_FREETEXT_FIELD=Partner_free_text_field
EXPORT_HEADER_INTERCONNECTS=Connector
EXPORT_HEADER_ADDRESS=Address
EXPORT_HEADER_CHARSET=Charset
EXPORT_HEADER_FUNCTION=fonction
EXPORT_HEADER_TITLE=Title
EXPORT_HEADER_ACADEMIC_TITLE=Academic_title
EXPORT_HEADER_FIRSTNAME=First_name
EXPORT_HEADER_LASTNAME=Last_name
EXPORT_HEADER_PARTNER_TITLE=Partner_title
EXPORT_HEADER_PARTNER_ACADEMIC_TITLE=Partner_Academic_title
EXPORT_HEADER_PARTNER_FIRSTNAME=Parnter_first_name
EXPORT_HEADER_PARTNER_LASTNAME=Partner_last_name
EXPORT_HEADER_POSTALCODE=ZIP-code
EXPORT_HEADER_CITY=City
EXPORT_HEADER_STREET=Street
EXPORT_HEADER_COUNTRY=Country
EXPORT_HEADER_ADDITIONAL_ADDRESS_ONE=Address_extension_1
EXPORT_HEADER_ADDITIONAL_ADDRESS_TWO=Address_extension_2
EXPORT_HEADER_CITY_OF_BORN=Place_of_birth
EXPORT_HEADER_TELEPHONE=Phone
EXPORT_HEADER_FAX=Fax
EXPORT_HEADER_EMAIL=E-mail
EXPORT_HEADER_WWW=WWW
EXPORT_HEADER_MOBILE=Mobile
EXPORT_HEADER_COMPANY=Company
EXPORT_HEADER_POST_OFFICE_BOX_NUMBER=PO_box_number
EXPORT_HEADER_POST_OFFICE_BOX_PLZ=PO_box-zip_code
EXPORT_HEADER_WORK_AREA=Working_area
EXPORT_HEADER_CATEGORY=Category
EXPORT_HEADER_CATEGORY_RANG=Category_rank
EXPORT_HEADER_RANG=rank
EXPORT_HEADER_RESERVE=reserve
EXPORT_HEADER_STATUS=Status
EXPORT_HEADER_TABLE=Table
EXPORT_HEADER_SEAT=Seat
EXPORT_HEADER_CURRENT_NUMBER=Serial_number
EXPORT_HEADER_COLOUR=Color
EXPORT_HEADER_IN_COUNTRY=In_country
EXPORT_HEADER_LANGUAGES=Languages
EXPORT_HEADER_SEX=Sex
EXPORT_HEADER_NATIONALITY=Nationality
EXPORT_HEADER_HINT_RESPONSIBLE=Hint_host
EXPORT_HEADER_HINT_ORG_TEAM=hint_org_team
EXPORT_HEADER_PARTNER_STATUS=Partner_status
EXPORT_HEADER_PARTNER_TABLE=Partner_table
EXPORT_HEADER_PARTNER_SEAT=Partner_seat
EXPORT_HEADER_PARTNER_CURRENT_NUMBER=Partner_serial_no
EXPORT_HEADER_PARTNER_COLOUR=Partner_Color
EXPORT_HEADER_PARTNER_IN_COUNTRY=In_country
EXPORT_HEADER_PARTNER_LANGUAGES=Partner_languages
EXPORT_HEADER_PARTNER_SEX=Partner_sex
EXPORT_HEADER_PARTNER_NATIONALITY=Partner_nationality
EXPORT_HEADER_PARTNER_HINT_RESPONSIBLE=Partner_hint_host
EXPORT_HEADER_PARTNER_HINT_ORG_TEAM=Partner_hint_org_team
EXPORT_HEADER_ACCEPT=Number_acceptances
EXPORT_HEADER_DECLINE=Number_declinings
EXPORT_HEADER_OPEN=Number_open
EXPORT_HEADER_GUEST_IN_PLACE=Number_guests_on_seat
EXPORT_HEADER_GUEST_IN_RESERVE=Number_guests_on_reserve
EXPORT_HEADER_EVENT_NAME=Event_name
EXPORT_HEADER_EVENT_BEGIN=Event_begin
EXPORT_HEADER_EVENT_END=Event_end
EXPORT_HEADER_EVENT_LOCATION=Venue
EXPORT_HEADER_OBSERVATION=Observation

# MAIN DATA (STAMMDATEN-WORKER) TEXTS
MAIN_DATA_WARN_ALREADY_EXISTS=A master data entry with this name already exists

# STATS (Statistik Worker)
STATS_COLUMN_EVENT_NAME=Event name
STATS_COLUMN_DATE_BEGIN=Begin
STATS_COLUMN_INVITATION_TYPE=Invitation type
STATS_COLUMN_INVITATION_STATUS=Status
STATS_COLUMN_INVITATION_STATUS_PARTNER=Status partner
STATS_COLUMN_YEAR=Year
STATS_COLUMN_MONTH=Month
STATS_COLUMN_EVENTS=Events
STATS_NOT_INVITED=not invited

# USER LIST TEXTS
USER_LIST_WARN_MANDANT_ONE=User to be inserted is already assigned to client
USER_LIST_WARN_MANDANT_TWO=.
USER_LIST_WARN_ALREADY_USER=User to be inserted is already assigned to VerA.web.
USER_LIST_WARN_NO_ID=User to be inserted must not have an id

# WORKAREA TEXTS
WORKAREA_NEED_MANDANT=You cannot create any work areas because your user account is not assigned to a client.
WORKAREA_ERROR_INCORRECT_NAME_ONE=The work area named \u201C
WORKAREA_ERROR_INCORRECT_NAME_TWO=\u201D could not be created. Please assign a client first.

# VERIFY TEXTS
VERIFY_ERROR_ACCESS_TO_DB_UNABLE=Could not establish connection to database.
VERIFY_ERROR_ACCESS_TO_DB_INTERRUPTED=Connection to database interrupted.
VERIFY_ERROR_ACCESS_TO_DB_NOT_INTERRUPTED=Failed to interrupt database connection.
VERIFY_ERROR_DB_NOT_ACCESSIBLE=Failed to connect to database.
VERIFY_ERROR_DB_VERSION_NOT_DETERMINED=Could not determine version of database-schema.
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_ONE=The database schema\u2019s version (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_TWO=) does not match the version expected by VerA.web (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_THREE=).
VERIFY_ERROR_DB_LC_CTYPE_NOT_WANTED=Your database configuration does not support the expected charset (LC_CTYPE=
VERIFY_ERROR_DB_LC_COLLATE_NOT_WANTED=Your database configuration does not support the expected rules for text comparison(LC_COLLATE=
VERIFY_ERROR_XML=An error occured while creating a XML-test document.(
VERIFY_ERROR_JAVA_ONE=The installed java-version (
VERIFY_ERROR_JAVA_TWO=) does not match the expected version (1.4).

#TO BE DELETED
inlandjageschlechtweiblich=In Country: Yes - Sex:Female
inlandjageschlechtmannlich=In Country: Yes - Sex:Male
inlandneingeschlechtweiblich=In Country: No - Sex:Female
inlandneingeschlechtmannlich=In Country: No - Sex:Male

# GENERIC DIALOG MESSAGES
GENERIC_PLEASE_WAIT_HEADER=Please wait...
GENERIC_PLEASE_WAIT_MESSAGE=This process may take some time.

# WORK AREA (Bean) TEXTS
WORKAREA_ERROR_MISSING_NAME=The work area must have a distinct, non empty name.


zurpersonensuche=To People search
steuerdatei=Control file
dokumenttypauswahlen=Choose document type
EVENT_NO_DOCTYPES_ASSIGNED=No document types have been assigned to the event yet

# DATE HELPER TEXTS
DATE_HELPER_INCORRECT_DATE= is not a valid date. Please use the format DD.MM.YYYY!

#WIP
GENERIC_SHOW_CURRENT_EVENTS=Show current event
GENERIC_FURTHER_PROCEEDING=Next steps

LETTER_MAIN_PERSON=M
LETTER_PARTNER=P
LETTER_RESERVE=R
LETTER_DELEGATION=D
LETTER_HOST=H

GENERIC_LASTNAME_WITH_SOFT_HYPHEN=Last Name
GENERIC_FIRSTNAME_WITH_SOFT_HYPHEN=First Name
GENERIC_RELOAD=Reload
GENERIC_LOAD_EXISTING_IMPORTPROCESS=Load existing import process
GENERIC_IMPORTID=Import id
GENERIC_YEAR=Year
GENERIC_COUNT=Count
GENERIC_PARTICIPATION=Participation
GENERIC_NOT_ASSIGNED_TO_CATEGORY=Not assigned to category
GENERIC_NOT_ASSIGNED_TO_WORKAREA=Not assigned to work area
GENERIC_NO_HOST_ASSIGNED=No host assigned
GENERIC_NO_GUEST_FOUND=No guest found

GENERIC_PHONE_NUMBER_SHORT=Phone number
GENERIC_FAX_NUMBER_SHORT=Fax number

GENERIC_MONTH_YEAR=Month/Year
GENERIC_LOOK_AT=look at
GENERIC_MOBILE_PHONE=Mobilte phone

PHONE_OFFICIAL=Phone official
PHONE_PRIVATE=Phone private
PHONE_MOBILE=Phone mobile

GENERIC_PARTNER_FREETEXTFIELD=Partner free text field
GENERIC_VENUE=Venue

GENERIC_TOTAL=Total
OPTION_MARK_ADMINISTRATION_CATEGORY_1=Category
OPTION_MARK_ADMINISTRATION_CATEGORY_2=Occasion
OPTION_MARK_ADMINISTRATION_CATEGORY_3=Diplo. Corps

GENERIC_IMPORTID_HYPHEN=Import id

GENERIC_SUBSTITUTED_BY=substituted by
GENERIC_NONE=none
GENERIC_ADDRESS_BLOCK=Address block

GENERIC_CONTEXT_PLURAL=Contexts

PERSON_DETAIL_DELETE_PERSON_HEADER=Please confirm the deletion of the person!
PERSON_DETAIL_DELETE_PERSON_CANCEL_DELETION=If you want to stop the deletion, please abort the procedure.
PERSON_DETAIL_DELETE_PERSON_CONFIRM_DELETION_WARNING=Would you really like to delete this person?

# PERSON HEADER TEXTS
PERSON_HEADER_NO_DOCTYPE_CONFIG=No document type was configured to be shown.

#LAST ADDED
GENERIC_GENERATE_LOGIN_CREDENTIALS_FOR_ONLINE_REGISTRATION=Generate login credentials for the Online-Registration
GENERIC_COPY_CURRENT_PERSON=Copy current person
GENERIC_ASSIGN_CURRENT_PERSON_TO_EVENT=Assign current person to an event
GENERIC_PREVIOUS_PAGE=Previous page
GENERIC_PREVIOUS_PERSON=Previous person
GENERIC_FIRST_PAGE=First page
GENERIC_FIRST_PERSON=First person
GENERIC_LAST_PAGE=Last page
GENERIC_LAST_PERSON=Last person
GENERIC_NEXT_PAGE=Next page
GENERIC_NEXT_PERSON=Next person
GENERIC_INPUT_FIELD=Input field
GENERIC_SIMPLE_COMBOBOX=Simple combobox
GENERIC_MULTIPLE_COMBOBOX=Multiple combobox

# EVENT LOCATIONS (Veranstaltungsort)
HINT_DELETE_NOT_POSSIBLE_ONE=It is not possible to delete the Venue \u201C
HINT_DELETE_NOT_POSSIBLE_TWO=\u201D, because it is related, at least, to one event.
CONFIRMATION_CREATE_LOCATION_ONE=Do you really want to delete the Venue \u201C
CONFIRMATION_CREATE_LOCATION_TWO=\u201D?

INSERT_FUNCTION_FROM_MAIN_DATA=Add function from main data
INSERT_COMPANY_FROM_MAIN_DATA=Add company from main data

HINT_GUEST_ALREADY_INVITED_SINGULAR=One guest was already invited to the event.
HINT_GUEST_ALREADY_INVITED_PLURAL=guests were already invited to the event.

MESSAGE_REPLACED_PERSON_ONE=There were
MESSAGE_REPLACED_PERSON_TWO=persons replaced.
MESSAGE_FOUND_PERSON_ONE=There were
MESSAGE_FOUND_PERSON_TWO=persons found.

HINT_POPUP_CATEGORY_SELECTION_ONE=You have chosen
HINT_POPUP_CATEGORY_SELECTION_TWO=person(s). Depending on the amount of persons, this action could take a while.

DELETE_DISTRIBUTOR=Do you really want to delete the selected distribution list?
DELETE_DISTRIBUTORS=Do you really want to delete the selected distribution lists?
PLACEHOLDER_DATE_FORMAT=dd.mm.yyyy

DELETE_EVENT_TASKS_FIRST_LINE=Please confirm to delete the selected tasks!
DELETE_EVENT_TASKS_SECOND_LINE=Delete all selected tasks? This action can not be undone.

GM_NO_CHANGES=You have made no changes.
GM_CONFIRMATION_EMAIL_DISTRIBUTOR=Create distribution E-Mail?

CONTACT_PICTURE_UPLOAD=Upload picture
CONTACT_PICTURE_CHANGE=Change picture
CONTACT_PICTURE_WRONG_SIZE=Picture size must be exactly 186x245 pixels.
PICTURE_SIZE=Picture size
PIXELS=pixels

NO_PARTNER_IN_MASTERDATA=No Partner found

#GENERAL MESSAGE
GM_CATEGORY_MODIFY_S=One category successfully modified.
GM_CATEGORY_MODIFY_P=%s categories successfully modified.
GM_CATEGORY_MODIFY_N=No categories were modified.
GM_CATEGORY_DELETE_S=One category successfully deleted.
GM_CATEGORY_DELETE_P=%s categories successfully deleted.
GM_CATEGORY_DELETE_N=Please select one or more categories.
GM_CATEGORY_INSERT_S=One new category successfully created.
GM_CATEGORY_INSERT_P=%s new categories successfully created.
GM_CATEGORY_INSERT_N=No new categories were created.
GM_CLIENT_MODIFY_S=One client successfully modified.
GM_CLIENT_MODIFY_P=%s clients successfully modified.
GM_CLIENT_MODIFY_N=No clients were modified.
GM_CLIENT_DELETE_S=One client successfully deleted.
GM_CLIENT_DELETE_P=%s clients successfully deleted.
GM_CLIENT_DELETE_N=No clients were deleted.
GM_CLIENT_INSERT_S=One new client successfully created.
GM_CLIENT_INSERT_P=%s new clients successfully created.
GM_CLIENT_INSERT_N=No new clients were created.
GM_COLOR_MODIFY_S=One color successfully modified.
GM_COLOR_MODIFY_P=%s colors successfully modified.
GM_COLOR_MODIFY_N=No colors were modified.
GM_COLOR_DELETE_S=One color successfully deleted.
GM_COLOR_DELETE_P=%s colors successfully deleted.
GM_COLOR_DELETE_N=No colors were deleted.
GM_COLOR_INSERT_S=One new color successfully created.
GM_COLOR_INSERT_P=%s new colors successfully created.
GM_COLOR_INSERT_N=No new colors were created.
GM_DELEGATION_FIELD_MODIFY_S=One delegation field successfully modified.
GM_DELEGATION_FIELD_MODIFY_P=%s delegation fields successfully modified.
GM_DELEGATION_FIELD_MODIFY_N=No delegation fields were modified.
GM_DELEGATION_FIELD_DELETE_S=One delegation field successfully deleted.
GM_DELEGATION_FIELD_DELETE_P=%s delegation fields successfully deleted.
GM_DELEGATION_FIELD_DELETE_N=No delegation fields were deleted.
GM_DELEGATION_FIELD_INSERT_S=One new delegation field successfully created.
GM_DELEGATION_FIELD_INSERT_P=%s new delegation fields successfully created.
GM_DELEGATION_FIELD_INSERT_N=No new delegation fields were created.
GM_DISTRIBUTOR_MODIFY_S=One distribution list successfully modified.
GM_DISTRIBUTOR_MODIFY_P=%s distribution list successfully modified.
GM_DISTRIBUTOR_MODIFY_N=No distribution lists were modified.
GM_DISTRIBUTOR_DELETE_S=One distribution list successfully deleted.
GM_DISTRIBUTOR_DELETE_P=%s distribution lists successfully deleted.
GM_DISTRIBUTOR_DELETE_N=No distribution lists were deleted.
GM_DISTRIBUTOR_INSERT_S=One new distribution list successfully created.
GM_DISTRIBUTOR_INSERT_P=%s new distribution lists successfully created.
GM_DISTRIBUTOR_INSERT_N=No new distribution lists were created.
GM_DOCUMENT_TYPE_MODIFY_S=One document type successfully modified.
GM_DOCUMENT_TYPE_MODIFY_P=%s document types successfully modified.
GM_DOCUMENT_TYPE_MODIFY_N=No document types were modified.
GM_DOCUMENT_TYPE_DELETE_S=One document type successfully deleted.
GM_DOCUMENT_TYPE_DELETE_P=%s document types successfully deleted.
GM_DOCUMENT_TYPE_DELETE_N=Please select one or more document types.
GM_DOCUMENT_TYPE_INSERT_S=One new document type successfully added.
GM_DOCUMENT_TYPE_INSERT_P=%s new document types successfully added.
GM_DOCUMENT_TYPE_INSERT_N=No new document types were added.
GM_EMAIL_MODIFY_S=One e-mail successfully modified.
GM_EMAIL_MODIFY_P=%s e-mails successfully modified.
GM_EMAIL_MODIFY_N=No e-mails were modified.
GM_EMAIL_DELETE_S=One e-mail successfully deleted.
GM_EMAIL_DELETE_P=%s e-mails successfully deleted.
GM_EMAIL_DELETE_N=No e-mails were deleted.
GM_EMAIL_INSERT_S=One new e-mail successfully created.
GM_EMAIL_INSERT_P=%s new e-mails successfully created.
GM_EMAIL_INSERT_N=No new e-mails were created.
GM_EVENT_MODIFY_S=One event successfully modified.
GM_EVENT_MODIFY_P=%s events successfully modified.
GM_EVENT_MODIFY_N=No events were modified.
GM_EVENT_DELETE_S=One event successfully deleted.
GM_EVENT_DELETE_P=%s events successfully deleted.
GM_EVENT_DELETE_N=No events were deleted.
GM_EVENT_INSERT_S=One new event successfully created.
GM_EVENT_INSERT_P=%s new events successfully created.
GM_EVENT_INSERT_N=No new events were created.
GM_EVENT_LOCATION_MODIFY_S=One event location successfully modified.
GM_EVENT_LOCATION_MODIFY_P=%s Venues successfully modified.
GM_EVENT_LOCATION_MODIFY_N=No Venues were modified.
GM_EVENT_LOCATION_DELETE_S=One event location successfully deleted.
GM_EVENT_LOCATION_DELETE_P=%s event locations successfully deleted.
GM_EVENT_LOCATION_DELETE_N=No event locations were deleted.
GM_EVENT_LOCATION_INSERT_S=One event location successfully inserted.
GM_EVENT_LOCATION_INSERT_P=%s new Venues successfully created.
GM_EVENT_LOCATION_INSERT_N=The venue can not be saved. Please provide a title.
GM_GUEST_MODIFY_S=One guest successfully modified.
GM_GUEST_MODIFY_P=%s guests successfully modified.
GM_GUEST_MODIFY_N=No guests were modified.
GM_GUEST_DELETE_S=One guest successfully deleted.
GM_GUEST_DELETE_P=%s guests successfully deleted.
GM_GUEST_DELETE_N=No guests were deleted.
GM_GUEST_INSERT_S=One new guest successfully added.
GM_GUEST_INSERT_P=%s new guests successfully added.
GM_GUEST_INSERT_N=No new guests were added.
GM_MAIL_DRAFT_MODIFY_S=One mail draft successfully modified.
GM_MAIL_DRAFT_MODIFY_P=%s mail drafts successfully modified.
GM_MAIL_DRAFT_MODIFY_N=No mail drafts were modified.
GM_MAIL_DRAFT_DELETE_S=One mail draft successfully deleted.
GM_MAIL_DRAFT_DELETE_P=%s mail drafts successfully deleted.
GM_MAIL_DRAFT_DELETE_N=No mail drafts were deleted.
GM_MAIL_DRAFT_INSERT_S=One new mail draft successfully created.
GM_MAIL_DRAFT_INSERT_P=%s new mail drafts successfully created.
GM_MAIL_DRAFT_INSERT_N=No new mail drafts were created.
GM_OFFICIAL_TITLE_MODIFY_S=One official title successfully modified.
GM_OFFICIAL_TITLE_MODIFY_P=%s official titles successfully modified.
GM_OFFICIAL_TITLE_MODIFY_N=No official titles were modified.
GM_OFFICIAL_TITLE_DELETE_S=One official title successfully deleted.
GM_OFFICIAL_TITLE_DELETE_P=%s official titles successfully deleted.
GM_OFFICIAL_TITLE_DELETE_N=No official titles were deleted.
GM_OFFICIAL_TITLE_INSERT_S=One new official title successfully created.
GM_OFFICIAL_TITLE_INSERT_P=%s new official titles successfully created.
GM_OFFICIAL_TITLE_INSERT_N=No new official titles were created.
GM_PERSON_MODIFY_S=One person successfully modified.
GM_PERSON_MODIFY_P=%s persons successfully modified.
GM_PERSON_MODIFY_N=No persons were modified.
GM_PERSON_DELETE_S=One person successfully deleted.
GM_PERSON_DELETE_P=%s persons successfully deleted.
GM_PERSON_DELETE_N=No persons were deleted.
GM_PERSON_INSERT_S=One new person successfully created.
GM_PERSON_INSERT_P=%s new persons successfully created.
GM_PERSON_INSERT_N=No new persons were created.
GM_REPRESENTATIVE_MODIFY_S=One representative successfully modified.
GM_REPRESENTATIVE_MODIFY_P=%s representatives successfully modified.
GM_REPRESENTATIVE_MODIFY_N=No representatives were modified.
GM_REPRESENTATIVE_DELETE_S=One representative successfully deleted.
GM_REPRESENTATIVE_DELETE_P=%s representatives successfully deleted.
GM_REPRESENTATIVE_DELETE_N=No representatives were deleted.
GM_REPRESENTATIVE_INSERT_S=One new representative successfully created.
GM_REPRESENTATIVE_INSERT_P=%s new representatives successfully created.
GM_REPRESENTATIVE_INSERT_N=No new representatives were created.
GM_SALUTATION_MODIFY_S=One salutation successfully modified.
GM_SALUTATION_MODIFY_P=%s salutations successfully modified.
GM_SALUTATION_MODIFY_N=No salutations were modified.
GM_SALUTATION_DELETE_S=One salutation successfully deleted.
GM_SALUTATION_DELETE_P=%s salutations successfully deleted.
GM_SALUTATION_DELETE_N=No salutations were deleted.
GM_SALUTATION_INSERT_S=One new salutation successfully created.
GM_SALUTATION_INSERT_P=%s new salutations successfully created.
GM_SALUTATION_INSERT_N=No new salutations were created.
GM_TASK_MODIFY_S=One task successfully modified.
GM_TASK_MODIFY_P=%s tasks successfully modified.
GM_TASK_MODIFY_N=No tasks were modified.
GM_TASK_DELETE_S=One task successfully deleted.
GM_TASK_DELETE_P=%s tasks successfully deleted.
GM_TASK_DELETE_N=No tasks were deleted.
GM_TASK_INSERT_S=One new task successfully created.
GM_TASK_INSERT_P=%s new tasks successfully created.
GM_TASK_INSERT_N=No new tasks were created.
GM_USER_MODIFY_S=One user successfully modified.
GM_USER_MODIFY_P=%s users successfully modified.
GM_USER_MODIFY_N=No users were modified.
GM_USER_DELETE_S=One user successfully deleted.
GM_USER_DELETE_P=%s users successfully deleted.
GM_USER_DELETE_N=No users were deleted.
GM_USER_INSERT_S=One new user successfully created.
GM_USER_INSERT_P=%s new users successfully created.
GM_USER_INSERT_N=No new users were created.
GM_WORKAREA_MODIFY_S=One work area successfully modified.
GM_WORKAREA_MODIFY_P=%s work areas successfully modified.
GM_WORKAREA_MODIFY_N=No work areas were modified.
GM_WORKAREA_DELETE_S=One work area successfully deleted.
GM_WORKAREA_DELETE_P=%s work areas successfully deleted.
GM_WORKAREA_DELETE_N=No work areas were deleted.
GM_WORKAREA_INSERT_S=One new work area successfully created.
GM_WORKAREA_INSERT_P=%s new work areas successfully created.
GM_WORKAREA_INSERT_N=No new work areas were created.

GM_PDF_TEMPLATE_MODIFY_S=One PDF template successfully modified.
GM_PDF_TEMPLATE_MODIFY_P=%s PDF templates successfully modified.
GM_PDF_TEMPLATE_MODIFY_N=No PDF templates were modified.
GM_PDF_TEMPLATE_DELETE_S=One PDF template successfully deleted.
GM_PDF_TEMPLATE_DELETE_P=%s PDF templates successfully deleted.
GM_PDF_TEMPLATE_DELETE_N=No PDF templates were deleted.
GM_PDF_TEMPLATE_INSERT_S=One new PDF template successfully created.
GM_PDF_TEMPLATE_INSERT_P=%s new PDF templates successfully created.
GM_PDF_TEMPLATE_INSERT_N=No new PDF templates were created.

PDF_TEMPLATE_NOT_EMPTY_ERROR_MESSAGE=Name of template can not be empty
PDF_TEMPLATE_NO_FILE_ERROR_MESSAGE=A PDF File can not be empty
PDF_TEMPLATE_LIST_NOT_LOAD=PDF templates list could not be load
PDF_GENERATE_BUTTON=Generate PDF35
PDF_GENERATE_LABEL=PDF-Export

LOAD_MAILTEMPLATE_FAILED = Loading e-mail template failed
SELECT_MAILTEMPLATE = Please select e-mail template

ADDRESS_ERROR = E-mails sent successfully. At least one e-mail address contained errors! The distribution was not sent to the following e-mail address(es). Pleas correct the wrong address(es):

LABELLING_MUST_NOT_BE_EMPTY:The Titel must not be empty

birthplace_a_e1=Place of birth mustn't be longer than 100 characters
birthplace_a_e2=Place of birth mustn't be longer than 100 characters
birthplace_a_e3=Place of birth mustn't be longer than 100 characters
city_a_e1=City mustn't be longer than 300 characters
city_a_e2=City mustn't be longer than 300 characters
city_a_e3=City mustn't be longer than 300 characters
city_b_e1=City mustn't be longer than 300 characters
city_b_e2=City mustn't be longer than 300 characters
city_b_e3=City mustn't be longer than 300 characters
city_c_e1=City mustn't be longer than 300 characters
city_c_e2=City mustn't be longer than 300 characters
city_c_e3=City mustn't be longer than 300 characters
company_a_e1=Company/Institution mustn't be longer than 250 characters
company_a_e2=Company/Institution mustn't be longer than 250 characters
company_a_e3=Company/Institution mustn't be longer than 250 characters
company_b_e1=Company/Institution mustn't be longer than 250 characters
company_b_e2=Company/Institution mustn't be longer than 250 characters
company_b_e3=Company/Institution mustn't be longer than 250 characters
company_c_e1=Company/Institution mustn't be longer than 250 characters
company_c_e2=Company/Institution mustn't be longer than 250 characters
company_c_e3=Company/Institution mustn't be longer than 250 characters
country_a_e1=Country mustn't be longer than 100 characters
country_a_e2=Country mustn't be longer than 100 characters
country_a_e3=Country mustn't be longer than 100 characters
country_b_e1=Country mustn't be longer than 100 characters
country_b_e2=Country mustn't be longer than 100 characters
country_b_e3=Country mustn't be longer than 100 characters
country_c_e1=Country mustn't be longer than 100 characters
country_c_e2=Country mustn't be longer than 100 characters
country_c_e3=Country mustn't be longer than 100 characters
fax_a_e1=Fax mustn't be longer than 100 characters
fax_a_e2=Fax mustn't be longer than 100 characters
fax_a_e3=Fax mustn't be longer than 100 characters
fax_b_e1=Fax mustn't be longer than 100 characters
fax_b_e2=Fax mustn't be longer than 100 characters
fax_b_e3=Fax mustn't be longer than 100 characters
fax_c_e1=Fax mustn't be longer than 100 characters
fax_c_e2=Fax mustn't be longer than 100 characters
fax_c_e3=Fax mustn't be longer than 100 characters
firstname_a_e1=First name mustn't be longer than 100 characters
firstname_a_e2=First name mustn't be longer than 100 characters
firstname_a_e3=First name mustn't be longer than 100 characters
firstname_b_e1=First name mustn't be longer than 100 characters
firstname_b_e2=First name mustn't be longer than 100 characters
firstname_b_e3=First name mustn't be longer than 100 characters
fon_a_e1=Telephone mustn't be longer than 100 characters
fon_a_e2=Telephone mustn't be longer than 100 characters
fon_a_e3=Telephone mustn't be longer than 100 characters
fon_b_e1=Telephone mustn't be longer than 100 characters
fon_b_e2=Telephone mustn't be longer than 100 characters
fon_b_e3=Telephone mustn't be longer than 100 characters
fon_c_e1=Telephone mustn't be longer than 100 characters
fon_c_e2=Telephone mustn't be longer than 100 characters
fon_c_e3=Telephone mustn't be longer than 100 characters
function_a_e1=Function mustn't be longer than 250 characters
function_a_e2=Function mustn't be longer than 250 characters
function_a_e3=Function mustn't be longer than 250 characters
function_b_e1=Function mustn't be longer than 250 characters
function_b_e2=Function mustn't be longer than 250 characters
function_b_e3=Function mustn't be longer than 250 characters
function_c_e1=Function mustn't be longer than 250 characters
function_c_e2=Function mustn't be longer than 250 characters
function_c_e3=Function mustn't be longer than 250 characters
languages_a_e1=Languages mustn't be longer than 250 characters
languages_b_e1=Languages mustn't be longer than 250 characters
lastname_a_e1=Last name mustn't be longer than 100 characters
lastname_a_e2=Last name mustn't be longer than 100 characters
lastname_a_e3=Last name mustn't be longer than 100 characters
lastname_b_e1=Last name mustn't be longer than 100 characters
lastname_b_e2=Last name mustn't be longer than 100 characters
lastname_b_e3=Last name mustn't be longer than 100 characters
mail_a_e1=E-Mail mustn't be longer than 250 characters
mail_a_e2=E-Mail mustn't be longer than 250 characters
mail_a_e3=E-Mail mustn't be longer than 250 characters
mail_b_e1=E-Mail mustn't be longer than 250 characters
mail_b_e2=E-Mail mustn't be longer than 250 characters
mail_b_e3=E-Mail mustn't be longer than 250 characters
mail_c_e1=E-Mail mustn't be longer than 250 characters
mail_c_e2=E-Mail mustn't be longer than 250 characters
mail_c_e3=E-Mail mustn't be longer than 250 characters
mobil_a_e1=Mobile mustn't be longer than 100 characters
mobil_a_e2=Mobile mustn't be longer than 100 characters
mobil_a_e3=Mobile mustn't be longer than 100 characters
mobil_b_e1=Mobile mustn't be longer than 100 characters
mobil_b_e2=Mobile mustn't be longer than 100 characters
mobil_b_e3=Mobile mustn't be longer than 100 characters
mobil_c_e1=Mobile mustn't be longer than 100 characters
mobil_c_e2=Mobile mustn't be longer than 100 characters
mobil_c_e3=Mobile mustn't be longer than 100 characters
nationality_a_e1=Nationality/Citizenship mustn't be longer than 100 characters
nationality_b_e1=Nationality/Citizenship mustn't be longer than 100 characters
note_a_e1=Comment mustn't be longer than 2000 characters.
note_b_e1=Comment mustn't be longer than 2000 characters.
notehost_a_e1=Hint for host mustn't be longer than 2000 characters.
notehost_b_e1=Hint for host mustn't be longer than 2000 characters.
noteorga_a_e1=Hint for Orga mustn't be longer than 2000 characters.
noteorga_b_e1=Hint for Orga mustn't be longer than 2000 characters.
pobox_a_e1=Post office box mustn't be longer than 50 characters
pobox_a_e2=Post office box mustn't be longer than 50 characters
pobox_a_e3=Post office box mustn't be longer than 50 characters
pobox_b_e1=Post office box mustn't be longer than 50 characters
pobox_b_e2=Post office box mustn't be longer than 50 characters
pobox_b_e3=Post office box mustn't be longer than 50 characters
pobox_c_e1=Post office box mustn't be longer than 50 characters
pobox_c_e2=Post office box mustn't be longer than 50 characters
pobox_c_e3=Post office box mustn't be longer than 50 characters
poboxzipcode_a_e1=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_a_e2=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_a_e3=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_b_e1=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_b_e2=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_b_e3=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_c_e1=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_c_e2=Postal code for POB mustn't be longer than 50 characters
poboxzipcode_c_e3=Postal code for POB mustn't be longer than 50 characters
state_a_e1=Federal state mustn't be longer than 100 characters
state_a_e2=Federal state mustn't be longer than 100 characters
state_a_e3=Federal state mustn't be longer than 100 characters
state_b_e1=Federal state mustn't be longer than 100 characters
state_b_e2=Federal state mustn't be longer than 100 characters
state_b_e3=Federal state mustn't be longer than 100 characters
state_c_e1=Federal state mustn't be longer than 100 characters
state_c_e2=Federal state mustn't be longer than 100 characters
state_c_e3=Federal state mustn't be longer than 100 characters
street_a_e1=Street mustn't be longer than 100 characters
street_a_e2=Street mustn't be longer than 100 characters
street_a_e3=Street mustn't be longer than 100 characters
street_b_e1=Street mustn't be longer than 100 characters
street_b_e2=Street mustn't be longer than 100 characters
street_b_e3=Street mustn't be longer than 100 characters
street_c_e1=Street mustn't be longer than 100 characters
street_c_e2=Street mustn't be longer than 100 characters
street_c_e3=Street mustn't be longer than 100 characters
suffix1_a_e1=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_a_e2=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_a_e3=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_b_e1=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_b_e2=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_b_e3=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_c_e1=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_c_e2=Adresszusatz 1 mustn't be longer than 100 characters
suffix1_c_e3=Adresszusatz 1 mustn't be longer than 100 characters
suffix2_a_e1=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_a_e2=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_a_e3=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_b_e1=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_b_e2=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_b_e3=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_c_e1=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_c_e2=Adresszusatz 2 mustn't be longer than 100 characters
suffix2_c_e3=Adresszusatz 2 mustn't be longer than 100 characters
title_a_e1=Acad. title mustn't be longer than 250 characters
title_a_e2=Acad. title mustn't be longer than 250 characters
title_a_e3=Acad. title mustn't be longer than 250 characters
title_b_e1=Acad. title mustn't be longer than 250 characters
title_b_e2=Acad. title mustn't be longer than 250 characters
title_b_e3=Acad. title mustn't be longer than 250 characters
url_a_e1=WWW mustn't be longer than 250 characters
url_a_e2=WWW mustn't be longer than 250 characters
url_a_e3=WWW mustn't be longer than 250 characters
url_b_e1=WWW mustn't be longer than 250 characters
url_b_e2=WWW mustn't be longer than 250 characters
url_b_e3=WWW mustn't be longer than 250 characters
url_c_e1=WWW mustn't be longer than 250 characters
url_c_e2=WWW mustn't be longer than 250 characters
url_c_e3=WWW mustn't be longer than 250 characters
zipcode_a_e1=Postal code mustn't be longer than 250 characters
zipcode_a_e2=Postal code mustn't be longer than 250 characters
zipcode_a_e3=Postal code mustn't be longer than 250 characters
zipcode_b_e1=Postal code mustn't be longer than 250 characters
zipcode_b_e2=Postal code mustn't be longer than 250 characters
zipcode_b_e3=Postal code mustn't be longer than 250 characters
zipcode_c_e1=Postal code mustn't be longer than 250 characters
zipcode_c_e2=Postal code mustn't be longer than 250 characters
zipcode_c_e3=Postal code mustn't be longer than 250 characters
internal_id=The internal ID mustn't be longer than 45 characters.
INTERNAL_ID=The internal ID


# ALTERNATIVE SALUTATIONS
SALUTATION_EDITABLE_TEXT=Alternative salutations for this PDF template can be created here
SALUTATION_TO_SALUTATION=becomes
SALUTATION_ERROR_LOAD=Error while loading
SALUTATION_ERROR_EMPTY=Alternative Salutations must not be empty
SALUTATION_ERROR_SAVE=Error while saving
SALUTATION_ERROR_DELETE=Error while deleting
SALUTATION_ERROR_LENGTH=Alternative Salutations mustn't be longer than 100 characters
