language=Espa\u00F1ol
language_short=es

# BROWSER TAB-TITLE
BROWSER_TITLE_CATEGORY=Categor\u00EDas
BROWSER_TITLE_CLEANUP=Limpiar
BROWSER_TITLE_COLOURS=Colores
BROWSER_TITLE_GENERAL_CONFIGS=Configuraci\u00F3n general
BROWSER_TITLE_TASKS=Tareas
BROWSER_TITLE_DOCUMENT_TYPES=Tipos de documento
BROWSER_TITLE_IMPORT_DUPLICATE_ACCEPT=Estado de la importaci\u00F3n - Importar duplicados
BROWSER_TITLE_ERROR_OCCURS=Ha ocurrido un error
BROWSER_TITLE_EVENT_EDIT=Editar evento
BROWSER_TITLE_EVENT_CREATE=Crear nuevo evento
BROWSER_TITLE_EVENT_SELECT=Seleccionar evento
BROWSER_TITLE_PERSON_ASSIGN=Asignar persona
BROWSER_TITLE_EVENT_SEARCH=Buscar evento
BROWSER_TITLE_TASKS_EDIT=Editar tarea
BROWSER_TITLE_TASKS_CREATE=Crear nueva tarea
BROWSER_TITLE_EXPORT_PERSONDATA=Exportar datos de personas
BROWSER_TITLE_IMPORT_PERSONDATA=Importar datos de personas
BROWSER_TITLE_EVENT_GUESTLIST=Lista de invitados al evento
BROWSER_TITLE_EVENT_EXPORT_DATA=Generar archivo de control
BROWSER_TITLE_IMPORT_STATUS=Estado del proceso de importaci\u00F3n
BROWSER_TITLE_HELP=Ayuda
BROWSER_TITLE_INFO_VERAWEB=Acerca de VerA.web
BROWSER_TITLE_EVENT_LOCATION_EDIT=Editar localizaci\u00F3n del evento
BROWSER_TITLE_EVENT_LOCATION_CREATE=Crear nueva localizaci\u00F3n para el evento
BROWSER_TITLE_EVENT_LOCATION=Localizaciones del evento
BROWSER_TITLE_EMAIL_SUBMISSION_CREATE=Crear nueva plantilla de correo electr\u00F3nico
BROWSER_TITLE_EMAIL_SUBMISSION_EDIT=Editar plantilla de correo electr\u00F3nico
BROWSER_TITLE_EMAIL_SUBMISSION=Plantillas de correo electr\u00F3nico
BROWSER_TITLE_PDF_TEMPLATE=Plantilla PDF
BROWSER_TITLE_DISTRIBUTOR_CREATE=Crear distribuidor
BROWSER_TITLE_DISTRIBUTOR_LIST=Lista de distribuidores
BROWSER_TITLE_EMAIL_WRITE_DISTRIBUTOR=Escribir E-mail a distribuidor
BROWSER_TITLE_EMAIL_EDIT=Editar E-mail
BROWSER_TITLE_EMAIL_CREATE=Redactar E-mail
BROWSER_TITLE_EMAIL_OUTBOX=Bandeja de salida
BROWSER_TITLE_ROLE_WITH=con el rol
BROWSER_TITLE_ROLE_AVAILABLE=con el rol disponible
BROWSER_TITLE_ROLE_WITHOUT_INFO=sin informaci\u00F3n de roles
BROWSER_TITLE_SUCCESSFUL_LOGIN_ONE=Acceso satisfactorio
BROWSER_TITLE_SUCCESSFUL_LOGIN_TWO=al identificarse en el sistema
BROWSER_TITLE_PERSON_EDIT=Editar persona
BROWSER_TITLE_PERSON_CREATE=Crear nueva persona
BROWSER_TITLE_GUEST_ADD_EVENT=A\u00F1adir invitado al
BROWSER_TITLE_GUEST_HOST_ADD_EVENT=Seleccionar anfitri\u00F3n para
BROWSER_TITLE_GUEST_SELECT=Seleccionar invitado
BROWSER_TITLE_GUEST_HOST_SELECT=Seleccionar anfitri\u00F3n
BROWSER_TITLE_SEARCH_REPLACE_PERSONDATA=Buscar y reemplazar persona
BROWSER_TITLE_DUPLICATE_SEARCH=B\u00FAsqueda de duplicados
BROWSER_TITLE_TASK_ADD_RESPONSIBLE=Seleccionar responsable de la tarea
BROWSER_TITLE_PERSON_DELETE=Eliminar persona
BROWSER_TITLE_PERSON_LIST=Lista de personas
BROWSER_TITLE_SEARCH_REPLACE=Buscar y reemplazar
BROWSER_TITLE_GUEST_HOST_SEARCH=Buscar anfitri\u00F3n
BROWSER_TITLE_PERSON_SEARCH=Buscar persona
BROWSER_TITLE_PERSON_DATA_SALUTATION=Datos maestros - Denominaci\u00F3n
BROWSER_TITLE_LOGIN_REPRESENTATIVE=Acceder como representante
BROWSER_TITLE_STATISTIC_CREATE=Generar estad\u00EDsticas
BROWSER_TITLE_USER_CONFIGS=Configuraci\u00F3n de usuario
BROWSER_TITLE_WORK_AREAS=\u00C1reas de trabajo
BROWSER_TITLE_OVERVIEW_EVENTS_YEAR=Resumen del n\u00FAmero de eventos anual
BROWSER_TITLE_OVERVIEW_EVENTS_MONTH=Resumen del n\u00FAmero de eventos mensual
BROWSER_TITLE_OVERVIEW_GUEST_HOST_EVENTS=Resumen de eventos por anfitri\u00F3n
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST_HOST=Resumen de eventos, agrupados por anfitri\u00F3n
BROWSER_TITLE_OVERVIEW_GUEST_EVENTS=Resumen de eventos por invitado
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST=Resumen de eventos, agrupados por invitados
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_PLACE=Resumen de eventos por localizaci\u00F3n
BROWSER_TITLE_OVERVIEW_EVENTS_UNKNOWN_STATISTIC=ESTAD\u00CDSTICA DESCONOCIDA

# YOU MUST SET THESE PLACEHOLDERS WITH THE GENDER TYPE OF YOUR LANGUAGE FOR EACH OBJECT AS MALE OR FEMALE
GENDER_TYPE_CATEGORY=Mujer
GENDER_TYPE_CLIENT=Hombre
GENDER_TYPE_COLOR=Mujer
GENDER_TYPE_DELEGATION_FIELD=Mujer
GENDER_TYPE_DISTRIBUTOR=Hombre
GENDER_TYPE_DOCUMENT_TYPE=Hombre
GENDER_TYPE_EMAIL=Mujer
GENDER_TYPE_EVENT=Mujer
GENDER_TYPE_EVENT_LOCATION=Hombre
GENDER_TYPE_FUNCTION_OFFICIAL_TITLE=Mujer
GENDER_TYPE_GUEST=Hombre
GENDER_TYPE_MAIL_DRAFT=Mujer
GENDER_TYPE_PDF_TEMPLATE=Mujer
GENDER_TYPE_PERSON=Mujer
GENDER_TYPE_REPRESENTATIVE=Mujer
GENDER_TYPE_SALUTATION=Mujer
GENDER_TYPE_TASK=Mujer
GENDER_TYPE_USER=Hombre
GENDER_TYPE_WORKAREA=Hombre

# REPETITIVE OBJECTS IN THER SINGULAR- AND PLURAL-TYPE
GENERIC_ADDRESS_DATA_PLURAL=Datos de la direcci\u00F3n
GENERIC_CATEGORY_SINGULAR=Categor\u00EDa
GENERIC_KEYWORDS=Palabras clave
GENERIC_CATEGORY_PLURAL=Categor\u00EDas
GENERIC_CLIENT_SINGULAR=Mandante
GENERIC_CLIENT_PLURAL=Mandantes
GENERIC_COLOR_SINGULAR=Color
GENERIC_COLOR_PLURAL=Colores
GENERIC_COMPANY_SINGULAR=Empresa
GENERIC_COMPANY_PLURAL=Empresas
GENERIC_DELEGATION_FIELD_SINGULAR=Campo adicional
GENERIC_DELEGATION_FIELD_PLURAL=Campos adicionales
GENERIC_DISTRIBUTOR_SINGULAR=Distribuidor
GENERIC_DISTRIBUTOR_PLURAL=Distribuidores
GENERIC_EMAIL_SINGULAR=E-Mail
GENERIC_EMAIL_PLURAL=E-Mails
GENERIC_EVENT_SINGULAR=evento
GENERIC_EVENT_PLURAL=eventos
GENERIC_EVENT_LOCATION_SINGULAR=Localizaci\u00F3n del evento
GENERIC_EVENT_LOCATION_PLURAL=Localizaciones del evento
GENERIC_FUNCTION_SINGULAR=Funci\u00F3n
GENERIC_FUNCTION_PLURAL=Funciones
GENERIC_GUEST_SINGULAR=Invitado
GENERIC_GUEST_PLURAL=Invitados
GENERIC_GUEST_NONE=Sin invitados
GENERIC_INSTITUTION_SINGULAR=Instituci\u00F3n
GENERIC_INSTITUTION_PLURAL=Instituciones
GENERIC_MAIL_DRAFT_SINGULAR=plantilla
GENERIC_MAIL_DRAFT_PLURAL=plantillas
GENERIC_PDF_TEMPLATE_SINGULAR=Plantilla PDF
GENERIC_PDF_TEMPLATE_PLURAL=Plantillas PDF
GENERIC_PDF_TEMPLATE_S_P=Plantilla(s) PDF
GENERIC_PDF_FILE=Archivo PDF
GENERIC_OFFICIAL_TITLE_SINGULAR=T\u00EDtulo
GENERIC_OFFICIAL_TITLE_PLURAL=T\u00EDtulos
GENERIC_PERSON_SINGULAR=Persona
GENERIC_PERSON_PLURAL=Personas
GENERIC_REPRESENTATIVE_SINGULAR=Representante
GENERIC_REPRESENTATIVE_PLURAL=Representantes
GENERIC_SALUTATION_SINGULAR=Denominaci\u00F3n
GENERIC_SALUTATION_PLURAL=Denominaciones
GENERIC_STATUS_OPEN=Abierto
GENERIC_STATUS_ACCEPT=Confirmado
GENERIC_STATUS_DECLINE=Rechazado
GENERIC_STATUS_PARTICIPATED=Participante
GENERIC_TASK_SINGULAR=Tarea
GENERIC_TASK_PLURAL=Tareas
GENERIC_USER_SINGULAR=Usuario
GENERIC_USER_PLURAL=Usuarios
GENERIC_WORKAREA_SINGULAR=\u00C1rea de trabajo
GENERIC_WORKAREA_PLURAL=\u00C1reas de trabajo
GENERIC_SELECT_ALL=Seleccionar todo

# HEADER MESSAGES
HEADER_REPRESENTATION_FOR=En representaci\u00F3n de
HEADER_COUNT_INSERT_ZERO_PART_ONE=Se ha creado
HEADER_COUNT_INSERT_ONE_PART_ONE=Se ha creado
HEADER_COUNT_INSERT_ELSE_PART_ONE=Se han creado
HEADER_COUNT_INSERT_ZERO_PART_TWO=
HEADER_COUNT_INSERT_ONE_PART_TWO=
HEADER_COUNT_INSERT_ELSE_PART_TWO=
HEADER_COUNT_REMOVE_ZERO_PART_ONE=No se ha eliminado
HEADER_COUNT_REMOVE_ONE_PART_ONE=Se ha eliminado
HEADER_COUNT_REMOVE_ELSE_PART_ONE=Se han eliminado
HEADER_COUNT_REMOVE_ZERO_PART_TWO=
HEADER_COUNT_REMOVE_ONE_PART_TWO=
HEADER_COUNT_REMOVE_ELSE_PART_TWO=
HEADER_COUNT_UPDATE_ZERO_PART_ONE=Se ha modificado
HEADER_COUNT_UPDATE_ONE_PART_ONE =Se ha modificado
HEADER_COUNT_UPDATE_ELSE_PART_ONE=Se han modificado
HEADER_COUNT_UPDATE_ZERO_PART_TWO=
HEADER_COUNT_UPDATE_ONE_PART_TWO=
HEADER_COUNT_UPDATE_ELSE_PART_TWO=
HEADER_ELEMENT_FEMALE_NO=ninguna
HEADER_ELEMENT_FEMALE_ONE=un
HEADER_ELEMENT_FEMALE_NEW=
HEADER_ELEMENT_MALE_NO=
HEADER_ELEMENT_MALE_ONE=un
HEADER_ELEMENT_MALE_NEW=
HEADER_ELEMENT_NO_RECORD_SINGULAR=ning\u00FAn registro
HEADER_ELEMENT_NO_NEW_RECORD_SINGULAR=ning\u00FAn nuevo registro
HEADER_ELEMENT_ONE_RECORD_SINGULAR=un registro
HEADER_ELEMENT_ONE_NEW_RECORD_SINGULAR=un nuevo registro
HEADER_ELEMENT_PLURAL=Registros
HEADER_ELEMENT_NEW_PLURAL=nuevos registros

# FIXES
GENERIC_EDIT=Editar
GENERIC_OFFICIAL_TITLE_SHORT=T\u00EDtulo
LETTER_COMMERCIAL=(G)
GENERIC_WRITE_EMAIL=Redactar E-mail
GENERIC_SEARCH_FOR_PERSON=Buscar persona
GENERIC_CHOOSE_ROLE=Seleccionar rol
GENERIC_EVENT=Evento
GENERIC_EVENTS=Eventos
SHOW_ALL_RECORDS=Mostrar todos los registros
SHOW_RECORDS_1=Mostrar
SHOW_RECORDS_2=registros
GENERIC_NO_WORKAREA_TEXT=-

# GENERALLY USED
GENERIC_EMAIL_ADDRESS=Direcci\u00F3n de correo electr\u00F3nico
GENERIC_FROM=De
GENERIC_LANGUAGE=Idioma
GENERIC_LOGOUT=Cerrar sesi\u00F3n
GENERIC_ON=En
GENERIC_ON_LOWERCASE=en
GENERIC_PAGE=P\u00E1gina
GENERIC_PAGES=P\u00E1ginas
GENERIC_PLACE=plaza
GENERIC_ALTERNATIVE=Alternativo

# MENU
MENU_PERSONS=Personas
MENU_EVENTS=Eventos
MENU_MANAGEMENT=Gesti\u00F3n
MENU_ADMINISTRATION=Administraci\u00F3n

# ANMELDUNG
LOGIN_ERROR=El nombre de usuario y contrase\u00F1a son incorrectos. Por favor, vuelva a introducir los datos de acceso.
GENERIC_PASSWORD=Contrase\u00F1a
LOGIN_REPRESENTATION=Acceder como representante
GENERIC_LOGIN=Acceder
GENERIC_CLEAR_FIELDS=Reiniciar
HINT_LOGIN_ORGANISATION_ONE=Por favor, utilice el nombre de su organizaci\u00F3n o
HINT_LOGIN_ORGANISATION_TWO=nombre.apellido
HINT_LOGIN_ORGANISATION_THREE=como nombre de usuario

# WELCOME SITE: FIRST PAGE AFTER LOGIN
administration=Administraci\u00F3n
bittewaehlensieeineamtsbezeichnungfunktionaus=Por favor, seleccione una funci\u00F3n/t\u00EDtulo
eskannzuunerwartetenfehlernkommenbittewendensiesichanihrenadministrator=Pueden ocurrir errores inesperados. Por favor, contacte con su administrador.
willkommenbeiveraweb=Bienvenido a VerA.web
WELCOME_TEXT_GRANT_READ_STANDARD_FIELDS=Usted tiene la posibilidad de visualizar y exportar los datos maestros de personas y eventos.
WELCOME_TEXT_GRANT_READ_REMARK_FIELDS=Usted tiene la posibilidad de visualizar y exportar los datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_EXPORT_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar la informaci\u00F3n
WELCOME_TEXT_GRANT_WRITE_FULL=y observaciones
WELCOME_TEXT_GRANT_EXPORT_PART_TWO=de personas y eventos.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_TWO=Tambi\u00E9n puede visualizar y editar la configuraci\u00F3n del mandante.
WELCOME_TEXT_GRANT_ADMIN_PART_ONE=Usted tiene la posibilidad de visualizar, exportar, importar, editar y eliminar los datos maestros y observaciones de personas y eventos.
WELCOME_TEXT_GRANT_ADMIN_PART_TWO=Tambi\u00E9n puede visualizar y editar la configuraci\u00F3n global y por mandante.
WELCOME_TEXT_HELP=Si necesita m\u00E1s informaci\u00F3n, por favor visite la p\u00E1gina de \u201CAyuda\u201D.
WELCOME_TEXT_NO_ROLE=Su acceso no dispone de rol para utilizar VerA.web. Por favor, cierre su sesi\u00F3n y vuelva a intentarlo con una cuenta de usuario habilitada en VerA.web.
GENERIC_AVAILABLE_DUPLICATES=Duplicados existentes

# ADMINISTRATION/ANREDEN
GENERIC_SALUTATIONS=Denominaciones
GENERIC_SALUTATIONS_MARKED=Denominaciones seleccionadas
GENERIC_ID=ID
GENERIC_MAIN_FORM=Descripci\u00F3n
GENERIC_GENDER=G\u00E9nero
GENERIC_GENDER_FEMALE=Mujer
GENERIC_GENDER_MALE=Hombre
GENERIC_PAGING=Filtro por letra
MESSAGE_SUCCESS_INSERT_SALUTATION=Denominaci\u00F3n creada satisfactoriamente
QUESTION_DELETE=\u00BFRealmente desea eliminar su selecci\u00F3n?
GENERIC_NEW_PLURAL=nuevas
GENERIC_YES=S\u00ED
GENERIC_NO=No
MESSAGE_SUCCESS_DELETE_SALUTATION=Denominaci\u00F3n eliminada satisfactoriamente
MESSAGE_EXIST_MASTER_DATA_ENTRY=Ya existe una denominaci\u00F3n con el nombre
GENERIC_NAME=Nombre
GENERIC_NEW=Nueva/o

# ADMINISTRATION/ARBEITSBEREICHE
GENERIC_WORK_FIELDS=\u00C1reas de trabajo
GENERIC_WORK_FIELDS_MARKED=\u00C1rea(s) de trabajo seleccionada(s)
MESSAGE_MISSING_DATA=No se han encontrado datos
MESSAGE_INSERT_WORK_FIELD=Nuevo \u00E1rea de trabajo creado satisfactoriamente
MESSAGE_FAIL_DELETE_WORK_FIELD=No se ha eliminado ning\u00FAn \u00E1rea de trabajo
MESSAGE_SUCCESS_DELETE_WORK_FIELD=Se ha eliminado un \u00E1rea de trabajo

# ADMINISTRATION/BENUTZER
GENERIC_USER=Usuario
GENERIC_USER_MARKED=Usuario(s) seleccionado(s)
GENERIC_USERNAME=Nombre de usuario
GENERIC_USER_RIGHTS=Permisos de usuario
MESSAGE_SUCCESS_INSERT_USER=Se ha creado un nuevo usuario
MESSAGE_SUCCESS_DELETE_USER=Se ha eliminado un usuario
MESSAGE_FILL_USER_ROLE=Debe introducir una descripci\u00F3n para el rol de usuario

# ADMINISTRATION/DOKUMENTTYPEN
GENERIC_TOOLTIP=Aviso
HINT_FORMAT_INFO=OOo 1.1 para OpenOffice 1.1 (Archivo-sxc) y OOo 2.0 para OpenOffice 2.0 (Archivo-ods), xls para Microsoft Office: los signos distintivos 50 y 99 ser\u00E1n autom\u00E1ticamente aderidos a un nuevo evento. En caso del signo 50 no habr\u00E1 posibilidad de texto libre.(Archivo-xls) y CSV para Archivo-CSV.
HINT_EVENT_MARK=Los signos distintivos 50 y 99 ser\u00E1n autom\u00E1ticamente aderidos a un nuevo evento. En caso del signo 50 no habr\u00E1 posibilidad de texto libre.
GENERIC_DOCUMENT_TYPES_MARKED=Tipo(s) de documento seleccionado(s)
GENERIC_LABELLING=Descripci\u00F3n
GENERIC_ADRESS_TYPE=Tipo de direcci\u00F3n
GENERIC_CHARSET=Conjunto de caracteres
GENERIC_FORMAT=Formato
GENERIC_PARTNER_DOCUMENT=Documento para partner
GENERIC_SORT=Selecc.
GENERIC_SIGN=Signo
GENERIC_GA=GA
GENERIC_SD=SD
GENERIC_BUSINESS=Negocio
GENERIC_PRIVATE=Privado
GENERIC_MORE=Adicionales
GENERIC_LATIN=Lat\u00EDn
kyrillisch=Cir\u00EDlico
chinesisch=Chino
eswurdeeindokumenttypgeloscht=Se ha eliminado un tipo de documento.
eswurdeeinneuerdokumenttypangelegt=Nuevo tipo de documento creado satisfactoriamente.

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Estado
GENERIC_TO=Para
GENERIC_SUBJECT=Asunto
GENERIC_ERROR=Error
e-mails=E-Mails
GENERIC_BLEND_IN_TECHNICAL_ERROR_MESSAGE=Combinar error t\u00E9cnico
GENERIC_ERROR_DESCRIPTION=Descripci\u00F3n del error

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=Plantillas de correo electr\u00F3nico
GENERIC_MARKED_TEMPLATES_PP=Plantilla(s) seleccionada(s)
GENERIC_INSERT_NEW_TEMPLATES=Crear nueva plantilla
GENERIC_TEMPLATE_NAME=Nombre de la plantilla
eswurdeeineneuevorlageangelegt=Nueva plantilla creada satisfactoriamente.
GENERIC_TEXT=Texto
GENERIC_PLACEHOLDER=Identificador
GENERIC_ADD=A\u00F1adir
GENERIC_BACK_TO_TEMPLATES_LIST=Volver al listado de plantillas

# ADMINISTRATION/FARBEN
GENERIC_COLOR_PLURAL=Colores
GENERIC_CHROMATICITY=Cromaticidad
LETTERS_CHROMATICITY=R G B

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=Denominaciones seleccionadas
GENERIC_LABELLING=Denominaci\u00F3n
eswurdeeineneuefunktion/amtsbezeichnungangelegt=Se ha creado una nueva funci\u00F3n/denominaci\u00F3n.
eswurdeeinefunktion/amtsbezeichnunggeloscht=Se ha eliminado una funci\u00F3n/denominaci\u00F3n.

# ADMINISTRATION/KATEGORIEN
GENERIC_CATEGORY_PLURAL=Categor\u00EDas
markiertekategorie=Categor\u00EDa(s) seleccionada(s)
GENERIC_MARK_LONG=Clase
GENERIC_RANK=Rango
GENERIC_EVENTS_PP=Evento(s)
GENERIC_CATEGORY_SINGULAR=Categor\u00EDa
GENERIC_OCCASION=Suceso

# ADMINISTRATION/MANDANTEN
GENERIC_CLIENT_PLURAL=Mandantes
markierte(n)mandanten=Mandante(s) seleccionado(s)
GENERIC_DATA_NOT_ASSIGNED_TO_CLIENTS=Datos de mandantes no asociados
personen=Personas
GENERIC_IMPORT_PROCEDURES=Importar procesos
veranstaltungorte=Localizaci\u00F3n del evento
GENERIC_IMPORT_PERSONS=Importar personas
GENERIC_DISTRIBUTOR_SINGULAR=Distribuidor
GENERIC_USER=Usuario
GENERIC_ASSIGN_CLIENTS=Asignar mandantes
GENERIC_CLIENT_SINGULAR=Mandante

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=Configuraci\u00F3n del sistema
GENERIC_STANDARD_TABULATOR_CHOICE=Elecci\u00F3n est\u00E1ndar mediante tabulaciones
GENERIC_MAIN_TABS=Pesta\u00F1as principales
GENERIC_PERSONS_DATA=Datos de personas
GENERIC_MAILING_ADDRESSES=Direcciones
GENERIC_SUBTABS_OF_PERSONS_DATA=Subpesta\u00F1as de \u201CDatos de personas\u201D
GENERIC_MAIN_PERSON=Persona principal
GENERIC_PARTNER=Partner
GENERIC_SUBTABS_OF_MAILING_ADDRESSES=Subpesta\u00F1as de \u201CDirecciones\u201D
GENERIC_BUSINESS=Negocio
GENERIC_STANDARD_CHOICE_OF_SELECTED_BOX=Elecci\u00F3n est\u00E1ndar sobre el selector de conjuntos de caracteres
GENERIC_CHARSET=Conjunto de caracteres
GENERIC_STANDARD_SALUTATIONS_AND_FREE_TEXT_FIELDS=Denominaciones est\u00E1ndar y campos de texto libre
GENERIC_STANDARD_SALUTATION=Denominaci\u00F3n est\u00E1ndar
GENERIC_STANDARD_SALUTATION_PARTNER=Demoninaci\u00F3n est\u00E1ndar del partner
GENERIC_FREE_TEXT_FIELD=Campo de texto libre
GENERIC_FREE_TEXT_FIELD_CONNECTOR=Conexi\u00F3n de campo de texto libre
GENERIC_SHOW=Visualizaci\u00F3n
GENERIC_HELP=Ayuda
GENERIC_HELP_LINK=Enlace de ayuda
GENERIC_HELP_WINDOW=Ventana de ayuda
OPTION_HELP_WINDOW_1=Utilizar ventana de ayuda actual
OPTION_HELP_WINDOW_2=Abrir una nueva ventana navegador por llamada
OPTION_HELP_WINDOW_3=La misma ventana de ayuda por llamada (no la actual)
GENERIC_MISCELLANEOUS=Otros
GENERIC_FAX_CONFIG_FIELD=Fax-DN (@fax.aa)
GENERIC_PROTOCOL_TIME_CHANGE=Historial de cambios
GENERIC_PROTOCOL_COMMISIONING_TIME=Intervalo del registro de datos
HINT_GIVE_THE_RETENTION_PERIOD=Indique el per\u00EDodo de retenci\u00F3n
GENERIC_YEARS=A\u00F1os
GENERIC_MONTHS=Meses
GENERIC_DAYS=D\u00EDas
GENERIC_MAILING_ADDRESS_BUSINESS=Direcci\u00F3n de trabajo
GENERIC_MAILING_ADDRESS_PRIVATE=Direcci\u00F3n privada
GENERIC_MAILING_ADDRESS_OTHERS=Otras direcciones
GENERIC_LABELLING_LATIN=Conjunto de caracteres latinos
GENERIC_LABELLING_ALTERNATIVE=Conjunto de caracteres alternativo
GENERIC_ADDRESS_ADDITIONAL=Direcci\u00F3n adicional

# ADMINISTRATION/REPORTS
GENERIC_REPORTS=Res\u00FAmenes
MESSAGE_WAITING_MESSAGE_LOG_REPORT=Dependiendo del per\u00EDodo de tiempo seleccionado y la cantidad de datos, la generaci\u00F3n del informe puede tardar m\u00E1s tiempo de lo normal. Por favor, mantenga la paciencia hasta el final del proceso.
GENERIC_DATE_BEGIN=Fecha de inicio
GENERIC_DATE_END=Fecha de fin
GENERIC_BACKUP_FIEDS=Reiniciar campos
GENERIC_GENERATE_REPORT=Generar resumen

# ADMINISTRATION/STELLVERTRETUNGEN
GENERIC_REPRESENTATIVES=Delegados
GENERIC_AVAILABILITY_FILTER=Filtro de disponibilidad
GENERIC_REPRESENTATIVES_ALL=Todos los delegados
GENERIC_NO_REPRESENTATION_EXPIRED=Ninguna representaci\u00F3n pasada
GENERIC_ONLY_CURRENT_REPRESENTATIONS=S\u00F3lo representaciones actuales
GENERIC_ROLE=Rol
GENERIC_REPRESENTATIVE=Representante
gultigab=Disponible a partir de
GENERIC_VALID_TILL=Disponible hasta
GENERIC_NO_DATA_FOUND=No se han encontrado datos

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Localizaciones de eventos seleccionadas
GENERIC_ADD_NEW_EVENT_LOCATIONS=Crear nueva localizaci\u00F3n para evento
GENERIC_ID=ID
GENERIC_CONTACT_PERSON=Persona de contacto
GENERIC_TELEFON=Tel\u00E9fono
GENERIC_FAX=Fax
e-mail=E-Mail
GENERIC_REMARK=Observaciones
GENERIC_URL=Enlace
gps-daten=Datos de localizaci\u00F3n (GPS)
GENERIC_ROOM_NUMBER=N\u00FAmero de sala
EVENT_PLACES_CONFIRM_DELETE=Por favor, confirme la eliminaci\u00F3n de las localizaciones del evento

# VERWALTUNG/EINSTELLUNGEN
GENERIC_MANAGEMENT=Gesti\u00F3n
GENERIC_OPTIONS=Ajustes
GENERIC_SUBTABS_OF=Subpesta\u00F1as de
GENERIC_PERSONAL_DETAILED_VIEW=Vista detalle de personas
GENERIC_LIST_OF_GUESTS=Lista de invitados
zusatzlichefelder=Campos adicionales
GENERIC_FUNCTION_SINGULAR=Funci\u00F3n
GENERIC_POSTNUMBER_AND_CITY=C\u00F3digo postal / Ciudad
GENERIC_LIST_OF_PERSONS=Lista de personas
GENERIC_FEDERAL_STATE=Provincia
MESSAGE_OPTIONS_WERE_SUCCESSFULLY_SAVED=La configuraci\u00F3n se ha guardado satisfactoriamente.

# VERWALTUNG/VERTRETUNGEN
GENERIC_REPRESENTATIVE_PLURAL=Representaciones
markiertevertretung=Representaciones seleccionadas
GENERIC_REMOVE=Elimniar
GENERIC_NEW=Nuevo
eswurdeeineneuevertretungangelegt=Se ha creado una nueva representaci\u00F3n
eswurdeeinevertretunggeloscht=Se ha eliminado una representaci\u00F3n
siemuseneinevertretereingeben=Debe seleccionar un representante
derbeginndervertretungmusvordemendeliegen=La fecha de inicio debe ser anterior a la fecha final
MESSAGE_REPORT_NUMBER_PART_1=Se han eliminado
vertretungengeloscht=representaciones
# VERWALTUNG/INFO
GENERIC_INFO=Informaci\u00F3n
GENERIC_INFORMATION_ABOUT_VERAWEB=Acerca de VerA.web
veraweb=VerA.web
GENERIC_VERSION=Versi\u00F3n
build=Compilaci\u00F3n
GENERIC_BUILD_NUMBER=N\u00FAmero de compilaci\u00F3n
GENERIC_BUILD_TIME=Tiempo de compilaci\u00F3n (UTC)
GENERIC_REST_API=API de REST
GENERIC_DATABASE=Base de datos
GENERIC_LOGIN=Login
GENERIC_GROUPS=Grupos
GENERIC_NOT_AVAILABLE=No disponible

# ALLGEMEIN
GENERIC_YOU_ARE_HERE=Usted se encuentra aqu\u00ED
GENERIC_HOME=Inicio
GENERIC_DISCARD_CHANGES=Descartar cambios

# TABELLEN
GENERIC_DATE=Fecha
GENERIC_WORKAREA_SINGULAR=\u00C1rea de trabajo
GENERIC_LASTNAME=Apellido
GENERIC_FIRSTNAME=Nombre
amtsbezeichnung=T\u00EDtulo
GENERIC_COMPANY_INSTITUTION=Empresa / Instituci\u00F3n
GENERIC_STREET=Calle
GENERIC_POST_NUMBER=C\u00F3digo postal
GENERIC_CITY=Ciudad
GENERIC_MARKED_PERSONS_PP=Persona(s) seleccionada(s)
expotieren=Exportar
GENERIC_ASSIGN_CATEGORIES=Asignar categor\u00EDas
GENERIC_REMOVE_CATEGORIES=Eliminar categor\u00EDas
GENERIC_ASSING_WORKAREA=Asignar \u00E1reas de trabajo
GENERIC_REMOVE_WORKAREA=Eliminar \u00E1reas de trabajo
GENERIC_EXECUTE=Aplicar
personenanzahlproseite=Personas | Personen | Total por p\u00E1gina
GENERIC_ALL=Todas
seite=P\u00E1gina
GENERIC_DATE_OF_BIRTH=Fecha de nacimiento
GENERIC_PLACE_OF_BIRTH=Lugar de nacimiento
GENERIC_NATIONALITY_CITIZENSHIP=Nacionalidad/Ciudadan\u00EDa
GENERIC_LANGUAGES=Idiomas
GENERIC_HINT_FOR_HOST=Aviso para el anfitri\u00F3n
GENERIC_ACCOUNT_OPENING_DATE=Fecha de acreditaci\u00F3n
GENERIC_AT=a las
GENERIC_OCLOCK=horas
GENERIC_ORIGIN_DATA=Origen de los datos
GENERIC_PERSON_SINGULAR=persona

# DATEITYP
csv=CSV (Comma-Separated-Values)
xml=XML (VerA.web-XML)
zkm=ZKM (VerA.web-XML sobre el m\u00F3dulo central de comunicaci\u00F3n)
madlan-personen=MAdLAN-Personas (MAdLAN-Importar-Personas)
madlan-firmen=MAdLAN-Empresas (MAdLAN-Importar-Empresas)
x-manage-csv=X-Manage-CSV (X-Manage Contactos)
csvpersdatanschriftdoktyp=CSVPersdat+Anschrift+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp=CSVPersdat+Doktyp (Comma-Separated-Values)
csvpersdatdoktyp10=CSVPersdat+Doktyp 1.0 (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Categor\u00EDas (Comma-Separated-Values)
csviso885915=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)

# PERSONEN/PERSONENUEBERSICHT
GENERIC_PERSON_SUMMARY=Lista de personas
GENERIC_SEARCH_PERSONS=Buscar personas
GENERIC_CREATE_PERSON=Crear nueva persona
GENERIC_PERSONS_DELETED=personas

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
GENERIC_EDIT_PERSON=Editar persona
GENERIC_DOCUMENTED_ON=Documentado el
GENERIC_LAST_EDITED_ON=\u00DAltima edici\u00F3n el
GENERIC_PERSONS_ID=Identificador de personas
GENERIC_OA=Aplicaci\u00F3n en l\u00EDnea
GENERIC_OA_USERNAME=Nombre de usuario para aplicaci\u00F3n en l\u00EDnea
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=Para esta persona, la vista previa correspondiente no ha sido generada.
GENERIC_COPY_PERSON=Copiar persona
GENERIC_CREATE_TAG=Crear etiqueta
GENERIC_ASSIGN_TO_EVENT=Asignar un evento
GENERIC_DELETE_PERSON=Eliminar persona
GENERIC_STATISTIC=Estad\u00EDsticas
ausstammdatenhinzufugen=Obtener de los datos maestros

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
GENERIC_GENERATE_ALL=Generar todos

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
GENERIC_CATEGORIES_AND_OCCASIONS=Categor\u00EDas y sucesos

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=Lista de todos los eventos por invitado
GENERIC_VIEW_OVER_GUEST_EVENT=Desde
statistikfurgast=Estad\u00EDsticas para invitado
GENERIC_EVENT=Evento
GENERIC_BEGIN=Comienzo

# PERSONEN/PERSONENSUCHE
GENERIC_SEARCH_PERSON=B\u00FAsqueda de personas
GENERIC_SEARCH=B\u00FAsqueda
GENERIC_VALIDITY_DATE=Fecha de disponibilidad
GENERIC_ADVANCED_SEARCH=B\u00FAsqueda avanzada
HINT_PLACEHOLDER=Aviso: Puede utilizar comodines para su b\u00FAsqueda. El asterisco (*) se utilizar\u00E1 para representar n\u00FAmeros, as\u00ED como el s\u00EDmbolo de interrogaci\u00F3n(?) para caracteres individuales. La b\u00FAsqueda se realizar\u00E1 mediante nombre, apellido, ciudad, c\u00F3digo postal, calle, Empresa/Instituci\u00F3n, tel\u00E9fono, fax, tel\u00E9fono m\u00F3vil, correo electr\u00F3nico, observaciones, categor\u00EDas, \u00E1rea de trabajo y funci\u00F3n/t\u00EDtulo.

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=Datos de acceso guardados satisfactoriamente.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Ya existen datos de acceso para esta persona.

# PERSONEN/NEUE PERSON ANLEGEN
GENERIC_IS_COMPANY=Empresa
GENERIC_SALUTATION_SINGULAR=Denominaci\u00F3n
frau=Sra.
herr=D.
lady=Srta.
sir=Sr.
GENERIC_PLEASE_CHOOSE=Por favor, seleccione
GENERIC_ACAD_TITLE=T\u00EDtulo acad\u00E9mico
GENERIC_IN_COUNTRY=En el pa\u00EDs
GENERIC_HINT_FOR_ORGA=Aviso para la organizaci\u00F3n
GENERIC_COMPANY_SINGULAR=Empresa
GENERIC_COUNTRY=Pa\u00EDs
plz/postfach=C\u00F3digo postal/apartado de correos
GENERIC_POST_OFFICE_BOX=Apartado de correos
iban=IBAN
bic=BIC
GENERIC_MOBILE=M\u00F3vil
LETTERS_WWW=WWW
dublettenprufungdurchfuhren=Examinar duplicados
zurpersonenubersicht=Listado de personas

# PERSONEN/SUCHEN UND ERSETZEN IN PERSONENDATEN
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=Aviso: al utilizar el comod\u00EDn \u2018*\u2019, ser\u00E1n reemplazadas todas las que contengan las secciones del texto de b\u00FAsqueda (orden inclu\u00EDdo), si no se reemplazar\u00E1n aquellas que coincidan ex\u00E1ctamente con el texto de b\u00FAsqueda.
GENERIC_SEARCH_V=Buscar
GENERIC_REPLACE=Reemplazar
GENERIC_IN_THE_FOLLOWING_FIELDS=En los pr\u00F3ximos campos
anrede/titel=Denominaci\u00F3n / T\u00EDtulo
GENERIC_EMPLOYMENT_TITLE_SHORT=Cargo
GENERIC_INSTITUTION_SINGULAR=Instituci\u00F3n
GENERIC_ADDRESSES=Direcci\u00F3n
telefon/fax=Tel\u00E9fono / fax
GENERIC_REPLACE_INDIVIDUALLY=Reemplazar individualmente
GENERIC_REPLACE_ALL=Reemplazar todas

# PERSONEN/DUBLETTENSUCHE
GENERIC_DUPLICATE_SEARCH=B\u00FAsqueda de duplicados

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Exportar desde los datos de personas
HINT_EXPORT_MANDANT_PERSON=Mediante esta funci\u00F3n, usted exporta s\u00F3lo las personas correspondientes a los mandantes actuales.
GENERIC_WITHOUT=Sin
botschaften=Embajadas
finanzamtsprecher=Portavoz financiero
journalisten=Periodistas
lieferant=Proveedor
nogs=ONGs
politik=Pol\u00EDtico
pressevertreter=Representante de prensa
wirtschaft=Econom\u00EDa
GENERIC_EXPORT=Exportaci\u00F3n
EXPORT_AS_CSV=Lista de invitados completa
EXPORT_AS_CSV_SHORT=Lista de invitados corta
GENERIC_START_EXPORT=Iniciar exportaci\u00F3n
ENCODING_TYPE_CYRILLIC=Cir\u00EDlico
ENCODING_TYPE_WEST=Del oeste
ENCODING_TYPE_BALTIC=B\u00E1ltico
ENCODING_TYPE_EAST=Del este
ENCODING_TYPE_TURKISH=Turco
EXPORT_DATA_TYPE_CSV=CSV (Comma-Separated-Values)
EXPORT_DATA_TYPE_XML=XML (VerA.web-XML)
EXPORT_DATA_TYPE_ZKM=ZKM (VerA.web-XML mediante el m\u00F3dulo de comunicaci\u00F3n central)
EXPORT_DATA_TYPE_MADLAN_PERSON=MAdLAN-Personas (MAdLAN-Importar-Personas)
EXPORT_DATA_TYPE_MADLAN_COMPANY=MAdLAN-Empresas (MAdLAN-Importar-Empresas)
EXPORT_DATA_TYPE_X_MANAGE_CSV=X-Manage-CSV (X-Manage Kontakte)
EXPORT_DATA_TYPE_CSVPERSDATA_ADDRESS_DOCTYPE=CSVPersdat+Direcci\u00F3n+TipoDocumento (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_DOCTYPE=CSVPersdat+TipoDocumento (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_DOCTYPE_1_0=CSVPersdat+TipoDocumento 1.0 (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_CATEGORY=CSVPersdat+Categor\u00EDas (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSV_ISO_8859_15=CSV-ISO-8859-15 (Im-/Export ISO-8859-15)
EXPORT_TITLE_CSV=CSV
EXPORT_TITLE_XML=XML
EXPORT_TITLE_ZKM=ZKM
EXPORT_TITLE_MADLAN_PERSON=MAdLAN-Personas
EXPORT_TITLE_MADLAN_COMPANY=MAdLAN-Empresas
EXPORT_TITLE_X_MANAGE_CSV=X-Manage-CSV
EXPORT_TITLE_CSVPERSDATA_ADDRESS_DOCTYPE=CSV DatosPersonas+Direcciones+TiposDocumentos
EXPORT_TITLE_CSVPERSDATA_DOCTYPE=CSV DatosPersonas+TiposDocumentos
EXPORT_TITLE_CSVPERSDATA_DOCTYPE_1_0=CSV DatosPersonas+TiposDocumentos 1.0
EXPORT_TITLE_CSVPERSDATA_CATEGORY=CSV DatosPersonas+Categor\u00EDas
EXPORT_TITLE_CSV_ISO_8859_15=CSV ISO-8859-15
LABEL_EXPORT_ZKM=Ziel (ZKM-Abreviatura)
LABEL_EXPORT_MADLAN_ENCODING=Codificaci\u00F3n
LABEL_EXPORT_MADLAN_ENCODING_CYRILLIC=Codificaci\u00F3n (Cir\u00EDlica)
HINT_EXPORT_CSV=Dependiendo de la cantidad de datos exportados (mediante el n\u00FAmero de categor\u00EDas y tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_ZKM=El archivo de exportaci\u00F3n ser\u00E1 almacenado en la carpeta de salida ZKM como se podr\u00E1 gestionar un control sobre la descarga. La descarga se podr\u00E1 abortar de forma segura.
HINT_EXPORT_CSVPERSDATA_ADDRESS_DOCTYPE=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as \u201CDatos de personas\u201D, \u201CDirecciones\u201D, \u201CTipos de documento\u201D y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_DOCTYPE=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as \u201CDatos de personas\u201D, \u201CTipos de documento\u201D y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_DOCTYPE_1_0=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as \u201CDatos de personas\u201D, \u201CTipos de documento\u201D y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSVPERSDATA_CATEGORY=Se exportar\u00E1n \u00FAnicamente los campos ubicados en las pesta\u00F1as \u201CDatos de personas\u201D, \u201CTipos de documento\u201D y sus respectivas pesta\u00F1as inferiores. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de categor\u00EDas), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.
HINT_EXPORT_CSV_ISO_8859_15=Este formato es adecuado para la importaci\u00F3n/exportaci\u00F3n sobre aplicaciones como MS Office, las cuales utilizan el juego de caracteres ISO-8859-15. Dependiendo de la cantidad de datos exportados (en particular, sobre el n\u00FAmero de categor\u00EDas y tipos de documento), MS Excel y OO Calc pueden no llegar a leer los datos exportados por completo.

# PERSONEN/IMPORT VON PERSONENDATEN
GENERIC_IMPORT_FROM_PERSONS_DATA=Importaci\u00F3n de datos de personas
HINT_IMPORT_SHORT_CONTENT=Aviso: Al importar los datos, es posible que los datos de mayor longitud sean acortados para su visualizaci\u00F3n en VerA.web.
GENERIC_TARGET_CLIENT=Mandante objetivo
GENERIC_IMPORT_DATA=Importar-Archivo
GENERIC_DATA_TYPE=Tipo de archivo
dateiauswahlen=Seleccionar archivo
keineausgewahlt=Ning\u00FAn seleccionado
GENERIC_START_IMPORT=Comenzar importaci\u00F3n

# PERSONENDROPDOWN
GENERIC_NEW_PERSON=Nueva persona
GENERIC_EXPORT_PERSONS=Exportaci\u00F3n de personas
GENERIC_IMPORT_PERSONS=Importaci\u00F3n de personas

# VERANSTALTUNGENDROPDOWN
GENERIC_EVENT_VIEW=Lista de eventos
veranstaltunguuche=B\u00FAsqueda de eventos
GENERIC_NEW_EVENT=Nuevo evento
GENERIC_STATISTICS=Estad\u00EDsticas

# ADMINISTRATIONDROPDOWN
GENERIC_SALUTATIONS=Denominaciones
GENERIC_WORKAREA_PLURAL=\u00C1reas de trabajo
e-mail-postausgang=E-Mail-Buz\u00F3n de salida
GENERIC_PROGRAM_PERFERENCES=Preferencias de programa
GENERIC_EVENT_LOCATION_PLURAL=Localizaciones de eventos

# VERANSTALTUNGSUEBERSICHT
GENERIC_END=Fin
GENERIC_HOST=Anfitri\u00F3n
GENERIC_EVENT_LOCATION_SINGULAR=Localizaci\u00F3n del evento
GENERIC_EVENT_SEARCH=Buscar eventos
GENERIC_CREATE_NEW_EVENT=Crear nuevo evento
GENERIC_NUMBER_PER_PAGE=Total por p\u00E1gina
seitexvony=P\u00E1gina x de y

# EVENT HEADER
EVENT_ID=ID-Evento
EVENT_NAME=Nombre del evento
EVENT_URL=Enlace al evento
EVENT_URL_MEDIA_REPRESENTATIVE=Enlace para representates de prensa
EVENT_MAX_GUEST=N\u00FAmero m\u00E1ximo de invitados
EVENT_MAX_RESERVE=N\u00FAmero m\u00E1ximo en lista de espera
EVENT_INVITATION_TYPE=Tipo de invitaci\u00F3n
EVENT_INVITATION_TYPE_WITHOUT_PARTNER=Sin partner
EVENT_INVITATION_TYPE_ONLY_PARTNER=S\u00F3lo partner
EVENT_INVITATION_TYPE_WITH_PARTNER=Con partner

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
GENERIC_EDIT_EVENT=Editar evento
GENERIC_TO_GUEST_MANAGEMENT=Gesti\u00F3n de invitados
GENERIC_GENERAL=General
GENERIC_TASK_PLURAL=Tareas
GENERIC_ADDITIONAL_PERSONS_DATA=Datos adicionales
kurzbereichnung=Abreviatura
GENERIC_OPEN_EVENT=Evento abierto
umxuhr=A las x horas
veranstalgungsort=Localizaci\u00F3n del evento
GENERIC_SEARCH_FOR_HOST=Buscar anfitri\u00F3n
GENERIC_DELETE_HOST=Eliminar anfitri\u00F3n
GENERIC_HOST_PARTNER=Anfitri\u00F3n-Partner
GENERIC_LOGIN_REQUIRED=Login necesario
GENERIC_SUBSCRIPTION_OF_PRESS_REPRESENTATIVES_POSSIBLE=Acceso habilitado a representantes de prensa
GENERIC_SAVE_EVENT=Guardar evento
GENERIC_TO_EVENT_VIEW=Lista de eventos

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPES_MARKED_DELETE=Eliminar tipo(s) de documento seleccionado(s)
GENERIC_REMOVE=Eliminar
GENERIC_ADD_NEW_DOCUMENT_TYPE=A\u00F1adir nuevo tipo de documento
xvonydokumenttypen=x de y tipos de documento

# VERANSTALTUNG BEARBEITEN/AUFGABEN
GENERIC_ADD_NEW_TASK=Crear nueva tarea
MESSAGE_NO_TASKS_FOR_THIS_EVENT=No existe ninguna tarea asignada a este evento
GENERIC_SELECTED_ENTRIES=Entradas seleccionadas
GENERIC_TITLE=T\u00EDtulo
GENERIC_RESPONSIBLE=Responsable

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
GENERIC_TASKS_ID=ID-Tarea
GENERIC_COMPLETION=Finalizaci\u00F3n
GENERIC_PRIORITY=Prioridad
GENERIC_DESCRIPTION=Descripci\u00F3n
GENERIC_ADD_RESPONSIBLES=A\u00F1adir responsables
verantwortlichenentfernen=Eliminar responsables
GENERIC_SAVE_TASK=Guardar tarea
GENERIC_BACK_TO_TASKS_VIEW=Lista de tareas

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
GENERIC_ADD_NEW_EMPLOYMENT_TITLE=A\u00F1adir nuevo t\u00EDtulo
MESSAGE_NO_EMPLOYMENT_TITLES_FOUND=No se han encontrado t\u00EDtulos

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
GENERIC_ADD_NEW_KATEGORIES=A\u00F1adir nueva categor\u00EDa

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
GENERIC_PRECONDITION_PLURAL=Precondiciones
EVENT_PRECONDITION_MARKED=Precondiciones seleccionadas
EVENT_PRECONDITION_ADD=A\u00F1adir precondiciones
EVENT_PRECONDITION_INVITATIONSTATUS=Estado de invitaci\u00F3n
EVENT_PRECONDITION_STARTDATE=Fecha de inicio
EVENT_PRECONDITION_NOT_FOUND=No se han encontrado precondiciones

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Buscar s\u00F3lo en eventos futuros
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=Puede utilizar comodines en su b\u00FAsqueda: asterisco (*) para b\u00FAsqueda plurar y el s\u00EDmbolo de interrogaci\u00F3n para b\u00FAsqueda individual.

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=Con partner
eswurdeeineneueveranstaltungangelegt=Se ha creado un nuevo evento.

# VERTEILER
angelegtvon=Creado por
angelegtam=Creado el
erzeugtausveranstaltung=Generado por evento

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=Restringir estad\u00EDsticas para el pr\u00F3ximo intervalo temporal
statistiktypauswahlen=Seleccionar tipo de estad\u00EDsticas
zeitrahmenbeginn=Inicio-Intervalo
zeitrahmenende=Final-Intervalo
STATISTIC_RADIO_PER_YEAR=Total de eventos por a\u00F1o
STATISTIC_RADIO_PER_MONTH=Total de eventos por mes
STATISTIC_RADIO_GROUPED_BY_HOST=Total de eventos, agrupados por anfitri\u00F3n
STATISTIC_RADIO_PER_HOST=Listado de eventos de un anfitri\u00F3n (con b\u00FAsqueda)
STATISTIC_RADIO_PER_GUEST=Listado de eventos de un invitado (con b\u00FAsqueda)
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=Listado de eventos ordenados por localizaci\u00F3n
statistikerstellen=Generar estad\u00EDsticas

# GAESTEVERWALTUNG DER VERANSTALTUNG
gasteverwaltungderveranstaltung=Gesti\u00F3n de invitados del evento
maxanzahlgaste=Total de invitados
gastedetails=Detalles de invitados
offen=Abierto
zusagen=Aceptado
absagen=Rechazado
teilnahmen=Participaciones
aufplatz=Con plaza
aufreserve=En reserva
filter=Filtro
platzwahl=Selecci\u00F3n de plaza
lfdnr=N\u00B0 Serie
nichteingeladen=No invitado
laufendenummerberechnen=Calcular n\u00FAmero de serie
allestammdatenneuladen=Cargar datos maestros de nuevo
HINT_ENTRY_POINT=Direkteinsprung: s\u00F3lo es posible mediante ordenaci\u00F3n por nombre, apellido o correo electr\u00F3nico..
HINT_GUEST_MANAGEMENT_FILTER=Para la generaci\u00F3n del listado de invitados se considerara el criterio establecido en el filtro superior.
HINT_GUEST_MANAGEMENT_MARKED=Si selecciona un s\u00F3lo invitado, ser\u00E1 el \u00FAnico en ser exportado. De lo contrario, se exportar\u00E1 el listado completo.
TABLE_BEFORE_GUEST=Invitado anterior
TABLE_FIRST_GUEST=Primer invitado
TABLE_LAST_GUEST=\u00DAltimo invitado
TABLE_NEXT_GUEST=Invitado siguiente

# GAESTELISTE
GUEST_LIST_ALL_GUEST=Todos los invitados
GUEST_LIST_ALL_GUEST_ON_PLACE=Todos los invitados con plaza
GUEST_LIST_ALL_GUEST_ON_RESERVE=Todos los invitados en reserva
GUEST_LIST_APPLY_GUEST_FROM_EVENT=Aplicar invitados desde evento
GUEST_LIST_CATEGORY_ASSIGN=Asignar categor\u00EDas
GUEST_LIST_CATEGORY_REMOVE=Eliminar categor\u00EDas
GUEST_LIST_DISTRIBUTOR_CREATE=Crear distribuidor
GUEST_LIST_CONFIRM_ACTION=Por favor, confirme la siguiente acci\u00F3n
GUEST_LIST_DIDNT_CHANGE=No se ha modificado la lista de invitados
GUEST_LIST_EXPAND_ONE=Se ha a\u00F1adido un invitado a la lista
GUEST_LIST_EXPAND_MULTIPLE_PART_ONE=Se han a\u00F1adido
GUEST_LIST_EXPAND_MULTIPLE_PART_TWO=invitados a la lista
GUEST_LIST_HINT_EXPORT_GUEST=Si selecciona un s\u00F3lo invitado, ser\u00E1 el \u00FAnico en ser exportado. De lo contrario, se exportar\u00E1 el listado completo
GUEST_LIST_HINT_FILTER=Para la generaci\u00F3n del listado de invitados se considerara el criterio establecido en el filtro superior.
GUEST_LIST_HINT_RED_PERSON=Las personas con fondo de color rojo ser\u00E1n marcadas como personas \u201Ca borrar\u201D
GUEST_LIST_CREATED_NO_PERSON=creado sin personas
GUEST_LIST_CREATED_ONE_PERSON=creado con una persona
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_ONE=creado con
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_TWO=personas
GUEST_LIST_NO_GUEST_INVITED=No existen invitados hasta el momento o el filtro utilizado no ha obtenido resultados
GUEST_LIST_NUMBER_CALCULATE=Calcular n\u00FAmero de serie
GUEST_LIST_NUMBER_CALCULATED_SAVED=El \u201Cn\u00FAmero de serie\u201D ser\u00E1 recalculado y guardado para todos los invitados
GUEST_LIST_ONLY_OPEN=s\u00F3lo pendientes
GUEST_LIST_ONLY_ACCEPT=s\u00F3lo aceptados
GUEST_LIST_ONLY_DECLINED=s\u00F3lo rechazados
GUEST_LIST_ONLY_PARTICIPATE=s\u00F3lo participantes
GUEST_LIST_PERSON_DATA_RELOAD=Recargar todos los datos maestros
GUEST_LIST_RESERVE=R
GUEST_LIST_SEARCH_PERSON_ADD=Buscar personas y a\u00F1adirlas a la lista de invitados

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=Generar lista de invitados
SELECT_OUTPUT_FORMAT=Seleccionar formato de salida
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=Lista agrupada por categor\u00EDa - con Partner
LIST_GROUP_BY_CATEGORY_WITH_TEL=Lista agrupada por categor\u00EDa - con n\u00FAmero de tel\u00E9fono y m\u00F3vil
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=Lista agrupada por categor\u00EDa - con partner y fax
LIST_SORT_PARTNER_TEL=Lista agrupada -con partner, n\u00FAmero de tel\u00E9fono y m\u00F3vil
SORT_CRITERIA=Criterios de filtraci\u00F3n
SORT_AFTER=Filtrar por
CONTINUAL_NUMBER=N\u00FAmero de serie
anschliesendnach=Despu\u00E9s de
zusatzlichesortierungnach=Filtro adicional por

# GASTDETAILS
GUEST_DETAIL_HINT_GUEST_HOST=Aviso para el anfitri\u00F3n
GUEST_DETAIL_HINT_ORGANISATION_TEAM=Aviso para la organizaci\u00F3n
GUEST_DETAIL_INVITATION_STATUS=Estado de la invitaci\u00F3n
GUEST_DETAIL_SEAT_NUMBER=Plaza
GUEST_DETAIL_TABLE_NUMBER=Mesa
gastdetails=Detalles del invitado
HINT_GUEST_LIST_EDIT_PERSONDATA=\u00DAnicamente modificar\u00E1 los datos de la persona correspondientes al evento actual, no produci\u00E9ndose cambios sobre los datos maestros.
istgastgeber=Anfitri\u00F3n
reserve=Reserva
aufstammdatenzurucksetzen=Restablecer desde los datos maestros
stammdatenbearbeiten=Editar datos maestros

# DOKUMENTTYPEN
dokumenttypwahlen=Seleccionar tipos de documento
mitgliedsausweis=Tarjeta de membres\u00EDa
etikett=Etiqueta
tischkarte=Tarjeta de mesa
adresstypundzeichensatzwahlen=Seleccionar tipo de direcci\u00F3n y conjunto de caracteres
adresstyp=Tipo de direcci\u00F3n
datenbearbeiten=Editar datos
verbinder=Interconexiones
freitextfeldpartner=Campo de texto libre (partner)
akatitel=T\u00EDtulo acad\u00E9mico (partner)
kontaktdaten=Datos de contacto
strase=Calle
postfachplz=C\u00F3digo postal
nummer=N\u00FAmero
zuruckzudenveranstaltungsdetails=Volver a detalles del evento

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Editar tipo de documento
dokument-id=ID-Documento
dokument-name=Nombre-Documento
dokumenttypspeichern=Guardar tipo de documento
zuruckzurdokumenttypenliste=Volver a tipos de documento
anmeldedatenerzeugen=Generar datos de acceso
esliegenkeinekategorienundereignissevor=No se presentan categor\u00EDas y sucesos
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=En verde se resaltan las entradas de sucesos repetidos.

# VERTEILERDETAILS
verteilerdetails=Detalles de la distribuci\u00F3n
verteilerversenden=Enviar distribuci\u00F3n
e-mail-clientaufrufen=Redactar E-Mail a cliente
mailclient_other=Otro Mailcliente
mailclient_msoutlook=Microsoft Outlook
verteilerverschickt=El distribuidor ha sido enviado con \u00E9xito.
verteilerfehler=El distribuidor no se pudo enviar con \u00E9xito, int\u00E9ntelo de nuevo m\u00E1s tarde.

# FEHLEND
zurstartseite=Inicio
solldieneuekategorie=\u00BFDesea crear la nueva categor\u00EDa
einsortiertwerden=?
pflichtfelder=Campos obligatorios
markiertekategorien=Categor\u00EDas seleccionadas
markiertekategorienloschen=Eliminar las categor\u00EDas seleccionadas
alledemarkieren=Eliminar selecci\u00F3n
furalleveranstaltungen=Para todos los eventos
speichern=Guardar
anderungsprotokollfurdenzeitraum=Historial de cambios para el per\u00EDodo de tiempo
objekt=Objeto
objektid=ID-Objeto
artderanderung=Tipo de cambio
geandertefelder=Campos modificados
datumauswahlen=Seleccionar fechaDatum ausw\u00E4hlen
folgendeaktionen=Acciones siguientes
wurden=ser
durchgefuhrt=realizadas
konnen=podr\u00E1n
aktuallisieren=Actualizar
cleanupjetztunwiderruflichdurchfuhren=Realizar cleanup definitivo
essindderzeitkeinecleanupsmoglichnotig=No es posible/necesario realizar un cleanup.
nochkeineauswahlgetroffen=A\u00FAn no se dispone de selecci\u00F3n
oberflachenbeschriftungen=Etiquetas visualizables
zusatzfelder=Campos adicionales
eswurdeeinzusatzfeld=Se ha creado
angelegt=un campo adicional
geandert=modificado
geloscht=eliminado
feldbezeichnung=Descripci\u00F3n del campo
eingabetyp=Tipo de entrada
erfolgreichgespeichert=\u00A1Guardado satisfactoriamente!
markiertendokumenttypen=Tipo(s) de documento seleccionado(s)
eigenesdokumentfurpartner=Documento para partners
sortierreihenfolge=Orden de clasificaci\u00F3n
gastgebermitausgeben=Anfitri\u00F3n con distribuci\u00F3n
iststandardfursteuerdatei=Est\u00E1ndar para el archivo de control
format=Formato
HINT_EXPORT_FORMAT=OOo 1.1 para OpenOffice 1.1 (Archivo-sxc) y OOo 2.0 para OpenOffice 2.0 (Archivo-ods),xls para Microsoft Office (Archivo-xls) y CSV para formato-CSV.
HINT_EVENT_IDENTIFICATION=Las marcas 50 y 99 ser\u00E1n a\u00F1adidas autom\u00E1ticamente al evento. Para la marca 50 no se dispondr\u00E1 de ning\u00FAn campo de texto libre.
wirklichloschen=Eliminar realmente
zumpersonenimport=Volver a Importar-Personas
importstatus=Estado de la importaci\u00F3n
importstatusvorhandenedublettenbearbeiten=Estado de la importaci\u00F3n: editar duplicados existentes
bittemarkierensiediezuimportierendenpersonen=Por favor, realice su selecci\u00F3n para importar personas.
dublettendiedurchden=Duplicados, los cuales ser\u00E1n a\u00F1adidos
importhinzugefugtwerdenwurden=a trav\u00E9s de la importaci\u00F3n
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=, se encuentra remarados mediante un checkbox. Seguidamente se muestran los datos ya almacenados dentro del sistema.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=Deber\u00E1 escoger los duplicados para integrarlos en la importaci\u00F3n.
alsdubletteubernehmen=Aceptar como duplicados
markiertepersonenalsdubletteubernehmen=Persona(s) seleccionada(s) como duplicado(s)
anzahlzuspeicherndedubletten=Recuento de duplicados a almacenar
eswurdenkeineeintragegefunden=No se han encontrado entradas
zuruckzumpersonenimport=Volver a importaci\u00F3n
fehlermeldung=Mensaje de error
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=Durante la ejecuci\u00F3n del proceso ha ocurrido un error. Por favor, contacte con su administrador.
unbekannterfehler=Error desconocido.
markiertenkategorien=Categor\u00EDas seleccionadas
markiertenkategorienentfernen=Eliminar categor\u00EDas seleccionadas
bitteauswahlen=Por favor, realice su selecci\u00F3n
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=El evento actual ha sido eliminado por otro usuario. Puede crear un nuevo evento si as\u00ED lo desea, o simplemente continuar trabajando sobre VerA.web.
bittebestatigensiedasspeicherndieserveranstaltung=Por favor, confirme la actualizaci\u00F3n del evento actual
keingastgeberausgewahlt=Anfitri\u00F3n no seleccionado
kurzbezeichnung=Descripci\u00F3n corta
maximalelangederwarteliste=Longitud m\u00E1xima de la lista de espera
sollendiestammdatenumdiesenorterweitertwerden=Los datos maestros deben ser modificados en relaci\u00F3n a la localizaci\u00F3n actual
markiertendokumenttypenentfernen=Eliminar tipo(s) de documento seleccionado(s)
eswurdenkeinedokumenttypengefunden=No se han encontrado tipos de documento.
markiertenamtsbezeichnungen=T\u00EDtulo(s) seleccionado(s)
markiertenamtsbezeichnungenentfernen=Eliminar t\u00EDtulo(s) seleccionado(s)
zurveranstaltungssuche=B\u00FAsqueda de eventos
veranstaltungssuche=B\u00FAsqueda de eventos
suchergebnis=Resultado de la b\u00FAsqueda
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=Por favor, para obtener la lista de invitados, seleccione un evento dentro del listado.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=Por favor, para asignar la persona de un evento, seleccione un evento dentro del listado.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=Por favor, seleccione una persona de la lista para establecerla como anfitri\u00F3n.
loschenvonveranstaltungenistnichtmoglich=No es posible eliminar eventos
weiteremeldungen=mensajes adicionales.
bittebestatigensiedasloschendermarkiertenveranstaltungen=Por favor, \u00A1confirme la eliminaci\u00F3n de los eventos seleccionados!
markierteveranstaltungloschen=Eliminar los eventos seleccionados
abbrechen=Cancelar
markierteveranstaltungen=Evento(s) seleccionado(s)
markierteveranstaltungenloschen=Eliminar evento(s) seleccionado(s)
zuruckzurgasteverwaltung=Volver a gesti\u00F3n de invitados
zuruckzurgasteliste=Volver a lista de invitados
zuruckzurveranstaltungsdetails=Volver a detalles de evento
zuruckzurveranstaltungsstatistiken=Volver a estad\u00EDsticas del evento
zuruckzurveranstaltungsaufgabe=Volver a tareas del evento
zuruckzurpersonensuche=Volver a b\u00FAsqueda de personas
zuruckzusuchenundersetzen=Buscar y reemplazar
zuruckzurveranstaltungssuche=B\u00FAsqueda de eventos
wahlensiebittezunachsteineodermehrereveranstaltungenaus=Por favor, comience por seleccionar uno o m\u00E1s eventos.
nurinzuunftigenveranstaltungensuchen=Buscar s\u00F3lo en eventos futuros
zuruck=Volver
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=Puede utilizar comodines en la b\u00FAsqueda. Al utilizar el comod\u00EDn \u2018*\u2019, ser\u00E1n seleccionadas todas las que contengan las secciones del texto de b\u00FAsqueda (orden inclu\u00EDdo), as\u00ED como podr\u00E1 realizar b\u00FAsquedas individuales mediante el comod\u00EDn \u2018?\u2019.
bittebestatigensiedasspeicherndieseraufgabe=Por favor, confirme la actualizaci\u00F3n sobre la tarea actual
verantworlichenhinzufugen=A\u00F1adir responsables
verantworlichenentfernen=Eliminar responsables
loschenvonaufgabenistnichtmoglich=No se puede eliminar tareas
bittebestatigensiedasloschenvonaufgaben=Por favor, confirme la eliminaci\u00F3n de las tareas
ausgewahlteeintrageloschen=Elminar entradas seleccionadas
start=Comenzar
zursuche=Buscar
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=Se ha conectado como administrador y le es permitido exportar todos los mandantes.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=Mediante esta funci\u00F3n, puede exportar exclusivamente personas pertenecientes a mandantes.
event=Evento
keine=Ning\u00FAn
category=Categor\u00EDa
weitereoptionen=Opciones adicionales
anmerkung=Nota
anmerkungen=Notas
markiertebezeichnunge=Denominaciones seleccionadas
markierteeintrageentfernen=Eliminar denominaciones seleccionadas
eswurdenkeinedatengefunden=No se han encontrado datos

eswurdenkeinedatengefunden=No se han encontrado datos
siehabenkeinedatenherkunftangegeben=Los datos de origen no han sido especificados.
HINT_IMPORT_NOT_POSSIBLE_OPENOFFICE=Ha intentado importar un archivo de OpenOffice. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_IMPORT_NOT_POSSIBLE_STAROFFICE=Ha intentado importar un archivo de StarOffice. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_IMPORT_NOT_POSSIBLE_EXCEL=Ha intentado importar un archivo Excel. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web. Por favor, guarde su archivo como archivo-CSV mediante su programa de hojas de c\u00E1lculo.
HINT_IMPORT_NOT_POSSIBLE_PDF=Ha intentado importar un archivo PDF. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_ZIP=Ha intentado importar un archivo ZIP. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_EXE=Ha intentado importar un archivo EXE. La importaci\u00F3n directa no est\u00E1 disponible en esta versi\u00F3n de VerA.web.
siehabenversuchteinedateimitderendung=Ha intentado importar un archivo con la extensi\u00F3n
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=Eso no es posible en la versi\u00F3n actual de VerA.web.
siehabenkeinedateiausgewahltoderdiesewarleer=No ha selecionado ning\u00FAn archivo o el archivo seleccionado est\u00E1 vac\u00EDo.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=Ha ocurrido un error inesperado al importar un archivo.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Presumiblemente, el archivo a importar no posee el formato esperado por el sistema.
detailsanzeigen=Mostrar detalles
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=Al importar datos con gran longitud, es posible que sean acortados para ser visualizados en VerA.web.
alledokumenttypenderzuimportierendenpersonenmussenimsystemvorhandenseinsollderimportjetztgestartetwerden=Todos los tipos de documento para la importaci\u00F3n de personas deber\u00E1n estar habilitados en el sistema. \u00BFComenzar proceso de importaci\u00F3n?
umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=Para hacer a un duplicado almacenable, deber\u00E1 seleccionarlos como almacenables mediante la opci\u00F3n \u201Cduplicados existentes\u201D.
HINT_UMLAUT_COMPARISON=Tenga en cuenta, que los caracteres \u00E4, \u00F6, \u00FC y \u00DF ser\u00E1n tratados como ae, oe, ue y ss, respectivamente.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=La importaci\u00F3n terminar\u00E1 una vez pulse sobre el bot\u00F3n \u201CFinalizar exportaci\u00F3n\u201D.
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=El proceso puede ser finalizado en caso de que los registros almacenables se hayan guardado.
vorhandenedubletten=Duplicados existentes
vorhandenedublettenbearbeiten=Editar duplicados existentes
zuimportierendedatensatzeinsgesamt=Importar total de registros
davondubletten=De duplicados
davonspeicherbar=De almacenables
ignoriertefehlerdatensatze=Datos err\u00F3neos ignorados
importabschlieszen=Finalizar exportaci\u00F3n
siehabenkeinendatensatzimportiert=No se han importado registros.
siehabeneinendatensatzimportiert=Se ha importado un registro.
siehaben=Se han importado
datensatzeimportiert=registros.
informationennichtverfugbar=Informaci\u00F3n no disponible
nichtgewahlt=No seleccionado
verfugbarerollen=Roles disponibles
passowrt=Contrase\u00F1a
inverteretunganmelden=Acceder como representante
vornamenachname=Nombre.Apellido
alsbenutzernamen=Como nombre de usuario
emailvorlage=Modelo E-Mail
amtsbezfunktion=T\u00EDtulo/Funci\u00F3n
postfachnummer=C\u00F3digo postal
email=E-Mail
verteileranlegen=Crear distribuci\u00F3n
sielegeneinenneuenverteilerausderpersonensuche=Se crea un nuevo distribuidor de la B\u00FAsqueda de personas
sielegeneinenneuenverteilerausderveranstaltung=Se crea un nuevo distribuidor para el evento
mit=con
einerperson=una persona
verteilername=nombre del representante
verteilerspeichern=Guardar representante
markierteadressen=Direcciones seleccionadas
markierteadressenausdemverteilerloschen=Eliminar direcciones seleccionadas
analleadressenversenden=Enviar a todas las direcciones
emailclientaufrufen=Redactar E-mail para cliente
esliegenkeineadressdatenfurdiesenverteilervor=No existen datos de direcci\u00F3n para el representante.
esliegenkeineadressenfurdiesenverteilervor=No existen direcciones para el representante.
esliegenkeinevorlagenvor=No existen plantillas.
zuruckzurverteilerubersicht=Gesti\u00F3n de representantes
eswurdekeineemailzumversendengespeichert=No existe ning\u00FAn E-Mail para enviar
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=Se almacenar\u00E1 autom\u00E1ticamente un E-Mail. Ser\u00E1 env\u00EDado directamente.
emailszumversendengespeichertdiesewerdennunautomatischversendet=E-Mails a enviar guardados autom\u00E1ticamente. Ser\u00E1n env\u00EDados directamente.
markiertenverteiler=Representante(s) seleccionado(s)
markierteverteilerloschen=Eliminar representante(s) seleccionado(s)
persondendaten=Datos de personas
solldiesergastaufplatzgesetztwerden=\u00BFDebe el invitado actual obtener una plaza?
solldiepartnerinderpartnermiteingeladenwerden=\u00BFDebe el partner ser invitado?
aktuellepersonwirklichentfernen=\u00BFDesea realmente eliminar la persona actual?
personspeichern=Guardar persona
zurpersonenliste=Volver a personas
zurpersonenuebersicht=Lista de personas
zurueckzurveranstaltung=Volver a eventos
zurdublettensuche=B\u00FAsqueda de duplicados
zurckzumsuchergebnis=Resultados de b\u00FAsqueda
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=La persona ha sido invitada satisfactoriamente al evento
hinzugefuegt=
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=La persona no ser\u00E1 invitada, puesto que ya se encuentra en la lista de invitados.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=La persona actual ser\u00E1 marcada como borrada. Por tanto, no ser\u00E1 posible acceder a ella mediante la b\u00FAsqueda de personas.
personanlegen=Crear persona
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=No se han encontrado duplicados. Usted podr\u00E1 ahora rellenar la informaci\u00F3n para almacenarla.
bittegebensiezunaechstden=Por favor, primero indique
vorundnachnamen= nombre y apellidos
sowieunteranschriftendie=as\u00ED como
anundfuhrendiedublettenprufungdurch=e inicie la b\u00FAsqueda de duplicados.
beifirmenwaehlensiediecheckbox=Para empresas, seleccione el check correspondiente
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=e introduzca el nombre de la empresa. El sistema comprobar\u00E1 la existencia de duplicados.
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=No existen duplicados, ahora puede introducir m\u00E1s informaci\u00F3n y despu\u00E9s guardarla.
geschaeftlich=Negocio
privat=Privado
zurueckzurpersonensuche=Buscar personas
zurueckzurpersonenuebersicht=Volver a persona Resumen
zurueck=Volver
dublettenpruefungdurchfuehren=Iniciar b\u00FAsqueda de duplicados
zurueckzumsuchergebnis=Resultados de b\u00FAsqueda
personspeicherndublettenpruefung=Guardar persona - B\u00FAsqueda-duplicados
neueneintraganlegen=Crear nueva entrada
existierendeneintragbearbeiten=Editar entradas existentes
eswurdenkeinedublettengefunden=No se han encontrado duplicados.
hinzufuegen=A\u00F1adir
ausgewaehltepersonenzurveranstaltunghinzufuegen=Invitar al evento a las personas seleccionadas.
personerfassen=Capturar persona
dublettenanlegen=Crear duplicados
abbrechenundzurueck=Cancelar y volver
gastsuchenveranstaltung=Buscar invitado - Evento
gastsuchen=Buscar invitado
verantwortlichenfueraufgabesuchen=Buscar responsable para tarea
verantwortlichenfueraufgabehinzufugen=Invitar responsable para tarea
gastgeberhinzufuegen=Invitar anfitri\u00F3n
personensuchegastgeberhinzufugen=B\u00FAsqueda de personas: invitar anfitri\u00F3n
gasthinzufuegen=A\u00F1adir invitado
personensuchegasthinzufugen=B\u00FAsqueda de personas: a\u00F1adir invitado
personfirma=Persona/Empresa
weitereangaben=Informaci\u00F3n adicional
keinekategoriezugeordnet=Sin categor\u00EDa asignada
keinarbeitsbereichzugeordnet=Sin \u00E1rea de trabajo asignada
keinarbeitsbereich=Sin \u00E1rea de trabajo
gueltigkeitsdatum=Fecha de disponibilidad
biszudiesemdatum=Hasta la fecha
abdiesemdatum=Desde la fecha
angenaudiesemdatum=Exactamente en la fecha
datumauswaehlen=Seleccionar fecha
HINT_SEARCH_MULTIPLE=La b\u00FAsqueda tambi\u00E9n es compatible con la b\u00FAsqueda m\u00FAltiple por categor\u00EDa. Por favor, seleccione varias categor\u00EDas, mantenga presionado el bot\u00F3n del rat\u00F3n y arrastre su selecci\u00F3n hacia la b\u00FAsqueda de categor\u00EDas. Como alternativa, puede hacer clic mientras mantiene pulsada la tecla \u201CCtrl\u201D con el bot\u00F3n izquierdo del rat\u00F3n. Tenga en cuenta que las pseudocategor\u00EDas \u201CTodas\u201D y \u201CNinguna\u201D no son seleccionables.
waehlensiebittezunaechsteinekategorieaus=Por favor, seleccione una categor\u00EDa.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=\u00BFDesea asignar la categor\u00EDa asignada a la persona
eswurdekeinekategoriezugeordnet=No se han asignado categor\u00EDas
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=\u00BFDesea asignar la categor\u00EDa seleccionada a %s personas/invitados
eswurdenkeinekategorienzugeordnet=No se han asignado categor\u00EDas
eswurdenkeinekategoriengefunden=No se han encontrado categor\u00EDas
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Desea desasignar la categor\u00EDa seleccionada a la persona actual
eswurdekeinekategorieentfernt=No se han eliminado categor\u00EDas
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Desea desasignar la categor\u00EDa seleccionada a %s personas/invitados
eswurdenkeinekategorienentfernt=No se han eliminado categor\u00EDas.
zuweisen=Asignar
waehlensieeinekategorieauswelchesie=Seleccione una categor\u00EDa a
moechten=
alleentfernen=Eliminar todas
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=No ha configurado categor\u00EDas. Mediante el apartado \u201CAdministraci\u00F3n\u201D es posible
definieren=definirlas.
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=Ha seleccionado %s persona(s). Dependiendo del n\u00FAmero de personas seleccionadas, el proceso puede durar un poco m\u00E1s.
waehlensiebittezunaechsteinenarbeitsbereichaus=Seleccione un \u00E1rea de trabajo.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a la persona/invitado actual
eswurdekeinarbeitsbereichzugeordnet=No se han asignado \u00E1reas de trabajo
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a estas personas/invitados
eswurdenkeinearbeitsbereichzugeordnet=No se han asignado \u00E1reas de trabajo
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Desea desasignar del \u00E1rea de trabajo seleccionada a la persona/invitado actual
eswurdekeinarbeitsbereichaufgehoben=No se han eliminado \u00E1reas de trabajo
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Desea desasignar del \u00E1rea de trabajo seleccionada a %s personas/invitados
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a la persona/invitado actual
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=Desea asignar el \u00E1rea de trabajo seleccionada a %s personas/invitados
waehlensieeinenarbeitsbereichauswelchensie=Seleccione un \u00E1rea de trabajo a
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=No ha configurado \u00E1reas de trabajo. Mediante el apartado \u201CAdministraci\u00F3n\u201D es posible
administrationallestellvertretungenimmandanten=Administraci\u00F3n - todos los delegados del mandante
administrationallestellvertretungen=Administraci\u00F3n - todos los delegados
verwaltungpersoenlichevertretungen=Gesti\u00F3n - delegados personales
vertretung=Delegado
markiertevertretungen=Delegado(s) seleccionado(s)
loeschen=Eliminar
markiertevertretungenloeschen=Eliminar delegado(s) seleccionado(s)
gueltigab=V\u00E1lido desde
gueltigbis=V\u00E1lido hasta
bitteauswaehlen=Por favor, seleccione
gaestelisteerstellenfuerveranstaltungeventshortname=Gestionar lista de invitados para el evento: $!event.shortname
gaesteverwaltungderveranstaltung=Lista de invitados del evento
gaestelisteerstellen=Gestionar lista de invitados
ausgabeformatwaehlen=Seleccionar formato de las tareas
listenachkategoriengruppiertmitpartner=Lista agrupada por categor\u00EDa - con Partner
listenachkategoriengruppiertmittelundmobiltelefon=Lista agrupada por categor\u00EDa - con tel\u00E9fono y m\u00F3vil
listenachkategoriengruppiertmitpartnerundfax=Lista agrupada por categor\u00EDa - con partner y fax
listenachsortierungmitpartnertelundmobiltelefon=Lista agrupada - con partner, tel\u00E9fono y m\u00F3vil
tisch=Mesa
zusaetzlichesortierungnach=Filtrado adicional porZus\u00E4tzliche Sortierung nach
zurueckzurgaesteverwaltung=Volver a gesti\u00F3n de invitados
verwaltungallebenutzerimmandanten=Gesti\u00F3n - usuarios en mandantes
verwaltungallebenutzer=Gesti\u00F3n - todos los usuarios
markiertenbenutzer=Usuario(s) seleccionado(s)
markiertenbenutzerloeschen=Eliminar usuario(s) seleccionado(s)
leseneingeschraenkt=Lectura restringida
lesenuneingeschraenkt=Lectura permitida
lesenundschreibeneingeschraenkt=Lectura y escritura restringidas
lesenundschreibenuneingeschraenkt=Lectura y escritura permitidas
mandantadministrieren=Administrar mandantes
administrieren=Administrar
stellvertretung=Declaraci\u00F3n
bittewahlensiedierolleausdiesievertretenmochten=Por favor, seleccione los roles que desee representar
benutzerrolle=Rol de usuario
vertreten=Representar
statistikfurgastgeber=Estad\u00EDsticas para el anfitri\u00F3n
imzeitraumvom=En el per\u00EDodo comprendido entre
biszum=a
bis=hasta
auswartigesamtintranetstil=Intranet relaciones exteriores
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Haga clic sobre unas de las personas de la lista para asignar una tarea
eswurdeeinepersongeloscht=Se ha eliminado una persona.
eswurdekeinepersongeloscht=No se han eliminado personas.
personengelouscht=personas eliminadas.
derarbeitsbereichwurdeerfolgreichhinzugefugt=\u00C1rea de trabajo creada satisfactoriamente.
diearbeitsbereichewurdenerfolgreichentfernt=El \u00E1rea de trabajo se ha eliminado satisfactoriamente.
diekategoriewurdeerfolgreichhinzugefugt=Categor\u00EDa creada satisfactoriamente.
diekategorienwurdenerfolgreichentfernt=Las categor\u00EDas se han eliminado satisfactoriamente.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=No posee el permiso para eliminar personas.
wauhlensiebittezunauchsteineodermehrerepersonenaus=Por favor, seleccione una o m\u00E1s personas.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=La fecha de vigencia corresponde a las siguientes personas en el futuro
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=Las siguientes personas est\u00E1n registradas en eventos actuales o futuros
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=asignado. Puede encontrar informaci\u00F3n detallada a trav\u00E9s de la lista de invitados de los
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=respectivos eventos. Las personas de todos los eventos ser\u00E1n
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=Las siguientes personas poseen, al menos, una tarea en al menos un
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=evento futuro. Para m\u00E1s informaci\u00F3n, por favor acceda a la
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=lista de tareas de los respectivos eventos. Las personas de todos los eventos ser\u00E1n
aufgabenentfernt=Tarea eliminada
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=Si usted quiere modificar su selecci\u00F3n, por favor, cancele la eliminaci\u00F3n.
sollenallemarkiertenpersonengeloeschtwerden=\u00BFDebe ser eliminadas las personas seleccionadas?
dieseaktionkannnichtrueckgaungiggemachtwerden=Esa acci\u00F3n no se podr\u00E1 deshacer.
bittebestaetigensiedasloeschendermarkiertenpersonen=Por favor, \u00A1confirme la eliminaci\u00F3n de las personas seleccionadas!
loeschenvonpersonenistnichtmoeglich=La eliminaci\u00F3n de personas no es posible
markiertepersonenzurveranstaltunghinzufuegen=A\u00F1adir la(s) persona(s) seleccionada(s) al evento
zudieserpersonistkeinehauptpersoneingetragen=La persona actual no est\u00E1 asignada a ninguna persona principal.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=Esta persona no puede ser asignada como reserva, ya que los datos necesarios
nichtvollstaendigerfasstwurden=no estaban totalmente cubiertos.
waehlensiebittezunaechsteineodermehrerepersonenaus=Por favor, seleccione una o m\u00E1s personas.
exportieren=Exportar
einladen=Invitar
aufreservesetzen=Ubicar en reserva
delegationanmelden=Registrar delegaci\u00F3n
alledemarkiereninklpartnerwenneingeladen=(De)seleccionar todos (inc. partner, si est\u00E1n invitados)
arbeitsshybereich=\u00C1rea de trabajo
eswurdenkeineeintraegegefunden=No se han encontrado entradas.
suchenersetzen=Buscar y reemplazar
suchenersetzeninpersonendaten=Buscar y reemplazar en los datos de personas
vornamederhauptpersonunddespartners=Nombre de la persona principal y el partner
nachnamederhauptpersonunddespartners=Apellido de la persona principal y el partner
anredetitel=Denominaci\u00F3n/T\u00EDtulo
anredeundtitel=Denominaci\u00F3n y t\u00EDtulo
straszligeadresszusatzundland=Calle, direcci\u00F3n addicional y pa\u00EDs
plzortundplzpostfach=C\u00F3digo postal/Ciudad y c\u00F3digo postal/Apartado de correos
telefontelefaxundmobiltelefon=Tel\u00E9fono, telefax y tel\u00E9fono m\u00F3vil
telefonfax=Tel\u00E9fono / Fax
emailadresse=Direcci\u00F3n de correo electr\u00F3nico
internetadresse=Direcci\u00F3n-Internet
ihresuchemussausmindestenseinembuchstabenbestehen=Su b\u00FAsqueda debe contener al menos un car\u00E1cter.
siemuessenmindestenseinfeldausgewhlthaben=Usted debe haber seleccionado al menos un campo.
eswurdekeinepersonersetzt=Ninguna persona fue sustituida.
eswurdeeinepersonersetzt=Se ha sustituido una persona.
personenersetzt=Personas sustitu\u00EDdas.
siemuessenmindestenseinfeldausgewaehlthaben=Usted debe haber seleccionado al menos un campo.
eswurdekeinepersongefunden=No se han encontrado personas.
eswurdeeinepersongefunden=Se ha encontrado una persona.
personengefunden=Personas encontradas.
einzelneeinzraegezumersetzenselektieren=Seleccione los elementos para su reemplazo
allesofortersetzen=Reemplazar todos inmediatamente
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=Si utiliza el asterisco (*), el reemplazo ser\u00E1 ejecutado por grupo. En caso contrario, la ejecuci\u00F3n ser\u00E1 individual.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=Debe introducir la fecha mediante el formato DD.MM.AAAA
markierteanredenloschen=Eliminar denominaciones seleccionadas
markiertendokumenttypenloschen=Eliminar tipos de documento seleccionados
markierteveranstaltungsorteloschen=Eliminar localizaciones de evento seleccionadas
markiertevorlagenloschen=Eliminar plantillas seleccionadas

keinedateigefunden=No se han encontrado archivos.
standardauswahlderselectboxbdquozeichensatzrdquo=Selecci\u00F3n est\u00E1ndar del selectbox \u201Egrupo de caracteres\u201C
zusaetzlichefelder=Campos adicionales
postausgang=Bandeja de salida
beimversendendieseremailisteinfehleraufgetreten=Error al enviar el correo electr\u00F3nico.
siekonnendiesejetztbearbeitenunderneutsenden=Ahora puede editarlo y enviar de nuevo.
dieseemailwartetaufihrefertigstellungdurcheinenbenutzer=\u00C9ste correo electr\u00F3nico se encuentra a la espera de terminaci\u00F3n por parte de un usuario.
dieseemailwartetaufihreversendung=\u00C9ste correo electr\u00F3nico se encuentra a la espera de env\u00EDo.
dieseemailwirdgeradeversendetundsollte=\u00C9ste correo electr\u00F3nico ser\u00E1 enviado y deber\u00EDa
nichtbearbeitet=no ser
werden=modificado.
dieseemailwurdebereitsversendetundsollte=\u00C9ste correo electr\u00F3nico ser\u00E1 enviado y deber\u00EDa
nichtmehrbearbeitet=no volver a ser
technischefehlermeldungausblenden=Ocultar error t\u00E9cnico
markiertenmandanten=Mandante(s) seleccionado(s)
markiertenmandantenwirklichloschen=Eliminar realmente mandante(s) seleccionado(s)
alledatensatzewurdenerfolgreichmandantenzugeordnet=Todos los registros han sido asignados a un mandante satisfactoriamente.
esexistiertnochkeinmandant=A\u00FAn no existen mandantes.
zuordnen=Asignar
zuordnen_klein=asignar
markierteanreden=Denominaciones seleccionadas
markierteanredenloeschen=Eliminar denominaciones seleccionadas
markiertenarbeitsbereiche=\u00C1rea(s) de trabajo seleccionada(s)
markierteeintraegeentfernen=Eliminar entradas seleccionadas
emailpostausgang=Bandeja de salida
markierteemailsloeschen=Eliminar E-Mail(s) seleccionado(s)
markierteemails=E-Mail(s) seleccionado(s)
wartet=Esperar
wirdversendet=Ser\u00E1 enviado
gesendet=Enviado
unbekannt=Desconocido
firmainstitutionauswaehlen=Seleccionar empresa/instituci\u00F3n
bittewaehlensieeinefirmainstitutionaus=Por favor, seleccione una empresa o instituci\u00F3n
schliessen=Cerrar
verawebuebersicht=VerA.web :: Vista general
uebersichtanzeigen=Mostrar vista general
neuendatensatzanlegen=Insertar nuevo registro
openofficedateiherrunterladen=Descargar documento OpenOffice
keinedatensaetzegefunden=No se han encontrado registros
einendatensatzgefunden=Un registro encontrado
datensaetzegefunden=Registros encontrados
anzeigen=mostrar
wollensiediesendatensatzunwiderruflichentfernen=\u00BFDese eliminar irrevocablemente el registro?
verawebdetailansicht=VerA.web :: Vista detalle
datensatzbearbeiten=Editar registro
zuruecksetzen=Restaurar
datensatzloeschen=Eliminar registro
siekoennenbeidersuchesogenannteplatzhalterverwendenderstehtfuermehrereunddasfuereinzelnezeichen=En su b\u00FAsqueda, podr\u00E1 utilizar comodines, el asterisco (*) servir\u00E1 para b\u00FAsquedas globales y el s\u00EDmbolo de interrogaci\u00F3n (?) para b\u00FAsquedas individuales
undamtsbezeichnungfunktion=y t\u00EDtulo/funci\u00F3n
HINT_SEARCH_WHERE=La b\u00FAsqueda se basa en nombres, apellidos, localizaci\u00F3n, c\u00F3digo postal, calle, empresa/instituci\u00F3n, tel\u00E9fono, fax, m\u00F3vil, e-mail, observaciones, categor\u00EDas y \u00E1reas de trabajo
neuenorteingeben=Asignar nueva localizaci\u00F3n
bittegebensieeinenneuenorteinundklickensieaufhinzufuegen=Por favor, introduzca una nueva localizaci\u00F3n y presione sobre \u201CAsignar\u201D
neuerveranstaltungsort=Nueva localizaci\u00F3n
personenetikett=Etiquetas-Personas
zuruckzurubersicht=Volver a vista principal
gpsdaten=Datos-GPS
platzhalterintexteinfuegen=Insertar marcador de posici\u00F3n en el texto
intexteinfuegen=Insertar en el texto
emailvorlagen=Plantillas de correo electr\u00F3nico
pdfvorlagen=Plantillas PDF
pdfvorlage=Plantilla PDF
vorhandenevorlagen=Plantillas disponibles
bitteauswhaelengt=Por favor, seleccione
vorlageladen=Cargar plantilla
neuevorlagename=Nueva plantilla (nombre)
neuevorlagespeichern=Guardar nueva plantilla
neuevorlagenmuessensowohleinenbetreffalsauchtextenthalten=La nueva plantilla debe contener su asunto correspondiente (adjunta no se guardar\u00e1n)
zurueckzumverteiler=Volver a distribuci\u00F33n
markiertenveranstaltungsorte=Localizaciones seleccionadas
hinweis=Aviso
aktiv=activo
inaktiv=inactivo
aktionen=Acciones
anschrift=Direcci\u00F3n
anderungenspeichern=Guardar cambios
senden=Enviar

# GENERIC
GENERIC_UPLOAD_BUTTON=Seleccionar archivo
GENERIC_TO=para
GENERIC_FEDERAL_STATE=Provincia
GENERIC_PERSONAL_DATA=Datos personales
GENERIC_NUMBER_OF_GUESTS=N\u00FAmero de invitados
GENERIC_TELEFON=Tel\u00E9fono

# MESSAGES
MESSAGE_INVITATION_WITHOUT_MAIN_PERSON=Este invitado ser\u00E1 inclu\u00EDdo sin persona principal
MESSAGE_INVITATION_WITHOUT_PARTNER=Este invitado ser\u00E1 inclu\u00EDdo sin partner
MESSAGE_INVITATION_WITHOUT_PERSON_PART1=Desea ahora
MESSAGE_INVITATION_WITHOUT_PERSON_PART2_BUTTON=invitar posteriormente
MESSAGE_END_AND_START_DATE=La fecha fin del evento deber\u00E1 ubicarse temporalmente despu\u00E9s que la fecha de inicio.
MESSAGE_EVENT_MISSING_SHORT_DESCRIPTION=No se ha podido guardar el evento. Por favor, introduzca una descripci\u00F3n corta.
MESSAGE_EVENT_WRING_DATE_FORMAT=Debe introducir la fecha de inicio del evento mediante el formato DD.MM.AAAA.
MESSAGE_GENERIC_MISSING_DESCRIPTION=Debe introducir una descripci\u00F3n.
MESSAGE_EVENTDOCTYPE_ASSIGNMENT_WRONG=Se han producido errores en la asignaci\u00F3n de un tipo de documento a un evento.
MESSAGE_EVENT_LOCATION_TITLE_EMPTY=La localizaci\u00F3n del evento no se puede guardar. Por favor, introduzca un t\u00EDtulo.
MESSAGE_EVENT_LOCATION_MAX_REMARK_REACHED=El contenido del campo de observaciones tiene un m\u00E1ximo de 1000 caracteres.
MESSAGE_EMAIL_DRAFT_NAME_MISSING=Debe introducir un nombre para la plantilla de correo electr\u00F3nico.
MESSAGE_EMAIL_DRAFT_SUBJECT_MISSING=No ha introducido un asunto para la plantilla de correo electr\u00F3nico.
MESSAGE_EMAIL_DRAFT_TEXT_MISSING=No ha introducido ning\u00FAn texto en la plantilla de correo electr\u00F3nico.
MESSAGE_EMAIL_LIST_NAME_EMPTY=Por favor, introduzca un nombre para el distribuidor.
MESSAGE_TASK_TIME_WITHOUT_DATE=No est\u00E1 permitido introducir tiempo sin haber seleccionado fecha previamente.
MESSAGE_TASK_END_DATE_NOT_FUTURE=No se pueden guardar las tareas. La fecha final debe ser en el futuro.
MESSAGE_TASK_END_DATE_WITHOUT_BEGIN_DATE=No se pueden guardar las tareas. Por favor, introduzca tambi\u00E9n una fecha de inicio.
MESSAGE_TASK_BEGIN_DATE_BEFORE_END_DATE=No se pueden guardar las tareas. La fecha de inicio debe ubicarse antes que la fecha fin.
MESSAGE_TASK_NO_SHORTNAME=No se pueden guardar las tareas. Por favor, introduzca una descripci\u00F3n corta.
MESSAGE_TASK_MAX_REMARK_REACHED=No se pueden guardar las tareas. El campo de descripci\u00F3n no puede contener m\u00E1s de 1000 caracteres.
MESSAGE_TASK_EMAIL_WITHOUT_SENDER=El E-Mail no puede ser enviado sin remitente.
MESSAGE_TASK_EMAIL_WITHOUT_RECEIVER=El E-Mail no puede ser enviado sin destinatario.
MESSAGE_TASK_EMAIL_WITHOUT_SUBJECT=El E-Mail no puede ser enviado sin asunto.
MESSAGE_ORG_UNIT_NO_NAME=Debe introducir un nombre.
MESSAGE_PERSON_MAX_COMPANY_REACHED=Podr\u00E1 introducir un m\u00E1ximo de 100 caracteres para la firma o instituci\u00F3n.
MESSAGE_PERSON_MAX_NAME_REACHED=Podr\u00E1 introducir un m\u00E1ximo de 100 caracteres para el nombre de la persona principal.
MESSAGE_PERSON_MAX_LASTNAME_REACHED=Podr\u00E1 introducir un m\u00E1ximo de 100 caracteres para el apellido de la persona principal.
MESSAGE_PERSON_NO_MAIL=Debe introducir un correo electr\u00F3nico.
MESSAGE_PERSON_NO_COMPANY_NAME=Debe introducir un nombre para la firma o instituci\u00F3n.
MESSAGE_PERSON_NO_NAME_LAST_NAME=Debe introducir un nombre y apellidos.
MESSAGE_PERSON_NO_NAME=Debe introducir un nombre.
MESSAGE_PERSON_NO_LASTNAME=Debe introducir los apellidos.
MESSAGE_PERSON_CATEGORY_NO_CONNECTION_PERSON_CATEGORY=No se puede guardar la relaci\u00F3n entre persona y categor\u00EDa.
MESSAGE_DOCTYPE_MAX_CONNECTOR_REACHED=El conector puede ser de hasta 50 caracteres de longitud.
MESSAGE_PROXY_NO_REPRESENTATIVE=El campo "Representante" es obligatorio.
MESSAGE_PROXY_NO_ROLE=El campo "Rol" es obligatorio.
MESSAGE_PROXY_MISSING_BOTH=Los campos "Rol" y "Representante" son obligatorios.
MESSAGE_PROXY_REPRESENTATIVE_BEGIN_BEFORE_END=El comienzo de la representaci\u00F3n debe comenzar antes que el final.
MESSAGE_FUNCTION_MISSING_NAME=Debe introducir un nombre para la funci\u00F3n.
MESSAGE_USER_MISSING_ROLE=Debe introducir una descripci\u00F3n para el rol de usuario.
MESSAGE_ORGUNIT_BUSY=Hay asignados usuarios para el mandante/los mandantes. Debe primero eleminar la asignacion.

# EVENT LIST TEXTS
EVENT_LIST_WARNING_EVENTS_IN_FUTURE=Al menos un evento de los seleccionados est\u00E1 activo o lo estar\u00E1 en el futuro.
EVENT_LIST_WARNING_SELECTION_CHANGING=Si quiere modificar su selecci\u00F3n, por favor, cancele la eliminaci\u00F3n.
EVENT_LIST_DELETE_CONFIRMATION_MESSAGE=\u00BFDeben eliminarse todos los eventos seleccionados? Esta acci\u00F3n no se podr\u00E1 deshacer.

# PERSON LIST TEXTS
PERSON_LIST_WARNING_NO_PERMISSION_TO_DELETE=No tiene permiso para eliminar personas.
PERSON_LIST_WARNING_ONLY_DELETE_ONE_PERSON=Debe eliminar siempre s\u00F3lo una persona. Por favor, seleccione s\u00F3lo una entrada o contacte con su administrador.
PERSON_LIST_QUESTION_DELETE_CONFIRMATION=\u00BFDeben eliminarse todas las personas seleccionados?

# EVENT DETAIL SITE TEXTS
EVENT_DETAIL_ALREADY_EXISTS_ONE=Ya existe un evento con el nombre \u201C
EVENT_DETAIL_ALREADY_EXISTS_TWO=\u201D. \u00BFDesea de todas formas guardar el evento nuevo?

# CATEGORY TEXTS
CATEGORY_DETAIL_ALREADY_EXISTS=Ya existe una entrada de datos maestros bajo el nombre

# CHANGELOG REPORTS TEXTS
CHANGELOG_NO_PROTOCOL_AVAILABLE=No existen datos hist\u00F3ricos.

# BROWSER TITLES
BROWSER_TITLE_REPORTS=Reports


#NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GUEST_LIST_RESET_ALL_TO_MASTER_DATA=Reiniciar todos los valores de los datos maestros
GUEST_LIST_EDIT_MASTER_DATA=Editar datos maestros de personas
GUEST=Invitado
GENERIC_OF=de


TOOLTIP_EDIT_HEADLINES=Usted puede modificar los encabezados antes de imprimir pulsando sobre \u201CEditar\u201D. Por favor, guarde antes de imprimir.
GENERIC_PREVIOUS_PAGE=P\u00E1gina anterior
GENERIC_APPLY_TO_GUESTLIST=A\u00F1adir a la lista de invitados
GENERIC_APPLY_GUEST_TO_GUESTLIST=Seleccionar invitado directamente desde la lista de invitados
GENERIC_APPLY=Seleccionar
GENERIC_APPLY_PERSON_AS_HOST=Seleccionar persona directamente como anfitri\u00F3n
etikettfuraktuellepersonerzeugen=Generar etiqueta para la persona actual

aktuellepersonloschenundzurpersonenlistezuruckkehren=Eliminar persona actual y volver a la lista de personas
freifeldvorschaufur=Campo libre-Vista previa para
zudieserpersonwurdedasentsprechendevorschaufeldnochncihterzeugt=El campo Vista Previa no ser\u00E1 generado para esta persona
siemussendierolleangebenunterdersieverawebnutzenmochten=Debe introducir los roles que desea utilizar en VerA.web.
GENERIC_CHOOSE=seleccionar
GENERIC_RESET=Reiniciar
siehabenkeineausreichendeberechtigungumdiegastelistezuentfernen=No tiene permisos para eliminar invitados
wahlensiebittezunachsteinenodermehreregasteaus=Por favor, seleccione uno o m\u00E1s invitados
bittebestatigensiedasloschendermarkiertengasteliste=Por favor, \u00A1confirme la eliminaci\u00F3n de los invitados seleccionados!
GENERIC_NO_GUESTLIST_DELETED=No se han eliminado invitados.


EVENT_DOCTYPE_RESET_INFO=Por favor, compruebe que el evento tiene asociados los tipos de documento. Si este fuera el caso, necesita volver a crear los tipos de documento para los invitados, haciendo clic en \u201CRestablecer datos maestros\u201D.

diesistuberdenmenupunktadministrationprogrammeinstellungenmoglich=Se encuentra dentro del men\u00FA \u201CAdministraci\u00F3n \u2192 Preferencias de programa\u201D.

GENERIC_CHOSEN_GUESTLIST=Invitados seleccionados
exportierfahigegasteliste=Invitados exportables
unvollstandigegasteliste=Invitados incompletos

GUESTLIST_FILTER_EXPORT_INFO=S\u00F3lo ser\u00E1n exportados los invitados seleccionados a trav\u00E9s del filtro ejecutado sobre la lista de invitados.

GUEST_CANNOT_BE_EXPORTED_1=Un invitado
GUEST_CANNOT_BE_EXPORTED_2=no se ha
GUEST_CANNOT_BE_EXPORTED_3=podido
GUEST_CANNOT_BE_EXPORTED_4=exportar
PERSON_MISSING_DOCTYPE_SPECIFIC_DATA=porque para esa persona no se han guardado datos espec\u00EDficos del tipo de documento

GUESTS_CANNOT_BE_EXPORTED_1=invitados
GUESTS_CANNOT_BE_EXPORTED_2=no se han
GUESTS_CANNOT_BE_EXPORTED_3=podido
GUESTS_CANNOT_BE_EXPORTED_4=exportar
PERSONS_MISSING_DOCTYPE_SPECIFIC_DATA=porque para esas personas no se han guardado datos espec\u00EDficos del tipo de documento
GENERIC_TO_EVENTDETAIL=Volver a detalles del evento
GENERIC_INSERT_CURRENT_MONTH=insertar mes actual
GENERIC_SELECT_FUNCTION=Seleccionar funci\u00F3n
diestammdatendiesesgasteswurdengeloschtsiekonnennurdatenimrahmendieserveranstaltungbearbeiten=Se han eliminado los datos maestros de este invitado. S\u00F3lo se pueden editar datos en relaci\u00F3n al evento actual.
DELETE_SELECTED_MANDATOR=Eliminar mandante(s) seleccionado(s)
PROMPT_APPLY_CATEGORY_RANK_FROM_MASTERDATA=\u00BFUtilizar los datos de rango de categor\u00EDa de los datos maestros?


# NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GUEST_LIST_RESET_ALL_TO_MASTER_DATA=Reiniciar todos los valores mediante datos maestros
GUEST_LIST_EDIT_MASTER_DATA=Editar datos maestros de personas
GUEST=Invitado
GENERIC_OF_CAPITAL=de
GENERIC_ASSIGN=Aceptar
GENERIC_CANCEL=Cancelar
GENERIC_DELETE=Eliminar
GENERIC_CONNECTOR=Conector
GENERIC_VIEW_DOCUMENT_TYPE=Vista de tipos de documento
GENERIC_GENERATE_DOCUMENT_TYPE=Generar tipo de documento

# GUEST DETAIL TEXTS
GUEST_DETAIL_PARTNER=el partner
GUEST_DETAIL_PARTNER_GENITIV=del partner
GUEST_DETAIL_MAINPERSON=la persona principal

GUEST_DETAIL_DUP_SEAT_ERROR_ONE=Por favor, modifique el asiento por
GUEST_DETAIL_DUP_SEAT_ERROR_TWO=de
GUEST_DETAIL_DUP_SEAT_ERROR_THREE=sobre la lista de invitados. Esta persona se sienta actualmente en
GUEST_DETAIL_DUP_SEAT_ERROR_FOUR=el asiento introducido
GUEST_DETAIL_DUP_SEAT_ERROR_FIVE=. El cambio no se ha producidoDie \u00C4nderung wurde nicht gespeichert.

# GUEST TEXTS
GUEST_CALC_SERIALNO=Este evento pertenece a una fecha en el pasado. Aun as\u00ED, \u00BFdesea volver a calcular su n\u00FAmero de serie?

# MAILING LIST TEXTS
MAILING_LIST_NO_ADDRESSES=La creaci\u00F3n de un nuevo distribuidor finaliz\u00F3 con errores, debido a la inexistencia de datos de direcciones en las personas seleccionadas
MAILING_LIST_SELECTED_FILE=El archivo seleccionado
MAILING_LIST_ALREADY_SELECTED_FILE=Este archivo ya ha sido seleccionado
MAILING_LIST_SELECTED_TOO_MANY=Hay demasiados archivos seleccionados
MAILING_LIST_SELECTED_TOO_BIG=El archivo es demasiado grande

# ORG UNIT LIST TEXTS
ORG_UNIT_NO_MANDANT_ID=El mandante a insertar no deber\u00E1 tener ID
ORG_UNIT_MANDANT_ALREADY_EXISTS_ONE=El mandante a insertar
ORG_UNIT_MANDANT_ALREADY_EXISTS_TWO=ya existe.
ORG_UNIT_MANDANT_ID_COMPULSORY_ONE=Actualizar mandante
ORG_UNIT_MANDANT_ID_COMPULSORY_TWO= debe tener un ID
ORG_UNIT_MANDANT_EXISTS_ONE=Un mandante con el nombre
ORG_UNIT_MANDANT_EXISTS_TWO=ya existe.

# PERSON CATEGORIES TEXTS
PERSON_CATEGORIES_SELECT_WARNING=Para insertar una nueva categor\u00EDa, por favor, seleccione una. (S\u00F3lo ha introducido el rango.)

# EXPORT FILE HEADERS
EXPORT_HEADER_DOCUMENT_TYPE=Tipo_Documento
EXPORT_HEADER_FREETEXT_FIELD=Campo_libre
EXPORT_HEADER_PARTNER_FREETEXT_FIELD=Campo_libre_Partner
EXPORT_HEADER_INTERCONNECTS=Conector
EXPORT_HEADER_ADDRESS=Direcci\u00F3n
EXPORT_HEADER_CHARSET=Charset
EXPORT_HEADER_FUNCTION=Funci\u00F3n
EXPORT_HEADER_TITLE=G\u00E9nero
EXPORT_HEADER_ACADEMIC_TITLE=T\u00EDtulo_acad
EXPORT_HEADER_FIRSTNAME=Nombre
EXPORT_HEADER_LASTNAME=Apellidos
EXPORT_HEADER_PARTNER_TITLE=G\u00E9nero_Partner
EXPORT_HEADER_PARTNER_ACADEMIC_TITLE=T\u00EDtulo_acad_Partner
EXPORT_HEADER_PARTNER_FIRSTNAME=Nombre_Partner
EXPORT_HEADER_PARTNER_LASTNAME=Apellidos_Partner
EXPORT_HEADER_POSTALCODE=CP
EXPORT_HEADER_CITY=Ciudad
EXPORT_HEADER_STREET=Calle
EXPORT_HEADER_COUNTRY=Pa\u00EDs
EXPORT_HEADER_ADDITIONAL_ADDRESS_ONE=Direcci\u00F3n_adicional_1
EXPORT_HEADER_ADDITIONAL_ADDRESS_TWO=Direcci\u00F3n_adicional_2
EXPORT_HEADER_CITY_OF_BORN=Lugar_nacimiento
EXPORT_HEADER_TELEPHONE=Tel\u00E9fono
EXPORT_HEADER_FAX=Fax
EXPORT_HEADER_EMAIL=Email
EXPORT_HEADER_WWW=WWW
EXPORT_HEADER_MOBILE=M\u00F3vil
EXPORT_HEADER_COMPANY=Empresa
EXPORT_HEADER_POST_OFFICE_BOX_NUMBER=Apt_Correos
EXPORT_HEADER_POST_OFFICE_BOX_PLZ=CP
EXPORT_HEADER_WORK_AREA=\u00C1rea_trabajo
EXPORT_HEADER_CATEGORY=Categor\u00EDa
EXPORT_HEADER_CATEGORY_RANG=Rango_Categor\u00EDa
EXPORT_HEADER_RANG=Rango
EXPORT_HEADER_RESERVE=Reserva
EXPORT_HEADER_STATUS=Estado
EXPORT_HEADER_TABLE=Mesa
EXPORT_HEADER_SEAT=Sitio
EXPORT_HEADER_CURRENT_NUMBER=N\u00FAmero_serie
EXPORT_HEADER_COLOUR=Color
EXPORT_HEADER_IN_COUNTRY=En_pa\u00EDs
EXPORT_HEADER_LANGUAGES=Idiomas
EXPORT_HEADER_SEX=G\u00E9nero
EXPORT_HEADER_NATIONALITY=Nacionalidad
EXPORT_HEADER_HINT_RESPONSIBLE=Aviso_Anfitri\u00F3n
EXPORT_HEADER_HINT_ORG_TEAM=Aviso_Orga
EXPORT_HEADER_PARTNER_STATUS=Estado_Partner
EXPORT_HEADER_PARTNER_TABLE=Mesa_Partner
EXPORT_HEADER_PARTNER_SEAT=Sitio_Partner
EXPORT_HEADER_PARTNER_CURRENT_NUMBER=N\u00FAmero_serie_Partner
EXPORT_HEADER_PARTNER_COLOUR=Color_Partner
EXPORT_HEADER_PARTNER_IN_COUNTRY=En_pa\u00EDs
EXPORT_HEADER_PARTNER_LANGUAGES=Idiomas_Partner
EXPORT_HEADER_PARTNER_SEX=G\u00E9nero_Partner
EXPORT_HEADER_PARTNER_NATIONALITY=Nacionalidad_Partner
EXPORT_HEADER_PARTNER_HINT_RESPONSIBLE=Aviso_Anfitri\u00F3n_Partner
EXPORT_HEADER_PARTNER_HINT_ORG_TEAM=Aviso_Orga_Partner
EXPORT_HEADER_ACCEPT=Selecci\u00F3n_Aceptada
EXPORT_HEADER_DECLINE=Selecci\u00F3n_Rechazada
EXPORT_HEADER_OPEN=Selecci\u00F3n_Pendiente
EXPORT_HEADER_GUEST_IN_PLACE=Total_invitados_con_sitio
EXPORT_HEADER_GUEST_IN_RESERVE=Total_invitados_en_reserva
EXPORT_HEADER_EVENT_NAME=Nombre_evento
EXPORT_HEADER_EVENT_BEGIN=Inicio_evento
EXPORT_HEADER_EVENT_END=Fin_evento
EXPORT_HEADER_EVENT_LOCATION=Lugar_evento
EXPORT_HEADER_OBSERVATION=Observaciones

# MAIN DATA (STAMMDATEN-WORKER) TEXTS
MAIN_DATA_WARN_ALREADY_EXISTS=Ya existe una entrada de datos maestros bajo el nombre

# STATS (Statistik Worker)
STATS_COLUMN_EVENT_NAME=Nombre del evento
STATS_COLUMN_DATE_BEGIN=Inicio
STATS_COLUMN_INVITATION_TYPE=Tipo de invitaci\u00F3n
STATS_COLUMN_INVITATION_STATUS=Estado
STATS_COLUMN_INVITATION_STATUS_PARTNER=Estado del partner
STATS_COLUMN_YEAR=A\u00F1o
STATS_COLUMN_MONTH=Mes
STATS_COLUMN_EVENTS=Eventos
STATS_NOT_INVITED=no invitado

# USER LIST TEXTS
USER_LIST_WARN_MANDANT_ONE=El usuario a insertar ya se encuentra asignado al mandante
USER_LIST_WARN_MANDANT_TWO=.
USER_LIST_WARN_ALREADY_USER=El usuario a insertar ya existe en VerA.web.
USER_LIST_WARN_NO_ID=El usuario a insertar no debe tener ID

# WORKAREA TEXTS
WORKAREA_NEED_MANDANT=No pueden crear una \u00E1rea del trabajo porque usted no est\u00E1n identificado con un mandante.
WORKAREA_ERROR_INCORRECT_NAME_ONE=El \u00E1rea de trabajo con el nombre \u201C
WORKAREA_ERROR_INCORRECT_NAME_TWO=\u201D no se ha podido crear. Por favor, identifique en primer lugar un mandante.

# VERIFY TEXTS
VERIFY_ERROR_ACCESS_TO_DB_UNABLE=No ha podido establecerse conexi\u00F3n con la base de datos.
VERIFY_ERROR_ACCESS_TO_DB_INTERRUPTED=La conexi\u00F3n con la base de datos se ha visto interrumpida.
VERIFY_ERROR_ACCESS_TO_DB_NOT_INTERRUPTED=La conexi\u00F3n con la base de datos no se ha podido interrumpir con \u00E9xito.
VERIFY_ERROR_DB_NOT_ACCESSIBLE=No ha podido establecerse conexi\u00F3n con la base de datos.
VERIFY_ERROR_DB_VERSION_NOT_DETERMINED=No se pudo determinar la versi\u00F3n del esquema de la base de datos.
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_ONE=La versi\u00F3n del esquema de base de datos (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_TWO=) no es la esperada por VerA.web (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_THREE=).
VERIFY_ERROR_DB_LC_CTYPE_NOT_WANTED=Su configuraci\u00F3n actual de base de datos no puede interpretar el conjunto de caracteres (LC_CTYPE=
VERIFY_ERROR_DB_LC_COLLATE_NOT_WANTED=Su configuraci\u00F3n actual de base de datos no puede interpretar las reglas de comparaci\u00F3n de texto (LC_COLLATE=
VERIFY_ERROR_XML=Se ha producido un error al generar un documento XML de prueba. (
VERIFY_ERROR_JAVA_ONE=La versi\u00F3n de Java instalada (
VERIFY_ERROR_JAVA_TWO=) no se corresponde con la versi\u00F3n esperada (1.4).

#TO BE DELETED
inlandjageschlechtweiblich=En el pa\u00EDs: S\u00ED - G\u00E9nero: mujer
inlandjageschlechtmannlich=En el pa\u00EDs: S\u00ED - G\u00E9nero: hombre
inlandneingeschlechtweiblich=En el pa\u00EDs: No - G\u00E9nero: mujer
inlandneingeschlechtmannlich=En el pa\u00EDs: No - G\u00E9nero: hombre

# GENERIC DIALOG MESSAGES
GENERIC_PLEASE_WAIT_HEADER=Por favor, espere...
GENERIC_PLEASE_WAIT_MESSAGE=El proceso puede tardar m\u00E1s de lo normal.

# WORK AREA (Bean) TEXTS
WORKAREA_ERROR_MISSING_NAME=El campo de trabajo no puede estar vac\u00EDo


zurpersonensuche=Volver a b\u00FAsqueda de personas
steuerdatei=Archivo de control
dokumenttypauswahlen=Seleccionar tipo de documento
EVENT_NO_DOCTYPES_ASSIGNED=El evento no tiene tipos de documento asociados

# DATE HELPER TEXTS
DATE_HELPER_INCORRECT_DATE= no es una fecha v\u00E1lida. Por favor, \u00A1utilice el formato de entrada DD.MM.AAAA!

#WIP
GENERIC_SHOW_CURRENT_EVENTS=Mostrar eventos actuales
GENERIC_FURTHER_PROCEEDING=Acciones posteriores

LETTER_MAIN_PERSON=PP
LETTER_PARTNER=P
LETTER_RESERVE=R
LETTER_DELEGATION=D
LETTER_HOST=A

GENERIC_LASTNAME_WITH_SOFT_HYPHEN=Nach\u00ADname
GENERIC_FIRSTNAME_WITH_SOFT_HYPHEN=Vor\u00ADname
GENERIC_RELOAD=Recargar
GENERIC_LOAD_EXISTING_IMPORTPROCESS=Cargar proceso de importaci\u00F3n existente
GENERIC_IMPORTID=ImportID
GENERIC_YEAR=A\u00F1o
GENERIC_COUNT=Total
GENERIC_PARTICIPATION=Participaci\u00F3n
GENERIC_NOT_ASSIGNED_TO_CATEGORY=Sin categor\u00EDa asignada
GENERIC_NOT_ASSIGNED_TO_WORKAREA=Sin \u00E1rea de trabajo asignada
GENERIC_NO_HOST_ASSIGNED=Sin anfitri\u00F3n asignado
GENERIC_NO_GUEST_FOUND=Sin invitados

GENERIC_PHONE_NUMBER_SHORT=Tlf.
GENERIC_FAX_NUMBER_SHORT=Fax.

GENERIC_MONTH_YEAR=Mes/A\u00F1o
GENERIC_LOOK_AT=visualizar
GENERIC_MOBILE_PHONE=M\u00F3vil

PHONE_OFFICIAL=Tlf. negocios
PHONE_PRIVATE=Tlf. privado
PHONE_MOBILE=Tlf. m\u00F3vil

GENERIC_PARTNER_FREETEXTFIELD=Campo de texto libre para partner
GENERIC_VENUE=Localizaci\u00F3n del evento

GENERIC_TOTAL=Total
OPTION_MARK_ADMINISTRATION_CATEGORY_1=Categor\u00EDa
OPTION_MARK_ADMINISTRATION_CATEGORY_2=Suceso
OPTION_MARK_ADMINISTRATION_CATEGORY_3=Diplo. Corps

GENERIC_IMPORTID_HYPHEN=Import-ID

GENERIC_SUBSTITUTED_BY=representado por
GENERIC_NONE=Ning\u00FAn
GENERIC_ADDRESS_BLOCK=Bloque de direcci\u00F3n

GENERIC_CONTEXT_PLURAL=Contextos

PERSON_DETAIL_DELETE_PERSON_HEADER=Por favor, \u00A1confirme la eliminaci\u00F3n de la persona!
PERSON_DETAIL_DELETE_PERSON_CANCEL_DELETION=Si no quiere eliminar esta persona, por favor, cancele el proceso.
PERSON_DETAIL_DELETE_PERSON_CONFIRM_DELETION_WARNING=\u00BFDebe la persona actual ser eliminada?

# PERSON HEADER TEXTS
PERSON_HEADER_NO_DOCTYPE_CONFIG=No se ha configurado ning\u00FAn tipo de documento.

#LAST ADDED
GENERIC_GENERATE_LOGIN_CREDENTIALS_FOR_ONLINE_REGISTRATION=Datos de acceso para la aplicaci\u00F3n en l\u00EDnea
GENERIC_COPY_CURRENT_PERSON=Copiar persona actual
GENERIC_ASSIGN_CURRENT_PERSON_TO_EVENT=Invitar persona al evento
GENERIC_PREVIOUS_PAGE=P\u00E1gina anterior
GENERIC_PREVIOUS_PERSON=Persona anterior
GENERIC_FIRST_PAGE=P\u00E1gina inicial
GENERIC_FIRST_PERSON=Primera persona
GENERIC_LAST_PAGE=\u00FAltima p\u00E1gina
GENERIC_LAST_PERSON=\u00FAltima persona
GENERIC_NEXT_PAGE=P\u00E1gina siguiente
GENERIC_NEXT_PERSON=Persona siguiente
GENERIC_INPUT_FIELD=Campo de texto
GENERIC_SIMPLE_COMBOBOX=Campo de selecci\u00F3n simple
GENERIC_MULTIPLE_COMBOBOX=Campo de selecci\u00F3n m\u00FAltiple

# EVENT LOCATIONS (Veranstaltungsort)
HINT_DELETE_NOT_POSSIBLE_ONE=La localizaci\u00F3n \u201C
HINT_DELETE_NOT_POSSIBLE_TWO=\u201D no ha podido ser eliminada, debido a que se encuentra relacionada con al menos un evento.
CONFIRMATION_CREATE_LOCATION_ONE=\u00BFDesea realmente eliminar la localizaci\u00F3n \u201C
CONFIRMATION_CREATE_LOCATION_TWO=\u201D?

INSERT_FUNCTION_FROM_MAIN_DATA=Tomar funci\u00F3n desde datos maestros
INSERT_COMPANY_FROM_MAIN_DATA=Tomar empresa desde datos maestros

HINT_GUEST_ALREADY_INVITED_SINGULAR=Un invitado ya se encontraba en la lista de invitados.
HINT_GUEST_ALREADY_INVITED_PLURAL=invitados ya se encontraban en la lista de invitados.

MESSAGE_REPLACED_PERSON_ONE=Se han reemplazado
MESSAGE_REPLACED_PERSON_TWO=personas.
MESSAGE_FOUND_PERSON_ONE=Se han encontrado
MESSAGE_FOUND_PERSON_TWO=personas.

HINT_POPUP_CATEGORY_SELECTION_ONE=Ha seleccionado
HINT_POPUP_CATEGORY_SELECTION_TWO=persona(s). Dependiendo del n\u00FAmero de personas seleccionadas, el proceso puede durar un poco m\u00E1s.

DELETE_DISTRIBUTOR=\u00BFDesea realmente eliminar el distribuidor seleccionado?
DELETE_DISTRIBUTORS=\u00BFDesea realmente eliminar los distribuidores seleccionados?
PLACEHOLDER_DATE_FORMAT=dd.mm.aaaa

DELETE_EVENT_TASKS_FIRST_LINE=Por favor, \u00A1confirme la eliminaci\u00F3n de las tareas seleccionados!
DELETE_EVENT_TASKS_SECOND_LINE=\u00BFDeben eliminarse todos las tareas seleccionados? Esta acci\u00F3n no se podr\u00E1 deshacer.

GM_NO_CHANGES=No se han producido cambios.
GM_CONFIRMATION_EMAIL_DISTRIBUTOR=\u00BFCrear correo electr\u00F3nico de distribuci\u00F3n?

CONTACT_PICTURE_UPLOAD=Subir foto
CONTACT_PICTURE_CHANGE=Modificar foto
CONTACT_PICTURE_WRONG_SIZE=La foto debe comprender las dimensiones 186x245 pixels.
PICTURE_SIZE=tama\u00F1o de la imagen
PIXELS=pixels

NO_PARTNER_IN_MASTERDATA=Kein Partner in Stammdaten hinterlegt

#GENERAL MESSAGE
GM_CATEGORY_MODIFY_S=Se ha modificado una categor\u00EDa.
GM_CATEGORY_MODIFY_P=Se han modificado %s categor\u00EDas.
GM_CATEGORY_MODIFY_N=No se han modificado categor\u00EDas.
GM_CATEGORY_DELETE_S=Se ha eliminado una categor\u00EDa.
GM_CATEGORY_DELETE_P=Se han eliminado %s categor\u00EDas.
GM_CATEGORY_DELETE_N=Por favor, comience por seleccionar una o m\u00E1s categor\u00EDas.
GM_CATEGORY_INSERT_S=Se ha creado una categor\u00EDa.
GM_CATEGORY_INSERT_P=Se han creado %s categor\u00EDas.
GM_CATEGORY_INSERT_N=No se han creado categor\u00EDas.
GM_CLIENT_MODIFY_S=Se ha modificado un mandante.
GM_CLIENT_MODIFY_P=Se han modificado %s mandantes.
GM_CLIENT_MODIFY_N=No se han modificado mandantes.
GM_CLIENT_DELETE_S=Se ha eliminado un mandante.
GM_CLIENT_DELETE_P=Se han eliminado %s mandantes.
GM_CLIENT_DELETE_N=No se han eliminado mandantes.
GM_CLIENT_INSERT_S=Se ha creado un mandante.
GM_CLIENT_INSERT_P=Se han creado %s mandantes.
GM_CLIENT_INSERT_N=No se han creado mandantes.
GM_COLOR_MODIFY_S=Se ha modificado un color.
GM_COLOR_MODIFY_P=Se han modificado %s colores.
GM_COLOR_MODIFY_N=No se han modificado colores.
GM_COLOR_DELETE_S=Se ha eliminado un color.
GM_COLOR_DELETE_P=Se han eliminado %s colores.
GM_COLOR_DELETE_N=No se han eliminado colores.
GM_COLOR_INSERT_S=Se ha creado un color.
GM_COLOR_INSERT_P=Se han creado %s colores.
GM_COLOR_INSERT_N=No se han creado colores.
GM_DELEGATION_FIELD_MODIFY_S=Se ha modificado un campo adicional.
GM_DELEGATION_FIELD_MODIFY_P=Se han modificado %s campos adicionales.
GM_DELEGATION_FIELD_MODIFY_N=No se han modificado campos adicionales.
GM_DELEGATION_FIELD_DELETE_S=Se ha eliminado un campo adicional.
GM_DELEGATION_FIELD_DELETE_P=Se han eliminado %s campos adicionales.
GM_DELEGATION_FIELD_DELETE_N=No se han eliminado campos adicionales.
GM_DELEGATION_FIELD_INSERT_S=Se ha creado un campo adicional.
GM_DELEGATION_FIELD_INSERT_P=Se han creado %s campos adicionales.
GM_DELEGATION_FIELD_INSERT_N=No se han creado campos adicionales.
GM_DISTRIBUTOR_MODIFY_S=Se ha modificado un distribuidor.
GM_DISTRIBUTOR_MODIFY_P=Se han modificado %s distribuidores.
GM_DISTRIBUTOR_MODIFY_N=No se han modificado distribuidores.
GM_DISTRIBUTOR_DELETE_S=Se ha eliminado un distribuidor.
GM_DISTRIBUTOR_DELETE_P=Se han eliminado %s distribuidores.
GM_DISTRIBUTOR_DELETE_N=No se han eliminado distribuidores.
GM_DISTRIBUTOR_INSERT_S=Se ha creado un distribuidor.
GM_DISTRIBUTOR_INSERT_P=Se han creado %s distribuidores.
GM_DISTRIBUTOR_INSERT_N=No se han creado distribuidores.
GM_DOCUMENT_TYPE_MODIFY_S=Se ha modificado un tipo de documento.
GM_DOCUMENT_TYPE_MODIFY_P=Se han modificado %s tipos de documento.
GM_DOCUMENT_TYPE_MODIFY_N=No se han modificado tipos de documento.
GM_DOCUMENT_TYPE_DELETE_S=Se ha eliminado un tipo de documento.
GM_DOCUMENT_TYPE_DELETE_P=Se han eliminado %s tipos de documento.
GM_DOCUMENT_TYPE_DELETE_N=Por favor, comience pro seleccionar uno o m\u00E1s tipos de documento.
GM_DOCUMENT_TYPE_INSERT_S=Se ha a\u00F1adido un tipo de documento.
GM_DOCUMENT_TYPE_INSERT_P=Se han a\u00F1adido %s tipos de documento.
GM_DOCUMENT_TYPE_INSERT_N=No se han a\u00F1adido tipos de documento.
GM_EMAIL_MODIFY_S=Se ha modificado un e-mail.
GM_EMAIL_MODIFY_P=Se han modificado %s e-mails.
GM_EMAIL_MODIFY_N=No se han modificado e-mails.
GM_EMAIL_DELETE_S=Se ha eliminado un e-mail.
GM_EMAIL_DELETE_P=Se han eliminado %s e-mails.
GM_EMAIL_DELETE_N=No se han eliminado e-mails.
GM_EMAIL_INSERT_S=Se ha creado un e-mail.
GM_EMAIL_INSERT_P=Se han creado %s e-mails.
GM_EMAIL_INSERT_N=No se han creado e-mails.
GM_EVENT_MODIFY_S=Se ha modificado un evento.
GM_EVENT_MODIFY_P=Se han modificado %s eventos.
GM_EVENT_MODIFY_N=No se han modificado eventos.
GM_EVENT_DELETE_S=Se ha eliminado un evento.
GM_EVENT_DELETE_P=Se han eliminado %s eventos.
GM_EVENT_DELETE_N=No se han eliminado eventos.
GM_EVENT_INSERT_S=Se ha creado un evento.
GM_EVENT_INSERT_P=Se han creado %s eventos.
GM_EVENT_INSERT_N=No se han creado eventos.
GM_EVENT_LOCATION_MODIFY_S=Se ha modificado una localizaci\u00F3n de evento.
GM_EVENT_LOCATION_MODIFY_P=Se han modificado %s localizaciones de evento.
GM_EVENT_LOCATION_MODIFY_N=No se han modificado localizaciones de evento.
GM_EVENT_LOCATION_DELETE_S=Se ha eliminado una localizaci\u00F3n de evento.
GM_EVENT_LOCATION_DELETE_P=Se han eliminado %s localizaciones de evento.
GM_EVENT_LOCATION_DELETE_N=No se han eliminado localizaciones de evento.
GM_EVENT_LOCATION_INSERT_S=Se ha created una localizaci\u00F3n de evento.
GM_EVENT_LOCATION_INSERT_P=Se han created %s localizaciones de evento.
GM_EVENT_LOCATION_INSERT_N=No se han created localizaciones de evento.
GM_GUEST_MODIFY_S=Se ha modificado un invitado.
GM_GUEST_MODIFY_P=Se han modificado %s invitados.
GM_GUEST_MODIFY_N=No se han modificado invitados.
GM_GUEST_DELETE_S=Se ha eliminado un invitado.
GM_GUEST_DELETE_P=Se han eliminado %s invitados.
GM_GUEST_DELETE_N=No se han eliminado invitados.
GM_GUEST_INSERT_S=Se ha creado una localizaci\u00F3n de evento.
GM_GUEST_INSERT_P=Se han a\u00F1adido %s invitados.
GM_GUEST_INSERT_N=La localizaci\u00F3n del evento no se puede guardar. Por favor, introduzca un t\u00EDtulo.
GM_MAIL_DRAFT_MODIFY_S=Se ha modificado un asunto.
GM_MAIL_DRAFT_MODIFY_P=Se han modificado %s asuntos.
GM_MAIL_DRAFT_MODIFY_N=No se han modificado asuntos.
GM_MAIL_DRAFT_DELETE_S=Se ha eliminado un asunto.
GM_MAIL_DRAFT_DELETE_P=Se han eliminado %s asuntos.
GM_MAIL_DRAFT_DELETE_N=No se han eliminado asuntos.
GM_MAIL_DRAFT_INSERT_S=Se ha creado un asunto.
GM_MAIL_DRAFT_INSERT_P=Se han creado %s asuntos.
GM_MAIL_DRAFT_INSERT_N=No se han creado asuntos.
GM_OFFICIAL_TITLE_MODIFY_S=Se ha modificado un t\u00EDtulo.
GM_OFFICIAL_TITLE_MODIFY_P=Se han modificado %s t\u00EDtulos.
GM_OFFICIAL_TITLE_MODIFY_N=No se han modificado t\u00EDtulos.
GM_OFFICIAL_TITLE_DELETE_S=Se ha eliminado un t\u00EDtulo.
GM_OFFICIAL_TITLE_DELETE_P=Se han eliminado %s t\u00EDtulos.
GM_OFFICIAL_TITLE_DELETE_N=No se han eliminado t\u00EDtulos.
GM_OFFICIAL_TITLE_INSERT_S=Se ha creado un t\u00EDtulo.
GM_OFFICIAL_TITLE_INSERT_P=Se han creado %s t\u00EDtulos.
GM_OFFICIAL_TITLE_INSERT_N=No se han creado t\u00EDtulos.
GM_PERSON_MODIFY_S=Se ha modificado una persona.
GM_PERSON_MODIFY_P=Se han modificado %s personas.
GM_PERSON_MODIFY_N=No se han modificado personas.
GM_PERSON_DELETE_S=Se ha eliminado una persona.
GM_PERSON_DELETE_P=Se han eliminado %s personas.
GM_PERSON_DELETE_N=No se han eliminado personas.
GM_PERSON_INSERT_S=Se ha creado una persona.
GM_PERSON_INSERT_P=Se han creado %s personas.
GM_PERSON_INSERT_N=No se han creado personas.
GM_REPRESENTATIVE_MODIFY_S=Se ha modificado un representante.
GM_REPRESENTATIVE_MODIFY_P=Se han modificado %s representantes.
GM_REPRESENTATIVE_MODIFY_N=No se han modificado representantes.
GM_REPRESENTATIVE_DELETE_S=Se ha eliminado un representante.
GM_REPRESENTATIVE_DELETE_P=Se han eliminado %s representantes.
GM_REPRESENTATIVE_DELETE_N=No se han eliminado representantes.
GM_REPRESENTATIVE_INSERT_S=Se ha creado un representante.
GM_REPRESENTATIVE_INSERT_P=Se han creado %s representantes.
GM_REPRESENTATIVE_INSERT_N=No se han creado representantes.
GM_SALUTATION_MODIFY_S=Se ha modificado una denominaci\u00F3n.
GM_SALUTATION_MODIFY_P=Se han modificado %s denominaciones.
GM_SALUTATION_MODIFY_N=No se han modificado denominaciones.
GM_SALUTATION_DELETE_S=Se ha eliminado una denominaci\u00F3n.
GM_SALUTATION_DELETE_P=Se han eliminado %s denominaciones.
GM_SALUTATION_DELETE_N=No se han eliminado denominaciones.
GM_SALUTATION_INSERT_S=Se ha creado una denominaci\u00F3n.
GM_SALUTATION_INSERT_P=Se han creado %s denominaciones.
GM_SALUTATION_INSERT_N=No se han creado denominaciones.
GM_TASK_MODIFY_S=Se ha modificado una tarea.
GM_TASK_MODIFY_P=Se han modificado %s tareas.
GM_TASK_MODIFY_N=No se han modificado tareas.
GM_TASK_DELETE_S=Se ha eliminado una tarea.
GM_TASK_DELETE_P=Se han eliminado %s tareas.
GM_TASK_DELETE_N=No se han eliminado tareas.
GM_TASK_INSERT_S=Se ha creado una tarea.
GM_TASK_INSERT_P=Se han creado %s tareas.
GM_TASK_INSERT_N=No se han creado tareas.
GM_USER_MODIFY_S=Se ha modificado un usuario.
GM_USER_MODIFY_P=Se han modificado %s usuarios.
GM_USER_MODIFY_N=No se han modificado usuarios.
GM_USER_DELETE_S=Se ha eliminado un usuario.
GM_USER_DELETE_P=Se han eliminado %s usuarios.
GM_USER_DELETE_N=No se han eliminado usuarios.
GM_USER_INSERT_S=Se ha creado un usuario.
GM_USER_INSERT_P=Se han creado %s usuarios.
GM_USER_INSERT_N=No se han creado usuarios.
GM_WORKAREA_MODIFY_S=Se ha modificado una \u00E1rea de trabajo.
GM_WORKAREA_MODIFY_P=Se han modificado %s \u00E1reas de trabajo.
GM_WORKAREA_MODIFY_N=No se han modificado \u00E1reas de trabajo.
GM_WORKAREA_DELETE_S=Se ha eliminado una \u00E1rea de trabajo.
GM_WORKAREA_DELETE_P=Se han eliminado %s \u00E1reas de trabajo.
GM_WORKAREA_DELETE_N=No se han eliminado \u00E1reas de trabajo.
GM_WORKAREA_INSERT_S=Se ha creado una \u00E1rea de trabajo.
GM_WORKAREA_INSERT_P=Se han creado %s \u00E1reas de trabajo.
GM_WORKAREA_INSERT_N=No se han creado \u00E1reas de trabajo.

GM_PDF_TEMPLATE_MODIFY_S=Se ha modificado una plantilla.
GM_PDF_TEMPLATE_MODIFY_P=Se han modificado %s plantillas.
GM_MPDF_TEMPLATE_MODIFY_N=No se han modificado plantillas.
GM_MPDF_TEMPLATE_DELETE_S=Se ha eliminado una plantilla.
GM_PDF_TEMPLATE_DELETE_P=Se han eliminado %s plantillas.
GM_PDF_TEMPLATE_DELETE_N=No se han eliminado plantillas.
GM_PDF_TEMPLATE_INSERT_S=Se ha creado una nueva plantilla.
GM_PDF_TEMPLATE_INSERT_P=Se han creado %s plantillas.
GM_PDF_TEMPLATE_INSERT_N=No se han creado plantillas.

PDF_TEMPLATE_NOT_EMPTY_ERROR_MESSAGE=El nombre de la plantilla no debe estar vac\u00EDo
PDF_TEMPLATE_NO_FILE_ERROR_MESSAGE=Por favor, seleccione un archivo PDF
PDF_TEMPLATE_LIST_NOT_LOAD=Lista de plantillas PDF es vac\u00EDo
PDF_GENERATE_BUTTON=Generar PDF
PDF_GENERATE_LABEL=Exportaci\u00F3n a PDF

LOAD_MAILTEMPLATE_FAILED = Cargando plantilla de correo electr\u00F3nico no
SELECT_MAILTEMPLATE = Por favor, seleccione la plantilla de correo electr\u00F3nico

ADDRESS_ERROR = Su correo electr\u00F3nico ha sido enviado al distribuidor. Al minimos una direcci\u00F3n de correo electr\u00F3nico de este distribuidor es mal! El distribuidor no podr\u00EDa ser enviado a esta direcci\u00F3n de correo electr\u00F3nico. Por favor, compruebe y si es necesario correcta la siguiente direcci\u00F3n de correo electr\u00F3nico:  

LABELLING_MUST_NOT_BE_EMPTY:El t\u00EDtulo no debe estar vac\u00EDo

birthplace_a_e1=Lugar de nacimiento no debe contener m\u00E1s de 100 caracteres
birthplace_a_e2=Lugar de nacimiento no debe contener m\u00E1s de 100 caracteres
birthplace_a_e3=Lugar de nacimiento no debe contener m\u00E1s de 100 caracteres
city_a_e1=Ciudad no debe contener m\u00E1s de 300 caracteres
city_a_e2=Ciudad no debe contener m\u00E1s de 300 caracteres
city_a_e3=Ciudad no debe contener m\u00E1s de 300 caracteres
city_b_e1=Ciudad no debe contener m\u00E1s de 300 caracteres
city_b_e2=Ciudad no debe contener m\u00E1s de 300 caracteres
city_b_e3=Ciudad no debe contener m\u00E1s de 300 caracteres
city_c_e1=Ciudad no debe contener m\u00E1s de 300 caracteres
city_c_e2=Ciudad no debe contener m\u00E1s de 300 caracteres
city_c_e3=Ciudad no debe contener m\u00E1s de 300 caracteres
company_a_e1=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_a_e2=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_a_e3=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_b_e1=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_b_e2=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_b_e3=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_c_e1=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_c_e2=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
company_c_e3=Empresa/Instituci\u00F3n no debe contener m\u00E1s de 250 caracteres
country_a_e1=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_a_e2=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_a_e3=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_b_e1=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_b_e2=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_b_e3=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_c_e1=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_c_e2=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
country_c_e3=Pa\u00EDs no debe contener m\u00E1s de 100 caracteres
fax_a_e1=Fax no debe contener m\u00E1s de 100 caracteres
fax_a_e2=Fax no debe contener m\u00E1s de 100 caracteres
fax_a_e3=Fax no debe contener m\u00E1s de 100 caracteres
fax_b_e1=Fax no debe contener m\u00E1s de 100 caracteres
fax_b_e2=Fax no debe contener m\u00E1s de 100 caracteres
fax_b_e3=Fax no debe contener m\u00E1s de 100 caracteres
fax_c_e1=Fax no debe contener m\u00E1s de 100 caracteres
fax_c_e2=Fax no debe contener m\u00E1s de 100 caracteres
fax_c_e3=Fax no debe contener m\u00E1s de 100 caracteres
firstname_a_e1=Nombre no debe contener m\u00E1s de 100 caracteres
firstname_a_e2=Nombre no debe contener m\u00E1s de 100 caracteres
firstname_a_e3=Nombre no debe contener m\u00E1s de 100 caracteres
firstname_b_e1=Nombre no debe contener m\u00E1s de 100 caracteres
firstname_b_e2=Nombre no debe contener m\u00E1s de 100 caracteres
firstname_b_e3=Nombre no debe contener m\u00E1s de 100 caracteres
fon_a_e1=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_a_e2=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_a_e3=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_b_e1=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_b_e2=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_b_e3=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_c_e1=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_c_e2=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
fon_c_e3=Tel\u00E9fono no debe contener m\u00E1s de 100 caracteres
function_a_e1=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_a_e2=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_a_e3=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_b_e1=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_b_e2=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_b_e3=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_c_e1=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_c_e2=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
function_c_e3=Funci\u00F3 no debe contener m\u00E1s de 250 caracteres
languages_a_e1=Idiomas no debe contener m\u00E1s de 250 caracteres
languages_b_e1=Idiomas no debe contener m\u00E1s de 250 caracteres
lastname_a_e1=Apellido no debe contener m\u00E1s de 100 caracteres
lastname_a_e2=Apellido no debe contener m\u00E1s de 100 caracteres
lastname_a_e3=Apellido no debe contener m\u00E1s de 100 caracteres
lastname_b_e1=Apellido no debe contener m\u00E1s de 100 caracteres
lastname_b_e2=Apellido no debe contener m\u00E1s de 100 caracteres
lastname_b_e3=Apellido no debe contener m\u00E1s de 100 caracteres
mail_a_e1=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_a_e2=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_a_e3=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_b_e1=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_b_e2=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_b_e3=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_c_e1=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_c_e2=E-Mail no debe contener m\u00E1s de 250 caracteres
mail_c_e3=E-Mail no debe contener m\u00E1s de 250 caracteres
mobil_a_e1=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_a_e2=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_a_e3=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_b_e1=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_b_e2=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_b_e3=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_c_e1=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_c_e2=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
mobil_c_e3=M\u00F3vil no debe contener m\u00E1s de 100 caracteres
nationality_a_e1=Nacionalidad no debe contener m\u00E1s de 100 caracteres
nationality_b_e1=Nacionalidad no debe contener m\u00E1s de 100 caracteres
note_a_e1=El comentario no debe tener m\u00E1s de 2000 caracteres.
note_b_e1=El comentario no debe tener m\u00E1s de 2000 caracteres.
notehost_a_e1=Aviso para el anfitri\u00F3n no puede contener m\u00E1s de 2000 caracteres.
notehost_b_e1=Aviso para el anfitri\u00F3n no puede contener m\u00E1s de 2000 caracteres.
noteorga_a_e1=Aviso para organizaci\u00F3n no puede contener m\u00E1s de 2000 caracteres.
noteorga_b_e1=Aviso para organizaci\u00F3n no puede contener m\u00E1s de 2000 caracteres.
pobox_a_e1=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_a_e2=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_a_e3=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_b_e1=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_b_e2=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_b_e3=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_c_e1=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_c_e2=Apartado de correos no debe contener m\u00E1s de 50 caracteres
pobox_c_e3=Apartado de correos no debe contener m\u00E1s de 50 caracteres
poboxzipcode_a_e1=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_a_e2=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_a_e3=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_b_e1=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_b_e2=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_b_e3=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_c_e1=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_c_e2=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
poboxzipcode_c_e3=C\u00F3digo postal para POB no debe contener m\u00E1s de 50 caracteres
state_a_e1=Provincia no debe contener m\u00E1s de 100 caracteres
state_a_e2=Provincia no debe contener m\u00E1s de 100 caracteres
state_a_e3=Provincia no debe contener m\u00E1s de 100 caracteres
state_b_e1=Provincia no debe contener m\u00E1s de 100 caracteres
state_b_e2=Provincia no debe contener m\u00E1s de 100 caracteres
state_b_e3=Provincia no debe contener m\u00E1s de 100 caracteres
state_c_e1=Provincia no debe contener m\u00E1s de 100 caracteres
state_c_e2=Provincia no debe contener m\u00E1s de 100 caracteres
state_c_e3=Provincia no debe contener m\u00E1s de 100 caracteres
street_a_e1=Calle no debe contener m\u00E1s de 100 caracteres
street_a_e2=Calle no debe contener m\u00E1s de 100 caracteres
street_a_e3=Calle no debe contener m\u00E1s de 100 caracteres
street_b_e1=Calle no debe contener m\u00E1s de 100 caracteres
street_b_e2=Calle no debe contener m\u00E1s de 100 caracteres
street_b_e3=Calle no debe contener m\u00E1s de 100 caracteres
street_c_e1=Calle no debe contener m\u00E1s de 100 caracteres
street_c_e2=Calle no debe contener m\u00E1s de 100 caracteres
street_c_e3=Calle no debe contener m\u00E1s de 100 caracteres
suffix1_a_e1=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_a_e2=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_a_e3=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_b_e1=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_b_e2=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_b_e3=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_c_e1=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_c_e2=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix1_c_e3=Direcci\u00F3n adocional 1 no debe contener m\u00E1s de 100 caracteres
suffix2_a_e1=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_a_e2=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_a_e3=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_b_e1=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_b_e2=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_b_e3=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_c_e1=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_c_e2=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
suffix2_c_e3=Direcci\u00F3n adocional 2 no debe contener m\u00E1s de 100 caracteres
title_a_e1=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
title_a_e2=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
title_a_e3=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
title_b_e1=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
title_b_e2=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
title_b_e3=T\u00EDtulo acad\u00E9mico no debe contener m\u00E1s de 250 caracteres
url_a_e1=WWW no debe contener m\u00E1s de 250 caracteres
url_a_e2=WWW no debe contener m\u00E1s de 250 caracteres
url_a_e3=WWW no debe contener m\u00E1s de 250 caracteres
url_b_e1=WWW no debe contener m\u00E1s de 250 caracteres
url_b_e2=WWW no debe contener m\u00E1s de 250 caracteres
url_b_e3=WWW no debe contener m\u00E1s de 250 caracteres
url_c_e1=WWW no debe contener m\u00E1s de 250 caracteres
url_c_e2=WWW no debe contener m\u00E1s de 250 caracteres
url_c_e3=WWW no debe contener m\u00E1s de 250 caracteres
zipcode_a_e1=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_a_e2=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_a_e3=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_b_e1=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_b_e2=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_b_e3=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_c_e1=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_c_e2=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
zipcode_c_e3=C\u00F3digo Postal no debe contener m\u00E1s de 250 caracteres
internal_id=ID interno no debe contener m\u00E1s de 45 caracteres.
INTERNAL_ID=ID interno


# ALTERNATIVE SALUTATIONS
SALUTATION_EDITABLE_TEXT=Puedes ingresar un saludo alternativo para este PDF aqu\u00ED
SALUTATION_TO_SALUTATION=voluntad
SALUTATION_ERROR_LOAD=Error durante la carga
SALUTATION_ERROR_EMPTY=Saludos alternativos no deben estar vac\u00EDos
SALUTATION_ERROR_SAVE=Error al guardar
SALUTATION_ERROR_DELETE=Error al suprimir
SALUTATION_ERROR_LENGTH=Saludos alternativos no debe contener m\u00E1s de 100 caracteres
