#!/bin/sh
# DJB Daemontools startup script for VerA.web Online-Anmeldung

cd "$(dirname "$0")"
exec >&2
date -u +'INFO  [%F %T,000] starting up VWOA' >>/var/log/vwoa.log
sleep 3
exec java -Dfile.encoding=UTF-8 -Djava.awt.headless=true \
    -Djava.security.egd=file:/dev/./urandom -Xmx128m \
    -jar vwoa.jar server config.json
