language=Deutsch
language_short=de

# BROWSER TAB-TITLE
BROWSER_TITLE_CATEGORY=Kategorien
BROWSER_TITLE_CLEANUP=Cleanup
BROWSER_TITLE_COLOURS=Farben
BROWSER_TITLE_GENERAL_CONFIGS=Allgemeine Einstellungen
BROWSER_TITLE_TASKS=Aufgaben
BROWSER_TITLE_DOCUMENT_TYPES=Dokumenttypen
BROWSER_TITLE_IMPORT_DUPLICATE_ACCEPT=Importstatus\u200A\u2014\u200ADubletten \u00FCbernehmen
BROWSER_TITLE_ERROR_OCCURS=Ein Fehler ist aufgetreten
BROWSER_TITLE_EVENT_EDIT=Veranstaltung bearbeiten
BROWSER_TITLE_EVENT_CREATE=Neue Veranstaltung erstellen
BROWSER_TITLE_EVENT_SELECT=Veranstaltung ausw\u00E4hlen
BROWSER_TITLE_PERSON_ASSIGN=Person zuordnen
BROWSER_TITLE_EVENT_SEARCH=Veranstaltung suchen
BROWSER_TITLE_TASKS_EDIT=Aufgabe bearbeiten
BROWSER_TITLE_TASKS_CREATE=Neue Aufgabe erstellen
BROWSER_TITLE_EXPORT_PERSONDATA=Export von Personendaten
BROWSER_TITLE_IMPORT_PERSONDATA=Import von Personendaten
BROWSER_TITLE_EVENT_GUESTLIST=G\u00E4steliste f\u00FCr Veranstaltung
BROWSER_TITLE_EVENT_EXPORT_DATA=Steuerdatei erzeugen f\u00FCr Veranstaltung
BROWSER_TITLE_IMPORT_STATUS=Status des Importvorgangs
BROWSER_TITLE_HELP=Hilfe
BROWSER_TITLE_INFO_VERAWEB=Info \u00FCber VerA.web
BROWSER_TITLE_EVENT_LOCATION_EDIT=Veranstaltungsort bearbeiten
BROWSER_TITLE_EVENT_LOCATION_CREATE=Neuen Veranstaltungsort eingeben
BROWSER_TITLE_EVENT_LOCATION=Veranstaltungsorte
BROWSER_TITLE_EMAIL_SUBMISSION_CREATE=Neue E-Mail-Vorlage anlegen
BROWSER_TITLE_EMAIL_SUBMISSION_EDIT=E-Mail-Vorlage bearbeiten
BROWSER_TITLE_EMAIL_SUBMISSION=E-Mail-Vorlagen
BROWSER_TITLE_PDF_TEMPLATE=PDF-Vorlagen
BROWSER_TITLE_DISTRIBUTOR_CREATE=Verteiler erstellen
BROWSER_TITLE_DISTRIBUTOR_LIST=Verteilerliste
BROWSER_TITLE_EMAIL_WRITE_DISTRIBUTOR=E-Mail an Verteiler schreiben
BROWSER_TITLE_EMAIL_EDIT=E-Mail bearbeiten
BROWSER_TITLE_EMAIL_CREATE=Neue E-Mail anlegen
BROWSER_TITLE_EMAIL_OUTBOX=E-Mail-Postausgang
BROWSER_TITLE_ROLE_WITH=mit der Rolle
BROWSER_TITLE_ROLE_AVAILABLE=mit verf\u00FCgbaren Rollen
BROWSER_TITLE_ROLE_WITHOUT_INFO=ohne Rolleninformationen
BROWSER_TITLE_SUCCESSFUL_LOGIN_ONE=Sie wurden erfolgreich
BROWSER_TITLE_SUCCESSFUL_LOGIN_TWO=am System angemeldet
BROWSER_TITLE_PERSON_EDIT=Person bearbeiten
BROWSER_TITLE_PERSON_CREATE=Neue Person anlegen
BROWSER_TITLE_GUEST_ADD_EVENT=Gast hinzuf\u00FCgen zu
BROWSER_TITLE_GUEST_HOST_ADD_EVENT=Gastgeber ausw\u00E4hlen f\u00FCr
BROWSER_TITLE_GUEST_SELECT=Gast ausw\u00E4hlen
BROWSER_TITLE_GUEST_HOST_SELECT=Gastgeber ausw\u00E4hlen
BROWSER_TITLE_SEARCH_REPLACE_PERSONDATA=Suchen und Ersetzen in Personendaten
BROWSER_TITLE_DUPLICATE_SEARCH=Dublettensuche
BROWSER_TITLE_TASK_ADD_RESPONSIBLE=Verantwortlichen f\u00FCr Aufgabe ausw\u00E4hlen
BROWSER_TITLE_PERSON_DELETE=Person l\u00F6schen
BROWSER_TITLE_PERSON_LIST=Personen\u00FCbersicht
BROWSER_TITLE_SEARCH_REPLACE=Suchen und Ersetzen
BROWSER_TITLE_GUEST_HOST_SEARCH=Gastgeber suchen
BROWSER_TITLE_PERSON_SEARCH=Person suchen
BROWSER_TITLE_PERSON_DATA_SALUTATION=Stammdaten\u200A\u2014\u200AAnreden
BROWSER_TITLE_LOGIN_REPRESENTATIVE=Anmelden als Stellvertreter
BROWSER_TITLE_STATISTIC_CREATE=Statistik erstellen
BROWSER_TITLE_USER_CONFIGS=Benutzer Einstellungen
BROWSER_TITLE_WORK_AREAS=Arbeitsbereiche
BROWSER_TITLE_OVERVIEW_EVENTS_YEAR=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Jahr
BROWSER_TITLE_OVERVIEW_EVENTS_MONTH=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Monat
BROWSER_TITLE_OVERVIEW_GUEST_HOST_EVENTS=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastgebers
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST_HOST=Gesamt\u00FCbersicht \u00FCber alle Veranstaltungen, gruppiert nach Gastgeber
BROWSER_TITLE_OVERVIEW_GUEST_EVENTS=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastes
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST=Gesamt\u00FCbersicht \u00FCber alle Veranstaltungen, gruppiert nach G\u00E4sten
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_PLACE=\u00DCbersicht \u00FCber alle Veranstaltungen sortiert nach Veranstaltungsort
BROWSER_TITLE_OVERVIEW_EVENTS_UNKNOWN_STATISTIC=UNBEKANNTE STATISTIK

# YOU MUST SET THESE PLACEHOLDERS WITH THE GENDER TYPE OF YOUR LANGUAGE FOR EACH OBJECT AS MALE OR FEMALE
GENDER_TYPE_CATEGORY=Female
GENDER_TYPE_CLIENT=Male
GENDER_TYPE_COLOR=Female
GENDER_TYPE_DELEGATION_FIELD=Female
GENDER_TYPE_DISTRIBUTOR=Male
GENDER_TYPE_DOCUMENT_TYPE=Male
GENDER_TYPE_EMAIL=Female
GENDER_TYPE_EVENT=Female
GENDER_TYPE_EVENT_LOCATION=Male
GENDER_TYPE_FUNCTION_OFFICIAL_TITLE=Female
GENDER_TYPE_GUEST=Male
GENDER_TYPE_MAIL_DRAFT=Female
GENDER_TYPE_PDF_TEMPLATE=Female
GENDER_TYPE_PERSON=Female
GENDER_TYPE_REPRESENTATIVE=Female
GENDER_TYPE_SALUTATION=Female
GENDER_TYPE_TASK=Female
GENDER_TYPE_USER=Male
GENDER_TYPE_WORKAREA=Male

# REPETITIVE OBJECTS IN THER SINGULAR- AND PLURAL-TYPE
GENERIC_ADDRESS_DATA_PLURAL=Adressdaten
GENERIC_CATEGORY_SINGULAR=Kategorie
GENERIC_KEYWORDS=Schl\u00FCsselw\u00F6rter
GENERIC_CATEGORY_PLURAL=Kategorien
GENERIC_CLIENT_SINGULAR=Mandant
GENERIC_CLIENT_PLURAL=Mandanten
GENERIC_COLOR_SINGULAR=Farbe
GENERIC_COLOR_PLURAL=Farben
GENERIC_COMPANY_SINGULAR=Firma
GENERIC_COMPANY_PLURAL=Firmen
GENERIC_DELEGATION_FIELD_SINGULAR=Zusatzfeld
GENERIC_DELEGATION_FIELD_PLURAL=Zusatzfelder
GENERIC_DISTRIBUTOR_SINGULAR=Verteiler
GENERIC_DISTRIBUTOR_PLURAL=Verteiler
GENERIC_EMAIL_SINGULAR=E-Mail
GENERIC_EMAIL_PLURAL=E-Mails
GENERIC_EVENT_SINGULAR=Veranstaltung
GENERIC_EVENT_PLURAL=Veranstaltungen
GENERIC_EVENT_LOCATION_SINGULAR=Veranstaltungsort
GENERIC_EVENT_LOCATION_PLURAL=Veranstaltungsorte
GENERIC_FUNCTION_SINGULAR=Funktion
GENERIC_FUNCTION_PLURAL=Funktionen
GENERIC_GUEST_SINGULAR=Gast
GENERIC_GUEST_PLURAL=G\u00E4ste
GENERIC_GUEST_NONE=Keine G\u00E4ste
GENERIC_INSTITUTION_SINGULAR=Institution
GENERIC_INSTITUTION_PLURAL=Institutionen
GENERIC_MAIL_DRAFT_SINGULAR=Vorlage
GENERIC_MAIL_DRAFT_PLURAL=Vorlagen
GENERIC_PDF_TEMPLATE_SINGULAR=PDF-Vorlage
GENERIC_PDF_TEMPLATE_PLURAL=PDF-Vorlagen
GENERIC_PDF_TEMPLATE_S_P=PDF-Vorlage(n)
GENERIC_PDF_FILE=PDF-Datei
GENERIC_OFFICIAL_TITLE_SINGULAR=Amtsbezeichnung
GENERIC_OFFICIAL_TITLE_PLURAL=Amtsbezeichnungen
GENERIC_PERSON_SINGULAR=Person
GENERIC_PERSON_PLURAL=Personen
GENERIC_REPRESENTATIVE_SINGULAR=Vertretung
GENERIC_REPRESENTATIVE_PLURAL=Vertretungen
GENERIC_SALUTATION_SINGULAR=Anrede
GENERIC_SALUTATION_PLURAL=Anreden
GENERIC_STATUS_OPEN=Offen
GENERIC_STATUS_ACCEPT=Zusage
GENERIC_STATUS_DECLINE=Absage
GENERIC_STATUS_PARTICIPATED=Teilgenommen
GENERIC_TASK_SINGULAR=Aufgabe
GENERIC_TASK_PLURAL=Aufgaben
GENERIC_USER_SINGULAR=Benutzer
GENERIC_USER_PLURAL=Benutzer
GENERIC_WORKAREA_SINGULAR=Arbeitsbereich
GENERIC_WORKAREA_PLURAL=Arbeitsbereiche
GENERIC_SELECT_ALL=Alle markieren

# HEADER MESSAGES
HEADER_REPRESENTATION_FOR=In Vertretung f\u00FCr
HEADER_COUNT_INSERT_ZERO_PART_ONE=Es wurde
HEADER_COUNT_INSERT_ONE_PART_ONE=Es wurde
HEADER_COUNT_INSERT_ELSE_PART_ONE=Es wurden
HEADER_COUNT_INSERT_ZERO_PART_TWO=angelegt
HEADER_COUNT_INSERT_ONE_PART_TWO=angelegt
HEADER_COUNT_INSERT_ELSE_PART_TWO=angelegt
HEADER_COUNT_REMOVE_ZERO_PART_ONE=Es wurde
HEADER_COUNT_REMOVE_ONE_PART_ONE=Es wurde
HEADER_COUNT_REMOVE_ELSE_PART_ONE=Es wurden
HEADER_COUNT_REMOVE_ZERO_PART_TWO=gel\u00F6scht
HEADER_COUNT_REMOVE_ONE_PART_TWO=gel\u00F6scht
HEADER_COUNT_REMOVE_ELSE_PART_TWO=gel\u00F6scht
HEADER_COUNT_UPDATE_ZERO_PART_ONE=Es wurde
HEADER_COUNT_UPDATE_ONE_PART_ONE=Es wurde
HEADER_COUNT_UPDATE_ELSE_PART_ONE=Es wurden
HEADER_COUNT_UPDATE_ZERO_PART_TWO=ge\u00E4ndert
HEADER_COUNT_UPDATE_ONE_PART_TWO=ge\u00E4ndert
HEADER_COUNT_UPDATE_ELSE_PART_TWO=ge\u00E4ndert
HEADER_ELEMENT_FEMALE_NO=keine
HEADER_ELEMENT_FEMALE_ONE=eine
HEADER_ELEMENT_FEMALE_NEW=neue
HEADER_ELEMENT_MALE_NO=kein
HEADER_ELEMENT_MALE_ONE=ein
HEADER_ELEMENT_MALE_NEW=neuer
HEADER_ELEMENT_NO_RECORD_SINGULAR=kein Datensatz
HEADER_ELEMENT_NO_NEW_RECORD_SINGULAR=kein neuer Datensatz
HEADER_ELEMENT_ONE_RECORD_SINGULAR=ein Datensatz
HEADER_ELEMENT_ONE_NEW_RECORD_SINGULAR=ein neuer Datensatz
HEADER_ELEMENT_PLURAL=Datens\u00E4tze
HEADER_ELEMENT_NEW_PLURAL=neue Datens\u00E4tze

# FIXES
GENERIC_EDIT=Bearbeiten
GENERIC_OFFICIAL_TITLE_SHORT=Amtsbez
LETTER_COMMERCIAL=(G)
GENERIC_WRITE_EMAIL=E-mail schreiben
GENERIC_SEARCH_FOR_PERSON=Person suchen
GENERIC_CHOOSE_ROLE=Rolle w\u00E4hlen
GENERIC_EVENT=Veranstaltung
GENERIC_EVENTS=Veranstaltungen
SHOW_ALL_RECORDS=Alle Datens\u00E4tze anzeigen lassen
SHOW_RECORDS_1=
SHOW_RECORDS_2=Datens\u00E4tze anzeigen lassen
GENERIC_NO_WORKAREA_TEXT=Kein

# GENERALLY USED
GENERIC_EMAIL_ADDRESS=E-Mail-Adresse
GENERIC_FROM=Von
GENERIC_LANGUAGE=Sprache
GENERIC_LOGOUT=Abmelden
GENERIC_ON=Auf
GENERIC_ON_LOWERCASE=auf
GENERIC_PAGE=Seite
GENERIC_PAGES=Seiten
GENERIC_PLACE=Platz
GENERIC_ALTERNATIVE=Alternative

# MENU
MENU_PERSONS=Personen
MENU_EVENTS=Veranstaltungen
MENU_MANAGEMENT=Verwaltung
MENU_ADMINISTRATION=Administration

# ANMELDUNG
LOGIN_ERROR=Es ist ein Fehler bei der Anmeldung aufgetreten. Bitte \u00FCberprufen Sie Ihren Benutzernamen und Ihr Passwort.
GENERIC_PASSWORD=Passwort
LOGIN_REPRESENTATION=In Vertretung anmelden
GENERIC_ACCOUNT=Benutzerkürzel
GENERIC_LOGIN=Anmelden
GENERIC_CLEAR_FIELDS=Felder leeren
HINT_LOGIN_ORGANISATION_ONE=Bitte verwenden Sie Ihr Organisationskennzeichen oder
HINT_LOGIN_ORGANISATION_TWO=vorname.nachname
HINT_LOGIN_ORGANISATION_THREE=als Benutzernamen

# WELCOME SITE: FIRST PAGE AFTER LOGIN
administration=Administration
bittewaehlensieeineamtsbezeichnungfunktionaus=Bitte w\u00E4hlen Sie eine Amtsbezeichnung / Funktion aus
eskannzuunerwartetenfehlernkommenbittewendensiesichanihrenadministrator=Es kann zu unerwarteten Fehlern kommen. Bitte wenden Sie sich an Ihren Administrator.
willkommenbeiveraweb=Willkommen bei VerA.web
WELCOME_TEXT_GRANT_READ_STANDARD_FIELDS=Sie haben hier die M\u00F6glichkeit, Stammdaten von Personen und Veranstaltungen anzuzeigen und zu exportieren.
WELCOME_TEXT_GRANT_READ_REMARK_FIELDS=Sie haben hier die M\u00F6glichkeit, Stammdaten von und Bemerkungen zu Personen und Veranstaltungen anzuzeigen und zu exportieren.
WELCOME_TEXT_GRANT_EXPORT_PART_ONE=Sie haben hier die M\u00F6glichkeit, Stammdaten von
WELCOME_TEXT_GRANT_WRITE_FULL=und Bemerkungen zu
WELCOME_TEXT_GRANT_EXPORT_PART_TWO=Personen und Veranstaltungen anzuzeigen, zu ex\u2011 und importieren, zu bearbeiten und zu l\u00F6schen.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_ONE=Sie haben hier die M\u00F6glichkeit, Stammdaten von und Bemerkungen zu Personen und Veranstaltungen anzuzeigen, zu ex\u2011 und importieren, zu bearbeiten und zu l\u00F6schen.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_TWO=Weiterhin k\u00F6nnen Sie mandantenspezifische Einstellungen einsehen und bearbeiten.
WELCOME_TEXT_GRANT_ADMIN_PART_ONE=Sie haben hier die M\u00F6glichkeit, Stammdaten von und Bemerkungen zu Personen und Veranstaltungen anzuzeigen, zu ex\u2011 und importieren, zu bearbeiten und zu l\u00F6schen.
WELCOME_TEXT_GRANT_ADMIN_PART_TWO=Weiterhin k\u00F6nnen Sie mandantenspezifische und globale Einstellungen einsehen und bearbeiten.
WELCOME_TEXT_HELP=Sollten Sie weitere Informationen ben\u00F6tigen, finden Sie diese auf der Seite \u201EHilfe\u201C.
WELCOME_TEXT_NO_ROLE=Zu Ihrer Anmeldung existieren keine Rollen, unter denen Sie in VerA.web agieren k\u00F6nnen. Bitte melden Sie sich ab und mit einer Benutzer\u2011 oder Rollenkennung erneut an, die in VerA.web nutzbar ist.
GENERIC_AVAILABLE_DUPLICATES=Vorhandene Dubletten

# ADMINISTRATION/ANREDEN
GENERIC_SALUTATIONS=Anreden
GENERIC_SALUTATIONS_MARKED=Markierte Anrede(n)
GENERIC_ID=ID
GENERIC_MAIN_FORM=Stammform
GENERIC_GENDER=Geschlecht
GENERIC_GENDER_FEMALE=Weiblich
GENERIC_GENDER_MALE=M\u00E4nnlich
GENERIC_PAGING=Direkteinsprung
MESSAGE_SUCCESS_INSERT_SALUTATION=Es wurde eine neue Anrede angelegt
QUESTION_DELETE=Wirklich L\u00F6schen?
GENERIC_NEW_PLURAL=neue
GENERIC_YES=Ja
GENERIC_NO=Nein
MESSAGE_SUCCESS_DELETE_SALUTATION=Es wurde eine Anrede gel\u00F6scht
MESSAGE_EXIST_MASTER_DATA_ENTRY=Es existiert bereits ein Stammdaten-Eintrag unter dem Namen
GENERIC_NAME=Name
GENERIC_NEW=Neu

# ADMINISTRATION/ARBEITSBEREICHE
GENERIC_WORK_FIELDS=Arbeitsbereiche
GENERIC_WORK_FIELDS_MARKED=Markierte(n) Arbeitsbereich(e)
MESSAGE_MISSING_DATA=Es wurden keine Daten gefunden
MESSAGE_INSERT_WORK_FIELD=Es wurde ein neuer Arbeitsbereich angelegt
MESSAGE_FAIL_DELETE_WORK_FIELD=Es wurde kein Arbeitsbereich gel\u00F6scht
MESSAGE_SUCCESS_DELETE_WORK_FIELD=Es wurde ein Arbeitsbereich gel\u00F6scht

# ADMINISTRATION/BENUTZER
GENERIC_USER=Benutzer
GENERIC_USER_MARKED=Markierte(n) Benutzer
GENERIC_USERNAME=Benutzername
GENERIC_USER_RIGHTS=Benutzerrechte
MESSAGE_SUCCESS_INSERT_USER=Es wurde ein neuer Benutzer angelegt
MESSAGE_SUCCESS_DELETE_USER=Es wurde ein Benutzer gel\u00F6scht
MESSAGE_FILL_USER_ROLE=Sie m\u00FCssen eine Benutzerrollenbezeichnung eingeben

# ADMINISTRATION/DOKUMENTTYPEN
GENERIC_TOOLTIP=Hinweis
HINT_FORMAT_INFO=OOo 1.1 steht f\u00FCr OpenOffice 1.1 (sxc-Datei) und OOo 2.0 f\u00FCr OpenOffice 2.0 (ods-Datei), xls steht f\u00FCr Microsoft Office Kennzeichen: Kennz. 50 und 99 werden autom. neuen Veranstaltungen hinzugef\u00FCgt. Beim Kennz. 50 wird kein Freitextfeld erzeugt. (xls-Datei) und CSV steht f\u00FCr CSV-Dateiformat.
HINT_EVENT_MARK=Kennz. 50 und 99 werden autom. neuen Veranstaltungen hinzugef\u00FCgt. Beim Kennz. 50 wird kein Freitextfeld erzeugt.
GENERIC_DOCUMENT_TYPES_MARKED=Markierte(n) Dokumenttyp(en)
GENERIC_LABELLING=Bezeichnung
GENERIC_ADRESS_TYPE=Adress-Typ
GENERIC_CHARSET=Zeichensatz
GENERIC_FORMAT=Format
GENERIC_PARTNER_DOCUMENT=Dokument f\u00FCr Partner
GENERIC_SORT=Sortier.
GENERIC_SIGN=Kennz.
GENERIC_GA=GA
GENERIC_SD=SD
GENERIC_BUSINESS=Gesch\u00E4ftlich
GENERIC_PRIVATE=Privat
GENERIC_MORE=Weitere
GENERIC_LATIN=Latein
kyrillisch=Kyrillisch
chinesisch=Chinesisch
eswurdeeindokumenttypgeloscht=Es wurde ein Dokumenttyp gel\u00F6scht.
eswurdeeinneuerdokumenttypangelegt=Es wurde ein neuer Dokumenttyp angelegt.

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Status
GENERIC_TO=An
GENERIC_SUBJECT=Betreff
GENERIC_ERROR=Fehler
e-mails=E-Mails
GENERIC_BLEND_IN_TECHNICAL_ERROR_MESSAGE=Technische Fehlermeldung einblenden
GENERIC_ERROR_DESCRIPTION=Fehlerbeschreibung

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=E-Mail-Vorlagen
GENERIC_MARKED_TEMPLATES_PP=Markierte Vorlage(n)
GENERIC_INSERT_NEW_TEMPLATES=Neue Vorlage anlegen
GENERIC_TEMPLATE_NAME=Name der Vorlage
eswurdeeineneuevorlageangelegt=Es wurde eine neue Vorlage angelegt.
GENERIC_TEXT=Text
GENERIC_PLACEHOLDER=Platzhalter
GENERIC_ADD=Hinzuf\u00FCgen
GENERIC_BACK_TO_TEMPLATES_LIST=Zur\u00FCck zur Vorlagenliste

# ADMINISTRATION/FARBEN
GENERIC_CHROMATICITY=Farbwert
LETTERS_CHROMATICITY=R G B

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=Markierte Bezeichnung(en)
eswurdeeineneuefunktion/amtsbezeichnungangelegt=Es wurde eine neue Funktion/Amtsbezeichnung angelegt.
eswurdeeinefunktion/amtsbezeichnunggeloscht=Es wurde eine Funktion/Amtsbezeichnung gel\u00F6scht.

# ADMINISTRATION/KATEGORIEN
markiertekategorie=Markierte Kategorie(n)
GENERIC_MARK_LONG=Kennzeichen
GENERIC_RANK=Rang
GENERIC_EVENTS_PP=Veranstaltung(en)
GENERIC_OCCASION=Ereignis

# ADMINISTRATION/MANDANTEN
markierte(n)mandanten=Markierte(n) Mandanten
GENERIC_DATA_NOT_ASSIGNED_TO_CLIENTS=Nicht Mandanten zugeordnete Daten
personen=Personen
GENERIC_IMPORT_PROCEDURES=Import Vorg\u00E4nge
veranstaltungorte=Veranstaltungorte
GENERIC_ASSIGN_CLIENTS=Mandanten zuordnen

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=Programeinstellungen
GENERIC_STANDARD_TABULATOR_CHOICE=Standard Auswahl von Tabulatoren
GENERIC_MAIN_TABS=Haupttabs
GENERIC_PERSONS_DATA=Personendaten
GENERIC_MAILING_ADDRESSES=Anschriften
GENERIC_SUBTABS_OF_PERSONS_DATA=Subtabs von \u201EPersonendaten\u201C
GENERIC_MAIN_PERSON=Hauptperson
GENERIC_PARTNER=Partner
GENERIC_SUBTABS_OF_MAILING_ADDRESSES=Subtabs von \u201EAnschriften\u201C
GENERIC_STANDARD_CHOICE_OF_SELECTED_BOX=Standard Auswahl der Selectbox \u201EZeichensatz\u201C
GENERIC_STANDARD_SALUTATIONS_AND_FREE_TEXT_FIELDS=Standard-Anreden und Freitextfelder
GENERIC_STANDARD_SALUTATION=Standard-Anrede
GENERIC_STANDARD_SALUTATION_PARTNER=Standard-Anrede Partner
GENERIC_FREE_TEXT_FIELD=Freitextfeld
GENERIC_FREE_TEXT_FIELD_CONNECTOR=Freitextfeld-Verbinder
GENERIC_SHOW=Anzeige
GENERIC_HELP=Hilfe
GENERIC_HELP_LINK=Hilfe-Link
GENERIC_HELP_WINDOW=Hilfe-Fenster
OPTION_HELP_WINDOW_1=Aktuelles Browser-Fenster verwenden
OPTION_HELP_WINDOW_2=Pro Aufruf ein neues Browser-Fenster \u00F6ffnen
OPTION_HELP_WINDOW_3=Bei jedem Aufruf das selbe Browser-Fenster (nicht das aktuelle)
GENERIC_MISCELLANEOUS=Sonstiges
GENERIC_PROTOCOL_TIME_CHANGE=\u00C4nderungsprotokoll
GENERIC_PROTOCOL_COMMISIONING_TIME=Vorhaltezeit der Protokolldaten
HINT_GIVE_THE_RETENTION_PERIOD=Geben Sie die Aufbewahrungsfrist ein
GENERIC_YEARS=Jahre
GENERIC_MONTHS=Monate
GENERIC_DAYS=Tage
GENERIC_MAILING_ADDRESS_BUSINESS=Anschrift Gesch\u00E4ftlich
GENERIC_MAILING_ADDRESS_PRIVATE=Anschrift Privat
GENERIC_MAILING_ADDRESS_OTHERS=Anschrift Weitere
GENERIC_LABELLING_LATIN=Zeichensatz Latein
GENERIC_LABELLING_ALTERNATIVE=Zeichensatz Alternative
GENERIC_ADDRESS_ADDITIONAL=Adresszusatz

# ADMINISTRATION/REPORTS
GENERIC_REPORTS=Reports
MESSAGE_WAITING_MESSAGE_LOG_REPORT=Abh\u00E4ngig vom ausgew\u00E4hlten Zeitraum und der daraus resultierenden Anzahl von Daten, kann die Erzeugung des Berichts relativ lange dauern. Haben Sie bitte ein wenig Geduld.
GENERIC_DATE_BEGIN=Datum Beginn
GENERIC_DATE_END=Datum Ende
GENERIC_BACKUP_FIEDS=Felder zur\u00FCcksetzen
GENERIC_GENERATE_REPORT=Report erzeugen

# ADMINISTRATION/STELLVERTRETUNGEN
GENERIC_REPRESENTATIVES=Stellvertretungen
GENERIC_AVAILABILITY_FILTER=G\u00FCltigkeitsfilter
GENERIC_REPRESENTATIVES_ALL=Alle Vertretungen
GENERIC_NO_REPRESENTATION_EXPIRED=Keine abgelaufenen Vertretungen
GENERIC_ONLY_CURRENT_REPRESENTATIONS=Nur aktuelle Vertretungen
GENERIC_ROLE=Rolle
GENERIC_REPRESENTATIVE=Vertreter
gultigab=G\u00FCltig ab
GENERIC_VALID_TILL=G\u00FCltig bis
GENERIC_NO_DATA_FOUND=Keine Daten gefunden

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Markierte(n) Veranstaltungsort(e)
GENERIC_ADD_NEW_EVENT_LOCATIONS=Neuen Veranstaltungsort hinzuf\u00FCgen
GENERIC_CONTACT_PERSON=Ansprechpartner
GENERIC_TELEFON=Telefon
GENERIC_FAX=Fax
e-mail=E-Mail
GENERIC_REMARK=Bemerkung
GENERIC_URL=URL
gps-daten=GPS-Daten
GENERIC_ROOM_NUMBER=Raumnummer
EVENT_PLACES_CONFIRM_DELETE=Bitte best\u00E4tigen Sie das L\u00F6schen von Veranstaltungsorten

# VERWALTUNG/EINSTELLUNGEN
GENERIC_MANAGEMENT=Verwaltung
GENERIC_OPTIONS=Einstellungen
GENERIC_SUBTABS_OF=Subtabs von
GENERIC_PERSONAL_DETAILED_VIEW=Personendetailansicht
GENERIC_LIST_OF_GUESTS=G\u00E4steliste
zusatzlichefelder=Zus\u00E4tzliche Felder
GENERIC_POSTNUMBER_AND_CITY=PLZ / Ort
GENERIC_LIST_OF_PERSONS=Personenliste
GENERIC_FEDERAL_STATE=Bundesland
MESSAGE_OPTIONS_WERE_SUCCESSFULLY_SAVED=Einstellungen wurden erfolgreich gespeichert.

# VERWALTUNG/VERTRETUNGEN
markiertevertretung=Markierte Vertretung(en)
GENERIC_DELETE=L\u00F6schen
eswurdeeineneuevertretungangelegt=Es wurde eine neue Vertretung angelegt
eswurdeeinevertretunggeloscht=Es wurde eine Vertretung gel\u00E4scht
siemuseneinevertretereingeben=Sie m\u00FCssen eine Vertreter eingeben
derbeginndervertretungmusvordemendeliegen=Der Beginn der Vertretung muss vor dem Ende liegen
MESSAGE_REPORT_NUMBER_PART_1=Es wurden
vertretungengeloscht=Vertretungen gel\u00E4scht
# VERWALTUNG/INFO
GENERIC_INFO=Info
GENERIC_INFORMATION_ABOUT_VERAWEB=Informationen zu VerA.web
veraweb=VerA.web
GENERIC_VERSION=Version
build=Build
GENERIC_BUILD_TIME=Buildzeit (GMT)
GENERIC_REST_API=REST-API
INFO_LIC_LIC=Lizenz
INFO_LIC_INFOS=Nutzungsbedingungen
INFO_LIC_DOCS=weitere Dokumente
INFO_VWOR_MANDATORY=Anmerkung: ein Betrieb ohne die REST-API ist nicht mehr zul\u00E4ssig.
GENERIC_DATABASE=Datenbank
GENERIC_GROUPS=Gruppen
GENERIC_NOT_AVAILABLE=Nicht verf\u00FCgbar

# ALLGEMEIN
GENERIC_YOU_ARE_HERE=Sie sind hier
GENERIC_HOME=Home
GENERIC_DISCARD_CHANGES=Bearbeitung verwerfen?

# TABELLEN
GENERIC_DATE=Datum
GENERIC_LASTNAME=Nachname
GENERIC_FIRSTNAME=Vorname
GENERIC_INTERNAL_ID=Interne ID
amtsbezeichnung=Amtsbezeichnung
GENERIC_COMPANY_INSTITUTION=Firma / Institution
GENERIC_STREET=Stra\u00DFe
GENERIC_POST_NUMBER=PLZ
GENERIC_CITY=Ort
GENERIC_MARKED_PERSONS_PP=Markierte Person(en)
expotieren=Expotieren
GENERIC_ASSIGN_CATEGORIES=Kategorien zuordnen
GENERIC_REMOVE_CATEGORIES=Kategorien entfernen
GENERIC_ASSING_WORKAREA=Arbeitsbereich zuordnen
GENERIC_REMOVE_WORKAREA=Arbeitsbereich entfernen
GENERIC_EXECUTE=Durchf\u00FChren
personenanzahlproseite=Personen | Anzahl pro Seite
GENERIC_ALL=Alle
seite=Seite
GENERIC_DATE_OF_BIRTH=Geburtsdatum
GENERIC_PLACE_OF_BIRTH=Geburtsort
GENERIC_NATIONALITY_CITIZENSHIP=Nationalit\u00E4t/Staatsangeh\u00F6rigkeit
GENERIC_LANGUAGES=Sprachen
GENERIC_HINT_FOR_HOST=Hinweis f\u00FCr Gastgeber
GENERIC_ACCOUNT_OPENING_DATE=Akkreditierungsdatum
GENERIC_AT=um
GENERIC_OCLOCK=Uhr
GENERIC_ORIGIN_DATA=Datenherkunft

# DATEITYP
csv=CSV (Comma-Separated-Values)
x-manage-csv=X-Manage-CSV (X-Manage Kontakte)
csvpersdatanschrift=CSVPersdat+Anschrift (Comma-Separated-Values)
csvpersdat=CSVPersdat (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Kategorien (Comma-Separated-Values)

# PERSONEN/PERSONENUEBERSICHT
GENERIC_PERSON_SUMMARY=Personen\u00FCbersicht
GENERIC_SEARCH_PERSONS=Personen suchen
GENERIC_CREATE_PERSON=Neue Person anlegen
GENERIC_PERSONS_DELETED=Personen gel\u00F6scht

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
GENERIC_EDIT_PERSON=Person bearbeiten
GENERIC_DOCUMENTED_ON=Erfasst am
GENERIC_LAST_EDITED_ON=Zuletzt ge\u00E4ndert am
GENERIC_PERSONS_ID=Personen-ID
GENERIC_OA=Online-Anmeldung
GENERIC_OA_USERNAME=Online-Anmeldung Benutzername
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=Zu dieser Person wurde das entsprechende Vorschaufeld noch nicht erzeugt.
GENERIC_COPY_PERSON=Person kopieren
GENERIC_CREATE_TAG=Etikett erzeugen
GENERIC_ASSIGN_TO_EVENT=Einer Veranstaltung zuordnen
GENERIC_DELETE_PERSON=Person l\u00F6schen
GENERIC_STATISTIC=Statistik
ausstammdatenhinzufugen=Aus Stammdaten hinzuf\u00FCgen

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
GENERIC_GENERATE_ALL=Alle erzeugen

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
GENERIC_CATEGORIES_AND_OCCASIONS=Kategorien und Ereignisse

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=\u00FCbersicht \u00FCber alle Veranstaltungen eines Gastes.
GENERIC_VIEW_OVER_GUEST_EVENT=Ab
statistikfurgast=Statistik f\u00FCr Gast
GENERIC_BEGIN=Beginn

# PERSONEN/PERSONENSUCHE
GENERIC_SEARCH_PERSON=Personensuche
GENERIC_SEARCH=Suche
GENERIC_VALIDITY_DATE=G\u00FCltigkeitsdatum
GENERIC_ADVANCED_SEARCH=Erweiterte Suche
HINT_PLACEHOLDER=Hinweis Sie k\u00E4nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen. Die Suche erfolgt im Vornamen, Nachnamen, Ort, PLZ, Stra\u00DFe, Firma/Institution, Telefon, Fax, Mobil, E-Mail, Bemerkungen, Kategorien, Arbeitsbereiche und Amtsbezeichnung/Funktion.

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=Die Anmeldedaten wurden erfolgreich erzeugt.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Anmeldedaten f\u00FCr diese Person sind bereits vorhanden.

# PERSONEN/NEUE PERSON ANLEGEN
GENERIC_IS_COMPANY=Ist Firma
frau=Frau
herr=Herr
lady=Lady
sir=Sir
GENERIC_PLEASE_CHOOSE=Bitte w\u00E4hlen Sie
GENERIC_ACAD_TITLE=Akad. Titel
GENERIC_IN_COUNTRY=Inland
GENERIC_HINT_FOR_ORGA=Hinweis f\u00FCr Orga
GENERIC_COUNTRY=Land
plz/postfach=PLZ / Postfach
GENERIC_POST_OFFICE_BOX=Postfach
iban=IBAN
bic=BIC
GENERIC_MOBILE=Mobil
LETTERS_WWW=WWW
dublettenprufungdurchfuhren=Dublettenpr\u00FCfung durchf\u00FChren
zurpersonenubersicht=Zur Personen\u00FCbersicht

# PERSONEN/SUCHEN UND ERSETZEN IN PERSONENDATEN
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=Hinweis Wenn Sie den Platzhalter * verwenden, werden auch Teilst\u00FCcke ersetzt, sonst nur vollst\u00E4ndige Datenfelder.
GENERIC_SEARCH_V=Suchen
GENERIC_REPLACE=Ersetzen
GENERIC_IN_THE_FOLLOWING_FIELDS=In folgenden Feldern
anrede/titel=Anrede / Titel
GENERIC_EMPLOYMENT_TITLE_SHORT=Amtsbezeichn.
GENERIC_ADDRESSES=Adresse
telefon/fax=Telefon / Fax
GENERIC_REPLACE_INDIVIDUALLY=Einzeln ersetzen
GENERIC_REPLACE_ALL=Alle ersetzen

# PERSONEN/DUBLETTENSUCHE
GENERIC_DUPLICATE_SEARCH=Dublettensuche

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Export von Personendaten
HINT_EXPORT_MANDANT_PERSON=Sie exportieren mit dieser Funktion ausschlie\u00DFlich Personen aus Ihrem aktuellen Mandanten.
GENERIC_WITHOUT=Ohne
botschaften=Botschaften
finanzamtsprecher=Finanzamtsprecher
journalisten=Journalisten
lieferant=Lieferant
nogs=NOGs
politik=Politik
pressevertreter=Pressevertreter
wirtschaft=Wirtschaft
GENERIC_EXPORT=Export
EXPORT_AS_CSV=G\u00E4steliste komplett
EXPORT_AS_CSV_SHORT=G\u00E4steliste Kurzform
GENERIC_START_EXPORT=Export starten
ENCODING_TYPE_CYRILLIC=Kyrillisch
ENCODING_TYPE_WEST=Westlich
ENCODING_TYPE_BALTIC=Baltisch
ENCODING_TYPE_EAST=\u00D6stlich
ENCODING_TYPE_TURKISH=T\u00FCrkisch
EXPORT_DATA_TYPE_CSV=CSV (Comma-Separated-Values)
EXPORT_DATA_TYPE_X_MANAGE_CSV=X-Manage-CSV (X-Manage Kontakte)
EXPORT_DATA_TYPE_CSVPERSDATA_ADDRESS=CSVPersdat+Anschrift (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA=CSVPersdat (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_CATEGORY=CSVPersdat+Kategorien (Comma-Separated-Values)
EXPORT_TITLE_CSV=CSV
EXPORT_TITLE_X_MANAGE_CSV=X-Manage-CSV
EXPORT_TITLE_CSVPERSDATA_ADDRESS=CSV Personendaten+Anschriften
EXPORT_TITLE_CSVPERSDATA=CSV Personendaten
EXPORT_TITLE_CSVPERSDATA_CATEGORY=CSV Personendaten+Kategorien
HINT_EXPORT_CSV=Je nach Menge der exportierten Felder (insbesondere ist dies von der Anzahl exportierter Kategorien abh\u00E4ngig) kann es passieren, dass MS Excel und OO Calc die exportierten Daten nicht vollst\u00E4ndig lesen k\u00F6nnen.
HINT_EXPORT_CSVPERSDATA_ADDRESS=Es werden nur die Felder aus den Karteireitern \u201EPersonendaten\u201C, \u201EAnschriften\u201C und deren untergeordneten Karteireitern exportiert. Je nach Menge der exportierten Felder kann es passieren, dass MS Excel und OO Calc die exportierten Daten nicht vollst\u00E4ndig lesen k\u00F6nnen.
HINT_EXPORT_CSVPERSDATA=Es werden nur die Felder aus dem Karteireiter \u201EPersonendaten\u201C und den untergeordneten Karteireitern exportiert. Je nach Menge der exportierten Felder kann es passieren, dass MS Excel und OO Calc die exportierten Daten nicht vollst\u00E4ndig lesen k\u00F6nnen.
HINT_EXPORT_CSVPERSDATA_CATEGORY=Es werden nur die Felder aus den Karteireitern \u201EPersonendaten\u201C, \u201EKategorien\u201C und deren untergeordneten Karteireitern exportiert. Je nach Menge der exportierten Felder (insbesondere ist dies von der Anzahl exportierter Kategorien abh\u00E4ngig) kann es passieren, dass MS Excel und OO Calc die exportierten Daten nicht vollst\u00E4ndig lesen k\u00F6nnen.
SELECTION_CSV=Alle makieren

# PERSONEN/IMPORT VON PERSONENDATEN
GENERIC_IMPORT_FROM_PERSONS_DATA=Import von Personendaten
HINT_IMPORT_SHORT_CONTENT=Hinweis Beim Import k\u00E4nnen Feldinhalte, die l\u00E4nger als bei VerA.web vorgesehen sind, gek\u00FCrzt \u00FCbernommen werden.
GENERIC_TARGET_CLIENT=Zielmandant
GENERIC_IMPORT_DATA=Import-Datei
GENERIC_DATA_TYPE=Dateityp
GENERIC_FILE_ENCODING=Kodierung der Datei
GENERIC_AUTO_ENCODING=Unicode oder Windows \u201EWesteuropa\u201C cp1252 (automatische Erkennung)
dateiauswahlen=Datei ausw\u00E4hlen
keineausgewahlt=Keine ausgew\u00E4hlt
GENERIC_START_IMPORT=Import starten

# PERSONENDROPDOWN
GENERIC_NEW_PERSON=Neue Person
GENERIC_EXPORT_PERSONS=Personenexport
GENERIC_IMPORT_PERSONS=Personenimport

# VERANSTALTUNGENDROPDOWN
GENERIC_EVENT_VIEW=Veranstaltungs\u00FCbersicht
veranstaltunguuche=Veranstaltungssuche
GENERIC_NEW_EVENT=Neue Veranstaltung
GENERIC_STATISTICS=Statistiken

# ADMINISTRATIONDROPDOWN
e-mail-postausgang=E-Mail-Postausgang
GENERIC_PROGRAM_PERFERENCES=Programmeinstellungen

# VERANSTALTUNGSUEBERSICHT
GENERIC_END=Ende
GENERIC_HOST=Gastgeber
GENERIC_EVENT_SEARCH=Veranstaltung suchen
GENERIC_CREATE_NEW_EVENT=Neue Veranstaltung anlegen
GENERIC_NUMBER_PER_PAGE=Anzahl pro Seite
seitexvony=Seite x von y

# EVENT HEADER
EVENT_ID=Veranstaltungs-ID
EVENT_NAME=Veranstaltungsname
EVENT_URL=Veranstaltungs-URL
EVENT_URL_MEDIA_REPRESENTATIVE=URL f\u00FCr Pressevertreter
EVENT_MAX_GUEST=Maximal Anzahl G\u00E4ste
EVENT_MAX_RESERVE=Maximal Anzahl Warteliste
EVENT_INVITATION_TYPE=Einladungsart
EVENT_INVITATION_TYPE_WITHOUT_PARTNER=Ohne Partner
EVENT_INVITATION_TYPE_ONLY_PARTNER=Nur Partner
EVENT_INVITATION_TYPE_WITH_PARTNER=Mit Partner

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
GENERIC_EDIT_EVENT=Veranstaltung bearbeiten
GENERIC_TO_GUEST_MANAGEMENT=Zur G\u00E4steverwaltung
GENERIC_GENERAL=Allgemein
GENERIC_ADDITIONAL_PERSONS_DATA=Zus\u00E4tzliche Personendaten
kurzbereichnung=Kurzbereichnung
GENERIC_OPEN_EVENT=Offene Veranstaltung
umxuhr=Um x uhr
veranstalgungsort=Veranstalgungsort
GENERIC_SEARCH_FOR_HOST=Gastgeber suchen
GENERIC_DELETE_HOST=Gastgeber entfernen
GENERIC_HOST_PARTNER=Gastgeber-Partner
GENERIC_LOGIN_REQUIRED=Login notwendig
GENERIC_SUBSCRIPTION_OF_PRESS_REPRESENTATIVES_POSSIBLE=Anmeldung von Pressevertretern m\u00F6glich
GENERIC_SAVE_EVENT=Veranstaltung speichern
GENERIC_TO_EVENT_VIEW=Zur Veranstaltungs\u00FCbersicht

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPES_MARKED_DELETE=Markierte(n) Dokumenttyp(en) entfernen
GENERIC_REMOVE=Entfernen
GENERIC_ADD_NEW_DOCUMENT_TYPE=Neuen Dokumenttyp hinzuf\u00FCgen
xvonydokumenttypen=x von y Dokumenttypen

# VERANSTALTUNG BEARBEITEN/AUFGABEN
GENERIC_ADD_NEW_TASK=Neue Aufgabe anlegen
MESSAGE_NO_TASKS_FOR_THIS_EVENT=Es liegen keine Aufgaben f\u00FCr diese Veranstaltung vor
GENERIC_SELECTED_ENTRIES=Ausgew\u00E4hlte Eintr\u00E4ge
GENERIC_TITLE=Titel
GENERIC_RESPONSIBLE=Verantwortlicher

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
GENERIC_TASKS_ID=Aufgaben-ID
GENERIC_COMPLETION=Fertigstellung
GENERIC_PRIORITY=Priorit\u00E4t
GENERIC_DESCRIPTION=Beschreibung
GENERIC_ADD_RESPONSIBLES=Verantwortlichen hinzuf\u00FCgen
verantwortlichenentfernen=Verantwortlichen entfernen
GENERIC_SAVE_TASK=Aufgabe Speichern
GENERIC_BACK_TO_TASKS_VIEW=Zur\u00FCck zur Aufgaben\u00FCbersicht

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
GENERIC_ADD_NEW_EMPLOYMENT_TITLE=Neue Amtsbezeichnung Hinzuf\u00FCgen
MESSAGE_NO_EMPLOYMENT_TITLES_FOUND=Es wurden keine Amtsbezeichnungen gefunden.

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
GENERIC_ADD_NEW_KATEGORIES=Neue Kategorie hinzuf\u00FCgen

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
GENERIC_PRECONDITION_PLURAL=Vorbedingungen
EVENT_PRECONDITION_MARKED=Markierte Vorbendingung(en)
EVENT_PRECONDITION_ADD=Vorbedingung hinzuf\u00FCgen
EVENT_PRECONDITION_INVITATIONSTATUS=Teilnahmestatus
EVENT_PRECONDITION_STARTDATE=Startdatum
EVENT_PRECONDITION_NOT_FOUND=Es wurden keine Vorbedingungen gefunden

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Nur in zuk\u00FCnftigen Veranstaltungen suchen
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere das ? f\u00FCr einzelne

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=Mit Partner
eswurdeeineneueveranstaltungangelegt=Es wurde eine neue Veranstaltung angelegt.

# VERTEILER
angelegtvon=Angelegt von
angelegtam=Angelegt am
erzeugtausveranstaltung=Erzeugt aus Veranstaltung

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=Statistik auf folgenden Zeitrahmen einschr\u00E4nken
statistiktypauswahlen=Statistiktyp ausw\u00E4hlen
zeitrahmenbeginn=Zeitrahmen-beginn
zeitrahmenende=Zeitrahmen-ende
STATISTIC_RADIO_PER_YEAR=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Jahr
STATISTIC_RADIO_PER_MONTH=Gesamt\u00FCbersicht \u00FCber die Anzahl der Veranstaltungen pro Monat
STATISTIC_RADIO_GROUPED_BY_HOST=Gesamt\u00FCbersicht \u00FCber alle Veranstaltungen, gruppiert nach Gastgeber
STATISTIC_RADIO_PER_HOST=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastgebers (mit Suche)
STATISTIC_RADIO_PER_GUEST=\u00DCbersicht \u00FCber alle Veranstaltungen eines Gastes (mit Suche)
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=\u00DCbersicht \u00FCber alle Veranstaltungen sortiert nach Veranstaltungsort
statistikerstellen=Statistik erstellen

# GAESTEVERWALTUNG DER VERANSTALTUNG
gasteverwaltungderveranstaltung=G\u00E4steverwaltung der Veranstaltung
maxanzahlgaste=Max. Anzahl G\u00E4ste
gastedetails=G\u00E4stedetails
offen=Offen
zusagen=Zusagen
absagen=Absagen
teilnahmen=Teilnahmen
aufplatz=Auf Platz
aufreserve=Auf Reserve
filter=Filter
platzwahl=Platzwahl
lfdnr=Lfd.-NR.
nichteingeladen=Nicht eingeladen
laufendenummerberechnen=Laufende Nummer berechnen
allestammdatenneuladen=Alle Stammdaten neu laden
HINT_ENTRY_POINT=Direkteinsprung: ist nur bei einer Sortierung nach Name, Vorname oder E-Mail m\u00F6glich.
HINT_GUEST_MANAGEMENT_FILTER=Beim Erstellen von G\u00E4stelisten wird Ihr oben ausgew\u00E4hlter Filter ber\u00FCcksichtigt.
HINT_GUEST_MANAGEMENT_MARKED=Wenn Sie einzelne G\u00E4ste markieren, werden nur diese exportiert, ansonsten die vollst\u00E4ndige Liste.
TABLE_BEFORE_GUEST=Vorheriger Gast
TABLE_FIRST_GUEST=Erster Gast
TABLE_LAST_GUEST=Letzter Gast
TABLE_NEXT_GUEST=N\u00E4chster Gast

# GAESTELISTE
GUEST_LIST_ALL_GUEST=Alle G\u00E4ste
GUEST_LIST_ALL_GUEST_ON_PLACE=Alle G\u00E4ste auf Platz
GUEST_LIST_ALL_GUEST_ON_RESERVE=Alle G\u00E4ste auf Reserve
GUEST_LIST_APPLY_GUEST_FROM_EVENT=G\u00E4ste aus Veranstaltung \u00FCbernehmen
GUEST_LIST_CATEGORY_ASSIGN=Kategorien zuordnen
GUEST_LIST_CATEGORY_REMOVE=Kategorien entfernen
GUEST_LIST_DISTRIBUTOR_CREATE=Verteiler erstellen
GUEST_LIST_CONFIRM_ACTION=Bitte best\u00E4tigen Sie die folgende Aktion
GUEST_LIST_DIDNT_CHANGE=Die G\u00E4steliste wurde nicht ver\u00E4ndert
GUEST_LIST_EXPAND_ONE=Die G\u00E4steliste wurde um einen Gast erweitert
GUEST_LIST_EXPAND_MULTIPLE_PART_ONE=Die G\u00E4steliste wurde um
GUEST_LIST_EXPAND_MULTIPLE_PART_TWO=G\u00E4ste erweitert
GUEST_LIST_HINT_EXPORT_GUEST=Wenn Sie einzelne G\u00E4ste markieren, werden nur diese exportiert, ansonsten die vollst\u00E4ndige Liste
GUEST_LIST_HINT_FILTER=Beim Erstellen von G\u00E4stelisten wird Ihr oben ausgew\u00E4hlter Filter ber\u00FCcksichtigt
GUEST_LIST_HINT_RED_PERSON=Rot hinterlegte Personen wurden bereits als \u201Ezu l\u00F6schen\u201C markiert
GUEST_LIST_CREATED_NO_PERSON=wurde ohne Personen angelegt
GUEST_LIST_CREATED_ONE_PERSON=wurde mit einer Person angelegt
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_ONE=wurde mit
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_TWO=Personen angelegt
GUEST_LIST_NO_GUEST_INVITED=Es wurden noch keine G\u00E4ste eingeladen oder Ihre Filterung ergibt keine Treffer
GUEST_LIST_NUMBER_CALCULATE=Laufende Nummer berechnen
GUEST_LIST_NUMBER_CALCULATED_SAVED=Die \u201ELaufende Nummer\u201C wurde f\u00FCr alle G\u00E4ste neu berechnet und gespeichert
GUEST_LIST_ONLY_OPEN=nur Offene
GUEST_LIST_ONLY_ACCEPT=nur Zusagen
GUEST_LIST_ONLY_DECLINED=nur Absagen
GUEST_LIST_ONLY_PARTICIPATE=nur Teilnahmen
GUEST_LIST_PERSON_DATA_RELOAD=Alle Stammdaten neu laden
GUEST_LIST_RESERVE=R
GUEST_LIST_SEARCH_PERSON_ADD=Personen suchen und zu der G\u00E4steliste hinzuf\u00FCgen

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=G\u00E4steliste erstellen
SELECT_OUTPUT_FORMAT=Ausgabeformat w\u00E4hlen
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Partner
LIST_GROUP_BY_CATEGORY_WITH_TEL=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Tel. und Mobiltelefon
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Partner und Fax
LIST_SORT_PARTNER_TEL=Liste nach Sortierung\u200A\u2014\u200Amit Partner, Tel. und Mobiltelefon
SORT_CRITERIA=Sortierkriterien
SORT_AFTER=Sortieren nach
CONTINUAL_NUMBER=Laufende Nummer
anschliesendnach=Anschlie\u00DFend nach
zusatzlichesortierungnach=Zus\u00E4tzliche sortierung nach

# GASTDETAILS
GUEST_DETAIL_HINT_GUEST_HOST=Hinweis Gastgeber
GUEST_DETAIL_HINT_ORGANISATION_TEAM=Hinweis Orgateam
GUEST_DETAIL_INVITATION_STATUS=Status der Einladung
GUEST_DETAIL_SEAT_NUMBER=Platz-Nummer
GUEST_DETAIL_TABLE_NUMBER=Tisch-Nummer
gastdetails=Gastdetails
HINT_GUEST_LIST_EDIT_PERSONDATA=Sie bearbeiten hier ausschlie\u00DFlich Personendaten im Rahmen der aktuellen Veranstaltung, keine grundlegenden Stammdaten.
istgastgeber=Ist Gastgeber
reserve=Reserve
aufstammdatenzurucksetzen=Auf Stammdaten zur\u00FCcksetzen
stammdatenbearbeiten=Stammdaten bearbeiten

# DOKUMENTTYPEN
dokumenttypwahlen=Dokumenttyp w\u00E4hlen
mitgliedsausweis=Mitgliedsausweis
etikett=Etikett
tischkarte=Tischkarte
adresstypundzeichensatzwahlen=Adresstyp und Zeichensatz w\u00E4hlen
adresstyp=Adresstyp
datenbearbeiten=Daten bearbeiten
verbinder=Verbinder
freitextfeldpartner=Freitextfeld (Partner)
akatitel=Aka. Titel (Partner)
kontaktdaten=Kontaktdaten
strase=Stra\u00DFe
postfachplz=Postfach PLZ
nummer=Nummer
zuruckzudenveranstaltungsdetails=Zur\u00FCck zu den Veranstaltungsdetails

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Dokumenttyp bearbeiten
dokument-id=Dokument-ID
dokument-name=Dokument-Name
dokumenttypspeichern=Dokumenttyp speichern
zuruckzurdokumenttypenliste=Zur\u00FCck zur Dokumenttypenliste
anmeldedatenerzeugen=Anmeldedaten erzeugen
esliegenkeinekategorienundereignissevor=Es liegen keine Kategorien und Ereignisse vor
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=Bei gr\u00FCn hinterlegten Eintr\u00E4gen handelt es sich um wiederkehrende Ereignisse.

# VERTEILERDETAILS
verteilerdetails=Verteilerdetails
verteilerversenden=Verteiler versenden
e-mail-clientaufrufen=E-Mail-Client aufrufen
mailclient_other=Anderer Mailclient
mailclient_msoutlook=Microsoft Outlook
verteilerverschickt=Der Verteiler wurde erfolgreich verschickt
verteilerfehler=Der Verteiler konnte nicht erfolgreich verschickt werden, versuchen sie es sp\u00E4ter noch einmal.

# FEHLEND
zurstartseite=Zur Startseite
solldieneuekategorie=Soll die neue Kategorie
einsortiertwerden=einsortiert werden?
pflichtfelder=Pflichtfelder
markiertekategorien=Markierte Kategorie(n)
markiertekategorienloschen=Markierte Kategorien l\u00F6schen
alledemarkieren=Alle markieren
furalleveranstaltungen=F\u00FCr alle Veranstaltungen
speichern=Speichern
anderungsprotokollfurdenzeitraum=\u00C4nderungsprotokoll f\u00FCr den Zeitraum
objekt=Objekt
objektid=Objekt-Id
artderanderung=Art der \u00C4nderung
geandertefelder=Ge\u00E4nderte Felder
datumauswahlen=Datum ausw\u00E4hlen
folgendeaktionen=Folgende Aktionen
wurden=WURDEN
durchgefuhrt=durchgef\u00FChrt
konnen=K\u00D6NNEN
aktuallisieren=Aktuallisieren
cleanupjetztunwiderruflichdurchfuhren=Cleanup jetzt unwiderruflich durchf\u00FChren.
essindderzeitkeinecleanupsmoglichnotig=Es sind derzeit keine Cleanups m\u00F6glich / n\u00F6tig.
nochkeineauswahlgetroffen=Noch keine Auswahl getroffen
oberflachenbeschriftungen=Oberfl\u00E4chenbeschriftungen
zusatzfelder=Zusatzfelder
eswurdeeinzusatzfeld=Es wurde ein Zusatzfeld
angelegt=angelegt
geandert=ge\u00E4ndert
geloscht=gel\u00F6scht
feldbezeichnung=Feldbezeichnung
eingabetyp=Eingabetyp
erfolgreichgespeichert=Erfolgreich gespeichert!
markiertendokumenttypen=Markierte(r) Dokumenttyp(en)
eigenesdokumentfurpartner=Eigenes Dokument f\u00FCr Partner
sortierreihenfolge=Sortierreihenfolge
gastgebermitausgeben=Gastgeber mit Ausgeben
iststandardfursteuerdatei=Ist Standard f\u00FCr Steuerdatei
format=Format
HINT_EXPORT_FORMAT=OOo 1.1 steht f\u00FCr OpenOffice 1.1 (sxc-Datei) und OOo 2.0 f\u00FCr OpenOffice 2.0 (ods-Datei),xls steht f\u00FCr Microsoft Office (xls-Datei) und CSV steht f\u00FCr CSV-Dateiformat.
HINT_EVENT_IDENTIFICATION=Kennz. 50 und 99 werden autom. neuen Veranstaltungen hinzugef\u00FCgt. Beim Kennz. 50 wird kein Freitextfeld erzeugt.
wirklichloschen=Wirklich l\u00F6schen
zumpersonenimport=Zum Personen-Import
importstatus=Importstatus
importstatusvorhandenedublettenbearbeiten=Importstatus: vorhandene Dubletten bearbeiten
bittemarkierensiediezuimportierendenpersonen=Bitte markieren Sie die zu importierenden Personen.
dublettendiedurchden=Dubletten, die durch den
importhinzugefugtwerdenwurden=Import hinzugef\u00FCgt werden w\u00FCrden
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=, sind mit einer Checkbox gekennzeichnet.Darunter befinden sich die bereits im System vorhandenen, entsprechenden Datens\u00E4tze.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=Um eine Dublette in den Import zu integrieren, m\u00FCssen Sie sie \u00FCbernehmen.
alsdubletteubernehmen=Als Dublette \u00FCbernehmen
markiertepersonenalsdubletteubernehmen=Markierte Person(en) als Dublette \u00FCbernehmen
anzahlzuspeicherndedubletten=Anzahl zu speichernde Dubletten
eswurdenkeineeintragegefunden=Es wurden keine Eintr\u00E4ge gefunden.
zuruckzumpersonenimport=Zur\u00FCck zum Personenimport
fehlermeldung=Fehlermeldung
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=Bei der Bearbeitung Ihrer Anfrage ist ein Fehler aufgetreten.Bitte melden Sie dies Ihrem Administrator.
unbekannterfehler=Unbekannter Fehler.
markiertenkategorien=Markierte(n) Kategorie(n)
markiertenkategorienentfernen=Markierte(n) Kategorie(n) entfernen
bitteauswahlen=Bitte ausw\u00E4hlen
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=Die Veranstaltung, an der Sie gerade gearbeitet haben, wurde von einem anderen Anwender gel\u00F6scht.Sie k\u00F6nnen nun eine neue Veranstaltung anlegen oder anderweitig mit VerA.web arbeiten.
bittebestatigensiedasspeicherndieserveranstaltung=Bitte best\u00E4tigen Sie das Speichern dieser Veranstaltung
keingastgeberausgewahlt=Kein Gastgeber ausgew\u00E4hlt
kurzbezeichnung=Kurzbezeichnung
maximalelangederwarteliste=Maximale L\u00E4nge der Warteliste
sollendiestammdatenumdiesenorterweitertwerden=Sollen die Stammdaten um diesen Ort erweitert werden
markiertendokumenttypenentfernen=Markierte(r) Dokumenttyp(en) entfernen
eswurdenkeinedokumenttypengefunden=Es wurden keine Dokumenttypen gefunden.
markiertenamtsbezeichnungen=Markierte(n) Amtsbezeichnung(en)
markiertenamtsbezeichnungenentfernen=Markierte(n) Amtsbezeichnung(en) entfernen
zurveranstaltungssuche=Zur Veranstaltungssuche
veranstaltungssuche=Veranstaltungssuche
suchergebnis=Suchergebnis
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=Bitte klicken Sie eine der aufgelisteten Veranstaltungen an, um die G\u00E4ste zu \u00FCbernehmen.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=Bitte klicken Sie eine der aufgelisteten Veranstaltungen an, um die Person dieser Veranstaltung zuzuordnen.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=Bitte klicken Sie eine der aufgelisteten Personen an um diese als Gastgeber zu \u00FCbernehmen.
loschenvonveranstaltungenistnichtmoglich=L\u00F6schen von Veranstaltungen ist nicht m\u00F6glich
weiteremeldungen=weitere Meldungen.
bittebestatigensiedasloschendermarkiertenveranstaltungen=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Veranstaltungen!
markierteveranstaltungloschen=Markierte Veranstaltung l\u00F6schen
abbrechen=Abbrechen
markierteveranstaltungen=Markierte Veranstaltung(en)
markierteveranstaltungenloschen=Markierte Veranstaltungen l\u00F6schen
zuruckzurgasteverwaltung=Zur\u00FCck zur G\u00E4steverwaltung
zuruckzurgasteliste=Zur\u00FCck zur G\u00E4steliste
zuruckzurveranstaltungsdetails=Zur\u00FCck zur Veranstaltungsdetails
zuruckzurveranstaltungsstatistiken=Zur\u00FCck zur Veranstaltungsstatistiken
zuruckzurveranstaltungsaufgabe=Zur\u00FCck zur Veranstaltungsaufgabe
zuruckzurpersonensuche=Zur\u00FCck zur Personensuche
zuruckzusuchenundersetzen=Zur\u00FCck zu Suchen und Ersetzen
zuruckzurveranstaltungssuche=Zur\u00FCck zur Veranstaltungssuche
wahlensiebittezunachsteineodermehrereveranstaltungenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Veranstaltungen aus.
nurinzuunftigenveranstaltungensuchen=Nur in zuk\u00FCnftigen Veranstaltungen suchen
zuruck=Zur\u00FCck
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen.
bittebestatigensiedasspeicherndieseraufgabe=Bitte best\u00E4tigen Sie das Speichern dieser Aufgabe
verantworlichenhinzufugen=Verantworlichen hinzuf\u00FCgen
verantworlichenentfernen=Verantworlichen entfernen
loschenvonaufgabenistnichtmoglich=L\u00F6schen von Aufgaben ist nicht m\u00F6glich
bittebestatigensiedasloschenvonaufgaben=Bitte best\u00E4tigen Sie das L\u00F6schen von Aufgaben
ausgewahlteeintrageloschen=Ausgew\u00E4hlte Eintr\u00E4ge l\u00F6schen
start=Start
zursuche=Zur Suche
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=Sie sind als \u201EVoll-Administrator\u201C angemeldet und exportieren hiermit Mandanten\u00FCbergreifend.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=Sie exportieren mit dieser Funktion ausschlie\u00DFlich Personen aus Ihrem aktuellen Mandanten.
event=Veranstaltung
keine=Keine
category=Kategorie
weitereoptionen=Weitere Optionen
anmerkung=Anmerkung
anmerkungen=Anmerkungen
markiertebezeichnunge=Markierte Bezeichnung(en)
markierteeintrageentfernen=Markierte Eintr\u00E4ge entfernen
eswurdenkeinedatengefunden=Es wurden keine Daten gefunden
siehabenkeinedatenherkunftangegeben=Sie haben keine Datenherkunft angegeben.
HINT_IMPORT_NOT_POSSIBLE_OPENOFFICE=Sie haben versucht, eine OpenOffice-Datei zu importieren. Der direkte Import ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_IMPORT_NOT_POSSIBLE_STAROFFICE=Sie haben versucht, eine StarOffice-Datei zu importieren. Der direkte Import ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_IMPORT_NOT_POSSIBLE_EXCEL=Sie haben versucht, eine Microsoft Excel-Datei zu importieren. Der direkte Import von Excel-Dokumenten ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.Bitte speichern Sie diese Datei zuerst mit Ihrem Tabellenkalkulationsprogramm als .csv-Datei ab.
HINT_IMPORT_NOT_POSSIBLE_PDF=Sie haben versucht, eine PDF-Datei zu importieren. Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
HINT_IMPORT_NOT_POSSIBLE_ZIP=Sie haben versucht, eine ZIP-Datei zu importieren. Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
HINT_IMPORT_NOT_POSSIBLE_EXE=Sie haben versucht, eine EXE-Datei zu importieren. Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
siehabenversuchteinedateimitderendung=Sie haben versucht, eine Datei mit der Endung
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=zu importieren. Dies ist in der aktuellen Version von VerA.web leider nicht m\u00F6glich.
siehabenkeinedateiausgewahltoderdiesewarleer=Sie haben keine Datei ausgew\u00E4hlt oder diese war leer.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=Es ist ein unerwarteter Fehler beim importieren einer Datei aufgetreten.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Vermutlich befindet sich die Import-Datei nicht im vom System erwartem Format.
detailsanzeigen=Details anzeigen
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=Beim Import k\u00F6nnen Feldinhalte, die l\u00E4nger als bei VerA.web vorgesehen sind, gek\u00FCrzt \u00FCbernommen werden.

umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=Um Dubletten speicherbar zu machen, m\u00FCssen sie zun\u00E4chst im Bereich \u201Evorhandene Dubletten\u201C \u00FCbernommen werden.
HINT_UMLAUT_COMPARISON=Beachten Sie, dass \u00E4 mit ae, \u00F6 mit oe, \u00FC mit ue und \u00DF mit ss verglichen wird.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=Der Import ist erst beendet, wenn der Button \u201EImport abschlie\u00DFen\u201C geklickt wurde.
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=Der Import kann erst abgeschlossen werden, wenn speicherbare Datens\u00E4tze vorhanden sind.
vorhandenedubletten=Vorhandene Dubletten
vorhandenedublettenbearbeiten=Vorhandene Dubletten bearbeiten
zuimportierendedatensatzeinsgesamt=Zu importierende Datens\u00E4tze insgesamt
davondubletten=Davon Dubletten
davonspeicherbar=Davon speicherbar
ignoriertefehlerdatensatze=Ignorierte Fehlerdatens\u00E4tze
importabschlieszen=Import abschlie\u00DFen
siehabenkeinendatensatzimportiert=Sie haben keinen Datensatz importiert.
siehabeneinendatensatzimportiert=Sie haben einen Datensatz importiert.
siehaben=Sie haben
datensatzeimportiert=Datens\u00E4tze importiert.
nichtgewahlt=Nicht gew\u00E4hlt
verfugbarerollen=Verf\u00FCgbare Rollen
passowrt=Passwort
inverteretunganmelden=In Vertretung anmelden
vornamenachname=Vorname.Nachname
alsbenutzernamen=Als Benutzernamen
emailvorlage=E-Mail Vorlage
amtsbezfunktion=Amtsbez./Funktion
postfachnummer=Postfach Nummer
email=E-Mail
verteileranlegen=Verteiler anlegen
sielegeneinenneuenverteilerausderpersonensuche=Sie legen einen neuen Verteiler aus der Personensuche
sielegeneinenneuenverteilerausderveranstaltung=Sie legen einen neuen Verteiler aus der Veranstaltung
mit=mit
einerperson=einer Person
sielegeneinenneuenverteiler_rest_an=an
verteilername=Verteilername
verteilerspeichern=Verteiler speichern
markierteadressen=Markierte Adresse(n)
markierteadressenausdemverteilerloschen=Markierte Adresse(n) loschen
analleadressenversenden=An alle Adressen versenden
emailclientaufrufen=E-Mail-Client aufrufen
esliegenkeineadressdatenfurdiesenverteilervor=Es liegen keine Adressdaten f\u00FCr diesen Verteiler vor.
esliegenkeineadressenfurdiesenverteilervor=Es liegen keine Adressen f\u00FCr diesen Verteiler vor.
esliegenkeinevorlagenvor=Es liegen keine Vorlagen vor.
zuruckzurverteilerubersicht=Zur\u00FCck zur Verteiler\u00FCbersicht
eswurdekeineemailzumversendengespeichert=Es wurde keine E-Mail zum Versenden gespeichert
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=Es wurde eine E-Mail automatisch gespeichert. Diese wird nun automatisch versendet.
emailszumversendengespeichertdiesewerdennunautomatischversendet=E-Mails zum Versenden automatisch gespeichert. Diese werden nun automatisch versendet.
markiertenverteiler=Markierte(n) Verteiler
markierteverteilerloschen=Markierte Verteiler l\u00F6schen
persondendaten=Persondendaten
solldiesergastaufplatzgesetztwerden=Soll dieser Gast auf Platz gesetzt werden?
solldiepartnerinderpartnermiteingeladenwerden=Soll die Partnerin / der Partner mit eingeladen werden?
aktuellepersonwirklichentfernen=Aktuelle Person wirklich entfernen?
personspeichern=Person speichern
zurpersonenliste=Zur Personenliste
zurpersonenuebersicht=Zur Personen\u00FCbersicht
zurueckzurveranstaltung=Zur\u00FCck zur Veranstaltung
zurdublettensuche=Zur Dublettensuche
zurckzumsuchergebnis=Zur\u00FCck zum Suchergebnis
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=Diese Person wurde erfolgreich zur G\u00E4steliste der Veranstaltung
hinzugefuegt=hinzugef\u00FCgt
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=Diese Person wurde nicht hinzugef\u00FCgt, da Sie bereits auf der G\u00E4steliste steht.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=Diese Person wurde bereits als gel\u00F6scht markiert und wird beim Suchen nicht mehr angezeigt.
personanlegen=Person anlegen
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=Es wurden keine Dubletten gefunden. Sie k\u00F6nnen jetzt weitere Daten eingeben und die Daten speichern.
bittegebensiezunaechstden=Bitte geben Sie zun\u00E4chst unter Personendaten den
vorundnachnamen=Vor\u2011 und Nachnamen
sowieunteranschriftendie=sowie unter Anschriften die
anundfuhrendiedublettenprufungdurch=an und f\u00FChren die Dublettenpr\u00FCfung durch.
beifirmenwaehlensiediecheckbox=Bei Firmen w\u00E4hlen Sie die Checkbox
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=und tragen dann den Firmennamen ein. Das System pr\u00FCft Ihre Angaben daraufhin auf Dubletten.
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=Liegt keine Dublette vor, k\u00F6nnen Sie weitere Daten eingeben und die Daten speichern.
geschaeftlich=Gesch\u00E4ftlich
privat=Privat
zurueckzurpersonensuche=Zur\u00FCck zur Personensuche
zurueckzurpersonenuebersicht=Zur\u00FCck zur Personen\u00FCbersicht
zurueck=Zur\u00FCck
dublettenpruefungdurchfuehren=Dublettenpr\u00FCfung durchf\u00FChren
zurueckzumsuchergebnis=Zur\u00FCck zum Suchergebnis
personspeicherndublettenpruefung=Person speichern\u200A\u2014\u200ADubletten-Pr\u00FCfung
neueneintraganlegen=Neuen Eintrag anlegen
existierendeneintragbearbeiten=Existierenden Eintrag bearbeiten
eswurdenkeinedublettengefunden=Es wurden keine Dubletten gefunden.
hinzufuegen=Hinzuf\u00FCgen
ausgewaehltepersonenzurveranstaltunghinzufuegen=Ausgew\u00E4hlte Personen zur Veranstaltung hinzuf\u00FCgen.
personerfassen=Person erfassen
dublettenanlegen=Dubletten anlegen
abbrechenundzurueck=Abbrechen und zur\u00FCck
gastsuchenveranstaltung=Gast suchen\u200A\u2014\u200AVeranstaltung
gastsuchen=Gast suchen
verantwortlichenfueraufgabesuchen=Verantwortlichen f\u00FCr Aufgabe suchen
verantwortlichenfueraufgabehinzufugen=Verantwortlichen f\u00FCr Aufgabe hinzuf\u00FCgen
gastgeberhinzufuegen=Gastgeber hinzuf\u00FCgen
personensuchegastgeberhinzufugen=Personensuche: Gastgeber hinzuf\u00FCgen
gasthinzufuegen=Gast hinzuf\u00FCgen
personensuchegasthinzufugen=Personensuche: Gast hinzuf\u00FCgen
personfirma=Person/Firma
weitereangaben=Weitere Angaben
keinekategoriezugeordnet=Keine Kategorie zugeordnet
keinarbeitsbereichzugeordnet=Kein Arbeitsbereich zugeordnet
keinarbeitsbereich=Kein Arbeitsbereich
gueltigkeitsdatum=G\u00FCltigkeitsdatum
biszudiesemdatum=Bis zu diesem Datum
abdiesemdatum=Ab diesem Datum
angenaudiesemdatum=An genau diesem Datum
datumauswaehlen=Datum ausw\u00E4hlen
HINT_SEARCH_MULTIPLE=Die Suche unterst\u00FCtzt auch die Mehrfachsuche nach Kategorien. Um mehrere Kategorien auszuw\u00E4hlen, halten Sie bitte die Maustaste gedr\u00FCckt und ziehen Sie den Mauszeiger \u00FCber die in der Suche zu ber\u00FCcksichtigenden Kategorien. Alternativ k\u00F6nnen Sie bei gedr\u00FCckter STRG-Taste mit der linken Maustaste auf die zu ber\u00FCcksichtigenden Kategorien klicken. Beachten Sie bitte, dass die beiden Pseudokategorien \u201EAlle\u201C und \u201EKeine\u201C nicht zusammen mit anderen Kategorien ausgew\u00E4hlt werden k\u00F6nnen.
waehlensiebittezunaechsteinekategorieaus=W\u00E4hlen Sie bitte zun\u00E4chst eine Kategorie aus.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=Wollen Sie dieser Person bzw. diesem Gast die ausgew\u00E4hlte Kategorie zuordnen
eswurdekeinekategoriezugeordnet=Es wurde keine Kategorie zugeordnet
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=Wollen Sie %s Personen bzw. G\u00E4sten die ausgew\u00E4hlte Kategorie zuordnen
eswurdenkeinekategorienzugeordnet=Es wurden keine Kategorien zugeordnet
eswurdenkeinekategoriengefunden=Es wurden keine Kategorien gefunden
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Wollen Sie diese Personen bzw. diesen Gast aus der ausgew\u00E4hlten Kategorie entfernen
eswurdekeinekategorieentfernt=Es wurde keine Kategorie entfernt
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Wollen Sie %s Personen bzw. G\u00E4ste aus der ausgew\u00E4hlten Kategorie entfernen
eswurdenkeinekategorienentfernt=Es wurden keine Kategorien entfernt.
zuweisen=Zuweisen
waehlensieeinekategorieauswelchesie=W\u00E4hlen Sie eine Kategorie aus, welche Sie
moechten=m\u00F6chten
alleentfernen=Alle entfernen
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Sie haben keine Kategorien konfiguriert. Diese k\u00F6nnen Sie im Administrationsbereich unter dem Punkt
definieren=definieren.
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=Sie haben %s Person(en) ausgew\u00E4hlt. Abh\u00E4ngig von der Anzahl der ausgew\u00E4hlten Personen kann die Aktion eine gewisse Zeit in Anspruch nehmen.
waehlensiebittezunaechsteinenarbeitsbereichaus=W\u00E4hlen Sie bitte zun\u00E4chst einen Arbeitsbereich aus.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=Wollen Sie diese Person bzw. diesen Gast den ausgew\u00E4hlten Arbeitsbereich zuordnen
eswurdekeinarbeitsbereichzugeordnet=Es wurde kein Arbeitsbereich zugeordnet
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=Wollen Sie diesen Personen bzw. diesen G\u00E4ste den ausgew\u00E4hlten Arbeitsbereich zuordnen
eswurdenkeinearbeitsbereichzugeordnet=Es wurden keine Arbeitsbereich zugeordnet
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Wollen Sie die Zuordnung dieser Person bzw. diesem Gast zum ausgew\u00E4hlten Arbeitsbereich aufheben
eswurdekeinarbeitsbereichaufgehoben=Es wurde kein Arbeitsbereich aufgehoben
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Wollen Sie die Zuordnung von %s Personen bzw. G\u00E4sten zum ausgew\u00E4hlten Arbeitsbereich aufheben
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Wollen Sie diese Person bzw. diesen Gast dem ausgew\u00E4hlten Arbeitsbereich zuordnen
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=Wollen Sie %s Personen bzw. G\u00E4ste dem ausgew\u00E4hlten Arbeitsbereich zuordnen
waehlensieeinenarbeitsbereichauswelchensie=W\u00E4hlen Sie einen Arbeitsbereich aus, welchen Sie
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Sie haben keine Arbeitsbereiche konfiguriert. Diese k\u00F6nnen Sie im Administrationsbereich unter dem Punkt
administrationallestellvertretungenimmandanten=Administration\u200A\u2014\u200Aalle Stellvertretungen im Mandanten
administrationallestellvertretungen=Administration\u200A\u2014\u200Aalle Stellvertretungen
verwaltungpersoenlichevertretungen=Verwaltung\u200A\u2014\u200Apers\u00F6nliche Vertretungen
vertretung=Vertretung
markiertevertretungen=Markierte Vertretung(en)
loeschen=L\u00F6schen
markiertevertretungenloeschen=Markierte Vertretung(en) l\u00F6schen
gueltigab=G\u00FCltig ab
gueltigbis=G\u00FCltig bis
bitteauswaehlen=Bitte ausw\u00E4hlen
gaestelisteerstellenfuerveranstaltungeventshortname=G\u00E4steliste erstellen f\u00FCr Veranstaltung: $!event.shortname
gaesteverwaltungderveranstaltung=G\u00E4steverwaltung der Veranstaltung
gaestelisteerstellen=G\u00E4steliste erstellen
ausgabeformatwaehlen=Ausgabeformat w\u00E4hlen
listenachkategoriengruppiertmitpartner=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Partner
listenachkategoriengruppiertmittelundmobiltelefon=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Tel. und Mobiltelefon
listenachkategoriengruppiertmitpartnerundfax=Liste nach Kategorien gruppiert\u200A\u2014\u200Amit Partner und Fax
listenachsortierungmitpartnertelundmobiltelefon=Liste nach Sortierung\u200A\u2014\u200Amit Partner, Tel. und Mobiltelefon
tisch=Tisch
zusaetzlichesortierungnach=Zus\u00E4tzliche Sortierung nach
zurueckzurgaesteverwaltung=Zur\u00FCck zur G\u00E4steverwaltung
verwaltungallebenutzerimmandanten=Verwaltung\u200A\u2014\u200Aalle Benutzer im Mandanten
verwaltungallebenutzer=Verwaltung\u200A\u2014\u200Aalle Benutzer
markiertenbenutzer=Markierte(n) Benutzer
markiertenbenutzerloeschen=Markierte(n) Benutzer l\u00D6schen
leseneingeschraenkt=Lesen eingeschr\u00E4nkt
lesenuneingeschraenkt=Lesen uneingeschr\u00E4nkt
lesenundschreibeneingeschraenkt=Lesen und Schreiben eingeschr\u00E4nkt
lesenundschreibenuneingeschraenkt=Lesen und Schreiben uneingeschr\u00E4nkt
mandantadministrieren=Mandant Administrieren
administrieren=Administrieren
stellvertretung=Stellvertretung
bittewahlensiedierolleausdiesievertretenmochten=Bitte w\u00E4hlen Sie die Rolle aus die Sie vertreten m\u00F6chten
benutzerrolle=Benutzerrolle
vertreten=Vertreten
statistikfurgastgeber=Statistik f\u00FCr Gastgeber
imzeitraumvom=Im Zeitraum vom
biszum=Bis zum
bis=Bis
auswartigesamtintranetstil=Ausw\u00E4rtiges Amt Intranet-Stil
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Klicken Sie eine der aufgelisteten Personen an, um sie der Aufgabe hinzuzuf\u00FCgen
eswurdeeinepersongeloscht=Es wurde eine Person gel\u00F6scht.
eswurdekeinepersongeloscht=Es wurde keine Person gel\u00F6scht.
personengelouscht=Personen gel\u00F6scht.
derarbeitsbereichwurdeerfolgreichhinzugefugt=Der Arbeitsbereich wurde erfolgreich hinzugef\u00FCgt.
diearbeitsbereichewurdenerfolgreichentfernt=Die Arbeitsbereiche wurden erfolgreich entfernt.
diekategoriewurdeerfolgreichhinzugefugt=Die Kategorie wurde erfolgreich hinzugef\u00FCgt.
diekategorienwurdenerfolgreichentfernt=Die Kategorien wurden erfolgreich entfernt.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=Sie haben keine ausreichende Berechtigung um Personen zu entfernen.
wauhlensiebittezunauchsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=Bei den folgenden Personen liegt das G\u00FCltigkeitsdatum in der Zukunft
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=Folgende Personen sind mindestens einer laufenden oder zuk\u00FCnftigen Veranstaltung
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=zugeordnet. Detailinformationen k\u00F6nnen Sie \u00FCber die G\u00E4stelisten der
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=jeweiligen Veranstaltungen abrufen. Die Personen werden aus allen G\u00E4stelisten
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=Folgende Personen sind mindestens einer Aufgabe in mindestens einer laufenden oder
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=zuk\u00FCnftigen Veranstaltung zugeordnet. Detailinformationen rufen Sie bitte \u00FCber die
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=Aufgabenlisten der jeweiligen Veranstaltungen auf. Die Personen werden aus allen
aufgabenentfernt=Aufgaben entfernt
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=Wenn Sie Ihre Auswahl anpassen wollen, brechen Sie bitte das L\u00F6schen ab.
sollenallemarkiertenpersonengeloeschtwerden=Sollen alle markierten Personen gel\u00F6scht werden?
dieseaktionkannnichtrueckgaungiggemachtwerden=Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.
bittebestaetigensiedasloeschendermarkiertenpersonen=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Personen!
loeschenvonpersonenistnichtmoeglich=L\u00F6schen von Personen ist nicht m\u00F6glich
markiertepersonenzurveranstaltunghinzufuegen=Markierte Person(en) zur Veranstaltung hinzuf\u00FCgen
zudieserpersonistkeinehauptpersoneingetragen=Zu dieser Person ist keine Hauptperson eingetragen.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=Diese Person kann nicht auf Reserve gesetzt werden, da die notwendigen Daten
nichtvollstaendigerfasstwurden=nicht vollst\u00E4ndig erfasst wurden.
waehlensiebittezunaechsteineodermehrerepersonenaus=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Personen aus.
exportieren=Exportieren
einladen=Einladen
aufreservesetzen=Auf Reserve setzen
delegationanmelden=Delegation anmelden
alledemarkiereninklpartnerwenneingeladen=Alle (de)markieren (inkl. Partner, wenn eingeladen)
arbeitsshybereich=Arbeits\u00ADbereich
eswurdenkeineeintraegegefunden=Es wurden keine Eintr\u00E4ge gefunden.
suchenersetzen=Suchen und Ersetzen
suchenersetzeninpersonendaten=Suchen und Ersetzen in Personendaten
vornamederhauptpersonunddespartners=Vorname der Hauptperson und des Partners
nachnamederhauptpersonunddespartners=Nachname der Hauptperson und des Partners
anredetitel=Anrede / Titel
anredeundtitel=Anrede und Titel
straszligeadresszusatzundland=Stra\u00DFe, Adresszusatz und Land
plzortundplzpostfach=PLZ / Ort und PLZ / Postfach
telefontelefaxundmobiltelefon=Telefon, Telefax und Mobiltelefon
telefonfax=Telefon / Fax
emailadresse=E-Mail-Adresse
internetadresse=Internet-Adresse
ihresuchemussausmindestenseinembuchstabenbestehen=Ihre Suche muss aus mindestens einem Buchstaben bestehen.
siemuessenmindestenseinfeldausgewhlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersonersetzt=Es wurde keine Person ersetzt.
eswurdeeinepersonersetzt=Es wurde eine Person ersetzt.
personenersetzt=Personen ersetzt.
siemuessenmindestenseinfeldausgewaehlthaben=Sie m\u00FCssen mindestens ein Feld ausgew\u00E4hlt haben.
eswurdekeinepersongefunden=Es wurde keine Person gefunden.
eswurdeeinepersongefunden=Es wurde eine Person gefunden.
personengefunden=Personen gefunden.
einzelneeinzraegezumersetzenselektieren=Einzelne Einzr\u00E4ge zum Ersetzen selektieren
allesofortersetzen=Alle sofort ersetzen
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=Wenn Sie den Platzhalter * verwenden, werden auch Teilst\u00FCcke ersetzt, sonst nur vollst\u00E4ndige Datenfelder.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=Sie m\u00FCssen das Datum des Zeitrahmens im Format TT.MM.JJJJ angeben
markierteanredenloschen=Markierte Anrede(n) l\u00F6schen
markiertendokumenttypenloschen=Markierte Dokumenttyp(en) l\u00F6schen
markierteveranstaltungsorteloschen=Markierte Veranstaltungsorte l\u00F6schen
markiertevorlagenloschen=Markierte Vorlagen l\u00F6schen
keinedateigefunden=Keine Datei gefunden.
standardauswahlderselectboxbdquozeichensatzrdquo=Standard Auswahl der Selectbox \u201EZeichensatz\u201C
zusaetzlichefelder=Zus\u00E4tzliche Felder
postausgang=Postausgang
beimversendendieseremailisteinfehleraufgetreten=Beim Versenden dieser E-Mail ist ein Fehler aufgetreten.
siekonnendiesejetztbearbeitenunderneutsenden=Sie k\u00F6nnen diese jetzt bearbeiten und erneut senden.
dieseemailwartetaufihrefertigstellungdurcheinenbenutzer=Diese E-Mail wartet auf ihre Fertigstellung durch einen Benutzer.
dieseemailwartetaufihreversendung=Diese E-Mail wartet auf ihre Versendung.
dieseemailwirdgeradeversendetundsollte=Diese E-Mail wird gerade versendet und sollte
nichtbearbeitet=nicht bearbeitet
werden=werden.
dieseemailwurdebereitsversendetundsollte=Diese E-Mail wurde bereits versendet und sollte
nichtmehrbearbeitet=nicht mehr bearbeitet
technischefehlermeldungausblenden=Technische Fehlermeldung ausblenden
markiertenmandanten=Markierte(r) Mandant(en)
markiertenmandantenwirklichloschen=Markierte(n) Mandant(en) wirklich l\u00F6schen
alledatensatzewurdenerfolgreichmandantenzugeordnet=Alle Datens\u00E4tze wurden erfolgreich einem Mandanten zugeordnet.
esexistiertnochkeinmandant=Es existiert noch kein Mandant.
zuordnen=Zuordnen
zuordnen_klein=zuordnen
markierteanreden=Markierte Anrede(n)
markierteanredenloeschen=Markierte Anreden l\u00F6schen
markiertenarbeitsbereiche=Markierte(n) Arbeitsbereich(e)
markierteeintraegeentfernen=Markierte Eintr\u00E4ge entfernen
emailpostausgang=E-Mail-Postausgang
markierteemailsloeschen=Markierte E-Mail(s) l\u00F6schen
markierteemails=Markierte E-Mail(s)
wartet=Wartet
wirdversendet=Wird versendet
gesendet=Gesendet
unbekannt=Unbekannt
firmainstitutionauswaehlen=Firma/Institution ausw\u00E4hlen
bittewaehlensieeinefirmainstitutionaus=Bitte w\u00E4hlen Sie eine Firma / Institution aus
schliessen=Schlie\u00DFen
verawebuebersicht=VerA.web :: \u00DCbersicht
uebersichtanzeigen=\u00DCbersicht anzeigen
neuendatensatzanlegen=Neuen Datensatz anlegen
openofficedateiherrunterladen=OpenOffice-Datei herrunterladen
keinedatensaetzegefunden=Keine Datens\u00E4tze gefunden
einendatensatzgefunden=Einen Datensatz gefunden
datensaetzegefunden=Datens\u00E4tze gefunden
anzeigen=anzeigen
wollensiediesendatensatzunwiderruflichentfernen=Wollen Sie diesen Datensatz unwiderruflich entfernen
verawebdetailansicht=VerA.web :: Detailansicht
datensatzbearbeiten=Datensatz bearbeiten
zuruecksetzen=Zur\u00FCcksetzen
datensatzloeschen=Datensatzl\u00F6schen
siekoennenbeidersuchesogenannteplatzhalterverwendenderstehtfuermehrereunddasfuereinzelnezeichen=Sie k\u00F6nnen bei der Suche sogenannte Platzhalter verwenden, der * steht f\u00FCr mehrere und das ? f\u00FCr einzelne Zeichen
undamtsbezeichnungfunktion=und Amtsbezeichnung/Funktion
HINT_SEARCH_WHERE=Die Suche erfolgt im Vornamen, Nachnamen, Ort, PLZ, Stra\u00DFe, Firma/Institution, Telefon, Fax, Mobil, E-Mail, Bemerkungen, Kategorien, Arbeitsbereiche
neuenorteingeben=Neuen Ort eingeben
bittegebensieeinenneuenorteinundklickensieaufhinzufuegen=Bitte geben Sie einen neuen Ort ein und klicken Sie auf \u201EHinzuf\u00FCgen\u201C
neuerveranstaltungsort=Neuer Veranstaltungsort
personenetikett=Personen-Etikett
zuruckzurubersicht=Zuruck zur \u00DCbersicht
gpsdaten=GPS-Daten
platzhalterintexteinfuegen=Platzhalter in Text einf\u00FCgen
intexteinfuegen=In Text einf\u00FCgen
emailvorlagen=E-Mail Vorlagen
pdfvorlagen=PDF-Vorlagen
pdfvorlage=PDF-Vorlage
vorhandenevorlagen=Vorhandene Vorlagen
bitteauswhaelengt=Bitte ausw\u00E4hlen
vorlageladen=Vorlage laden
neuevorlagename=Neue Vorlage (Name)
neuevorlagespeichern=Neue Vorlage speichern
neuevorlagenmuessensowohleinenbetreffalsauchtextenthalten=Neue Vorlagen m\u00FCssen sowohl einen Betreff als auch Text enthalten (Anh\u00E4nge werden nicht gespeichert)
zurueckzumverteiler=Zur\u00FCck zum Verteiler
markiertenveranstaltungsorte=Markierte(r) Veranstaltungsort(e)
hinweis=Hinweis
aktiv=aktiv
inaktiv=inaktiv
net_do=nicht installiert
aktionen=Aktionen
anschrift=Anschrift
anderungenspeichern=\u00C4nderungen speichern
senden=Senden

# GENERIC
GENERIC_UPLOAD_BUTTON=Datei ausw\u00E4hlen
GENERIC_PERSONAL_DATA=Pers\u00F6nliche Daten
GENERIC_NUMBER_OF_GUESTS=G\u00E4steanzahl

# MESSAGES
MESSAGE_INVITATION_WITHOUT_MAIN_PERSON=Dieser Gast wurde ohne Hauptperson eingeladen
MESSAGE_INVITATION_WITHOUT_PARTNER=Dieser Gast wurde ohne Partner eingeladen
MESSAGE_INVITATION_WITHOUT_PERSON_PART1=M\u00F6chten Sie diese jetzt
MESSAGE_INVITATION_WITHOUT_PERSON_PART2_BUTTON=nachtr\u00E4glich einladen
MESSAGE_END_AND_START_DATE=Das Ende der Veranstaltung muss zeitlich nach dem Beginn der Veranstaltung liegen.
MESSAGE_EVENT_MISSING_SHORT_DESCRIPTION=Die Veranstaltung kann nicht gespeichert werden. Vergeben Sie bitte eine Kurzbezeichnung.
MESSAGE_EVENT_WRING_DATE_FORMAT=Sie m\u00FCssen den Beginn der Veranstaltung im Format TT.MM.JJJJ angeben.
MESSAGE_GENERIC_MISSING_DESCRIPTION=Sie m\u00FCssen eine Bezeichung eingeben.
MESSAGE_EVENTDOCTYPE_ASSIGNMENT_WRONG=Die Zuordnung eines Dokumenttypens zu einer Veranstaltung ist fehlerhaft.
MESSAGE_EVENT_LOCATION_TITLE_EMPTY=Der Veranstaltungsort kann nicht gespeichert werden. Vergeben Sie Bitte einen Titel.
MESSAGE_EVENT_LOCATION_MAX_REMARK_REACHED=Der Inhalt des Bemerkungsfelds darf maximal 1000 Zeichen lang sein.
MESSAGE_EMAIL_DRAFT_NAME_MISSING=Sie m\u00FCssen der E-Mail-Vorlage einen Namen geben.
MESSAGE_EMAIL_DRAFT_SUBJECT_MISSING=Sie haben der E-Mail-Vorlage keinen Betreff gegeben.
MESSAGE_EMAIL_DRAFT_TEXT_MISSING=Sie haben in dieser E-Mail-Vorlage keinen Text eingegeben.
MESSAGE_EMAIL_LIST_NAME_EMPTY=Bitte geben sie dem Verteiler einen Namen.
MESSAGE_TASK_TIME_WITHOUT_DATE=Die Eingabe einer Uhrzeit ohne ein zugeh\u00F6riges Datum ist nicht zul\u00E4ssig.
MESSAGE_TASK_END_DATE_NOT_FUTURE=Die Aufgabe kann nicht gespeichert werden. Das Enddatum muss in der Zukunft liegen.
MESSAGE_TASK_END_DATE_WITHOUT_BEGIN_DATE=Die Aufgabe kann nicht gespeichert werden. Bitte geben Sie neben dem Enddatum auch ein Startdatum an.
MESSAGE_TASK_BEGIN_DATE_BEFORE_END_DATE=Die Aufgabe kann nicht gespeichert werden. Das Startdatum muss vor dem Enddatum liegen.
MESSAGE_TASK_NO_SHORTNAME=Die Aufgabe kann nicht gespeichert werden. Vergeben Sie bitte eine Kurzbezeichnung.
MESSAGE_TASK_MAX_REMARK_REACHED=Die Aufgabe kann nicht gespeichert werden. Das Feld Beschreibung darf nicht mehr als 1000 Zeichen besitzen.
MESSAGE_TASK_EMAIL_WITHOUT_SENDER=Die E-Mail kann nicht ohne Absender versendet werden.
MESSAGE_TASK_EMAIL_WITHOUT_RECEIVER=Die E-Mail kann nicht ohne Empf\u00E4nger versendet werden.
MESSAGE_TASK_EMAIL_WITHOUT_SUBJECT=Die E-Mail kann nicht ohne Betreff versendet werden.
MESSAGE_ORG_UNIT_NO_NAME=Sie m\u00FCssen einen Namen eingeben.
MESSAGE_PERSON_MAX_COMPANY_REACHED=Sie d\u00FCrfen maximal 100 Zeichen f\u00FCr die Firma/Institution angeben.
MESSAGE_PERSON_MAX_NAME_REACHED=Sie d\u00FCrfen maximal 100 Zeichen f\u00FCr den Vornamen der Hauptperson angeben.
MESSAGE_PERSON_MAX_LASTNAME_REACHED=Sie d\u00FCrfen maximal 100 Zeichen f\u00FCr den Nachnamen der Hauptperson angeben.
MESSAGE_PERSON_NO_MAIL=Sie m\u00FCssen eine Email-Adresse angeben.
MESSAGE_PERSON_NO_COMPANY_NAME=Sie m\u00FCssen einen Namen f\u00FCr die Firma/Institution angeben.
MESSAGE_PERSON_NO_NAME_LAST_NAME=Sie m\u00FCssen einen Vornamen und einen Nachnamen angeben.
MESSAGE_PERSON_NO_NAME=Sie m\u00FCssen einen Vornamen angeben.
MESSAGE_PERSON_NO_LASTNAME=Sie m\u00FCssen einen Nachnamen angeben.
MESSAGE_PERSON_CATEGORY_NO_CONNECTION_PERSON_CATEGORY=Kann Verbindung zwischen Person und Kategorie nicht speichern.
MESSAGE_DOCTYPE_MAX_CONNECTOR_REACHED=Der Verbinder darf maximal 50 Zeichen lang sein.
MESSAGE_PROXY_NO_REPRESENTATIVE=Das Feld \u201EVertreter\u201C ist Pflichtfeld.
MESSAGE_PROXY_NO_ROLE=Das Feld \u201ERolle\u201C ist Pflichtfeld.
MESSAGE_PROXY_MISSING_BOTH=Die Felder \u201ERolle\u201C und \u201EVertreter\u201C sind Pflichtfelder.
MESSAGE_PROXY_REPRESENTATIVE_BEGIN_BEFORE_END=Der Beginn der Vertretung muss vor dem Ende liegen.
MESSAGE_FUNCTION_MISSING_NAME=Sie m\u00FCssen der Funktion einen Namen geben.
MESSAGE_USER_MISSING_ROLE=Sie m\u00FCssen eine Benutzerrollenbezeichnung eingeben.
MESSAGE_ORGUNIT_BUSY=Solange dem Mandanten noch Benutzer zugeordnet sind k\u00F6nnen Sie ihn nicht l\u00F6schen.

# EVENT LIST TEXTS
EVENT_LIST_WARNING_EVENTS_IN_FUTURE=Mindestens eine markierte Veranstaltung l\u00E4uft aktuell oder liegt in der Zukunft.
EVENT_LIST_WARNING_SELECTION_CHANGING=Wenn Sie Ihre Auswahl anpassen wollen, brechen Sie bitte das L\u00F6schen ab.
EVENT_LIST_DELETE_CONFIRMATION_MESSAGE=Sollen alle markierten Veranstaltungen gel\u00F6scht werden? Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.

# PERSON LIST TEXTS
PERSON_LIST_WARNING_NO_PERMISSION_TO_DELETE=Sie haben keine Berechtigung Personen zu l\u00F6schen.
PERSON_LIST_WARNING_ONLY_DELETE_ONE_PERSON=Sie d\u00FCrfen immer nur eine Person l\u00F6schen. Bitte markieren Sie nur einen Eintrag, oder wenden Sie sich an Ihren Administrator.
PERSON_LIST_QUESTION_DELETE_CONFIRMATION=Sollen alle markierten Personen gel\u00F6scht werden?

# EVENT DETAIL SITE TEXTS
EVENT_DETAIL_ALREADY_EXISTS_ONE=Eine Verstaltung mit dem Namen \u201E
EVENT_DETAIL_ALREADY_EXISTS_TWO=\u201C existiert bereits. M\u00F6chten Sie die neue Veranstaltung dennoch speichern?

# CATEGORY TEXTS
CATEGORY_DETAIL_ALREADY_EXISTS=Es existiert bereits ein Stammdaten-Eintrag unter dem Namen

# CHANGELOG REPORTS TEXTS
CHANGELOG_NO_PROTOCOL_AVAILABLE=Es stehen keine Protokolldaten zur Verf\u00FCgung.

# BROWSER TITLES
BROWSER_TITLE_REPORTS=Reports

#NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GUEST_LIST_RESET_ALL_TO_MASTER_DATA=Alle Werte auf Stammdaten zur\u00FCcksetzen
GUEST_LIST_EDIT_MASTER_DATA=Personenstammdaten bearbeiten
GUEST=Gast
GENERIC_OF=von

TOOLTIP_EDIT_HEADLINES=Sie k\u00F6nnen die \u00DCberschriften vor dem Drucken noch ver\u00E4ndern indem Sie den \u201EBearbeiten\u201C-Link anklicken. Bitte Speichern Sie dies vor dem Drucken.
GENERIC_APPLY_TO_GUESTLIST=In G\u00E4steliste \u00FCbernehmen
GENERIC_APPLY_GUEST_TO_GUESTLIST=Gast direkt in G\u00E4steliste \u00FCbernehmen
GENERIC_APPLY=\u00DCbernehmen
GENERIC_APPLY_PERSON_AS_HOST=Person direkt als Gastgeber \u00FCbernehmen
etikettfuraktuellepersonerzeugen=Etikett f\u00FCr aktuelle Person erzeugen

aktuellepersonloschenundzurpersonenlistezuruckkehren=Aktuelle Person l\u00F6schen und zur Personenliste zur\u00FCckkehren
freifeldvorschaufur=Freifeld-Vorschau f\u00FCr
zudieserpersonwurdedasentsprechendevorschaufeldnochncihterzeugt=Zu dieser Person wurde das entsprechende Vorschaufeld noch nicht erzeugt
siemussendierolleangebenunterdersieverawebnutzenmochten=Sie m\u00FCssen die Rolle angeben, unter der Sie VerA.web nutzen m\u00F6chten.
GENERIC_CHOOSE=ausw\u00E4hlen
GENERIC_RESET=Zur\u00FCcksetzen
siehabenkeineausreichendeberechtigungumdiegastelistezuentfernen=Sie haben keine ausreichende Berechtigung um die G\u00E4ste zu entfernen
wahlensiebittezunachsteinenodermehreregasteaus=W\u00E4hlen Sie bitte zun\u00E4chst einen oder mehrere G\u00E4ste aus
bittebestatigensiedasloschendermarkiertengasteliste=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten G\u00E4ste!
GENERIC_NO_GUESTLIST_DELETED=Es wurde keine G\u00E4ste gel\u00F6scht.

EVENT_DOCTYPE_RESET_INFO=Bitte \u00FCberpr\u00FCfen Sie ob dieser Veranstaltung bereits Dokumenttypen zugeordnet sind. Sollte dies der Fall sein m\u00FCssen Sie die Dokumenttypen f\u00FCr diesen Gast neu erzeugen, klicken Sie hierzu auf \u201EAuf Stammdaten zur\u00FCcksetzen\u201C.

diesistuberdenmenupunktadministrationprogrammeinstellungenmoglich=Dies ist \u00FCber den Men\u00FCpunkt Administration \u2192 Programmeinstellungen m\u00F6glich.

GENERIC_CHOSEN_GUESTLIST=Ausgew\u00E4hlte G\u00E4ste
exportierfahigegasteliste=Exportierf\u00E4hige G\u00E4ste
unvollstandigegasteliste=Unvollst\u00E4ndige G\u00E4ste

GUESTLIST_FILTER_EXPORT_INFO=Sollten Sie in der G\u00E4steliste eine Filterung getroffen haben, werden nur die ausgew\u00E4hlten G\u00E4ste exportiert.

GUEST_CANNOT_BE_EXPORTED_1=Ein Gast
GUEST_CANNOT_BE_EXPORTED_2=kann
GUEST_CANNOT_BE_EXPORTED_3=nicht exportiert
GUEST_CANNOT_BE_EXPORTED_4=werden
PERSON_MISSING_DOCTYPE_SPECIFIC_DATA=weil zu dieser Person keine entsprechenden dokumenttypspezifische Daten gespeichert worden sind

GUESTS_CANNOT_BE_EXPORTED_1=G\u00E4ste
GUESTS_CANNOT_BE_EXPORTED_2=k\u00F6nnen
GUESTS_CANNOT_BE_EXPORTED_3=nicht exportiert
GUESTS_CANNOT_BE_EXPORTED_4=werden
PERSONS_MISSING_DOCTYPE_SPECIFIC_DATA=weil nicht zu jeder Person entsprechende dokumenttypspezifische Daten gespeichert worden sind
GENERIC_TO_EVENTDETAIL=Zu den Veranstaltungsdetails
GENERIC_INSERT_CURRENT_MONTH=aktuellen Monat einf\u00FCgen
GENERIC_SELECT_FUNCTION=Funktion ausw\u00E4hlen
diestammdatendiesesgasteswurdengeloschtsiekonnennurdatenimrahmendieserveranstaltungbearbeiten=Die Stammdaten dieses Gastes wurden gel\u00F6scht. Sie k\u00F6nnen nur Daten im Rahmen dieser Veranstaltung bearbeiten
DELETE_SELECTED_MANDATOR=Markierte(n) Mandanten l\u00F6schen
PROMPT_APPLY_CATEGORY_RANK_FROM_MASTERDATA=Soll der Rang der Kategorie aus den Stammdaten \u00FCbernommen werden?

# NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GENERIC_OF_CAPITAL=Von
GENERIC_ASSIGN=Zuweisen
GENERIC_CANCEL=Abbrechen
GENERIC_CONNECTOR=Verbinder
GENERIC_VIEW_DOCUMENT_TYPE=Dokumenttyp ansehen
GENERIC_GENERATE_DOCUMENT_TYPE=Dokumenttyp erzeugen

# GUEST DETAIL TEXTS
GUEST_DETAIL_PARTNER=dem Partner
GUEST_DETAIL_PARTNER_GENITIV=des Partners
GUEST_DETAIL_MAINPERSON=der Hauptperson

GUEST_DETAIL_DUP_SEAT_ERROR_ONE=Bitte \u00E4ndern Sie erst den Sitzplatz bei
GUEST_DETAIL_DUP_SEAT_ERROR_TWO=von
GUEST_DETAIL_DUP_SEAT_ERROR_THREE=\u00FCber die G\u00E4steliste. Diese Person sitzt aktuell auf
GUEST_DETAIL_DUP_SEAT_ERROR_FOUR=dem eingegebenen Sitzplatz
GUEST_DETAIL_DUP_SEAT_ERROR_FIVE=. Die \u00C4nderung wurde nicht gespeichert.

# GUEST TEXTS
GUEST_CALC_SERIALNO=Diese Veranstaltung liegt bereits in der Vergangenheit, m\u00F6chten Sie trotzdem die Laufende-Nummer neu berechnen?

# MAILING LIST TEXTS
MAILING_LIST_NO_ADDRESSES=Das Anlegen eines neuen Verteilers ist fehlgeschlagen, da zu den ausgew\u00E4hlten Personen keine Adressdaten vorliegen
MAILING_LIST_SELECTED_FILE=Ausgew\u00E4hlte Datei
MAILING_LIST_ALREADY_SELECTED_FILE=Diese Datei ist bereits ausgew\u00E4hlt
MAILING_LIST_SELECTED_TOO_MANY=Zu viele Dateien ausgew\u00E4hlt
MAILING_LIST_SELECTED_TOO_BIG=Datei ist zu gro\u00DF
MAILING_LIST_SIZE_NOTICE=Die Maximalgr\u00F6\u00DFe aller Anh\u00E4nge zusammen darf 1,6 MB nicht \u00FCberschreiten.

# ORG UNIT LIST TEXTS
ORG_UNIT_NO_MANDANT_ID=Einzuf\u00FCgender Mandant darf keine ID haben
ORG_UNIT_MANDANT_ALREADY_EXISTS_ONE=Einzuf\u00FCgender Mandant
ORG_UNIT_MANDANT_ALREADY_EXISTS_TWO=existiert bereits.
ORG_UNIT_MANDANT_ID_COMPULSORY_ONE=Zu aktualisierender Mandant
ORG_UNIT_MANDANT_ID_COMPULSORY_TWO= mu\u00DF eine ID haben
ORG_UNIT_MANDANT_EXISTS_ONE=Ein Mandant mit Namen
ORG_UNIT_MANDANT_EXISTS_TWO=existiert bereits.

# PERSON CATEGORIES TEXTS
PERSON_CATEGORIES_SELECT_WARNING=Um eine neue Kategorie hinzuzuf\u00FCgen, w\u00E4hlen Sie bitte eine Kategorie aus. (Sie haben nur einen Rang eingegeben.)

# EXPORT FILE HEADERS
EXPORT_HEADER_DOCUMENT_TYPE=Dokument_Typ
EXPORT_HEADER_FREETEXT_FIELD=Freitextfeld
EXPORT_HEADER_PARTNER_FREETEXT_FIELD=Partner_Freitextfeld
EXPORT_HEADER_INTERCONNECTS=Verbinder
EXPORT_HEADER_ADDRESS=Anschrift
EXPORT_HEADER_CHARSET=Zeichensatz
EXPORT_HEADER_FUNCTION=Funktion
EXPORT_HEADER_TITLE=Anrede
EXPORT_HEADER_ACADEMIC_TITLE=Akad_Titel
EXPORT_HEADER_FIRSTNAME=Vorname
EXPORT_HEADER_LASTNAME=Nachname
EXPORT_HEADER_PARTNER_TITLE=Partner_Anrede
EXPORT_HEADER_PARTNER_ACADEMIC_TITLE=Partner_Akad_Titel
EXPORT_HEADER_PARTNER_FIRSTNAME=Partner_Vorname
EXPORT_HEADER_PARTNER_LASTNAME=Partner_Nachname
EXPORT_HEADER_POSTALCODE=PLZ
EXPORT_HEADER_CITY=Ort
EXPORT_HEADER_STREET=Strasse
EXPORT_HEADER_COUNTRY=Land
EXPORT_HEADER_ADDITIONAL_ADDRESS_ONE=Adresszusatz_1
EXPORT_HEADER_ADDITIONAL_ADDRESS_TWO=Adresszusatz_2
EXPORT_HEADER_CITY_OF_BORN=Geburtsort
EXPORT_HEADER_TELEPHONE=Telefon
EXPORT_HEADER_FAX=Fax
EXPORT_HEADER_EMAIL=Email
EXPORT_HEADER_WWW=WWW
EXPORT_HEADER_MOBILE=Mobil
EXPORT_HEADER_COMPANY=Firma
EXPORT_HEADER_POST_OFFICE_BOX_NUMBER=Postfach_Nr
EXPORT_HEADER_POST_OFFICE_BOX_PLZ=Postfach_PLZ
EXPORT_HEADER_WORK_AREA=Arbeitsbereich
EXPORT_HEADER_CATEGORY=Kategorie
EXPORT_HEADER_CATEGORY_RANG=Kategorie_Rang
EXPORT_HEADER_RANG=Rang
EXPORT_HEADER_RESERVE=Reserve
EXPORT_HEADER_STATUS=Status
EXPORT_HEADER_TABLE=Tisch
EXPORT_HEADER_SEAT=Platz
EXPORT_HEADER_CURRENT_NUMBER=Lfd_Nr
EXPORT_HEADER_COLOUR=Farbe
EXPORT_HEADER_IN_COUNTRY=Inland
EXPORT_HEADER_LANGUAGES=Sprachen
EXPORT_HEADER_SEX=Geschlecht
EXPORT_HEADER_NATIONALITY=Nationalit\u00E4t
EXPORT_HEADER_HINT_RESPONSIBLE=Hinweis_Gastgeber
EXPORT_HEADER_HINT_ORG_TEAM=Hinweis_Orgateam
EXPORT_HEADER_PARTNER_STATUS=Partner_Status
EXPORT_HEADER_PARTNER_TABLE=Partner_Tisch
EXPORT_HEADER_PARTNER_SEAT=Partner_Platz
EXPORT_HEADER_PARTNER_CURRENT_NUMBER=Partner_Lfd_Nr
EXPORT_HEADER_PARTNER_COLOUR=Partner_Farbe
EXPORT_HEADER_PARTNER_IN_COUNTRY=Inland
EXPORT_HEADER_PARTNER_LANGUAGES=Partner_Sprachen
EXPORT_HEADER_PARTNER_SEX=Partner_Geschlecht
EXPORT_HEADER_PARTNER_NATIONALITY=Partner_Nationalit\u00E4t
EXPORT_HEADER_PARTNER_HINT_RESPONSIBLE=Partner_Hinweis_Gastgeber
EXPORT_HEADER_PARTNER_HINT_ORG_TEAM=Partner_Hinweis_Orgateam
EXPORT_HEADER_ACCEPT=Anzahl_Zusagen
EXPORT_HEADER_DECLINE=Anzahl_Absagen
EXPORT_HEADER_OPEN=Anzahl_Offene
EXPORT_HEADER_GUEST_IN_PLACE=Anzahl_Gaeste_auf_Platz
EXPORT_HEADER_GUEST_IN_RESERVE=Anzahl_Gaeste_auf_Reserve
EXPORT_HEADER_EVENT_NAME=Veranstaltungsname
EXPORT_HEADER_EVENT_BEGIN=Veranstaltung_Beginn
EXPORT_HEADER_EVENT_END=Veranstaltung_Ende
EXPORT_HEADER_EVENT_LOCATION=Ort_der_Veranstaltung
EXPORT_HEADER_OBSERVATION=Bemerkung

# MAIN DATA (STAMMDATEN-WORKER) TEXTS
MAIN_DATA_WARN_ALREADY_EXISTS=Es existiert bereits ein Stammdaten-Eintrag unter dem Namen

# STATS (Statistik Worker)
STATS_COLUMN_EVENT_NAME=Name der Veranstaltung
STATS_COLUMN_DATE_BEGIN=Beginn
STATS_COLUMN_INVITATION_TYPE=Einladungsart
STATS_COLUMN_INVITATION_STATUS=Status
STATS_COLUMN_INVITATION_STATUS_PARTNER=Status Partner
STATS_COLUMN_YEAR=Jahr
STATS_COLUMN_MONTH=Monat
STATS_COLUMN_EVENTS=Veranstaltungen
STATS_NOT_INVITED=nicht eingeladen

# USER LIST TEXTS
USER_LIST_WARN_MANDANT_ONE=Einzuf\u00FCgender Benutzer ist bereits dem Mandanten
USER_LIST_WARN_MANDANT_TWO= zugeordnet.
USER_LIST_WARN_ALREADY_USER=Einzuf\u00FCgender Benutzer ist bereits VerA.web zugeordnet.
USER_LIST_WARN_NO_ID=Einzuf\u00FCgender Benutzer darf keine ID haben

# WORKAREA TEXTS
WORKAREA_NEED_MANDANT=Sie k\u00F6nnen keine Arbeitsbereiche anlegen, weil Sie keinem Mandanten zugeordnet sind.
WORKAREA_ERROR_INCORRECT_NAME_ONE=Der Arbeitsbereich mit dem Namen \u201E
WORKAREA_ERROR_INCORRECT_NAME_TWO=\u201C konnte nicht angelegt werden. Bitte weisen Sie sich zuerst einen Mandanten zu.

# VERIFY TEXTS
VERIFY_ERROR_ACCESS_TO_DB_UNABLE=Die Verbindung zur Datenbank wurde nicht erfolgreich hergestellt.
VERIFY_ERROR_ACCESS_TO_DB_INTERRUPTED=Die Verbindung zur Datenbank wurde unterbrochen.
VERIFY_ERROR_ACCESS_TO_DB_NOT_INTERRUPTED=Die Verbindung zur Datenbank wurde nicht erfolgreich unterbrochen.
VERIFY_ERROR_DB_NOT_ACCESSIBLE=Die Verbindung zur Datenbank konnte nicht hergestellt werden.
VERIFY_ERROR_DB_VERSION_NOT_DETERMINED=Die Version des Datenbank-Schemas konnte nicht ermittelt werden.
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_ONE=Die Version des Datenbank-Schemas (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_TWO=) stimmt nicht mit der von VerA.web erwarteten (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_THREE=) \u00FCbereini.
VERIFY_ERROR_DB_LC_CTYPE_NOT_WANTED=Ihre Datenbankkonfiguration unterst\u00FCtzt nicht den erwarteten Zeichensatz (LC_CTYPE=
VERIFY_ERROR_DB_LC_COLLATE_NOT_WANTED=Ihre Datenbankkonfiguration unterst\u00FCtzt nicht die erwarteten Textvergleichsregeln (LC_COLLATE=
VERIFY_ERROR_XML=Bei der Erzeugung eines XML-Testdokumentes ist ein Fehler aufgetreten. (
VERIFY_ERROR_JAVA_ONE=Die installierte Java-Version (
VERIFY_ERROR_JAVA_TWO=) entspricht nicht der erwarteten Version (1.4).

#TO BE DELETED
inlandjageschlechtweiblich=Inland: Ja\u200A\u2014\u200AGeschlecht: Weiblich
inlandjageschlechtmannlich=Inland: Ja\u200A\u2014\u200AGeschlecht: M\u00E4nnlich
inlandneingeschlechtweiblich=Inland: Nein\u200A\u2014\u200AGeschlecht: Weiblich
inlandneingeschlechtmannlich=Inland: Nein\u200A\u2014\u200AGeschlecht: M\u00E4nnlich

# GENERIC DIALOG MESSAGES
GENERIC_PLEASE_WAIT_HEADER=Bitte warten...
GENERIC_PLEASE_WAIT_MESSAGE=Dieser Vorgang kann einen Moment dauern.

# WORK AREA (Bean) TEXTS
WORKAREA_ERROR_MISSING_NAME=Der Arbeitsbereich ben\u00F6tigt einen eindeutigen, nicht leeren Namen.

zurpersonensuche=Zur Personensuche
steuerdatei=Steuerdatei
dokumenttypauswahlen=Dokumenttyp ausw\u00E4hlen
EVENT_NO_DOCTYPES_ASSIGNED=Der Veranstaltung wurden noch keine Dokumenttypen zugeordnet

# DATE HELPER TEXTS
DATE_HELPER_INCORRECT_DATE= ist kein g\u00FCltiges Datum. Bitte verwenden Sie das Eingabeformat TT.MM.JJJJ!

#WIP
GENERIC_SHOW_CURRENT_EVENTS=Aktuelle Veranstaltungen anzeigen
GENERIC_FURTHER_PROCEEDING=Weiteres Vorgehen

LETTER_MAIN_PERSON=H
LETTER_PARTNER=P
LETTER_RESERVE=R
LETTER_DELEGATION=D
LETTER_HOST=G

GENERIC_LASTNAME_WITH_SOFT_HYPHEN=Nach\u00ADname
GENERIC_FIRSTNAME_WITH_SOFT_HYPHEN=Vor\u00ADname
GENERIC_RELOAD=Neu laden
GENERIC_LOAD_EXISTING_IMPORTPROCESS=Bestehenden Importvorgang laden
GENERIC_IMPORTID=ImportID
GENERIC_YEAR=Jahr
GENERIC_COUNT=Anzahl
GENERIC_PARTICIPATION=Teilnahme
GENERIC_NOT_ASSIGNED_TO_CATEGORY=Keiner Kategorie zugeordnet
GENERIC_NOT_ASSIGNED_TO_WORKAREA=Keinem Arbeitsbereich zugeordnet
GENERIC_NO_HOST_ASSIGNED=Kein Gastgeber zugeordnet
GENERIC_NO_GUEST_FOUND=Kein Gast gefunden

GENERIC_PHONE_NUMBER_SHORT=Telefonnr.
GENERIC_FAX_NUMBER_SHORT=Faxnr.

GENERIC_MONTH_YEAR=Monat/Jahr
GENERIC_LOOK_AT=anschauen
GENERIC_MOBILE_PHONE=Mobiltelefon

PHONE_OFFICIAL=Tel. dienstlich
PHONE_PRIVATE=Tel. privat
PHONE_MOBILE=Tel. mobil

GENERIC_PARTNER_FREETEXTFIELD=Partner Freitextfeld
GENERIC_VENUE=Veranstaltungsort

GENERIC_TOTAL=Gesamt
OPTION_MARK_ADMINISTRATION_CATEGORY_1=Kategorie
OPTION_MARK_ADMINISTRATION_CATEGORY_2=Ereignis
OPTION_MARK_ADMINISTRATION_CATEGORY_3=Diplo. Corps

GENERIC_IMPORTID_HYPHEN=Import-ID

GENERIC_SUBSTITUTED_BY=vertreten durch
GENERIC_NONE=Keine
GENERIC_ADDRESS_BLOCK=Adressblock

GENERIC_CONTEXT_PLURAL=Kontexte

PERSON_DETAIL_DELETE_PERSON_HEADER=Bitte best\u00E4tigen Sie das L\u00F6schen der Person!
PERSON_DETAIL_DELETE_PERSON_CANCEL_DELETION=Wenn Sie diese Person doch nicht l\u00F6schen wollen, brechen Sie bitte den Vorgang ab.
PERSON_DETAIL_DELETE_PERSON_CONFIRM_DELETION_WARNING=Soll diese Person wirklich gel\u00F6scht werden?

# PERSON HEADER TEXTS
PERSON_HEADER_NO_DOCTYPE_CONFIG=Es wurde kein Dokumenttyp zur Vorschauanzeige konfiguriert.

#LAST ADDED
GENERIC_GENERATE_LOGIN_CREDENTIALS_FOR_ONLINE_REGISTRATION=Anmeldedaten f\u00FCr die Online-Anmeldung erzeugen
GENERIC_COPY_CURRENT_PERSON=Aktuelle Person kopieren
GENERIC_ASSIGN_CURRENT_PERSON_TO_EVENT=Aktuelle Person einer Veranstaltung zuordnen
GENERIC_PREVIOUS_PAGE=Vorherige Seite
GENERIC_PREVIOUS_PERSON=Vorherige Person
GENERIC_FIRST_PAGE=Erste Seite
GENERIC_FIRST_PERSON=Erste Person
GENERIC_LAST_PAGE=Letzte Seite
GENERIC_LAST_PERSON=Letzte Person
GENERIC_NEXT_PAGE=N\u00E4chste Seite
GENERIC_NEXT_PERSON=N\u00E4chste Person
GENERIC_INPUT_FIELD=Eingabefeld
GENERIC_SIMPLE_COMBOBOX=Einfaches Auswahlfeld
GENERIC_MULTIPLE_COMBOBOX=Mehrfaches Auswahlfeld

# EVENT LOCATIONS (Veranstaltungsort)
HINT_DELETE_NOT_POSSIBLE_ONE=Der Ort \u201E
HINT_DELETE_NOT_POSSIBLE_TWO=\u201C kannt nicht gel\u00F6scht werden, da er von mindestenes einer Veranstaltung verwendet wird.
CONFIRMATION_CREATE_LOCATION_ONE=Soll der Veranstaltungsort \u201E
CONFIRMATION_CREATE_LOCATION_TWO=\u201C wirklich gel\u00F6scht werden?

INSERT_FUNCTION_FROM_MAIN_DATA=Amtsbezeichnung aus Stammdaten hinzuf\u00FCgen
INSERT_COMPANY_FROM_MAIN_DATA=Firma aus Stammdaten hinzuf\u00FCgen

HINT_GUEST_ALREADY_INVITED_SINGULAR=Ein Gast stand bereits auf der G\u00E4steliste.
HINT_GUEST_ALREADY_INVITED_PLURAL=G\u00E4ste standen bereits auf der G\u00E4steliste.

MESSAGE_REPLACED_PERSON_ONE=Es wurden
MESSAGE_REPLACED_PERSON_TWO=Personen ersetzt.
MESSAGE_FOUND_PERSON_ONE=Es wurden
MESSAGE_FOUND_PERSON_TWO=Personen gefunden.

HINT_POPUP_CATEGORY_SELECTION_ONE=Sie haben
HINT_POPUP_CATEGORY_SELECTION_TWO=Person(en) ausgew\u00E4hlt. Abh\u00E4ngig von der Anzahl der ausgew\u00E4hlten Personen kann die Aktion eine gewisse Zeit in Anspruch nehmen.

DELETE_DISTRIBUTOR=Soll der markierte Verteiler entfernt werden?
DELETE_DISTRIBUTORS=Sollen die markierten Verteiler entfernt werden?
PLACEHOLDER_DATE_FORMAT=TT.MM.JJJJ

DELETE_EVENT_TASKS_FIRST_LINE=Bitte best\u00E4tigen Sie das L\u00F6schen der markierten Aufgaben!
DELETE_EVENT_TASKS_SECOND_LINE=Sollen alle markierten Aufgaben gel\u00F6scht werden? Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden.

GM_NO_CHANGES=Sie haben keine \u00C4nderungen vorgenommen.
GM_CONFIRMATION_EMAIL_DISTRIBUTOR=E-mail addressen aus Verteiler \u00FCbernehmen?

CONTACT_PICTURE_UPLOAD=Kontaktfoto hochladen
CONTACT_PICTURE_CHANGE=Kontaktfoto \u00E4ndern
CONTACT_PICTURE_WRONG_SIZE=Das Bild entspricht nicht der erlaubten Gr\u00F6\u00DFe von 186x245 Pixeln.
PICTURE_SIZE=Bildgr\u00F6\u00DFe
PIXELS=Pixel

NO_PARTNER_IN_MASTERDATA=Kein Partner in Stammdaten hinterlegt

#GENERAL MESSAGE
GM_CATEGORY_MODIFY_S=Es wurde eine Kategorie ge\u00E4ndert.
GM_CATEGORY_MODIFY_P=Es wurden %s Kategorien ge\u00E4ndert.
GM_CATEGORY_MODIFY_N=Es wurde keine Kategorie ge\u00E4ndert.
GM_CATEGORY_DELETE_S=Es wurde eine Kategorie gel\u00F6scht.
GM_CATEGORY_DELETE_P=Es wurden %s Kategorien gel\u00F6scht.
GM_CATEGORY_DELETE_N=W\u00E4hlen Sie bitte zun\u00E4chste eine oder mehrere Kategorien aus.
GM_CATEGORY_INSERT_S=Es wurde eine neue Kategorie angelegt.
GM_CATEGORY_INSERT_P=Es wurden %s neuen Kategorien angelegt.
GM_CATEGORY_INSERT_N=Es wurde keine neue Kategorie angelegt.
GM_CLIENT_MODIFY_S=Es wurde ein Mandant ge\u00E4ndert.
GM_CLIENT_MODIFY_P=Es wurden %s Mandanten ge\u00E4ndert.
GM_CLIENT_MODIFY_N=Es wurde kein Mandant ge\u00E4ndert.
GM_CLIENT_DELETE_S=Es wurde ein Mandant gel\u00F6scht.
GM_CLIENT_DELETE_P=Es wurden %s Mandanten gel\u00F6scht.
GM_CLIENT_DELETE_N=Es wurde kein Mandant gel\u00F6scht.
GM_CLIENT_INSERT_S=Es wurde ein neuer Mandant angelegt.
GM_CLIENT_INSERT_P=Es wurden %s neuen Mandanten angelegt.
GM_CLIENT_INSERT_N=Es wurde kein neuer Mandant angelegt.
GM_COLOR_MODIFY_S=Es wurde eine Farbe ge\u00E4ndert.
GM_COLOR_MODIFY_P=Es wurden %s Farben ge\u00E4ndert.
GM_COLOR_MODIFY_N=Es wurde keine Farbe ge\u00E4ndert.
GM_COLOR_DELETE_S=Es wurde eine Farbe gel\u00F6scht.
GM_COLOR_DELETE_P=Es wurden %s Farben gel\u00F6scht.
GM_COLOR_DELETE_N=Es wurde keine Farbe gel\u00F6scht.
GM_COLOR_INSERT_S=Es wurde eine neue Farbe angelegt.
GM_COLOR_INSERT_P=Es wurden %s neuen Farben angelegt.
GM_COLOR_INSERT_N=Es wurde keine neue Farbe angelegt.
GM_DELEGATION_FIELD_MODIFY_S=Es wurde ein Zusatzfeld ge\u00E4ndert.
GM_DELEGATION_FIELD_MODIFY_P=Es wurden %s Zusatzfelder ge\u00E4ndert.
GM_DELEGATION_FIELD_MODIFY_N=Es wurde kein Zusatzfeld ge\u00E4ndert.
GM_DELEGATION_FIELD_DELETE_S=Es wurde ein Zusatzfeld gel\u00F6scht.
GM_DELEGATION_FIELD_DELETE_P=Es wurden %s Zusatzfelder gel\u00F6scht.
GM_DELEGATION_FIELD_DELETE_N=Es wurde kein Zusatzfeld gel\u00F6scht.
GM_DELEGATION_FIELD_INSERT_S=Es wurde ein neuer Zusatzfeld angelegt.
GM_DELEGATION_FIELD_INSERT_P=Es wurden %s neuen Zusatzfelder angelegt.
GM_DELEGATION_FIELD_INSERT_N=Es wurde kein neuer Zusatzfeld angelegt.
GM_DISTRIBUTOR_MODIFY_S=Es wurde ein Verteiler ge\u00E4ndert.
GM_DISTRIBUTOR_MODIFY_P=Es wurden %s Verteiler ge\u00E4ndert.
GM_DISTRIBUTOR_MODIFY_N=Es wurde kein Verteiler ge\u00E4ndert.
GM_DISTRIBUTOR_DELETE_S=Es wurde ein Verteiler gel\u00F6scht.
GM_DISTRIBUTOR_DELETE_P=Es wurden %s Verteiler gel\u00F6scht.
GM_DISTRIBUTOR_DELETE_N=Es wurde kein Verteiler gel\u00F6scht.
GM_DISTRIBUTOR_INSERT_S=Es wurde ein neuer Verteiler angelegt.
GM_DISTRIBUTOR_INSERT_P=Es wurden %s neuen Verteiler angelegt.
GM_DISTRIBUTOR_INSERT_N=Es wurde kein neuer Verteiler angelegt.
GM_DOCUMENT_TYPE_MODIFY_S=Es wurde ein Dokumenttyp ge\u00E4ndert.
GM_DOCUMENT_TYPE_MODIFY_P=Es wurden %s Dokumenttypen ge\u00E4ndert.
GM_DOCUMENT_TYPE_MODIFY_N=Es wurde kein Dokumenttyp ge\u00E4ndert.
GM_DOCUMENT_TYPE_DELETE_S=Es wurde ein Dokumenttyp gel\u00F6scht.
GM_DOCUMENT_TYPE_DELETE_P=Es wurden %s Dokumenttypen gel\u00F6scht.
GM_DOCUMENT_TYPE_DELETE_N=W\u00E4hlen Sie bitte zun\u00E4chst eine oder mehrere Dokumenttypen aus.
GM_DOCUMENT_TYPE_INSERT_S=Es wurde ein neuer Dokumenttyp hinzugef\u00FCgt.
GM_DOCUMENT_TYPE_INSERT_P=Es wurden %s neuen Dokumenttypen hinzugef\u00FCgt.
GM_DOCUMENT_TYPE_INSERT_N=Es wurde kein neuer Dokumenttyp hinzugef\u00FCgt.
GM_EMAIL_MODIFY_S=Es wurde eine E-mail ge\u00E4ndert.
GM_EMAIL_MODIFY_P=Es wurden %s E-mails ge\u00E4ndert.
GM_EMAIL_MODIFY_N=Es wurde keine E-mail ge\u00E4ndert.
GM_EMAIL_DELETE_S=Es wurde eine E-mail gel\u00F6scht.
GM_EMAIL_DELETE_P=Es wurden %s E-mails gel\u00F6scht.
GM_EMAIL_DELETE_N=Es wurde keine E-mail gel\u00F6scht.
GM_EMAIL_INSERT_S=Es wurde eine neue E-mail angelegt.
GM_EMAIL_INSERT_P=Es wurden %s neuen E-mails angelegt.
GM_EMAIL_INSERT_N=Es wurde keine neue E-mail angelegt.
GM_EVENT_MODIFY_S=Es wurde eine Veranstaltung ge\u00E4ndert.
GM_EVENT_MODIFY_P=Es wurden %s Veranstaltungen ge\u00E4ndert.
GM_EVENT_MODIFY_N=Es wurde keine Veranstaltung ge\u00E4ndert.
GM_EVENT_DELETE_S=Es wurde eine Veranstaltung gel\u00F6scht.
GM_EVENT_DELETE_P=Es wurden %s Veranstaltungen gel\u00F6scht.
GM_EVENT_DELETE_N=Es wurde keine Veranstaltung gel\u00F6scht.
GM_EVENT_INSERT_S=Es wurde eine neue Veranstaltung angelegt.
GM_EVENT_INSERT_P=Es wurden %s neuen Veranstaltungen angelegt.
GM_EVENT_INSERT_N=Es wurde keine neue Veranstaltung angelegt.
GM_EVENT_LOCATION_MODIFY_S=Es wurde ein Veranstaltungsort ge\u00E4ndert.
GM_EVENT_LOCATION_MODIFY_P=Es wurden %s Veranstaltungsorte ge\u00E4ndert.
GM_EVENT_LOCATION_MODIFY_N=Es wurde kein Veranstaltungsort ge\u00E4ndert.
GM_EVENT_LOCATION_DELETE_S=Es wurde ein Veranstaltungsort gel\u00F6scht.
GM_EVENT_LOCATION_DELETE_P=Es wurden %s Veranstaltungsorte gel\u00F6scht.
GM_EVENT_LOCATION_DELETE_N=Es wurde kein Veranstaltungsort gel\u00F6scht.
GM_EVENT_LOCATION_INSERT_S=Es wurde ein Veranstaltungsort angelegt.
GM_EVENT_LOCATION_INSERT_P=Es wurden %s neuen Veranstaltungsorte angelegt.
GM_EVENT_LOCATION_INSERT_N=Der Veranstaltungsort kann nicht gespeichert werden. Vergeben Sie Bitte einen Titel.
GM_GUEST_MODIFY_S=Es wurde ein Gast ge\u00E4ndert.
GM_GUEST_MODIFY_P=Es wurden %s G\u00E4ste ge\u00E4ndert.
GM_GUEST_MODIFY_N=Es wurde kein Gast ge\u00E4ndert.
GM_GUEST_DELETE_S=Es wurde ein Gast gel\u00F6scht.
GM_GUEST_DELETE_P=Es wurden %s G\u00E4ste gel\u00F6scht.
GM_GUEST_DELETE_N=Es wurde kein Gast gel\u00F6scht.
GM_GUEST_INSERT_S=Es wurde ein neuer Gast hinzugef\u00FCgt.
GM_GUEST_INSERT_P=Es wurden %s neuen G\u00E4ste hinzugef\u00FCgt.
GM_GUEST_INSERT_N=Es wurde kein neuer Gast hinzugef\u00FCgt.
GM_MAIL_DRAFT_MODIFY_S=Es wurde eine Vorlage ge\u00E4ndert.
GM_MAIL_DRAFT_MODIFY_P=Es wurden %s Vorlagen ge\u00E4ndert.
GM_MAIL_DRAFT_MODIFY_N=Es wurde keine Vorlage ge\u00E4ndert.
GM_MAIL_DRAFT_DELETE_S=Es wurde eine Vorlage gel\u00F6scht.
GM_MAIL_DRAFT_DELETE_P=Es wurden %s Vorlagen gel\u00F6scht.
GM_MAIL_DRAFT_DELETE_N=Es wurde keine Vorlage gel\u00F6scht.
GM_MAIL_DRAFT_INSERT_S=Es wurde eine neue Vorlage angelegt.
GM_MAIL_DRAFT_INSERT_P=Es wurden %s neuen Vorlagen angelegt.
GM_MAIL_DRAFT_INSERT_N=Es wurde keine neue Vorlage angelegt.
GM_OFFICIAL_TITLE_MODIFY_S=Es wurde eine Amtsbezeichnung ge\u00E4ndert.
GM_OFFICIAL_TITLE_MODIFY_P=Es wurden %s Amtsbezeichnungen ge\u00E4ndert.
GM_OFFICIAL_TITLE_MODIFY_N=Es wurde keine Amtsbezeichnung ge\u00E4ndert.
GM_OFFICIAL_TITLE_DELETE_S=Es wurde eine Amtsbezeichnung gel\u00F6scht.
GM_OFFICIAL_TITLE_DELETE_P=Es wurden %s Amtsbezeichnungen gel\u00F6scht.
GM_OFFICIAL_TITLE_DELETE_N=Es wurde keine Amtsbezeichnung gel\u00F6scht.
GM_OFFICIAL_TITLE_INSERT_S=Es wurde eine neue Amtsbezeichnung angelegt.
GM_OFFICIAL_TITLE_INSERT_P=Es wurden %s neuen Amtsbezeichnungen angelegt.
GM_OFFICIAL_TITLE_INSERT_N=Es wurde keine neue Amtsbezeichnung angelegt.
GM_PERSON_MODIFY_S=Es wurde eine Person ge\u00E4ndert.
GM_PERSON_MODIFY_P=Es wurden %s Personen ge\u00E4ndert.
GM_PERSON_MODIFY_N=Es wurde keine Person ge\u00E4ndert.
GM_PERSON_DELETE_S=Es wurde eine Person gel\u00F6scht.
GM_PERSON_DELETE_P=Es wurden %s Personen gel\u00F6scht.
GM_PERSON_DELETE_N=Es wurde keine Person gel\u00F6scht.
GM_PERSON_INSERT_S=Es wurde eine neue Person angelegt.
GM_PERSON_INSERT_P=Es wurden %s neuen Personen angelegt.
GM_PERSON_INSERT_N=Es wurde keine neue Person angelegt.
GM_REPRESENTATIVE_MODIFY_S=Es wurde ein Vertreter ge\u00E4ndert.
GM_REPRESENTATIVE_MODIFY_P=Es wurden %s Vertreter ge\u00E4ndert.
GM_REPRESENTATIVE_MODIFY_N=Es wurde kein Vertreter ge\u00E4ndert.
GM_REPRESENTATIVE_DELETE_S=Es wurde ein Vertreter gel\u00F6scht.
GM_REPRESENTATIVE_DELETE_P=Es wurden %s Vertreter gel\u00F6scht.
GM_REPRESENTATIVE_DELETE_N=Es wurde kein Vertreter gel\u00F6scht.
GM_REPRESENTATIVE_INSERT_S=Es wurde ein neuer Vertreter angelegt.
GM_REPRESENTATIVE_INSERT_P=Es wurden %s neuen Vertreter angelegt.
GM_REPRESENTATIVE_INSERT_N=Es wurde kein neuer Vertreter angelegt.
GM_SALUTATION_MODIFY_S=Es wurde eine Anrede ge\u00E4ndert.
GM_SALUTATION_MODIFY_P=Es wurden %s Anreden ge\u00E4ndert.
GM_SALUTATION_MODIFY_N=Es wurde keine Anrede ge\u00E4ndert.
GM_SALUTATION_DELETE_S=Es wurde eine Anrede gel\u00F6scht.
GM_SALUTATION_DELETE_P=Es wurden %s Anreden gel\u00F6scht.
GM_SALUTATION_DELETE_N=Es wurde keine Anrede gel\u00F6scht.
GM_SALUTATION_INSERT_S=Es wurde eine neue Anrede angelegt.
GM_SALUTATION_INSERT_P=Es wurden %s neuen Anreden angelegt.
GM_SALUTATION_INSERT_N=Es wurde keine neue Anrede angelegt.
GM_TASK_MODIFY_S=Es wurde eine Aufgabe ge\u00E4ndert.
GM_TASK_MODIFY_P=Es wurden %s Aufgaben ge\u00E4ndert.
GM_TASK_MODIFY_N=Es wurde keine Aufgabe ge\u00E4ndert.
GM_TASK_DELETE_S=Es wurde eine Aufgabe gel\u00F6scht.
GM_TASK_DELETE_P=Es wurden %s Aufgaben gel\u00F6scht.
GM_TASK_DELETE_N=Es wurde keine Aufgabe gel\u00F6scht.
GM_TASK_INSERT_S=Es wurde eine neue Aufgabe angelegt.
GM_TASK_INSERT_P=Es wurden %s neuen Aufgaben angelegt.
GM_TASK_INSERT_N=Es wurde keine neue Aufgabe angelegt.
GM_USER_MODIFY_S=Es wurde ein Benutzer ge\u00E4ndert.
GM_USER_MODIFY_P=Es wurden %s Benutzer ge\u00E4ndert.
GM_USER_MODIFY_N=Es wurde kein Benutzer ge\u00E4ndert.
GM_USER_DELETE_S=Es wurde ein Benutzer gel\u00F6scht.
GM_USER_DELETE_P=Es wurden %s Benutzer gel\u00F6scht.
GM_USER_DELETE_N=Es wurde kein Benutzer gel\u00F6scht.
GM_USER_INSERT_S=Es wurde ein neuer Benutzer angelegt.
GM_USER_INSERT_P=Es wurden %s neuen Benutzer angelegt.
GM_USER_INSERT_N=Es wurde kein neuer Benutzer angelegt.
GM_WORKAREA_MODIFY_S=Es wurde ein Arbeitsbereich ge\u00E4ndert.
GM_WORKAREA_MODIFY_P=Es wurden %s Arbeitsbereiche ge\u00E4ndert.
GM_WORKAREA_MODIFY_N=Es wurde kein Arbeitsbereich ge\u00E4ndert.
GM_WORKAREA_DELETE_S=Es wurde ein Arbeitsbereich gel\u00F6scht.
GM_WORKAREA_DELETE_P=Es wurden %s Arbeitsbereiche gel\u00F6scht.
GM_WORKAREA_DELETE_N=Es wurde kein Arbeitsbereich gel\u00F6scht.
GM_WORKAREA_INSERT_S=Es wurde ein neuer Arbeitsbereich angelegt.
GM_WORKAREA_INSERT_P=Es wurden %s neuen Arbeitsbereiche angelegt.
GM_WORKAREA_INSERT_N=Es wurde kein neuer Arbeitsbereich angelegt.

GM_PDF_TEMPLATE_MODIFY_S=Es wurde eine PDF Vorlage ge\u00E4ndert.
GM_PDF_TEMPLATE_MODIFY_P=Es wurden %s PDF Vorlagen ge\u00E4ndert.
GM_PDF_TEMPLATE_MODIFY_N=Es wurde keine PDF Vorlage ge\u00E4ndert.
GM_PDF_TEMPLATE_DELETE_S=Es wurde eine PDF Vorlage gel\u00F6scht.
GM_PDF_TEMPLATE_DELETE_P=Es wurden %s PDF Vorlagen gel\u00F6scht.
GM_PDF_TEMPLATE_DELETE_N=Es wurde keine PDF Vorlage gel\u00F6scht.
GM_PDF_TEMPLATE_INSERT_S=Es wurde eine neue PDF Vorlage angelegt.
GM_PDF_TEMPLATE_INSERT_P=Es wurden %s neuen PDF Vorlagen angelegt.
GM_PDF_TEMPLATE_INSERT_N=Es wurde keine neue PDF Vorlage angelegt.

PDF_TEMPLATE_NOT_EMPTY_ERROR_MESSAGE=Name der Vorlage darf nicht leer sein
PDF_TEMPLATE_NO_FILE_ERROR_MESSAGE=Es muss eine PDF-Datei ausgew\u00E4hlt werden
PDF_TEMPLATE_LIST_NOT_LOAD=Liste der PDF-Vorlagen konnte nicht geladen werden
PDF_GENERATE_BUTTON=PDF generieren
PDF_GENERATE_LABEL=PDF-Export

LOAD_MAILTEMPLATE_FAILED = Die E-Mail Vorlage konnte nicht geladen werden
SELECT_MAILTEMPLATE = Bitte w\u00E4hlen Sie eine E-Mail Vorlage aus

ADDRESS_ERROR = Die Email wurde an den Verteiler versendet. Mindestens eine E-Mail-Adresse dieses Verteilers ist jedoch fehlerhaft gewesen. Der Verteiler konnte an diese E-Mail-Adresse(n) nicht versendet werden. Bitte kontrollieren und korrigieren Sie die folgenden E-Mail-Adresse(n):

LABELLING_MUST_NOT_BE_EMPTY:Die Bezeichnung darf nicht leer sein

birthplace_a_e1=Geburtsort darf nicht l\u00E4nger als 100 Zeichen sein.
birthplace_a_e2=Geburtsort darf nicht l\u00E4nger als 100 Zeichen sein.
birthplace_a_e3=Geburtsort darf nicht l\u00E4nger als 100 Zeichen sein.
city_a_e1=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_a_e2=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_a_e3=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_b_e1=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_b_e2=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_b_e3=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_c_e1=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_c_e2=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
city_c_e3=Stadt darf nicht l\u00E4nger als 300 Zeichen sein.
company_a_e1=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_a_e2=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_a_e3=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_b_e1=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_b_e2=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_b_e3=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_c_e1=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_c_e2=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
company_c_e3=Firma/Institution darf nicht l\u00E4nger als 250 Zeichen sein.
country_a_e1=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_a_e2=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_a_e3=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_b_e1=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_b_e2=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_b_e3=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_c_e1=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_c_e2=Land darf nicht l\u00E4nger als 100 Zeichen sein.
country_c_e3=Land darf nicht l\u00E4nger als 100 Zeichen sein.
fax_a_e1=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_a_e2=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_a_e3=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_b_e1=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_b_e2=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_b_e3=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_c_e1=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_c_e2=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
fax_c_e3=Fax darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_a_e1=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_a_e2=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_a_e3=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_b_e1=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_b_e2=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
firstname_b_e3=Vorname darf nicht l\u00E4nger als 100 Zeichen sein.
fon_a_e1=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_a_e2=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_a_e3=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_b_e1=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_b_e2=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_b_e3=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_c_e1=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_c_e2=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
fon_c_e3=Telefon darf nicht l\u00E4nger als 100 Zeichen sein.
function_a_e1=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_a_e2=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_a_e3=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_b_e1=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_b_e2=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_b_e3=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_c_e1=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_c_e2=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
function_c_e3=Funktion darf nicht l\u00E4nger als 250 Zeichen sein.
languages_a_e1=Sprachen darf nicht l\u00E4nger als 250 Zeichen sein.
languages_b_e1=Sprachen darf nicht l\u00E4nger als 250 Zeichen sein.
lastname_a_e1=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
lastname_a_e2=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
lastname_a_e3=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
lastname_b_e1=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
lastname_b_e2=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
lastname_b_e3=Nachname darf nicht l\u00E4nger als 100 Zeichen sein.
mail_a_e1=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_a_e2=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_a_e3=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_b_e1=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_b_e2=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_b_e3=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_c_e1=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_c_e2=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mail_c_e3=E-Mail darf nicht l\u00E4nger als 250 Zeichen sein.
mobil_a_e1=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_a_e2=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_a_e3=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_b_e1=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_b_e2=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_b_e3=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_c_e1=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_c_e2=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
mobil_c_e3=Mobil darf nicht l\u00E4nger als 100 Zeichen sein.
nationality_a_e1=Nationalit\u00E4t/Staatsangeh\u00F6rigkeit darf nicht l\u00E4nger als 100 Zeichen sein.
nationality_b_e1=Nationalit\u00E4t/Staatsangeh\u00F6rigkeit darf nicht l\u00E4nger als 100 Zeichen sein.
note_a_e1=Bemerkung darf nicht l\u00E4nger als 2000 Zeichen sein.
note_b_e1=Bemerkung darf nicht l\u00E4nger als 2000 Zeichen sein.
notehost_a_e1=Hinweis f\u00FCr Gastgeber darf nicht l\u00E4nger als 2000 Zeichen sein.
notehost_b_e1=Hinweis f\u00FCr Gastgeber darf nicht l\u00E4nger als 2000 Zeichen sein.
noteorga_a_e1=Hinweis f\u00FCr Orga darf nicht l\u00E4nger als 2000 Zeichen sein.
noteorga_b_e1=Hinweis f\u00FCr Orga darf nicht l\u00E4nger als 2000 Zeichen sein.
pobox_a_e1=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_a_e2=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_a_e3=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_b_e1=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_b_e2=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_b_e3=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_c_e1=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_c_e2=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
pobox_c_e3=Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_a_e1=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_a_e2=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_a_e3=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_b_e1=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_b_e2=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_b_e3=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_c_e1=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_c_e2=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
poboxzipcode_c_e3=PLZ vom Postfach darf nicht l\u00E4nger als 50 Zeichen sein.
state_a_e1=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_a_e2=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_a_e3=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_b_e1=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_b_e2=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_b_e3=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_c_e1=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_c_e2=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
state_c_e3=Bundesland darf nicht l\u00E4nger als 100 Zeichen sein.
street_a_e1=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_a_e2=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_a_e3=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_b_e1=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_b_e2=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_b_e3=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_c_e1=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_c_e2=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
street_c_e3=Stra\u00DFe darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_a_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_a_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_a_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_b_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_b_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_b_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_c_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_c_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix1_c_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_a_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_a_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_a_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_b_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_b_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_b_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_c_e1=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_c_e2=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
suffix2_c_e3=Adresszusatz 1 darf nicht l\u00E4nger als 100 Zeichen sein.
title_a_e1=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
title_a_e2=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
title_a_e3=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
title_b_e1=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
title_b_e2=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
title_b_e3=Akad. Titel darf nicht l\u00E4nger als 250 Zeichen sein.
url_a_e1=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_a_e2=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_a_e3=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_b_e1=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_b_e2=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_b_e3=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_c_e1=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_c_e2=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
url_c_e3=WWW darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_a_e1=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_a_e2=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_a_e3=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_b_e1=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_b_e2=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_b_e3=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_c_e1=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_c_e2=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
zipcode_c_e3=PLZ darf nicht l\u00E4nger als 250 Zeichen sein.
internal_id=Die interne ID darf nicht l\u00E4nger als 45 Zeichen sein.
INTERNAL_ID=Interne ID

# ALTERNATIVE SALUTATIONS
SALUTATION_EDITABLE_TEXT=Hier k\u00F6nnen Sie Alternative Anreden f\u00FCr diese PDF-Vorlage erstellen
SALUTATION_TO_SALUTATION=wird zu
SALUTATION_ERROR_LOAD=Fehler beim Laden
SALUTATION_ERROR_EMPTY=Alternative Anrede darf nicht leer sein
SALUTATION_ERROR_SAVE=Fehler beim speichern
SALUTATION_ERROR_DELETE=Fehler beim l\u00F6schen
SALUTATION_ERROR_LENGTH=Alternative Anrede darf nicht l\u00E4nger als 100 Zeichen sein
