language=Fran\u00E7ais
language_short=fr

# BROWSER TAB-TITLE
BROWSER_TITLE_CATEGORY=Cat\u00E9gorie
BROWSER_TITLE_CLEANUP=Nettoyer
BROWSER_TITLE_COLOURS=Couleurs
BROWSER_TITLE_GENERAL_CONFIGS=Configurations g\u00E9n\u00E9ral
BROWSER_TITLE_TASKS=Devoirs
BROWSER_TITLE_DOCUMENT_TYPES=Types de documents
BROWSER_TITLE_IMPORT_DUPLICATE_ACCEPT=Statut d\u2019import\u200A\u2014\u200Aadopter les doublons
BROWSER_TITLE_ERROR_OCCURS=Une d\u00E9faillance est apparue
BROWSER_TITLE_EVENT_EDIT=Editer \u00E9v\u00E9nement
BROWSER_TITLE_EVENT_CREATE=Dresser nouveau \u00E9v\u00E9nement
BROWSER_TITLE_EVENT_SELECT=Choisir \u00E9v\u00E9nement
BROWSER_TITLE_PERSON_ASSIGN=Classer personne
BROWSER_TITLE_EVENT_SEARCH=Chercher \u00E9v\u00E9nement
BROWSER_TITLE_TASKS_EDIT=Editer devoir
BROWSER_TITLE_TASKS_CREATE=Dresser nouveau devoir
BROWSER_TITLE_EXPORT_PERSONDATA=Exportation des informations individuelles
BROWSER_TITLE_IMPORT_PERSONDATA=Importation des informations individuelles
BROWSER_TITLE_EVENT_GUESTLIST=Liste des invit\u00E9s pour \u00E9v\u00E9nement
BROWSER_TITLE_EVENT_EXPORT_DATA=G\u00E9n\u00E9rer le fichier de contr\u00F4le pour \u00E9v\u00E9nement
BROWSER_TITLE_IMPORT_STATUS=Statut de processus d\u2019importation
BROWSER_TITLE_HELP=Aide
BROWSER_TITLE_INFO_VERAWEB=Info sur VerA.web
BROWSER_TITLE_EVENT_LOCATION_EDIT=Editer le lieu de l\u2019\u00E9v\u00E9nement
BROWSER_TITLE_EVENT_LOCATION_CREATE=Entrer nouveau lieu de l\u2019\u00E9v\u00E9nement
BROWSER_TITLE_EVENT_LOCATION=Lieu de l\u2019\u00E9v\u00E9nement
BROWSER_TITLE_EMAIL_SUBMISSION_CREATE=Etablir nouveau mod\u00E8le d\u2019e-mail
BROWSER_TITLE_EMAIL_SUBMISSION_EDIT=Editer mod\u00E8le d\u2019e-mail
BROWSER_TITLE_EMAIL_SUBMISSION=Mod\u00E8les d\u2019e-mail
BROWSER_TITLE_PDF_TEMPLATE=Mod\u00E8les de PDF
BROWSER_TITLE_DISTRIBUTOR_CREATE=Dresser la liste de distribution
BROWSER_TITLE_DISTRIBUTOR_LIST=Liste de distribution
BROWSER_TITLE_EMAIL_WRITE_DISTRIBUTOR=Ecrire un e-mail \u00E0 la liste de distribution
BROWSER_TITLE_EMAIL_EDIT=Editer e-mail
BROWSER_TITLE_EMAIL_CREATE=Etablir nouveau e-mail
BROWSER_TITLE_EMAIL_OUTBOX=Bo\u00EEte d\u2019envoi d\u2019e-mail
BROWSER_TITLE_ROLE_WITH=avec le r\u00F4le
BROWSER_TITLE_ROLE_AVAILABLE=avec les r\u00F4les disponsibles
BROWSER_TITLE_ROLE_WITHOUT_INFO=sans informations des r\u00F4les
BROWSER_TITLE_SUCCESSFUL_LOGIN_ONE=Vous \u00EAtes inscrit
BROWSER_TITLE_SUCCESSFUL_LOGIN_TWO=au syst\u00E8me avec succ\u00E8s
BROWSER_TITLE_PERSON_EDIT=Editer personne
BROWSER_TITLE_PERSON_CREATE=Etablir nouvelle personne
BROWSER_TITLE_GUEST_ADD_EVENT=Ajouter invit\u00E9
BROWSER_TITLE_GUEST_HOST_ADD_EVENT=Choisir l\u2019h\u00F4te pour
BROWSER_TITLE_GUEST_SELECT=Choisir invit\u00E9
BROWSER_TITLE_GUEST_HOST_SELECT=Choisir l\u2019h\u00F4te
BROWSER_TITLE_SEARCH_REPLACE_PERSONDATA=Chercher et remplacer dans les informtation individuelle
BROWSER_TITLE_DUPLICATE_SEARCH=Recherche des doublons
BROWSER_TITLE_TASK_ADD_RESPONSIBLE=Choisir le responsable du devoir
BROWSER_TITLE_PERSON_DELETE=Supprimer la personne
BROWSER_TITLE_PERSON_LIST=Vue d\u2019ensemble des personnes
BROWSER_TITLE_SEARCH_REPLACE=Chercher et remplacer
BROWSER_TITLE_GUEST_HOST_SEARCH=Chercher l\u2019h\u00F4te
BROWSER_TITLE_PERSON_SEARCH=Chercher personne
BROWSER_TITLE_PERSON_DATA_SALUTATION=Donn\u00E9es de base\u200A\u2014\u200Atitres
BROWSER_TITLE_LOGIN_REPRESENTATIVE=Ouvrir une session en tant que suppl\u00E9ant
BROWSER_TITLE_STATISTIC_CREATE=Dresser statistique
BROWSER_TITLE_USER_CONFIGS=Param\u00E8tres utilisateur
BROWSER_TITLE_WORK_AREAS=Secteurs du travail
BROWSER_TITLE_OVERVIEW_EVENTS_YEAR=Aper\u00E7u complet du nombre des \u00E9v\u00E9nements
BROWSER_TITLE_OVERVIEW_EVENTS_MONTH=Aper\u00E7u complet du nombre des \u00E9v\u00E9nements par ann\u00E9e
BROWSER_TITLE_OVERVIEW_GUEST_HOST_EVENTS=Aper\u00E7u complet du nombre de tout les \u00E9v\u00E9nements d\u2019un h\u00F4te
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST_HOST=Aper\u00E7u complet du nombre de tout les \u00E9v\u00E9nements, rassembl\u00E9 par h\u00F4te
BROWSER_TITLE_OVERVIEW_GUEST_EVENTS=Aper\u00E7u complet de tout les \u00E9v\u00E9nements d\u2019un invit\u00E9
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_GUEST=Aper\u00E7u complet de tout les \u00E9v\u00E9nements, rassembl\u00E9 par invit\u00E9s
BROWSER_TITLE_OVERVIEW_EVENTS_SORT_PLACE=Aper\u00E7u complet de tout les \u00E9v\u00E9nements, trier par lieu de l\u2019\u00E9v\u00E9nement
BROWSER_TITLE_OVERVIEW_EVENTS_UNKNOWN_STATISTIC=STATISTIQUE INCONNU

# YOU MUST SET THESE PLACEHOLDERS WITH THE GENDER TYPE OF YOUR LANGUAGE FOR EACH OBJECT AS MALE OR FEMALE
GENDER_TYPE_CATEGORY=F\u00E9minin
GENDER_TYPE_CLIENT=Masculin
GENDER_TYPE_COLOR=F\u00E9minin
GENDER_TYPE_DELEGATION_FIELD=F\u00E9minin
GENDER_TYPE_DISTRIBUTOR=Masculin
GENDER_TYPE_DOCUMENT_TYPE=Masculin
GENDER_TYPE_EMAIL=F\u00E9minin
GENDER_TYPE_EVENT=F\u00E9minin
GENDER_TYPE_EVENT_LOCATION=Masculin
GENDER_TYPE_FUNCTION_OFFICIAL_TITLE=F\u00E9minin
GENDER_TYPE_GUEST=Masculin
GENDER_TYPE_MAIL_DRAFT=F\u00E9minin
GENDER_TYPE_PDF_TEMPLATE=F\u00E9minin
GENDER_TYPE_PERSON=F\u00E9minin
GENDER_TYPE_REPRESENTATIVE=F\u00E9minin
GENDER_TYPE_SALUTATION=F\u00E9minin
GENDER_TYPE_TASK=F\u00E9minin
GENDER_TYPE_USER=Masculin
GENDER_TYPE_WORKAREA=Masculin

# REPETITIVE OBJECTS IN THEIR SINGULAR- AND PLURAL-TYPE
GENERIC_ADDRESS_DATA_PLURAL=Coordonn\u00E9es
GENERIC_CATEGORY_SINGULAR=Cat\u00E9gorie
GENERIC_GUEST_CATEGORY_SINGULAR=Cat\u00E9gorie d\u2019invit\u00E9s
GENERIC_PERSON_CATEGORY_SINGULAR=Personne-Cat\u00E9gorie
GENERIC_KEYWORDS=Mots cl\u00E9s
GENERIC_CATEGORY_PLURAL=Cat\u00E9gories
GENERIC_CLIENT_SINGULAR=Mandant
GENERIC_CLIENT_PLURAL=Mandants
GENERIC_COLOR_SINGULAR=Couleur
GENERIC_COLOR_PLURAL=Couleurs
GENERIC_COMPANY_PLURAL=Enterprises
GENERIC_DELEGATION_FIELD_SINGULAR=Champ suppl\u00E9mentaire
GENERIC_DELEGATION_FIELD_PLURAL=Champs suppl\u00E9mentaire
GENERIC_DISTRIBUTOR_SINGULAR=Distributeur
GENERIC_DISTRIBUTOR_PLURAL=Distributeurs
GENERIC_EMAIL_SINGULAR=E-mail
GENERIC_EMAIL_PLURAL=E-mails
GENERIC_EVENT_SINGULAR=\u00C9v\u00E9nement
GENERIC_EVENT_PLURAL=\u00C9v\u00E9nements
GENERIC_EVENT_LOCATION_SINGULAR=Lieu de l\u2019\u00E9v\u00E9nement
GENERIC_EVENT_LOCATION_PLURAL=Lieux des \u00E9v\u00E9nements
GENERIC_FUNCTION_SINGULAR=Fonction
GENERIC_FUNCTION_PLURAL=Fonctions
GENERIC_GUEST_SINGULAR=Invit\u00E9
GENERIC_GUEST_PLURAL=Invit\u00E9s
GENERIC_GUEST_NONE=Aucun invit\u00E9
GENERIC_INSTITUTION_SINGULAR=Institution
GENERIC_INSTITUTION_PLURAL=Institutions
GENERIC_MAIL_DRAFT_SINGULAR=Mod\u00E8le
GENERIC_MAIL_DRAFT_PLURAL=Mod\u00E8les
GENERIC_PDF_TEMPLATE_SINGULAR=Mod\u00E8le de PDF
GENERIC_PDF_TEMPLATE_PLURAL=Mod\u00E8les de PDF
GENERIC_PDF_TEMPLATE_S_P=Mod\u00E8le(s) de PDF
GENERIC_PDF_FILE=Fichier PDF
GENERIC_OFFICIAL_TITLE_SINGULAR=D\u00E9signation officielle
GENERIC_OFFICIAL_TITLE_PLURAL=D\u00E9signations officielles
GENERIC_PERSON_SINGULAR=Personne
GENERIC_PERSON_PLURAL=Personnes
GENERIC_REPRESENTATIVE_SINGULAR=Suppl\u00E9ance
GENERIC_REPRESENTATIVE_PLURAL=Suppl\u00E9ances
GENERIC_SALUTATION_SINGULAR=Titre
GENERIC_SALUTATION_PLURAL=Titres
GENERIC_STATUS_OPEN=Ouvert
GENERIC_STATUS_ACCEPT=r\u00E9ponse positive
GENERIC_STATUS_DECLINE=r\u00E9ponse negative
GENERIC_STATUS_PARTICIPATED=Particip\u00E9
GENERIC_TASK_SINGULAR=t\u00E2che
GENERIC_TASK_PLURAL=t\u00E2ches
GENERIC_USER_SINGULAR=Utilisateur de PC
GENERIC_USER_PLURAL=Utilisateurs de PC
GENERIC_WORKAREA_SINGULAR=Secteur du travail
GENERIC_WORKAREA_PLURAL=Secteurs du travail
GENERIC_SELECT_ALL=S\u00E9lectionner tout
GENERIC_ADD_SELECTION=Ajuter la s\u00E9lection

# HEADER MESSAGES
HEADER_REPRESENTATION_FOR=Suppl\u00E9ance de
HEADER_COUNT_INSERT_ZERO_PART_ONE=Il a \u00E9t\u00E9
HEADER_COUNT_INSERT_ONE_PART_ONE=Il a \u00E9t\u00E9
HEADER_COUNT_INSERT_ELSE_PART_ONE=Ont \u00E9t\u00E9
HEADER_COUNT_INSERT_ZERO_PART_TWO=cr\u00E9\u00E9
HEADER_COUNT_INSERT_ONE_PART_TWO=cr\u00E9\u00E9
HEADER_COUNT_INSERT_ELSE_PART_TWO=cr\u00E9\u00E9
HEADER_COUNT_REMOVE_ZERO_PART_ONE=Il a \u00E9t\u00E9
HEADER_COUNT_REMOVE_ONE_PART_ONE=Il a \u00E9t\u00E9
HEADER_COUNT_REMOVE_ELSE_PART_ONE=Ont \u00E9t\u00E9
HEADER_COUNT_REMOVE_ZERO_PART_TWO=effac\u00E9
HEADER_COUNT_REMOVE_ONE_PART_TWO=effac\u00E9
HEADER_COUNT_REMOVE_ELSE_PART_TWO=effac\u00E9
HEADER_COUNT_UPDATE_ZERO_PART_ONE=Il a \u00E9t\u00E9
HEADER_COUNT_UPDATE_ONE_PART_ONE =Il a \u00E9t\u00E9
HEADER_COUNT_UPDATE_ELSE_PART_ONE=Ont \u00E9t\u00E9
HEADER_COUNT_UPDATE_ZERO_PART_TWO=chang\u00E9
HEADER_COUNT_UPDATE_ONE_PART_TWO=chang\u00E9
HEADER_COUNT_UPDATE_ELSE_PART_TWO=chang\u00E9
HEADER_ELEMENT_FEMALE_NO=pas de
HEADER_ELEMENT_FEMALE_ONE=une
HEADER_ELEMENT_FEMALE_NEW=nouvelle
HEADER_ELEMENT_MALE_NO=pas de
HEADER_ELEMENT_MALE_ONE=un
HEADER_ELEMENT_MALE_NEW=nouveau
HEADER_ELEMENT_NO_RECORD_SINGULAR=aucun enregistrement
HEADER_ELEMENT_NO_NEW_RECORD_SINGULAR=aucun enregistrement nouvel
HEADER_ELEMENT_ONE_RECORD_SINGULAR=un enregistrement
HEADER_ELEMENT_ONE_NEW_RECORD_SINGULAR=un enregistrement nouvel
HEADER_ELEMENT_PLURAL=Enregistrements
HEADER_ELEMENT_NEW_PLURAL=Nouveaux Enregistrements
HEADER_ELEMENT_NEW_TAB_HINT=ouvrir la page dans un nouvel onglet

# FIXES
GENERIC_EDIT=Modifier
GENERIC_OFFICIAL_TITLE_SHORT=D\u00E9sign. d. fonction
LETTER_COMMERCIAL=(C)
GENERIC_WRITE_EMAIL=Ecrire e-mail
GENERIC_SEARCH_FOR_PERSON=Chercher une personne
GENERIC_CHOOSE_ROLE=Choisir r\u00F4le
GENERIC_EVENT=\u00C9v\u00E9nement
GENERIC_EVENTS=\u00C9v\u00E9nements
SHOW_ALL_RECORDS=Afficher tout les enregistrements
SHOW_RECORDS_1=Afficher
SHOW_RECORDS_2=enregistrements
GENERIC_NO_WORKAREA_TEXT=Aucun

# GENERALLY USED
GENERIC_EMAIL_ADDRESS=Adresse \u00E9lectronique
GENERIC_FROM=De
GENERIC_LANGUAGE=Langue
GENERIC_LOGOUT=Fermeture de session
GENERIC_ON=A
GENERIC_ON_LOWERCASE=a
GENERIC_PAGE=Page
GENERIC_PAGES=Pages
GENERIC_PLACE=Place
GENERIC_ALTERNATIVE=Alternative

# MENU
MENU_PERSONS=Personnes
MENU_EVENTS=\u00C9v\u00E9nements
MENU_MANAGEMENT=Gestion
MENU_ADMINISTRATION=Administration

# ANMELDUNG
LOGIN_ERROR=Il y avait une erreur lors de l\u2019inscription. S\u2019il vous pla\u00EEt v\u00E9rifier votre nom d\u2019utilisateur et mot de passe.
GENERIC_PASSWORD=Mot de passe
LOGIN_REPRESENTATION=Ouvrir comme suppl\u00E9ance
GENERIC_ACCOUNT=Utilisateur
GENERIC_LOGIN=Ouvrir
GENERIC_CLEAR_FIELDS=vider les champs
HINT_LOGIN_ORGANISATION_ONE=Utiliser votre signe d\u2019organisation ou
HINT_LOGIN_ORGANISATION_TWO=Pr\u00E9nom.nom
HINT_LOGIN_ORGANISATION_THREE=comme nom d\u2019utilisateur s\u2019il vous pla\u00EEt.

# WELCOME SITE: FIRST PAGE AFTER LOGIN
administration=Administration
bittewaehlensieeineamtsbezeichnungfunktionaus=Choisissez un d\u00E9signation officielle s\u2019il vous pla\u00EEt
eskannzuunerwartetenfehlernkommenbittewendensiesichanihrenadministrator=Il peut entra\u00EEner des erreurs inattendues. Contactez votre administrateur s\u2019il vous pla\u00EEt.
willkommenbeiveraweb=Bienvenu \u00E0 VerA.web
WELCOME_TEXT_GRANT_READ_STANDARD_FIELDS=Avec VerA.web, vous pouvez afficher et exporter les donn\u00E9es de r\u00E9f\u00E9rence des personnes et des \u00E9v\u00E9nements.
WELCOME_TEXT_GRANT_READ_REMARK_FIELDS=Avec VerA.web, vous pouvez afficher et exporter les donn\u00E9es de r\u00E9f\u00E9rence et les remarques des personnes et des \u00E9v\u00E9nements.
WELCOME_TEXT_GRANT_EXPORT_PART_ONE=Avec VerA.web, vous pouvez afficher, exporter et importer
WELCOME_TEXT_GRANT_WRITE_FULL=les donn\u00E9es de r\u00E9f\u00E9rence et les remarques
WELCOME_TEXT_GRANT_EXPORT_PART_TWO=des personnes et des \u00E9v\u00E9nements.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_ONE=Avec VerA.web, vous pouvez afficher, modifier, eliminer, exporter et importer les donn\u00E9es de r\u00E9f\u00E9rence et les remarques des personnes et des \u00E9v\u00E9nements.
WELCOME_TEXT_GRANT_PARTIAL_ADMIN_PART_TWO=En outre, vous pouvez afficher et modifier les options sp\u00E9cifiques aux clients.
WELCOME_TEXT_GRANT_ADMIN_PART_ONE=Avec VerA.web, vous pouvez afficher, modifier, eliminer, exporter et importer les donn\u00E9es de r\u00E9f\u00E9rence et les remarques des personnes et des \u00E9v\u00E9nements.
WELCOME_TEXT_GRANT_ADMIN_PART_TWO=En outre, vous pouvez afficher et modifier les options globales et celles des clients.
WELCOME_TEXT_HELP=Pour obtenir des renseignements suppl\u00E9mentaires, veuillez presser sur \u00ABAide\u00BB.
WELCOME_TEXT_NO_ROLE=Aucun role est disponible pour votre connexion \u00E1 VerA.web. Veuillez conn\u00E9cter de nouveau avec un utilisateur ayant
GENERIC_AVAILABLE_DUPLICATES=Doublons disponibles

# ADMINISTRATION/ANREDEN
GENERIC_SALUTATIONS_MARKED=Titre(s) s\u00E9l\u00E9ctionn\u00E9(s)
GENERIC_ID=ID
GENERIC_MAIN_FORM=Forme de base
GENERIC_GENDER=Sexe
GENERIC_GENDER_FEMALE=F\u00E9minin
GENERIC_GENDER_MALE=Masculin
GENERIC_PAGING=Entr\u00E9e directe
MESSAGE_SUCCESS_INSERT_SALUTATION=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouveau titre
QUESTION_DELETE=R\u00E9ellement effacer?
GENERIC_NEW_PLURAL=nouveau
GENERIC_YES=Oui
GENERIC_NO=Non
MESSAGE_SUCCESS_DELETE_SALUTATION=Il a \u00E9t\u00E9 un titre effacer
MESSAGE_EXIST_MASTER_DATA_ENTRY=Il existe d\u00E9j\u00E0 une entr\u00E9e de donn\u00E9es de base sous le nom
GENERIC_NAME=Nom
GENERIC_NEW=Nouvel

# ADMINISTRATION/ARBEITSBEREICHE
GENERIC_WORK_FIELDS=Secteurs du travail
GENERIC_WORK_FIELDS_MARKED=Secteur(s) du travail s\u00E9l\u00E9ctionn\u00E9(s)
MESSAGE_MISSING_DATA=Aucun donn\u00E9e trouv\u00E9e
MESSAGE_INSERT_WORK_FIELD=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouveau secteur du travail
MESSAGE_FAIL_DELETE_WORK_FIELD=Il n\u2019y avait aucun secteur du travail effac\u00E9
MESSAGE_SUCCESS_DELETE_WORK_FIELD=Il a \u00E9t\u00E9 un secteur du travail effac\u00E9

# ADMINISTRATION/BENUTZER
GENERIC_USER=Utilisateur
GENERIC_USER_MARKED=Utilisateur(s) marqu\u00E9
GENERIC_USERNAME=Nom d\u2019utilisateur
GENERIC_USER_RIGHTS=Droits des utilisateurs
MESSAGE_SUCCESS_INSERT_USER=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouveau utilisateur
MESSAGE_SUCCESS_DELETE_USER=Il a \u00E9t\u00E9 effac\u00E9 un utilisateur
MESSAGE_FILL_USER_ROLE=Entrez un nom de r\u00F4le d\u2019utilisateur s\u2019il vou pla\u00EEt

# ADMINISTRATION/DOKUMENTTYPEN
GENERIC_TOOLTIP=Remarque
HINT_FORMAT_INFO=OOo 1.1 signifie OpenOffice 1.1 (.sxc fichier), OOo 2.0 signifie OpenOffice 2.0 (.ods fichier), xls signifie Microsoft Office (.xls fichier) et CSV signifie CSV format de fichier.
HINT_EVENT_MARK=Marque 50 et 99 sont automatiquement ajout\u00E9s \u00E0 de nouveaux \u00E9v\u00E9nements. Le marque 50 ne va pas cr\u00E9er un champ de texte.
GENERIC_DOCUMENT_TYPES_MARKED=Type(s) de documents s\u00E9l\u00E9ctionn\u00E9(s)
GENERIC_ADRESS_TYPE=Type d\u2019adresse
GENERIC_CHARSET=Jeu de caract\u00E8res
GENERIC_FORMAT=Format
GENERIC_PARTNER_DOCUMENT=Document pour partenaire
GENERIC_SORT=Trier
GENERIC_SIGN=Signe
GENERIC_GA=GA
GENERIC_SD=SD
GENERIC_BUSINESS=Commercial
GENERIC_PRIVATE=Priv\u00E9
GENERIC_MORE=Autre
GENERIC_LATIN=Latin
kyrillisch=Cyrillique
chinesisch=Chinois
eswurdeeindokumenttypgeloscht=Il a \u00E9t\u00E9 effac\u00E9 un type des documents
eswurdeeinneuerdokumenttypangelegt=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouveau type des documents

# ADMINISTRATION/E-MAIL-POSTAUSGANG
GENERIC_STATUS=Statut
GENERIC_SUBJECT=Objet
GENERIC_ERROR=Erreur
e-mails=E-mails
GENERIC_BLEND_IN_TECHNICAL_ERROR_MESSAGE=ins\u00E9rer message d\u2019erreur technique
GENERIC_ERROR_DESCRIPTION=Description d\u2019erreur

# ADMINISTRATION/E-MAIL-VORLAGEN
e-mail-vorlagen=Mod\u00E8le d\u2019e-mail
GENERIC_MARKED_TEMPLATES_PP=Mod\u00E8le(s) s\u00E9lectionn\u00E9(s)
GENERIC_INSERT_NEW_TEMPLATES=Cr\u00E9\u00E9 nouvel mod\u00E8le
GENERIC_TEMPLATE_NAME=Nom de mod\u00E8le
eswurdeeineneuevorlageangelegt=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouvel mod\u00E8le.
GENERIC_TEXT=Texte
GENERIC_PLACEHOLDER=Marque de r\u00E9servation
GENERIC_ADD=Ajouter
GENERIC_BACK_TO_TEMPLATES_LIST=Retourner \u00E0 la liste des mod\u00E8les

# ADMINISTRATION/FARBEN
GENERIC_CHROMATICITY=Valeur de la couleur
LETTERS_CHROMATICITY=R V B

# ADMINISTRATION/FUNKTIONEN/AMTSBEZEICHNUNGEN
markiertebezeichnung=D\u00E9signation s\u00E9l\u00E9ctionn\u00E9
GENERIC_LABELLING=D\u00E9signation
eswurdeeineneuefunktion/amtsbezeichnungangelegt=Il a \u00E9t\u00E9 cr\u00E9\u00E9 un nouvel fonction/titre.
eswurdeeinefunktion/amtsbezeichnunggeloscht=Il a \u00E9t\u00E9 effac\u00E9 und fonction/titre.

# ADMINISTRATION/KATEGORIEN
markiertekategorie=Cat\u00E9gorie(s) s\u00E9l\u00E9ctionn\u00E9e(s)
GENERIC_MARK_LONG=Signe de reconnaissance
GENERIC_RANK=Rang
GENERIC_EVENTS_PP=\u00C9v\u00E9nements
GENERIC_OCCASION=Ev\u00E9nement

# ADMINISTRATION/MANDANTEN
markierte(n)mandanten=Mandant(s) s\u00E9l\u00E9ctionn\u00E9(s)
GENERIC_DATA_NOT_ASSIGNED_TO_CLIENTS=Donn\u00E9es pas d\u00E9di\u00E9 au mandants
personen=Personnes
GENERIC_IMPORT_PROCEDURES=Processus d\u2019importation
veranstaltungorte=Lieux des \u00E9v\u00E9nements
GENERIC_ASSIGN_CLIENTS=Classer mandants

# ADMINISTRATION/PROGRAMMEINSTELLUNGEN
programeinstellungen=R\u00E9glage de programme
GENERIC_STANDARD_TABULATOR_CHOICE=S\u00E9lection standard de tabulations
GENERIC_MAIN_TABS=Onglets principaux
GENERIC_PERSONS_DATA=Donn\u00E9es personelles
GENERIC_MAILING_ADDRESSES=Adresses
GENERIC_SUBTABS_OF_PERSONS_DATA=Sous-onglets des \u00ABdonn\u00E9es personelles\u00BB
GENERIC_MAIN_PERSON=Personnage principal
GENERIC_PARTNER=Partenaire
GENERIC_SUBTABS_OF_MAILING_ADDRESSES=Sous-onglets des \u00ABAdresses\u00BB
GENERIC_STANDARD_CHOICE_OF_SELECTED_BOX=Choix standard du champ de s\u00E9lection \u00ABjeu de caract\u00E8res\u00BB
GENERIC_STANDARD_SALUTATIONS_AND_FREE_TEXT_FIELDS=Titres standard et Champs de texte libre
GENERIC_STANDARD_SALUTATION=Titre standard
GENERIC_STANDARD_SALUTATION_PARTNER=Titre standard Partenaire
GENERIC_FREE_TEXT_FIELD=Champ de texte libre
GENERIC_FREE_TEXT_FIELD_CONNECTOR=Connecteur des champs de texte libre
GENERIC_SHOW=affichage
GENERIC_HELP=Aide
GENERIC_HELP_LINK=Lien d\u2019aide
GENERIC_HELP_WINDOW=Fen\u00EAtre d\u2019aide
OPTION_HELP_WINDOW_1=Utiliser la fen\u00EAtre de navigateur actuelle
OPTION_HELP_WINDOW_2=Ouvrir nouvelle fen\u00EAtre de navigateur par appel
OPTION_HELP_WINDOW_3=Chaque fois que vous appelez la m\u00EAme fen\u00EAtre du navigateur ( pas le courant )
GENERIC_MISCELLANEOUS=Autres
GENERIC_PROTOCOL_TIME_CHANGE=Historique des modifications
GENERIC_PROTOCOL_COMMISIONING_TIME=D\u00E9riv\u00E9e de donn\u00E9es du journal
HINT_GIVE_THE_RETENTION_PERIOD=Entrez la p\u00E9riode de r\u00E9tention
GENERIC_YEARS=Ans
GENERIC_MONTHS=Mois
GENERIC_DAYS=Jours
GENERIC_MAILING_ADDRESS_BUSINESS=Adresse d\u2019affaires
GENERIC_MAILING_ADDRESS_PRIVATE=Adresse priv\u00E9
GENERIC_MAILING_ADDRESS_OTHERS=Autre Adresse
GENERIC_LABELLING_LATIN=Jeu de caract\u00E8res latins
GENERIC_LABELLING_ALTERNATIVE=Jeu de caract\u00E8res alternative
GENERIC_ADDRESS_ADDITIONAL=Compl\u00E9ment d\u2019adresse
GENERIC_VIEW_CONFIG=configuration de la vue

# ADMINISTRATION/REPORTS
GENERIC_REPORTS=Rapports
MESSAGE_WAITING_MESSAGE_LOG_REPORT=Selon la p\u00E9riode s\u00E9lectionn\u00E9e et le nombre r\u00E9sultant des donn\u00E9es, la g\u00E9n\u00E9ration du rapport peut prendre un certain temps. S\u2019il vous pla\u00EEt avoir un peu de patience.
GENERIC_DATE_BEGIN=Date de d\u00E9but
GENERIC_DATE_END=Date de fin
GENERIC_BACKUP_FIEDS=R\u00E9initialiser les champs
GENERIC_GENERATE_REPORT=Cr\u00E9er un rapport

# ADMINISTRATION/STELLVERTRETUNGEN
GENERIC_REPRESENTATIVES=Les d\u00E9l\u00E9gu\u00E9s
GENERIC_AVAILABILITY_FILTER=filtres de validit\u00E9
GENERIC_REPRESENTATIVES_ALL=Tous les d\u00E9l\u00E9gu\u00E9s
GENERIC_NO_REPRESENTATION_EXPIRED=Pas de repr\u00E9sentations expir\u00E9s
GENERIC_ONLY_CURRENT_REPRESENTATIONS=Repr\u00E9sentations actuelles uniquement
GENERIC_ROLE=R\u00F4le
GENERIC_REPRESENTATIVE=Repr\u00E9sentant
gultigab=Valable \u00E0 partir du
GENERIC_VALID_TILL=Expire
GENERIC_NO_DATA_FOUND=Aucune donn\u00E9e trouv\u00E9e

# ADMINISTRATION/VERANSTALTUNGSORTE
markierte=Lieu(x) marqu\u00E9(s)
GENERIC_ADD_NEW_EVENT_LOCATIONS=Nouveau lieu
GENERIC_CONTACT_PERSON=contact
GENERIC_FAX=Fax
e-mail=E-Mail
GENERIC_REMARK=Remarque
GENERIC_URL=URL
gps-daten=Les donn\u00E9es GPS
GENERIC_ROOM_NUMBER=Num\u00E9ro d\u2019appartement
EVENT_PLACES_CONFIRM_DELETE=S\u2019il vous pla\u00EEt confirmer la suppression des lieux

# VERWALTUNG/EINSTELLUNGEN
GENERIC_MANAGEMENT=Gestion
GENERIC_OPTIONS=Param\u00E8tres
GENERIC_SUBTABS_OF=Sous-onglets de
GENERIC_PERSONAL_DETAILED_VIEW=Vue d\u00E9taill\u00E9e des personnes
GENERIC_LIST_OF_GUESTS=Liste des invit\u00E9s
zusatzlichefelder=champs suppl\u00E9mentaires
GENERIC_POSTNUMBER_AND_CITY=Code Postale / Ville
GENERIC_LIST_OF_PERSONS=Liste des individus
MESSAGE_OPTIONS_WERE_SUCCESSFULLY_SAVED=Param\u00E8tres ont \u00E9t\u00E9 enregistr\u00E9s avec succ\u00E8s.

# VERWALTUNG/VERTRETUNGEN
markiertevertretung=Repr\u00E9sentations marqu\u00E9es
GENERIC_DELETE=Supprimer
eswurdeeineneuevertretungangelegt=Il a \u00E9t\u00E9 une nouvelle agence cr\u00E9\u00E9e
eswurdeeinevertretunggeloscht=Il a \u00E9t\u00E9 un repr\u00E9sentant supprim\u00E9
siemuseneinevertretereingeben=Vous devez entrer un repr\u00E9sentant
derbeginndervertretungmusvordemendeliegen=Le d\u00E9but de la repr\u00E9sentation doit \u00EAtre avant la fin
MESSAGE_REPORT_NUMBER_PART_1=Il y avait
vertretungengeloscht=Repr\u00E9sentations supprim\u00E9s
# VERWALTUNG/INFO
GENERIC_INFO=Info
GENERIC_INFORMATION_ABOUT_VERAWEB=Infos \u00E0 VerA.web
veraweb=VerA.web
GENERIC_VERSION=Version
build=Build
GENERIC_BUILD_NUMBER=Num\u00E9ro de Build
GENERIC_BUILD_TIME=Temps de Build (TUC)
GENERIC_REST_API=API REST
INFO_LIC_LIC=Licence
INFO_LIC_INFOS=Conditions d\u2019utilisation
INFO_LIC_DOCS=autres documents
INFO_LIC_SRC=code source
INFO_LIC_DEP=des d\u00E9pendances
INFO_VWOR_MANDATORY=Note: operation without the REST API is no longer permitted.
GENERIC_DATABASE=Base de donn\u00E9es
GENERIC_GROUPS=Groupes
GENERIC_NOT_AVAILABLE=indisponible

# ALLGEMEIN
GENERIC_YOU_ARE_HERE=Vous \u00EAtes ici
GENERIC_HOME=Page d\u2019acceuil
GENERIC_DISCARD_CHANGES=annuler les modifications

# TABELLEN
GENERIC_DATE=date
GENERIC_LASTNAME=Nom
GENERIC_FIRSTNAME=Pr\u00E9nom
GENERIC_INTERNAL_ID=ID interne
akwritemtsbezeichnung=Nom officiel
GENERIC_COMPANY_INSTITUTION=Soci\u00E9t\u00E9 / Institution
GENERIC_STREET=Rue
GENERIC_POST_NUMBER=Code postal
GENERIC_CITY=Domicile
GENERIC_MARKED_PERSONS_PP=Personne(s) S\u00E9l\u00E9ctionn\u00E9e(s)
expotieren=Export
GENERIC_ASSIGN_CATEGORIES=Attribuer des cat\u00E9gories
GENERIC_REMOVE_CATEGORIES=Retirer Cat\u00E9gories
GENERIC_ASSING_WORKAREA=Attribuer espace de travail
GENERIC_REMOVE_WORKAREA=Retirer espace de travail
GENERIC_EXECUTE=\u00C9xecuter
personenanzahlproseite=Personnes | Afficher par page
GENERIC_ALL=Tout
seite=Seite
GENERIC_DATE_OF_BIRTH=date de naissance
GENERIC_PLACE_OF_BIRTH=Lieu de naissance
GENERIC_NATIONALITY_CITIZENSHIP=Nationalit\u00E9
GENERIC_LANGUAGES=Langues
GENERIC_HINT_FOR_HOST=Remarque pour l\u2019h\u00F4te
GENERIC_ACCOUNT_OPENING_DATE=Date d\u2019accr\u00E9ditation
GENERIC_AT=\u00E0
GENERIC_OCLOCK=h
GENERIC_ORIGIN_DATA=Origine des donn\u00E9es

# DATEITYP
csv=CSV (Comma-Separated-Values)
x-manage-csv=X-Manage-CSV (X-Manage Kontakte)
csvpersdatanschrift=CSVPersdat+Anschrift (Comma-Separated-Values)
csvpersdat=CSVPersdat (Comma-Separated-Values)
csvpersdatkategorien=CSVPersdat+Kategorien (Comma-Separated-Values)

# PERSONEN/PERSONENUEBERSICHT
GENERIC_PERSON_SUMMARY=Vue d\u2019ensemble des personnes
GENERIC_SEARCH_PERSONS=Recherche des personnes
GENERIC_CREATE_PERSON=Nouvelle personne
GENERIC_PERSONS_DELETED=personnes supprim\u00E9s

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN
GENERIC_EDIT_PERSON=Editer la personne
GENERIC_DOCUMENTED_ON=Entr\u00E9e sur
GENERIC_LAST_EDITED_ON=Derni\u00E8re modification le
GENERIC_PERSONS_ID=Personnes-ID
GENERIC_OA=Connection online
GENERIC_OA_USERNAME=Nom d\u2019utilisateur (connection online)
zudieserpersonwurdedasentsprechendevorschaufeldnochnichterzeugt=La fen\u00EAtre de pr\u00E9visualisation correspondant n\u2019a pas encore \u00E9t\u00E9 g\u00E9n\u00E9r\u00E9 pour cet individu.
GENERIC_COPY_PERSON=copie personne
GENERIC_CREATE_TAG=\u00E9tiquette Produce
GENERIC_ASSIGN_TO_EVENT=Attribution d\u2019 un \u00E9v\u00E9nement
GENERIC_DELETE_PERSON=Afficher personne
GENERIC_STATISTIC=Statistique
ausstammdatenhinzufugen=Ajouter \u00E0 partir des donn\u00E9es de base

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/DOKUMENTTYPEN
GENERIC_GENERATE_ALL=g\u00E9n\u00E9rer tous

# PERSONEN/PERSONENUEBERSICHT/PERSON BEARBEITEN/KATEGORIEN
GENERIC_CATEGORIES_AND_OCCASIONS=Cat\u00E9gories et \u00E9v\u00E9nements

# PERSONEN/PERSONENUEBERSICHT/PERSONBEARBEITEN/STATISTIK
ubersichtuberalleveranstaltungeneinesgastes=Vue d\u2019ensemble de tous les \u00E9v\u00E9nements d\u2019un invit\u00E9.
GENERIC_VIEW_OVER_GUEST_EVENT=de
statistikfurgast=Statistique pour invit\u00E9
GENERIC_BEGIN=D\u00E9but

# PERSONEN/PERSONENSUCHE
GENERIC_SEARCH_PERSON=Recherche des personnes
GENERIC_SEARCH=Recherche
GENERIC_VALIDITY_DATE=Date d\u2019effet
GENERIC_ADVANCED_SEARCH=Recherche avanc\u00E9e
HINT_PLACEHOLDER=Remarque: Vous pouvez utiliser soi-disant wildcards dans la recherche, le \u00AB*\u00BB repr\u00E9sente un chiffre, et le \u00AB?\u00BB les caract\u00E8res individuels

# PERSONEN/NEUE PERSON ANLEGEN
MESSAGE_OSIAM_LOGIN_DATA_SUCCESFUL=Les donn\u00E9es de connexion ont \u00E9t\u00E9 cr\u00E9\u00E9 avec succ\u00E8s.
MESSAGE_OSIAM_LOGIN_DATA_EXIST=Les pouvoirs ont \u00E9t\u00E9 produits avec succ\u00E8s.

# PERSONEN/NEUE PERSON ANLEGEN
GENERIC_IS_COMPANY=Est une soci\u00E9t\u00E9
frau=Madamme
herr=Monsieur
lady=Lady
sir=Sir
GENERIC_PLEASE_CHOOSE=Veuillez s\u00E9lectionner
GENERIC_ACAD_TITLE=Niveau acad\u00E9mique
GENERIC_IN_COUNTRY=Domestique
GENERIC_HINT_FOR_ORGA=Remarque \u00E0 l\u2019organisation
GENERIC_COMPANY_SINGULAR=Soci\u00E9t\u00E9
GENERIC_COUNTRY=Pays
plz/postfach=Code postal / Bo\u00EEte postale
GENERIC_POST_OFFICE_BOX=Bo\u00EEte postale
iban=IBAN
bic=BIC
GENERIC_MOBILE=Mobile
LETTERS_WWW=WWW
dublettenprufungdurchfuhren=Effectuer la v\u00E9rification en double
zurpersonenubersicht=Vue d\u2019esnemble des personnes

# PERSONEN/SUCHEN UND ERSETZEN IN PERSONENDATEN
hinweiswennsiedenplatzhalterverwendenwerdenauchteilstuckeersetztsonstnurvollstandigedatenfelder=Note * Si vous utilisez le caract\u00E8re g\u00E9n\u00E9rique, \u00E9vite \u00E9galement \u00EAtre remplac\u00E9, sinon seuls les champs de donn\u00E9es compl\u00E8tes.
GENERIC_SEARCH_V=Recherche
GENERIC_REPLACE=Substitution
GENERIC_IN_THE_FOLLOWING_FIELDS=Dans les champs suivants
anrede/titel=Salutation / Titre
GENERIC_EMPLOYMENT_TITLE_SHORT=Nom officiel
GENERIC_ADDRESSES=Adresse
telefon/fax=Telefon / Fax
GENERIC_REPLACE_INDIVIDUALLY=Remplacer l\u2019unit\u00E9
GENERIC_REPLACE_ALL=Remplacer tout

# PERSONEN/DUBLETTENSUCHE
GENERIC_DUPLICATE_SEARCH=Recherche de doublons

# PERSONEN/EXPORT VON PERSONENDATEN
exportvonpersonendaten=Exporter des donn\u00E9es personnelles
HINT_EXPORT_MANDANT_PERSON=Avec cette fonction vous exportez seulement les personnes de vos clients actuels.
GENERIC_WITHOUT=sans
botschaften=ambassades
finanzamtsprecher=Porte-parole du minist\u00E8re des Finances
journalisten=Journalistes
lieferant=Fournisseur
nogs=NOGs
politik=Politique
pressevertreter=repr\u00E9sentants de la presse
wirtschaft=\u00E9conomie
GENERIC_EXPORT=Exportation
EXPORT_AS_CSV=Liste des invit\u00E9s compl\u00E8te
EXPORT_AS_CSV_SHORT=Liste des invit\u00E9s courte
GENERIC_START_EXPORT=D\u00E9marrer l\u2019exportation
ENCODING_TYPE_CYRILLIC=cyrillique
ENCODING_TYPE_WEST=ouest
ENCODING_TYPE_BALTIC=Baltique
ENCODING_TYPE_EAST=est
ENCODING_TYPE_TURKISH=turc
EXPORT_DATA_TYPE_CSV=CSV (Comma-Separated-Values)
EXPORT_DATA_TYPE_X_MANAGE_CSV=X-Manage-CSV (X-Manage contacts)
EXPORT_DATA_TYPE_CSVPERSDATA_ADDRESS=CSVPersdat+adresse (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA=CSVPersdat (Comma-Separated-Values)
EXPORT_DATA_TYPE_CSVPERSDATA_CATEGORY=CSVPersdat+categories (Comma-Separated-Values)
EXPORT_TITLE_CSV=CSV
EXPORT_TITLE_X_MANAGE_CSV=X-Manage-CSV
EXPORT_TITLE_CSVPERSDATA_ADDRESS=CSV donn\u00E9es personnelles+Adresses
EXPORT_TITLE_CSVPERSDATA=CSV donn\u00E9es personnelles
EXPORT_TITLE_CSVPERSDATA_CATEGORY=CSV donn\u00E9es personnelles+categories
HINT_EXPORT_CSV=Selon la quantit\u00E9 de champs export\u00E9s (cela d\u00E9pend particuli\u00E8rement du nombre de types de documents export\u00E9s et cat\u00E9gories), c\u2019est possible que MS Excel et Calc OO ne pourraient pas lire les donn\u00E9es export\u00E9es compl\u00E8tement.
HINT_EXPORT_CSVPERSDATA_ADDRESS=Il sera export\u00E9 que les blancs avec les onglets \u00ABdonn\u00E9es personnelles\u00BB, \u00ABadresses\u00BB, \u00ABtypes de documents\u00BB et leurs onglets subordonn\u00E9s. Selon la quantit\u00E9 de champs export\u00E9s il peut arriver que MS Excel et Calc OO les donn\u00E9es export\u00E9es ne peuvent \u00EAtre lus compl\u00E8tement.
HINT_EXPORT_CSVPERSDATA=Il sera export\u00E9 que les blancs avec le onglet \u00ABde donn\u00E9es \u00E0 caract\u00E8re personnel\u00BB, et son onglets subordonn\u00E9s. Selon la quantit\u00E9 de champs export\u00E9s il peut arriver que MS Excel et Calc OO les donn\u00E9es export\u00E9es ne peuvent \u00EAtre lus compl\u00E8tement.
HINT_EXPORT_CSVPERSDATA_CATEGORY=Il sera export\u00E9 que les blancs avec les onglets \u00ABde donn\u00E9es \u00E0 caract\u00E8re personnel\u00BB , \u00ABCat\u00E9gories\u00BB et ses onglets subordonn\u00E9s. Selon la quantit\u00E9 de champs export\u00E9s (en particulier, cela est export\u00E9 \u00E0 partir du nombre de cat\u00E9gories en fonction), il peut arriver que MS Excel et Calc OO les donn\u00E9es export\u00E9es ne peuvent \u00EAtre lus compl\u00E8tement.
SELECTION_CSV=Marquer tout
SELECTION_ONE=Marquer

# CSV SELEKTIONS FELDER
CSV_IS_COMPANY=Est une entreprise
CSV_SALUTATION=Salutation
CSV_ACADEMIC_TITLE=Titre acad\u00E9mique
CSV_FIRSTNAME=Pr\u00E9nom
CSV_NAME=Nom de famille
CSV_INLAND=Int\u00E9rieur
CSV_GENDER=Sexe
CSV_BIRTHDAY=Date de naissance
CSV_PLACE_OF_BIRTH=Lieu de naissance
CSV_ACC_DATE=Date d\u2019accr\u00E9ditation
CSV_LANGUAGES=Langues
CSV_NATIONALITY=Nationalit\u00E9
CSV_COMMENT=Remarque
CSV_HINT_ORGA=Note pour l\u2019organisation
CSV_HINT_GUEST=Note pour les h\u00F4tes
CSV_INTERNAL_ID=ID interne

CSV_CHANGE=Modifi\u00E9
CSV_CHANGE_BY=Modifi\u00E9 par
CSV_CREATE=Etabli
CSV_CREATE_BY=Cr\u00E9\u00E9 par
CSV_DELEGATE=D\u00E9l\u00E9gation
CSV_DIPLO=Date d\u2019accr\u00E9ditation
CSV_INLAND_ONE=Domestique 1
CSV_INLAND_TWO=Domestique 2
CSV_GENDER_GUEST=Invit\u00E9 de genre
CSV_GENDER_PERSON=Personne du genre
CSV_PICTURE_GAST=Photo UUID invit\u00E9
CSV_PICTURE_PERSON=Photo UUID personne
CSV_INVITE_GUEST=Invitation statut invit\u00E9
CSV_INVITE_PERSON=Invitation personne de statut
CSV_INVITE_TYPE=Type d\u2019invitation
CSV_HOST=H\u00F4te
CSV_KEY_WORD=Mots-cl\u00E9s
CSV_SPEAK_GAST=Invit\u00E9 de langue
CSV_SPEAK_PERSON=Personne de langue
CSV_LOGIN_NES=Connexion requise
CSV_STATE_GUEST=Nationalit\u00E9 Invit\u00E9
CSV_STATE_PERSON=Personne de nationalit\u00E9
CSV_NOTE_GUEST=Notehost invit\u00E9
CSV_NOTE_PERSON=Notehost personne
CSV_NOTE_ORGA_GUEST=Noteorga invit\u00E9
CSV_NOTE_ORGA_PERSON=Noteorga personne
CSV_ORDER_NR_GUEST=Num\u00E9ro de commande
CSV_ORDER_NR_PERSON=Num\u00E9ro de commande
CSV_OSIAM_LOGIN=Osiam Se connecter
CSV_RANK=Rang
CSV_RESERVE=R\u00E9serve
CSV_SEAT_GUEST=Invit\u00E9 au si\u00E8ge
CSV_SEAT_PERSON=Personne assise
CSV_TABLE_NR_GUEST=Num\u00E9ro de table invit\u00E9
CSV_TABLE_NR_PERSON=Num\u00E9ro de table

CSV_FUNCTION=Titre officiel / fonction
CSV_COMPANY=Soci\u00E9t\u00E9 / Institution
CSV_STREET=Rue
CSV_PLZ_PLACE=Code postal / Ville
CSV_PLACE=Lieu
CSV_FEDERAL_STATE=Etat
CSV_STATE=Pays
CSV_FEDERAL_STATE_POBOX=Zip / code postal
CSV_POBOX=Bo\u00EEte de bureau de poste
CSV_FON=T\u00E9l\u00E9phone
CSV_FAX=Fax
CSV_MOBIL=Mobile
CSV_MAIL=
CSV_WWW=www

CSV_CATEGORY_NAME=Cat\u00E9gorie
CSV_PERSON_CREATE=Personne cr\u00E9\u00E9e
CSV_PERSON_CREATE_BY=Personne cr\u00E9\u00E9e par
CSV_PERSON_CHANGED=Personne chang\u00E9e
CSV_PERSON_CHANGED_BY=Personne chang\u00E9e par
CSV_PERSON_DELETED=Personne supprim\u00E9e
CSV_PERSON_DATE_OVER=Date de la personne expir\u00E9e
CSV_PERSON_SOURCE_IMPORT=Importer une source de personne
CSV_W_NAME=Zone de travail
CSV_DELEGATION_LINK=Lien de d\u00E9l\u00E9gation
CSV_DELEGATION_USER=Utilisateur de d\u00E9l\u00E9gation
CSV_DELEGATION_PW=Mot de passe
CSV_PW_RESET_LINK=R\u00E9initialiser le mot de passe de d\u00E9l\u00E9gation

CSV_OPTIONAL_FIELD=Champ facultatif

# SELECTION HEADLINES
CSV_HEADLINE_MORE_FIELDS=Plus de champs
CSV_HEADLINE_OPTIONAL_FIELDS=Champs optionnels
CSV_HEADLINE_FUTHER_ADDRESSES=Adresses plus loin
CSV_HEADLINE_PERSON_B_E3=Donn\u00E9es personnelles accompagnant la personne e3
CSV_HEADLINE_PERSON_B_E2=Donn\u00E9es personnelles accompagnant la personne e2
CSV_HEADLINE_PERSON_H_E3=Principal des donn\u00E9es personnelles e3
CSV_HEADLINE_PERSON_H_E2=Donn\u00E9es personnelles principal e2
CSV_HEADLINE_FUTHER_ADDRESSES_PRIVAT=Adresses priv\u00E9es
CSV_HEADLINE_FUTHER_ADDRESSES_BUISNESS=Adresses Affaires
CSV_HEADLINE_PERSON_GUEST_DATA=Invit\u00E9s de donn\u00E9es personnelles
CSV_HEADLINE_PERSON_PARTNER=Partenaire de donn\u00E9es personnelles
CSV_HEADLINE_PERSON_H_PARTNER=Donn\u00E9es personnelles principales

# PERSONEN/IMPORT VON PERSONENDATEN
GENERIC_IMPORT_FROM_PERSONS_DATA=Importer des donn\u00E9es personnelles
HINT_IMPORT_SHORT_CONTENT=Remarque: Lors de l\u2019importation \u00E0 des contenus sur le terrain , qui sont fournis plus de VerA.web \u00EAtre adopt\u00E9es raccourcie.
GENERIC_TARGET_CLIENT=Client cible
GENERIC_IMPORT_DATA=Importer un fichier
GENERIC_DATA_TYPE=Type de fichier
GENERIC_FILE_ENCODING=Codage de fichier
GENERIC_AUTO_ENCODING=Unicode ou Windows \u00ABEurope de l\u2019Ouest\u00BB 1252 (d\u00E9tection automatique)
dateiauswahlen=Choisissez Fichier
keineausgewahlt=Aucun s\u00E9lectionn\u00E9
GENERIC_START_IMPORT=D\u00E9marrage de l\u2019importation

# PERSONENDROPDOWN
GENERIC_NEW_PERSON=Nouvelle personne
GENERIC_EXPORT_PERSONS=Exportation des personnes
GENERIC_IMPORT_PERSONS=Importation des personnes

# VERANSTALTUNGENDROPDOWN
GENERIC_EVENT_VIEW=Vue d\u2019ensemble des \u00E9v\u00E9nements
veranstaltunguuche=Rechercher des \u00E9v\u00E9nements
GENERIC_NEW_EVENT=Nouvel \u00E9v\u00E9nement
GENERIC_STATISTICS=Statistiques

# ADMINISTRATIONDROPDOWN
GENERIC_SALUTATIONS=Formules de politesse
e-mail-postausgang=E-mail d\u2019envoi
GENERIC_PROGRAM_PERFERENCES=Pr\u00E9f\u00E9rences

# VERANSTALTUNGSUEBERSICHT
GENERIC_END=Fin
GENERIC_HOST=H\u00F4te
GENERIC_EVENT_SEARCH=Recherche \u00E9v\u00E9nement
GENERIC_CREATE_NEW_EVENT=Cr\u00E9er un nouvel \u00E9v\u00E9nement
GENERIC_NUMBER_PER_PAGE=Afficher par page
seitexvony=Page x de y

# EVENT HEADER
EVENT_ID=ID de l\u2019\u00E9v\u00E9nement
EVENT_NAME=Nom de l\u2019\u00E9v\u00E9nement
EVENT_URL=URL de l\u2019\u00E9v\u00E9nement
EVENT_URL_MEDIA_REPRESENTATIVE=URL pour les repr\u00E9sentants des m\u00E9dias
EVENT_MAX_GUEST=Nombre maximum des invit\u00E9s
EVENT_MAX_RESERVE=Nombre maximum sur la liste d\u2019attente
EVENT_INVITATION_TYPE=Type d\u2019invitation
EVENT_INVITATION_TYPE_WITHOUT_PARTNER=sans Partenaire
EVENT_INVITATION_TYPE_ONLY_PARTNER=seulement Partenaire
EVENT_INVITATION_TYPE_WITH_PARTNER=avec Partenaire

# VERANSTALTUNG BEARBEITEN/ALLGEMEIN
GENERIC_EDIT_EVENT=Modifier l\u2019\u00E9v\u00E9nement
GENERIC_TO_GUEST_MANAGEMENT=Gestion des clients
GENERIC_GENERAL=G\u00E9n\u00E9ral
GENERIC_ADDITIONAL_PERSONS_DATA=Informations personnelles suppl\u00E9mentaires
kurzbereichnung=Nom court
GENERIC_OPEN_EVENT=\u00C9v\u00E9nement ouvert
umxuhr=\u00C0 x heures
veranstalgungsort=Lieu de l\u2019\u00E9v\u00E9nement
GENERIC_SEARCH_FOR_HOST=Recherche h\u00F4te
GENERIC_DELETE_HOST=Retirer h\u00F4te
GENERIC_HOST_PARTNER=Partenaire H\u00F4te
GENERIC_LOGIN_REQUIRED=Connexion requise
GENERIC_SUBSCRIPTION_OF_PRESS_REPRESENTATIVES_POSSIBLE=Enregistrement des repr\u00E9sentants de presse est possible.
GENERIC_SAVE_EVENT=Sauvegarder \u00E9v\u00E9nement
GENERIC_TO_EVENT_VIEW=Vue d\u2019ensemble des \u00E9v\u00E9nements

# VERANSTALTUNG BEARBEITEN/DOKUMENTTYPEN
GENERIC_DOCUMENT_TYPES_MARKED_DELETE=Supprimer la s\u00E9lection type de documents
GENERIC_REMOVE=Supprimer
GENERIC_ADD_NEW_DOCUMENT_TYPE=Nouveau type de documents
xvonydokumenttypen=x de y types de documents

# VERANSTALTUNG BEARBEITEN/AUFGABEN
GENERIC_ADD_NEW_TASK=Cr\u00E9ation d\u2019une nouvelle t\u00E2che
MESSAGE_NO_TASKS_FOR_THIS_EVENT=Il n\u2019y a pas de t\u00E2ches pour cet \u00E9v\u00E9nement.
GENERIC_SELECTED_ENTRIES=Entr\u00E9e(s) s\u00E9lectionn\u00E9e(s)
GENERIC_TITLE=Titre
GENERIC_RESPONSIBLE=responsable

# VERANSTALTUNG BEARBEITEN/AUFGABEN/AUFGABE ANLEGEN
GENERIC_TASKS_ID=T\u00E2che-ID
GENERIC_COMPLETION=ach\u00E8vement
GENERIC_PRIORITY=priorit\u00E9
GENERIC_DESCRIPTION=description
GENERIC_ADD_RESPONSIBLES=Personne responsable
verantwortlichenentfernen=Retirez personne responsable
GENERIC_SAVE_TASK=Enregistrer la t\u00E2che
GENERIC_BACK_TO_TASKS_VIEW=Liste des t\u00E2ches

# VERANSTALTUNG BEARBEITEN/FUNKTIONEN/AMTSBEZEICHNUNGEN
GENERIC_ADD_NEW_EMPLOYMENT_TITLE=Nouveau titre officielle
MESSAGE_NO_EMPLOYMENT_TITLES_FOUND=Pas de titres officiels ont \u00E9t\u00E9 trouv\u00E9s.

# VERANSTALTUNG BEARBEITEN/KATEGORIEN
GENERIC_ADD_NEW_KATEGORIES=Nouvelle cat\u00E9gorie

# VERANSTALTUNG BEARBEITEN/VORBEDINGUNGEN
GENERIC_PRECONDITION_PLURAL=Conditions pr\u00E9alables
EVENT_PRECONDITION_MARKED=Conditions pr\u00E9alables marqu\u00E9es
EVENT_PRECONDITION_ADD=Nouveau condition
EVENT_PRECONDITION_INVITATIONSTATUS=Statut de participation
EVENT_PRECONDITION_STARTDATE=Date de d\u00E9but
EVENT_PRECONDITION_NOT_FOUND=Aucune condition pr\u00E9alables trouv\u00E9e

# VERANSTALTUNGSSUCHE
nurinzukunftigenveranstaltungensuchen=Recherche des \u00E9v\u00E9nements dans le futur uniquement
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehreredasfureinzelne=Vous pouvez utiliser soi-disant wildcards dans la recherche, le * repr\u00E9sente un chiffre, et le ? les caract\u00E8res individuels.

# NEUE VERANSTALTUNG ANLEGEN
mitpartner=Avec partenaire
eswurdeeineneueveranstaltungangelegt=Un \u00E9v\u00E9nement a \u00E9t\u00E9 cr\u00E9\u00E9

# VERTEILER
angelegtvon=Cr\u00E9\u00E9e par
angelegtam=Cr\u00E9\u00E9e le
erzeugtausveranstaltung=Cr\u00E9ation de l\u2019\u00E9v\u00E9nement
mailclient_msoutlook=Microsoft Outlook

# STATISTIKEN
statistikauffolgendenzeitrahmeneinschranken=Cr\u00E9e limite de statistiques des \u00E9v\u00E9nements sur le calendrier suivant
statistiktypauswahlen=S\u00E9lectionner le type de statistiques
zeitrahmenbeginn=\u00C9ch\u00E9ancier d\u00E9but
zeitrahmenende=\u00C9ch\u00E9ancier fin
STATISTIC_RADIO_PER_YEAR=R\u00E9sum\u00E9 g\u00E9n\u00E9ral du nombre des \u00E9v\u00E9nements par ann\u00E9e
STATISTIC_RADIO_PER_MONTH=R\u00E9sum\u00E9 g\u00E9n\u00E9ral du nombre des \u00E9v\u00E9nements par mois
STATISTIC_RADIO_GROUPED_BY_HOST=Aper\u00E7u complet de tous les \u00E9v\u00E9nements , regroup\u00E9s par h\u00F4te
STATISTIC_RADIO_PER_HOST=Vue d\u2019ensemble des \u00E9v\u00E9nements d\u2019un h\u00F4te (avec recherche )
STATISTIC_RADIO_PER_GUEST=Vue d\u2019ensemble de tous les \u00E9v\u00E9nements d\u2019un invit\u00E9 (avec recherche )
STATISTIC_RADIO_GROUPED_BY_EVENT_PLACE=Vue d\u2019ensemble de tous les \u00E9v\u00E9nements tri\u00E9s par lieu
statistikerstellen=Cr\u00E9er Statistiques

# GAESTEVERWALTUNG DER VERANSTALTUNG
MAIN_PERSON_STATUS_ACCEPT = Personnage principal-R\u00E9ponse positive
MAIN_PERSON_STATUS_DECLINE = Personnage principal-R\u00E9ponse negative
MAIN_PERSON_STATUS_PARTICIPATED = Personnage principal-Particip\u00E9
MAIN_PERSON_STATUS_OPEN = Personnage principal-Ouvert
PARTNER_STATUS_ACCEPT = Partenaire-R\u00E9ponse positive
PARTNER_STATUS_DECLINE = Partenaire-R\u00E9ponse negative
PARTNER_STATUS_PARTICIPATED = Partenaire-Particip\u00E9
PARTNER_STATUS_OPEN = Partenaire-Ouvert
gasteverwaltungderveranstaltung=L\u2019administration des clients de l\u2019\u00E9v\u00E9nement
maxanzahlgaste=Nombre maximum des invit\u00E9s
gastedetails=Invit\u00E9 D\u00E9tails
offen=ouvrir
zusagen=engagements
absagen=annuler
teilnahmen=participations
aufplatz=a place
aufreserve=sur la r\u00E9serve
filter=Filter
platzwahl=Choix de l\u2019emplacement
lfdnr=Num\u00E9ro de s\u00E9rie
nichteingeladen=pas invit\u00E9(e)
laufendenummerberechnen=Calculer le nombre de s\u00E9rie
allestammdatenneuladen=Recharger tout donn\u00E9es de base
HINT_ENTRY_POINT=Entr\u00E9e directe: Il est possible pour quelqu\u2019un ou seulement \u00E0 un nom pr\u00E9nom\u200A\u2014\u200Aapr\u00E8s le tri.
HINT_GUEST_MANAGEMENT_FILTER=Lors de la cr\u00E9ation des listes d\u2019invit\u00E9s de filtres s\u00E9lectionn\u00E9s est consid\u00E9r\u00E9 comme votre top.
HINT_GUEST_MANAGEMENT_MARKED=Veuillez s\u00E9l\u00E9ctionner des clients \u00E0 exporter, sinon la liste compl\u00E8te sera export\u00E9e.
TABLE_BEFORE_GUEST=Invit\u00E9 pr\u00E9c\u00E9dent
TABLE_FIRST_GUEST=Invit\u00E9 principal
TABLE_LAST_GUEST=Dernier invit\u00E9
TABLE_NEXT_GUEST=Suivant invit\u00E9

# GAESTELISTE
GUEST_LIST_ALL_GUEST=Tous les invit\u00E9s
GUEST_LIST_ALL_GUEST_ON_PLACE=Tous les invit\u00E9s sur place
GUEST_LIST_ALL_GUEST_ON_RESERVE=Tous les invit\u00E9s comme r\u00E9serve
GUEST_LIST_APPLY_GUEST_FROM_EVENT=Prenez des invit\u00E9s de l\u2019\u00E9v\u00E9nement
GUEST_LIST_CATEGORY_ASSIGN=Attribuer des cat\u00E9gories
GUEST_LIST_CATEGORY_REMOVE=Retirer Cat\u00E9gories
GUEST_LIST_DISTRIBUTOR_CREATE=Cr\u00E9er un distributeur
GUEST_LIST_CONFIRM_ACTION=S\u2019il vous pla\u00EEt confirmer l\u2019action suivante
GUEST_LIST_DIDNT_CHANGE=La liste des invit\u00E9s n\u2019a pas \u00E9t\u00E9 modifi\u00E9
GUEST_LIST_EXPAND_ONE=Une personne a \u00E9t\u00E9 ajout\u00E9 a la liste des invit\u00E9
GUEST_LIST_EXPAND_MULTIPLE_PART_ONE=La liste des invit\u00E9s a \u00E9t\u00E9
GUEST_LIST_EXPAND_MULTIPLE_PART_TWO=\u00E9largi \u00E0 un invit\u00E9
GUEST_LIST_HINT_EXPORT_GUEST=Si vous marquez les clients individuels, seul ceux qui sont export\u00E9s, sinon la liste compl\u00E8te
GUEST_LIST_HINT_FILTER=Lors de la cr\u00E9ation des listes d\u2019invit\u00E9s choisi filtrer votre top est consid\u00E9r\u00E9
GUEST_LIST_HINT_RED_PERSON=Rouge d\u00E9pos\u00E9 gens \u00E9taient d\u00E9j\u00E0 en tant que \u00ABsupprimer\u00BB marqu\u00E9
GUEST_LIST_CREATED_NO_PERSON=a \u00E9t\u00E9 cr\u00E9\u00E9e sans une personne
GUEST_LIST_CREATED_ONE_PERSON=a \u00E9t\u00E9 cr\u00E9\u00E9e avec une persone
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_ONE=a \u00E9t\u00E9
GUEST_LIST_CREATED_MULTIPLE_PERSON_PART_TWO=cr\u00E9\u00E9e avec une persone
GUEST_LIST_NO_GUEST_INVITED=Aucun client \u00E9taient encore invit\u00E9s ou vos param\u00E8tres de filtrage ne \u200B\u200Bmontrent aucun r\u00E9sultat
GUEST_LIST_NUMBER_CALCULATE=Calculer le nombre de s\u00E9rie
GUEST_LIST_NUMBER_CALCULATED_SAVED=Le \u00ABnum\u00E9ro de s\u00E9rie\u00BB \u00E9tait pour tous les clients calcul\u00E9es et stock\u00E9es nouvelle
GUEST_LIST_ONLY_OPEN=Ouvrir seulement
GUEST_LIST_ONLY_ACCEPT=seuls engagements
GUEST_LIST_ONLY_DECLINED=seulement refus
GUEST_LIST_ONLY_PARTICIPATE=seulement la participation
GUEST_LIST_PERSON_DATA_RELOAD=Recharger tout donn\u00E9es de base
GUEST_LIST_RESERVE=R
GUEST_LIST_SEARCH_PERSON_ADD=Trouver des gens et l\u2019ajouter \u00E0 la liste des invit\u00E9s
GUEST_LIST_ADD_GUEST_FROM_EVENT=Prendre invit\u00E9s d\u2019 \u00E9v\u00E9nment

# GAESTELISTE ERSTELLEN
GUEST_LIST_CREATE=Cr\u00E9er une liste d\u2019invit\u00E9s
SELECT_OUTPUT_FORMAT=S\u00E9lectionner le format de sortie
LIST_GROUP_BY_CATEGORY_WITH_PARTNER=Liste regroup\u00E9s par cat\u00E9gories\u200A\u2014\u200Aavec des partenaires
LIST_GROUP_BY_CATEGORY_WITH_TEL=Liste regroup\u00E9s par cat\u00E9gories\u200A\u2014\u200Aavec Tel et le t\u00E9l\u00E9phone mobile.
LIST_GROUP_BY_CATEGORY_WITH_PARTNER_AND_FAX=Liste regroup\u00E9s par cat\u00E9gories\u200A\u2014\u200Aavec les partenaires et Fax
LIST_SORT_PARTNER_TEL=Liste par tri\u200A\u2014\u200Aavec Partner, T\u00E9l. et t\u00E9l\u00E9phone mobile
SORT_CRITERIA=Les crit\u00E8res de tri
SORT_AFTER=Trier par
CONTINUAL_NUMBER=num\u00E9ro de s\u00E9rie
anschliesendnach=puis, apr\u00E8s
zusatzlichesortierungnach=Suppl\u00E9mentaires Trier par

# GASTDETAILS
GUEST_DETAIL_HINT_GUEST_HOST=Conseil h\u00F4tes
GUEST_DETAIL_HINT_ORGANISATION_TEAM=Conseil Organisation
GUEST_DETAIL_INVITATION_STATUS=Statut d\u2019invitation
GUEST_DETAIL_SEAT_NUMBER=Num\u00E9ro de table
GUEST_DETAIL_TABLE_NUMBER=Num\u00E9ro de cours
gastdetails=D\u00E9tails des invit\u00E9s
HINT_GUEST_LIST_EDIT_PERSONDATA=Modifier ici les donn\u00E9es personnelles exclusivement dans le contexte des \u00E9v\u00E9nements actuels, pas des donn\u00E9es de base.
istgastgeber=H\u00F4te
reserve=Reserve
aufstammdatenzurucksetzen=Revenir aux donn\u00E9es de base
stammdatenbearbeiten=Modification des donn\u00E9es de base

# DOKUMENTTYPEN
dokumenttypwahlen=S\u00E9lectionner le type de documents
mitgliedsausweis=Carte de membre
etikett=\u00C9tiquette
tischkarte=Carte de table
adresstypundzeichensatzwahlen=Choisissez le type d\u2019adresse et jeu de caract\u00E8res
adresstyp=Type d\u2019adresse
datenbearbeiten=Modifier les informations
verbinder=Interconnexions
freitextfeldpartner=Champ de texte libre (Partenaire)
akatitel=Niveau acad\u00E9mique (Partenaire)
kontaktdaten=Contact
strase=Rue
postfachplz=Bo\u00EEte postale / Code postal
nummer=Nombre
zuruckzudenveranstaltungsdetails=Retour aux d\u00E9tails de l\u2019\u00E9v\u00E9nement

# PERSON BEARBEITEN/DOKUMENTTYPEN/BEARBEITEN
dokumenttypbearbeiten=Modifier le type de documents
dokument-id=Document-ID
dokument-name=Document-Nom
dokumenttypspeichern=Enregistrer Type de documents
zuruckzurdokumenttypenliste=Liste des Types de documents
anmeldedatenerzeugen=G\u00E9n\u00E9rer des informations d\u2019identification
esliegenkeinekategorienundereignissevor=Il n\u2019y a pas de cat\u00E9gories et d\u2019\u00E9v\u00E9nements avant.
beigrunhinterlegteneintragenhandeltessichumwiederkehrendeereignisse=En vert soulign\u00E9 entr\u00E9es est \u00E9v\u00E9nements r\u00E9currents.

# VERTEILERDETAILS
verteilerdetails=D\u00E9tails de la r\u00E9partition
verteilerversenden=Envoyer distribution
e-mail-clientaufrufen=Appel client E-mail
mailclient_other=Autre client de messagerie
verteilerverschickt=Le distributeur a \u00E9t\u00E9 envoy\u00E9 avec succ\u00E8s.
verteilerfehler=Le distributeur n\u2019a pas pu \u00EAtre envoy\u00E9 avec succ\u00E8s, r\u00E9essayer plus tard.

# FEHLEND
zurstartseite=Page d\u2019accueil
solldieneuekategorie=Tri de la
einsortiertwerden=nouvelle cat\u00E9gorie?
pflichtfelder=Les champs obligatoires
markiertekategorien=Cat\u00E9gories s\u00E9lectionn\u00E9s
markiertekategorienloschen=Supprimer les cat\u00E9gories s\u00E9lectionn\u00E9s
alledemarkieren=D\u00E9s\u00E9lectionner tout
furalleveranstaltungen=Pour tous les \u00E9v\u00E9nements
speichern=Sauvegarder
anderungsprotokollfurdenzeitraum=Changez Connexion pour la p\u00E9riode
objekt=Propri\u00E9t\u00E9
objektid=Identit\u00E9 de propri\u00E9t\u00E9
artderanderung=Type de changement
geandertefelder=champs modifi\u00E9s
datumauswahlen=Choisissez une date
folgendeaktionen=Actions suivantes
wurden=\u00C9TAIENT
durchgefuhrt=accompli
konnen=bo\u00EEte
aktuallisieren=Actualiser
cleanupjetztunwiderruflichdurchfuhren=Nettoyage d\u00E9sormais effectuer de mani\u00E8re irr\u00E9vocable.
essindderzeitkeinecleanupsmoglichnotig=Il n\u2019y a pas de nettoyages possibles / n\u00E9cessaires
nochkeineauswahlgetroffen=Aucune s\u00E9lection
oberflachenbeschriftungen=les \u00E9tiquettes de surface
zusatzfelder=champs suppl\u00E9mentaires
eswurdeeinzusatzfeld=Il y avait un champ suppl\u00E9mentaire
angelegt=\u00E9tabli
geandert=modifi\u00E9
geloscht=supprim\u00E9
feldbezeichnung=Nom de domaine
eingabetyp=Type d\u2019entr\u00E9e
erfolgreichgespeichert=Enregistr\u00E9e avec succ\u00E8s !
markiertendokumenttypen=Favoris type de documents
eigenesdokumentfurpartner=Document priv\u00E9 pour les partenaires
sortierreihenfolge=L\u2019ordre de tri
gastgebermitausgeben=H\u00F4tes avec sortie
iststandardfursteuerdatei=Est la norme pour le fichier de contr\u00F4le
format=Format
HINT_EXPORT_FORMAT=OOo 1.1 signifie OpenOffice 1.1 (.sxc fichier), OOo 2.0 signifie OpenOffice 2.0 (.ods fichier), xls signifie Microsoft Office (xls fichier) et CSV signifie CSV format de fichier.
HINT_EVENT_IDENTIFICATION=Marque 50 et 99 sont automatiquement ajout\u00E9s \u00E0 de nouveaux \u00E9v\u00E9nements. Le marque 50 ne va pas cr\u00E9er un champ de texte.
wirklichloschen=Vraiment supprimer
zumpersonenimport=Pour les personnes\u200A\u2014\u200AImport
importstatus=Importer Statut
importstatusvorhandenedublettenbearbeiten=Importer Statut : modifier les doublons existants
bittemarkierensiediezuimportierendenpersonen=S\u2019il vous pla\u00EEt choisir d\u2019importer personnes.
dublettendiedurchden=Doublons g\u00E9n\u00E9r\u00E9s par le
importhinzugefugtwerdenwurden=Importer serait ajout\u00E9
sindmiteinercheckboxgekennzeichnetdarunterbefindensichdiebereitsimsystemvorhandenenentsprechendendatensatze=,sont marqu\u00E9s avec une case \u00E0 cocher. Parmi ceux-ci sont d\u00E9j\u00E0 pr\u00E9sents dans le syst\u00E8me, les enregistrements correspondants.
umeinedubletteindenimportzuintegrierenmussensiesieubernehmen=Pour int\u00E9grer un doublet dans l\u2019importation, vous devez prendre en charge.
alsdubletteubernehmen=Prenez comme un doublon
markiertepersonenalsdubletteubernehmen=Prenez personne(s) s\u00E9lectionn\u00E9 en tant que duplicata
anzahlzuspeicherndedubletten=Nombre de stocker les doublons
eswurdenkeineeintragegefunden=Aucun \u00E9l\u00E9ment n\u2019a \u00E9t\u00E9 trouv\u00E9.
zuruckzumpersonenimport=Retour aux personnes importation
fehlermeldung=Message d\u2019erreur
beiderbearbeitungihreranfrageisteinfehleraufgetretenbittemeldensiediesihremadministrator=Traitement de votre demande une erreur est survenue. S\u2019il vous pla\u00EEt le signaler \u00E0 votre administrateur.
unbekannterfehler=Erreur inconnue.
markiertenkategorien=Cat\u00E9gories s\u00E9l\u00E9ctionn\u00E9es
markiertenkategorienentfernen=Supprimer les cat\u00E9gories s\u00E9lectionn\u00E9es
bitteauswahlen=Veuillez s\u00E9lectionner
dieveranstaltungandersiegeradegearbeitethabenwurdevoneinemanderenanwendergeloschtsiekonnennuneineneueveranstaltunganlegenoderanderweitigmitverawebarbeiten=L\u2019\u00E9v\u00E9nement , auquel vous venez travaill\u00E9 , a \u00E9t\u00E9 supprim\u00E9 par un autre utilisateur. Vous pouvez maintenant cr\u00E9er un nouvel \u00E9v\u00E9nement ou travailler autrement VerA.web.
bittebestatigensiedasspeicherndieserveranstaltung=S\u2019il vous pla\u00EEt confirmer l\u2019enregistrement de cet \u00E9v\u00E9nement
keingastgeberausgewahlt=Aucun h\u00F4te s\u00E9lectionn\u00E9
kurzbezeichnung=Nom court
maximalelangederwarteliste=La longueur maximale de la liste d\u2019attente
sollendiestammdatenumdiesenorterweitertwerden=Si les donn\u00E9es de base est \u00E9tendue \u00E0 un certain endroit
markiertendokumenttypenentfernen=Supprimer la s\u00E9lection type de documents
eswurdenkeinedokumenttypengefunden=Pas de types de documents ont \u00E9t\u00E9 trouv\u00E9s.
markiertenamtsbezeichnungen=Titre officiel S\u00E9lectionn\u00E9
markiertenamtsbezeichnungenentfernen=Supprimer Titre officiel S\u00E9lectionn\u00E9
zurveranstaltungssuche=\u00C0 la recherche des \u00E9v\u00E9nements
veranstaltungssuche=Recherche des \u00E9v\u00E9nements
suchergebnis=R\u00E9sultat de la recherche
bitteklickensieeinederaufgelistetenveranstaltungenanumdiegastezuubernehmen=S\u2019il vous pla\u00EEt cliquer sur l\u2019un des \u00E9v\u00E9nements \u00E9num\u00E9r\u00E9s \u00E0 recevoir des invit\u00E9s.
bitteklickensieeinederaufgelistetenveranstaltungenanumdiepersondieserveranstaltungzuzuordnen=S\u2019il vous pla\u00EEt cliquer sur l\u2019un des \u00E9v\u00E9nements \u00E9num\u00E9r\u00E9s \u00E0 associer la personne de cet \u00E9v\u00E9nement.
bitteklickensieeinederaufgelistetenpersonenanumdiesealsgastgeberzuuebernehmen=S\u2019il vous pla\u00EEt cliquer sur l\u2019une des personnes \u00E9num\u00E9r\u00E9es dans le but de mettre en \u00BDuvre ce que un h\u00F4te.
loschenvonveranstaltungenistnichtmoglich=Suppression des \u00E9v\u00E9nements est pas possible
weiteremeldungen=plusieurs messages.
bittebestatigensiedasloschendermarkiertenveranstaltungen=S\u2019il vous pla\u00EEt confirmer la suppression des \u00E9v\u00E9nements s\u00E9lectionn\u00E9s !
markierteveranstaltungloschen=Supprimer l\u2019\u00E9v\u00E9nement s\u00E9lectionn\u00E9
abbrechen=Annuler
markierteveranstaltungen=\u00C9v\u00E9nement(s) s\u00E9lectionn\u00E9(s)
markierteveranstaltungenloschen=Supprimer les \u00E9v\u00E9nements s\u00E9lectionn\u00E9s
zuruckzurgasteverwaltung=Retour \u00E0 Gestion des clients
zuruckzurgasteliste=Liste des invit\u00E9s
zuruckzurveranstaltungsdetails=Retour aux d\u00E9tails de l\u2019\u00E9v\u00E9nement
zuruckzurveranstaltungsstatistiken=Retour \u00E0 Statistiques de l\u2019\u00E9v\u00E9nement
zuruckzurveranstaltungsaufgabe=T\u00E2che d\u2019\u00E9v\u00E9nement
zuruckzurpersonensuche=Recherche de personnes
zuruckzusuchenundersetzen=Recherche et remplacement
zuruckzurveranstaltungssuche=Recherche des \u00E9v\u00E9nements
wahlensiebittezunachsteineodermehrereveranstaltungenaus=S\u2019il vous pla\u00EEt d\u2019abord choisir \u00E0 partir d\u2019un ou plusieurs \u00E9v\u00E9nements.
nurinzuunftigenveranstaltungensuchen=Rechercher Seuls les \u00E9v\u00E9nements futurs
zuruck=Revenir
siekonnenbeidersuchesogenannteplatzhalterverwendenderstehtfurmehrereunddasfureinzelnezeichen=Vous pouvez utiliser soi-disant wildcards dans la recherche, le * repr\u00E9sente un chiffre, et le ? les caract\u00E8res individuels.
bittebestatigensiedasspeicherndieseraufgabe=S\u2019il vous pla\u00EEt confirmer que vous enregistrez cet objet
verantworlichenhinzufugen=Ajouter personne responsable
verantworlichenentfernen=Retirer personne responsable
loschenvonaufgabenistnichtmoglich=Parti supprimer responsable supprimer des t\u00E2ches est pas possible
bittebestatigensiedasloschenvonaufgaben=S\u2019il vous pla\u00EEt confirmer la suppression des t\u00E2ches
ausgewahlteeintrageloschen=Supprimer les \u00E9l\u00E9ments s\u00E9lectionn\u00E9s
start=D\u00E9but
zursuche=aller \u00E0 la recherche
siesindalsvolladministratorangemeldetundexportierenhiermitmandantenubergreifend=Vous \u00EAtes connect\u00E9 comme \u00ABpleine administrateur\u00BB et l\u2019exportation par les pr\u00E9sentes \u00E0 travers clients.
sieexportierenmitdieserfunktionausschlieszlichpersonenausihremaktuellenmandanten=Avec cette fonction vous exportez seulement les personnes de votre client actuel.
event=\u00C9v\u00E9nement
keine=Non
category=Categorie
weitereoptionen=plus d\u2019options
anmerkung=note
anmerkungen=notes
markiertebezeichnunge=Nom s\u00E9lectionn\u00E9
markierteeintrageentfernen=Supprimer les \u00E9l\u00E9ments s\u00E9lectionn\u00E9s
eswurdenkeinedatengefunden=Aucune donn\u00E9e trouv\u00E9e
siehabenkeinedatenherkunftangegeben=Vous n\u2019avez pas d\u00E9clarer l\u2019origine des donn\u00E9es.
HINT_EXPORT_NOT_POSSIBLE_OPENOFFICE=Vous avez essay\u00E9 d\u2019importer un fichier OpenOffice. L\u2019importation directe n\u2019est pas possible dans la version actuelle de VerA.web. Enregistrer ce fichier d\u2019abord de votre feuille de calcul en tant que fichier-.csv s\u2019il vous pla\u00EEt.
HINT_EXPORT_NOT_POSSIBLE_STAROFFICE=Vous avez essay\u00E9 d\u2019importer un fichier StarOffice. L\u2019importation directe n\u2019est pas possible dans la version actuelle de VerA.web. Enregistrer ce fichier d\u2019abord de votre feuille de calcul en tant que fichier-.csv s\u2019il vous pla\u00EEt.
HINT_EXPORT_NOT_POSSIBLE_EXCEL=Vous avez essay\u00E9 d\u2019importer un fichier Microsoft Excel. L\u2019importation directe n\u2019est pas possible dans la version actuelle de VerA.web. Enregistrer ce fichier d\u2019abord de votre feuille de calcul en tant que fichier-.csv s\u2019il vous pla\u00EEt.
HINT_IMPORT_NOT_POSSIBLE_PDF=Vous avez essay\u00E9 d\u2019 importer un fichier PDF. Malheureusement ce n\u2019est pas possible dans la version actuelle de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_ZIP=Vous avez essay\u00E9 d\u2019 importer un fichier ZIP. Malheureusement ce n\u2019est pas possible dans la version actuelle de VerA.web.
HINT_IMPORT_NOT_POSSIBLE_EXE=Vous avez essay\u00E9 d\u2019 importer un fichier EXE. Malheureusement ce n\u2019est pas possible dans la version actuelle de VerA.web.
siehabenversuchteinedateimitderendung=Vous avez essay\u00E9 d\u2019importer un fichier avec l\u2019extension
zuimportierendiesistinderaktuellenversionvonverawebleidernichtmoglich=Malheureusement ce n\u2019est pas possible dans la version actuelle de VerA.web.
siehabenkeinedateiausgewahltoderdiesewarleer=Vous n\u2019avez pas s\u00E9lectionn\u00E9 un fichier ou c\u2019\u00E9tait vide.
esisteinunerwarteterfehlerbeimimportiereneinerdateiaufgetreten=Une erreur inattendue est survenue lors de l\u2019importation d\u2019un fichier.
vermutlichbefindetsichdieimportdateinichtimvomsystemerwartemformat=Probablement, le fichier d\u2019importation n\u2019est pas dans le format pr\u00E9vu du syst\u00E8me.
detailsanzeigen=Afficher les d\u00E9tails
beimimportkonnenfeldinhaltedielangeralsbeiverawebvorgesehensindgekurztubernommenwerden=Lors de l\u2019importation, les contenus de champs peuvent \u00EAtre raccourci, pour \u00EAtre adapter \u00E0 VerA.web.
alledokumenttypenderzuimportierendenpersonenmussenimsystemvorhandenseinsollderimportjetztgestartetwerden=Tous les types de documents des personnes \u00E0 importer doivent \u00EAtre pr\u00E9sents dans le syst\u00E8me. Voulez-vous lancer l\u2019importation maintenant?
umdublettenspeicherbarzumachenmussensiezunachstimbereichvorhandenedublettenubernommenwerden=Pour faire des doublons stock\u00E9s, ils doivent d\u2019abord \u00EAtre adopt\u00E9es dans le domaine de \u00ABdoublons existants\u00BB.
HINT_UMLAUT_COMPARISON=Notez que les tr\u00E9mas sont compar\u00E9 comme \u00E7a: \u00E4 avec ae, \u00F6 avec oe, \u00FC avec ue et \u00DF avec ss.
derimportisterstbeendetwennderbuttonimportabschlieszengeklicktwurde=L\u2019importation est termin\u00E9e lorsque le bouton \u00ABFin de l\u2019importation\u00BB a \u00E9t\u00E9 cliqu\u00E9.
derimportkannerstabgeschlossenwerdenwennspeicherbaredatensatzevorhandensind=L\u2019importation ne peut \u00EAtre effectu\u00E9e lorsque les dossiers enregistrables existent.
vorhandenedubletten=Doublons existants
vorhandenedublettenbearbeiten=Modifier les doublons existants
zuimportierendedatensatzeinsgesamt=Enregistrements au total pour importer
davondubletten=Doublons
davonspeicherbar=M\u00E9morisable
ignoriertefehlerdatensatze=Enregistrements d\u2019erreur ignorer
importabschlieszen=\u00C9xecuter l\u2019importation
siehabenkeinendatensatzimportiert=Vous avez import\u00E9 aucun enregistrement.
siehabeneinendatensatzimportiert=Vous avez import\u00E9 un enregistrement
siehaben=Vous avez
datensatzeimportiert=import\u00E9 des enregistrements.
nichtgewahlt=pas choisi
verfugbarerollen=R\u00F4les disponibles
passowrt=Mot de passe
inverteretunganmelden=Connectez-vous en repr\u00E9sentation
vornamenachname=Pr\u00E9nom.Nom
alsbenutzernamen=Comme nom d\u2019utilisateur
emailvorlage=Mod\u00E8le de courrier \u00E9lectronique
amtsbezfunktion=Nom officiel/Fonction
postfachnummer=Numero du bo\u00EEte postale
email=E-Mail
verteileranlegen=Cr\u00E9ation du distributeur
sielegeneinenneuenverteilerausderpersonensuche=Cr\u00E9er une nouvelle distribution de la recherche de personnes
sielegeneinenneuenverteilerausderveranstaltung=Cr\u00E9er une nouvelle distribution de l\u2019\u00E9v\u00E9nement
mit=avec
einerperson=une personne
sielegeneinenneuenverteiler_rest_an=
verteilername=Nom du distributeur
verteilerspeichern=Sauvegarder le distributeur
markierteadressen=Adresses s\u00E9l\u00E9ctionn\u00E9s
markierteadressenausdemverteilerloschen=Supprimer les Adresses s\u00E9l\u00E9ctionn\u00E9s
analleadressenversenden=Envoyer \u00E0 toutes les adresses
emailclientaufrufen=Appel client E-mail
esliegenkeineadressdatenfurdiesenverteilervor=Il n\u2019y a aucune information d\u2019adresse pour cette distribution.
esliegenkeineadressenfurdiesenverteilervor=Il n\u2019y a aucune adresse pour cette distribution.
esliegenkeinevorlagenvor=Il n\u2019y a aucun mod\u00E8le disponible
zuruckzurverteilerubersicht=Retour \u00E0 l\u2019aper\u00E7u de distributeur
eswurdekeineemailzumversendengespeichert=Il a \u00E9t\u00E9 sauvegard\u00E9 aucun e-mail pour envoyer
eswurdeeineemailzumversendengespeichertdiesewirdnunautomatischversendet=Il a \u00E9t\u00E9 stock\u00E9 un email automatiquement. Ceci enverra automatiquement maintenant.
emailszumversendengespeichertdiesewerdennunautomatischversendet=Enregistr\u00E9 automatiquement les emails \u00E0 envoyer. Ceux-ci sont maintenant automatiquement envoy\u00E9s.
markiertenverteiler=Distribution s\u00E9lectionn\u00E9e
markierteverteilerloschen=Supprimer la distribution s\u00E9lectionn\u00E9e
persondendaten=Donn\u00E9es de la personne
solldiesergastaufplatzgesetztwerden=Doit \u00EAtre utilis\u00E9 ce guest sur un lieu?
solldiepartnerinderpartnermiteingeladenwerden=Les partenaires devraient \u00EAtre invit\u00E9s?
aktuellepersonwirklichentfernen=Supprimer personne actuelle?
personspeichern=Sauvegarder la personne
mitarbeiteraktualisieren=Mettre \u00E0 jour tous les employ\u00E9s
zurpersonenliste=\u00C0 la liste de personne
zurpersonenuebersicht=Vue d\u2019ensemble des Personnes
zurueckzurveranstaltung=Retour \u00E0 l\u2019\u00E9v\u00E9nement
zurdublettensuche=\u00C0 la recherche de double
zurckzumsuchergebnis=Retour aux r\u00E9sultats de la recherche
diesepersonwurdeerfolgreichzurgaestelistederveranstaltung=Cette personne a \u00E9t\u00E9 correctement ajout\u00E9e \u00E0 la liste des invit\u00E9s pour l\u2019\u00E9v\u00E9nement
hinzugefuegt=
diesepersonwurdenichthinzugefuegtdasiebereitsaufdergaestelistesteht=Cette personne n\u2019\u00E9tait pas ajout\u00E9e car elle est d\u00E9j\u00E0 sur la liste des invit\u00E9s.
diesepersonwurdebereitsalsgeloeschtmarkiertundwirdbeimsuchennichtmehrangezeigt=Cette personne a \u00E9t\u00E9 marqu\u00E9 comme \u00E9tant supprim\u00E9 et n\u2019est plus affich\u00E9e lors de la recherche.
personanlegen=Cr\u00E9ation d\u2019une personne
eswurdenkeinedublettengefundensiekoennenjetztweiteredateneingebenunddiedatenspeichern=Aucun doublon trouv\u00E9. Vous pouvez entrer davantage les donn\u00E9es et les enregistrer.
bittegebensiezunaechstden=Tout d\u2019abord pr\u00E9ciser le pr\u00E9nom et le nom et effectuer la v\u00E9rification des doublons.
vorundnachnamen=
sowieunteranschriftendie=aussi bien que
anundfuhrendiedublettenprufungdurch=
beifirmenwaehlensiediecheckbox=Les entreprises cliquent sur la case \u00E0 cocher et puis entrez le nom de l\u2019entreprise. Ensuite, le syst\u00E8me v\u00E9rifie vos entr\u00E9es sur les doublons.
undtragendanndenfirmennameneindassystempruftihreangabendaraufhinaufdubletten=
liegtkeinedublettevorkoennensieweiteredateneingebenunddiedatenspeichern=Aucun doublon n\u2019existe, vous pouvez entrer davantage les donn\u00E9es et les enregistrer.
geschaeftlich=pour les entreprises
privat=priv\u00E9
zurueckzurpersonensuche=Recherche des personnes
zurueckzurpersonenuebersicht=Retour au sommaire personne
zurueck=Retour
dublettenpruefungdurchfuehren=Effectuer la v\u00E9rification des doublons
zurueckzumsuchergebnis=Retour aux r\u00E9sultats de la recherche
personspeicherndublettenpruefung=Sauvegarder la personne\u200A\u2014\u200Av\u00E9rification des doublons
neueneintraganlegen=Cr\u00E9ation d\u2019une nouvelle entr\u00E9e
existierendeneintragbearbeiten=Modifier l\u2019entr\u00E9e existante
eswurdenkeinedublettengefunden=Aucun doublon n\u2019ont \u00E9t\u00E9 trouv\u00E9s.
hinzufuegen=Ajouter
ausgewaehltepersonenzurveranstaltunghinzufuegen=Ajouter des personnes s\u00E9lectionn\u00E9 \u00E0 l\u2019\u00E9v\u00E9nement.
personerfassen=Saisir personne
dublettenanlegen=Cr\u00E9ation de doublons
abbrechenundzurueck=Annuler et retourner
gastsuchenveranstaltung=Chercher invit\u00E9\u200A\u2014\u200A\u00C9v\u00E9nement
gastsuchen=Chercher invit\u00E9
verantwortlichenfueraufgabesuchen=La recherche de ceux charg\u00E9s de t\u00E2che
verantwortlichenfueraufgabehinzufugen=Ajouter responsable pour t\u00E2che
gastgeberhinzufuegen=Ajouter h\u00F4te
personensuchegastgeberhinzufugen=Recherche de personne: Ajouter h\u00F4te
gasthinzufuegen=Ajouter invit\u00E9
personensuchegasthinzufugen=Recherche de personne: Ajouter invit\u00E9
personfirma=Personne/Compagnie
weitereangaben=Plus d\u2019informations
keinekategoriezugeordnet=Sans cat\u00E9gorie
keinarbeitsbereichzugeordnet=Aucun espace de travail assign\u00E9
keinarbeitsbereich=Aucun espace de travail
gueltigkeitsdatum=Date d\u2019effet
biszudiesemdatum=Jusqu\u2019\u00E0 cette date
abdiesemdatum=\u00C0 partir de cette date
angenaudiesemdatum=A exactement cette date
datumauswaehlen=choisir une date
HINT_SEARCH_MULTIPLE=La recherche prend en charge la recherche des cat\u00E9gories multiples. Pour s\u00E9lectionner plusieurs cat\u00E9gories, s\u2019il vous pla\u00EEt maintenez enfonc\u00E9 le bouton de la souris et faites glisser le vol stationnaire sur dans la recherche de consid\u00E9rer les cat\u00E9gories. Par ailleurs, CTRL-clic avec le bouton gauche de la souris, vous pouvez cliquer sur les cat\u00E9gories \u00E0 prendre en consid\u00E9ration. Veuillez noter que les deux cat\u00E9gories du pseudo \u00AB All \u00BB et \u00AB None \u00BB ainsi que d\u2019autres cat\u00E9gories ne peuvent pas \u00EAtre s\u00E9lectionn\u00E9es
waehlensiebittezunaechsteinekategorieaus=Veuillez d\u2019abord s\u00E9lectionner une cat\u00E9gorie.
wollensiediesepersonbzwdiesengastderausgewaehltenkategoriezuordnen=Voulez-vous assigner la cat\u00E9gorie s\u00E9l\u00E9ctionn\u00E9e \u00E0 la personne
Vous souhaitez attribuer \u00E0 cette personne ou cet invit\u00E9 de la cat\u00E9gorie s\u00E9lectionn\u00E9e?
eswurdekeinekategoriezugeordnet=Il \u00E9tait associ\u00E9 \u00E0 aucune cat\u00E9gorie
wollensiepersonenbzwgaestederausgewaehltenkategoriezuordnen=Voulez-vous assigner la cat\u00E9gorie s\u00E9l\u00E9ctionn\u00E9e aux %s personnes
Vous voulez supprimer %s les personnes ou l\u2019invit\u00E9 de la cat\u00E9gorie s\u00E9lectionn\u00E9e ?
eswurdenkeinekategorienzugeordnet=Aucune cat\u00E9gorie n\u2019\u00E9tait associ\u00E9s
eswurdenkeinekategoriengefunden=Aucune cat\u00E9gorie trouv\u00E9e
wollensiediesepersonenbzwdiesengastausderausgewaehltenkategorieentfernen=Voulez-vous supprimer cette personne ou cette invit\u00E9 \u00E0 partir de la cat\u00E9gorie s\u00E9lectionn\u00E9e
eswurdekeinekategorieentfernt=Il n\u2019y a aucune cat\u00E9gorie enlev\u00E9.
wollensiepersonenbzwgaesteausderausgewaehltenkategorieentfernen=Vous voulez supprimer %s personnes ou invit\u00E9es de la cat\u00E9gorie s\u00E9lectionn\u00E9e ?
eswurdenkeinekategorienentfernt=Pas de cat\u00E9gories ont \u00E9t\u00E9 supprim\u00E9es.
zuweisen=Assigner
waehlensieeinekategorieauswelchesie=S\u00E9lectionner une cat\u00E9gorie que vous souhaitez
moechten=
alleentfernen=Supprimer tous
siehabenkeinekategorienkonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Vous avez configur\u00E9 aucun les cat\u00E9gories. Vous pouvez d\u00E9finir dans le panneau d\u2019administration en vertu de l\u2019article.
definieren=
siehabenpersonenausgewaehltabhaengigvonderanzahlderausgewaehltenpersonenkanndieaktioneinegewissezeitinanspruchnehmen=Vous avez s\u00E9lectionn\u00E9 %s personne(s). Selon le nombre de personnes s\u00E9lectionn\u00E9es, l\u2019action peut prendre un certain temps.
waehlensiebittezunaechsteinenarbeitsbereichaus=Veuillez d\u2019abord s\u00E9lectionner un espace de travail.
wollensiediesepersonbzwdiesengastdenausgewaehltenarbeitsbereichzuordnen=\u00C0 attribuer \u00E0 cette personne ou cet invit\u00E9 de l\u2019espace de travail s\u00E9lectionn\u00E9?
eswurdekeinarbeitsbereichzugeordnet=Il a \u00E9t\u00E9 associ\u00E9 aucun espace de travail.
wollensiediesenpersonenbzwdiesengaestedenausgewaehltenarbeitsbereichzuordnen=\u00C0 attribuer \u00E0 ces personnes ou ces invit\u00E9s de l\u2019espace de travail s\u00E9lectionn\u00E9?
eswurdenkeinearbeitsbereichzugeordnet=Aucun espaces de travail n\u2019\u00E9taient associ\u00E9s
wollensiediezuordnungdieserpersonbzwdiesemgastzumausgewaehltenarbeitsbereichaufheben=Souhaitez vous dissocier de cette personne ou cet invit\u00E9 \u00E0 l\u2019espace de travail s\u00E9lectionn\u00E9?
eswurdekeinarbeitsbereichaufgehoben=Il \u00E9tait \u00E0 pr\u00E9sent lev\u00E9 pas un espace de travail
wollensiediezuordnungvonpersonenbzwgaestenzumausgewaehltenarbeitsbereichaufheben=Souhaitez vous dissocier ces %s personnes ou ces invit\u00E9 \u00E0 l\u2019espace de travail s\u00E9lectionn\u00E9?
wollensiediesepersonbzwdiesengastdemausgewaehltenarbeitsbereichzuordnen=Vous souhaitez attribuer \u00E0 cette personne ou cet invit\u00E9 de l\u2019espace de travail s\u00E9lectionn\u00E9?
wollensiepersonenbzwgaestedemausgewaehltenarbeitsbereichzuordnen=\u00C0 attribuer %s personnes ou invit\u00E9s de l\u2019espace de travail s\u00E9lectionn\u00E9?
waehlensieeinenarbeitsbereichauswelchensie=S\u00E9lectionner un espace de travail, qui vous
siehabenkeinearbeitsbereichekonfiguriertdiesekoennensieimadministrationsbereichunterdempunkt=Vous n\u2019avez pas configur\u00E9 des espaces de travail. Vous pouvez le faire dans le panneau d\u2019administration en vertu de l\u2019article
administrationallestellvertretungenimmandanten=Administration\u200A\u2014\u200Atous les d\u00E9l\u00E9gu\u00E9s dans le client
administrationallestellvertretungen=Administration\u200A\u2014\u200Atous les d\u00E9l\u00E9gu\u00E9s
verwaltungpersoenlichevertretungen=Gestion\u200A\u2014\u200Arepr\u00E9sentants personnels
vertretung=Repr\u00E9sentation
markiertevertretungen=Repr\u00E9sentation(s) s\u00E9l\u00E9ctionn\u00E9e(s)
loeschen=Supprimer
markiertevertretungenloeschen=Supprimer des repr\u00E9sentations s\u00E9lectionn\u00E9es
gueltigab=valable \u00E0 partir de
gueltigbis=valable jusqu\u2019au
bitteauswaehlen=Veuillez s\u00E9lectionner
gaestelisteerstellenfuerveranstaltungeventshortname=Cr\u00E9er la liste des invit\u00E9s pour l\u2019\u00E9v\u00E9nement: $!event.shortname
gaesteverwaltungderveranstaltung=Gestion des invit\u00E9s de l\u2019\u00E9v\u00E9nement
gaestelisteerstellen=Cr\u00E9er une liste d\u2019invit\u00E9s
ausgabeformatwaehlen=S\u00E9lectionner le format de sortie
listenachkategoriengruppiertmitpartner=Liste regroup\u00E9es par cat\u00E9gories\u200A\u2014\u200Aavec partenaire
listenachkategoriengruppiertmittelundmobiltelefon=Liste regroup\u00E9es par cat\u00E9gories\u200A\u2014\u200Aavec t\u00E9l\u00E9phone et t\u00E9l\u00E9phone portable
listenachkategoriengruppiertmitpartnerundfax=Liste regroup\u00E9es par cat\u00E9gories\u200A\u2014\u200Aavec partenaire et fax
listenachsortierungmitpartnertelundmobiltelefon=Liste tri\u00E9e\u200A\u2014\u200Aavec les partenaires, t\u00E9l\u00E9phone et t\u00E9l\u00E9phone portable
listenachsortierungmitinterneridundadresse=Liste tri\u00E9e\u200A\u2014\u200Aavec ID interne et adresse
tisch=Table
zusaetzlichesortierungnach=Un tri suppl\u00E9mentaire
zurueckzurgaesteverwaltung=Gestion des invit\u00E9s
verwaltungallebenutzerimmandanten=Gestion\u200A\u2014\u200Atous les utilisateurs du mandant
verwaltungallebenutzer=Gestion\u200A\u2014\u200Atous les utilisateurs
markiertenbenutzer=Utilisateur(s) s\u00E9l\u00E9ctionn\u00E9(s)
markiertenbenutzerloeschen=Supprimer l\u2019utilisateur s\u00E9lectionn\u00E9
neuenbenutzererstellen=Cr\u00E9er un nouvel utilisateur
leseneingeschraenkt=Lecture restreinte
lesenuneingeschraenkt=Lecture plein
lesenundschreibeneingeschraenkt=Lire et \u00E9crire restreint
lesenundschreibenuneingeschraenkt=Lire et \u00E9crire sans limitation
mandantadministrieren=Administration mandant
administrieren=Administration
stellvertretung=D\u00E9l\u00E9gu\u00E9
bittewahlensiedierolleausdiesievertretenmochten=Veuillez s\u00E9lectionner le r\u00F4le que vous souhaitez repr\u00E9senter.
benutzerrolle=R\u00F4le d\u2019utilisateur
vertreten=repr\u00E9sent\u00E9e
statistikfurgastgeber=Statistiques pour les h\u00F4tes
imzeitraumvom=Dans la p\u00E9riode allant du
biszum=jusqu\u2019\u00E0 la
bis=\u00E0
auswartigesamtintranetstil=Minist\u00E8re des affaires \u00E9trang\u00E8res intranet-style
klickensieeinederaufgelistetenpersonenanumsiederaufgabehinzuzufugen=Cliquez sur une des personnes inscrites pour les ajouter \u00E0 la t\u00E2che
eswurdeeinepersongeloscht=Aucune personne a \u00E9t\u00E9 supprim\u00E9.
eswurdekeinepersongeloscht=Elle a \u00E9t\u00E9 supprim\u00E9e aucune personne.
personengelouscht=personnes effac\u00E9s
derarbeitsbereichwurdeerfolgreichhinzugefugt=L\u2019aire de travail a \u00E9t\u00E9 ajout\u00E9 avec succ\u00E8s.
diearbeitsbereichewurdenerfolgreichentfernt=Les domaines d\u2019activit\u00E9 ont \u00E9t\u00E9 correctement supprim\u00E9s.
diekategoriewurdeerfolgreichhinzugefugt=La cat\u00E9gorie a \u00E9t\u00E9 ajout\u00E9e avec succ\u00E8s.
diekategorienwurdenerfolgreichentfernt=La cat\u00E9gorie a \u00E9t\u00E9 effac\u00E9e avec succ\u00E8s.
siehabenkeineausreichendeberechtigungmpersonenzuentfernen=Vous n\u2019avez pas les autorisations n\u00E9cessaires pour supprimer des personnes.
wauhlensiebittezunauchsteineodermehrerepersonenaus=S\u2019il vous pla\u00EEt d\u2019abord choisir \u00E0 partir d\u2019une ou plusieurs personnes.
beidenfolgendenpersonenliegtdasgultigkeitsdatuminderzukunft=La date de validit\u00E9 des personnes suivantes est dans le futur
folgendepersonensindmindestenseinerlaufendenoderzukumnftigenveranstaltung=Les personnes suivantes sont associ\u00E9es au moins un \u00E9v\u00E9nement actuel ou futur.
zugeordnetdetailinformationenkoennensieueberdiegaestelistender=Vous pouvez r\u00E9cup\u00E9rer des informations sur les listes d\u2019invit\u00E9s des \u00E9v\u00E9nements respectifs.
jeweiligenveranstaltungenabrufendiepersonenwerdenausallengastelisten=Les invit\u00E9s sont issus de toutes les listes d\u2019invit\u00E9s
folgendepersonensindmindestenseineraufgabeinmindestenseinerlaufendenoder=Les personnes suivantes sont associ\u00E9s au moins une t\u00E2che dans au moins un \u00E9v\u00E9nement actuel ou futur.
zukunftigenveranstaltungzugeordnetdetailinformationenrufensiebitteuberdie=Composez des d\u00E9tails de la liste des t\u00E2ches des \u00E9v\u00E9nements respectifs.
aufgabenlistenderjeweiligenveranstaltungenaufdiepersonenwerdenausallen=Les personnes sont retir\u00E9s de toutes les t\u00E2ches.
aufgabenentfernt=
wennsieihreauswahlanpassenwollenbrechensiebittedasloeschenab=Si vous souhaitez personnaliser votre s\u00E9lection, vous annulez la suppression.
sollenallemarkiertenpersonengeloeschtwerden=Supprimer toutes les personnes s\u00E9lectionn\u00E9es?
dieseaktionkannnichtrueckgaungiggemachtwerden=Cette action ne peut pas \u00EAtre annul\u00E9e.
bittebestaetigensiedasloeschendermarkiertenpersonen=Veuillez confirmer la suppression des personnes s\u00E9lectionn\u00E9es!
loeschenvonpersonenistnichtmoeglich=Suppression des personnes n\u2019est pas possible
markiertepersonenzurveranstaltunghinzufuegen=Ajouter des personnes s\u00E9lectionn\u00E9s \u00E0 l\u2019\u00E9v\u00E9nement
zudieserpersonistkeinehauptpersoneingetragen=Aucune entit\u00E9 n\u2019est inscrite \u00E0 cette personne.
diesepersonkannnichtaufreservegesetztwerdendadienotwendigendaten=Cette personne ne peut pas \u00EAtre sur la r\u00E9serve, que les donn\u00E9es n\u00E9cessaires
nichtvollstaendigerfasstwurden=n\u2019\u00E9taient pas int\u00E9gralement enregistr\u00E9es.
waehlensiebittezunaechsteineodermehrerepersonenaus=S\u00E9lectionner une ou plusieurs personnes au d\u00E9but.
exportieren=Exporter
einladen=inviter
aufreservesetzen=Situ\u00E9 sur la r\u00E9serve
delegationanmelden=Inscrivez d\u00E9l\u00E9gation
alledemarkiereninklpartnerwenneingeladen=Marque de tous (y compris les partenaires, s\u2019ils sont invit\u00E9s)
arbeitsshybereich=Espace de travail
eswurdenkeineeintraegegefunden=Aucune entr\u00E9e trouv\u00E9e
suchenersetzen=Recherche et remplacement
suchenersetzeninpersonendaten=Rechercher et remplacer dans les donn\u00E9es personnelles
vornamederhauptpersonunddespartners=Pr\u00E9nom de la personne et du partenaire
nachnamederhauptpersonunddespartners=Nom de la personne et du partenaire
anredetitel=Formule de politesse / Titre
anredeundtitel=Formule de politesse et titre
straszligeadresszusatzundland=Rue, adresse et pays
plzortundplzpostfach=Code postal / ville et code postal / bo\u00EEte postale
telefontelefaxundmobiltelefon=T\u00E9l\u00E9phone, fax et t\u00E9l\u00E9phone mobile
telefonfax=T\u00E9l\u00E9phone / fax
emailadresse=Adresse \u00E9lectronique
internetadresse=Adresse internet
ihresuchemussausmindestenseinembuchstabenbestehen=Votre recherche doit contenir au moins une lettre.
siemuessenmindestenseinfeldausgewhlthaben=Vous devez s\u00E9lectionner au moins un champ.
eswurdekeinepersonersetzt=Il n\u2019y avait pas personne remplac\u00E9
eswurdeeinepersonersetzt=Il y avait une personne remplac\u00E9
personenersetzt=personne remplac\u00E9
siemuessenmindestenseinfeldausgewaehlthaben=Vous devez s\u00E9lectionner au moins un champ.
eswurdekeinepersongefunden=Il n\u2019a pas \u00E9t\u00E9 trouv\u00E9 toute personne.
eswurdeeinepersongefunden=On a constat\u00E9 une personne.
personengefunden=personnes trouv\u00E9
einzelneeinzraegezumersetzenselektieren=S\u00E9lectionner des entr\u00E9es individuelles pour remplacer
allesofortersetzen=Remplacez imm\u00E9diatement
wennsiedenplatzhalterverwendenwerdenauchteilstueckeersetztsonstnurvollstaendigedatenfelder=Si vous utilisez le caract\u00E8re g\u00E9n\u00E9rique, \u00E9vite \u00E9galement \u00EAtre remplac\u00E9, sinon seuls les champs de donn\u00E9es compl\u00E8tes.
siemuessendasdatumdeszeitrahmensimformatttmmjjjjangeben=Vous aurez besoin de la date de l\u2019\u00E9ch\u00E9ancier au format JJ.MM.AAAA
markierteanredenloschen=Supprimez l\u2019adresse s\u00E9lectionn\u00E9e
markiertendokumenttypenloschen=Supprimer des types de documents s\u00E9lectionn\u00E9s
markierteveranstaltungsorteloschen=Supprimer les lieux s\u00E9lectionn\u00E9s
markiertevorlagenloschen=Supprimer des mod\u00E8les s\u00E9lectionn\u00E9s
keinedateigefunden=Aucun fichier trouv\u00E9.
standardauswahlderselectboxbdquozeichensatzrdquo=Catalogue standard Selectbox \u00ABJeu de caract\u00E8res\u00BB
zusaetzlichefelder=champs suppl\u00E9mentaires
postausgang=Bo\u00EEte d\u2019envoi
beimversendendieseremailisteinfehleraufgetreten=Une erreur s\u2019est produite lors de l\u2019envoi de l\u2019email.
siekonnendiesejetztbearbeitenunderneutsenden=Vous pouvez maintenant modifier et renvoyer.
dieseemailwartetaufihrefertigstellungdurcheinenbenutzer=Cet E-Mail est en attente pour sa r\u00E9alisation par un utilisateur.
dieseemailwartetaufihreversendung=Cet E-Mail est en attente pour leur exp\u00E9dition.
dieseemailwirdgeradeversendetundsollte=Cet e-mail est envoy\u00E9 seulement et ne devrait pas \u00EAtre modifi\u00E9.
nichtbearbeitet=
werden=
dieseemailwurdebereitsversendetundsollte=Cet e-mail a \u00E9t\u00E9 envoy\u00E9 d\u00E9j\u00E0 et devrait ne plus \u00EAtre \u00E9dit\u00E9.
nichtmehrbearbeitet=
technischefehlermeldungausblenden=Erreur technique message cacher
markiertenmandanten=Mandant(s) s\u00E9l\u00E9ctionn\u00E9(s)
markiertenmandantenwirklichloschen=Supprimer les mandant(s) s\u00E9l\u00E9ctionn\u00E9(s)?
alledatensatzewurdenerfolgreichmandantenzugeordnet=Tous les enregistrements ont \u00E9t\u00E9 allou\u00E9s avec succ\u00E8s \u00E0 un mandant.
esexistiertnochkeinmandant=Il n\u2019y a toujours aucun client.
zuordnen=Assigner
zuordnen_klein=assigner
markierteanreden=Titre(s) s\u00E9l\u00E9ctionn\u00E9(s)
markierteanredenloeschen=Supprimer les titre(s) s\u00E9l\u00E9ctionn\u00E9(s)
markiertenarbeitsbereiche=Espace(s) de travail s\u00E9l\u00E9ctionn\u00E9(s)
markierteeintraegeentfernen=Supprimer les entr\u00E9es s\u00E9lectionn\u00E9es
emailpostausgang=Bo\u00EEte d\u2019envoi d\u2019email
markierteemailsloeschen=Supprimer les emails s\u00E9l\u00E9ctionn\u00E9s
markierteemails=Email(s) s\u00E9l\u00E9ctionn\u00E9(s)
wartet=attente
wirdversendet=Sont exp\u00E9di\u00E9s
gesendet=Envoy\u00E9
unbekannt=inconnu
firmainstitutionauswaehlen=S\u00E9lectionner l\u2019entreprise / institution
bittewaehlensieeinefirmainstitutionaus=Veuillez s\u00E9lectionner une entreprise / institution
schliessen=Fermer
verawebuebersicht=VerA.web :: Vue d\u2019ensemble
uebersichtanzeigen=Voir la vue d\u2019ensemble
neuendatensatzanlegen=Cr\u00E9ation d\u2019un nouvel enregistrement de donn\u00E9es
openofficedateiherrunterladen=T\u00E9l\u00E9charger le fichier OpenOffice
keinedatensaetzegefunden=Aucun enregistrement trouv\u00E9
einendatensatzgefunden=Un enregistrement trouv\u00E9
datensaetzegefunden=Enregistrements trouv\u00E9s
anzeigen=afficher
wollensiediesendatensatzunwiderruflichentfernen=Supprimer d\u00E9finitivement cet enregistrement
verawebdetailansicht=VerA.web :: Vue de d\u00E9tail
datensatzbearbeiten=Modifier enregistrement
zuruecksetzen=r\u00E9initialisation
datensatzloeschen=Supprimer l\u2019enregistrement
PERSON_PART_SEARCH_HINT=Les r\u00E9sultats contenant une partie de votre donn\u00E9e sont \u00E9galement affich\u00E9s.
siekoennenbeidersuchesogenannteplatzhalterverwendenderstehtfuermehrereunddasfuereinzelnezeichen=Vous pouvez utiliser soi-disant wildcards dans la recherche, le * repr\u00E9sente un chiffre, et le ? les caract\u00E8res individuels.
undamtsbezeichnungfunktion=et titre/fonction
HINT_SEARCH_WHERE=La recherche s\u2019effectue dans les pr\u00E9nom, nom, ville, code postal, rue, soci\u00E9t\u00E9, t\u00E9l\u00E9phone, fax, e-mail mobile, commentaires, cat\u00E9gories, espaces de travail.
neuenorteingeben=Entrez un nouveau lieu
bittegebensieeinenneuenorteinundklickensieaufhinzufuegen=S\u2019il vous pla\u00EEt entrer un nouvel lieu et cliquez sur \u00ABAjouter\u00BB
neuerveranstaltungsort=Nouveau lieu de l\u2019\u00E9v\u00E9nement
personenetikett=\u00C9tiquette de personnes
zuruckzurubersicht=Vue d\u2019ensemble
gpsdaten=Donn\u00E9es GPS
platzhalterintexteinfuegen=Ins\u00E9rer le texte d\u2019espace r\u00E9serv\u00E9
intexteinfuegen=ins\u00E9rer dans le texte
emailvorlagen=Mod\u00E8les de courrier \u00E9lectronique
pdfvorlagen=Mod\u00E8les de PDF
pdfvorlage=Mod\u00E8le de PDF
vorhandenevorlagen=Mod\u00E8les existants
bitteauswhaelengt=Veuillez s\u00E9lectionner
vorlageladen=T\u00E9l\u00E9charger mod\u00E8les
neuevorlagename=Nouveau mod\u00E8le (nom)
neuevorlagespeichern=Enregistrer nouveau mod\u00E8le
neuevorlagenmuessensowohleinenbetreffalsauchtextenthalten=Nouveaux mod\u00E8les doivent contenir un objet et le texte (ci-joint ne sera pas sauv\u00E9)
zurueckzumverteiler=Retour au distributeur
markiertenveranstaltungsorte=Lieu(x) des \u00E9v\u00E9nements s\u00E9l\u00E9ctionn\u00E9(s)
hinweis=Conseil
aktiv=actif
inaktiv=inactif
net_do=pas install\u00E9
aktionen=Actiones
anschrift=Adresse
anderungenspeichern=Enregistrer les modifications
senden=Envoyer

# GENERIC
GENERIC_UPLOAD_BUTTON=S\u00E9lectionner le fichier
GENERIC_TO=\u00E0
GENERIC_FEDERAL_STATE=\u00C9tat f\u00E9d\u00E9r\u00E9
GENERIC_PERSONAL_DATA=Donn\u00E9es personnelles
GENERIC_NUMBER_OF_GUESTS=Nombre d\u2019invit\u00E9s
GENERIC_TELEFON=T\u00E9l\u00E9phone

# MESSAGES
MESSAGE_INVITATION_WITHOUT_MAIN_PERSON=Ce client a \u00E9t\u00E9 invit\u00E9 sans personne principale.
MESSAGE_INVITATION_WITHOUT_PARTNER=Ce client a \u00E9t\u00E9 invit\u00E9 sans partenaire.
MESSAGE_INVITATION_WITHOUT_PERSON_PART1=Vous ensuite invite maintenant eux?
MESSAGE_INVITATION_WITHOUT_PERSON_PART2_BUTTON=
MESSAGE_END_AND_START_DATE=La fin de l\u2019\u00E9v\u00E9nement doit \u00EAtre temporis\u00E9e jusqu\u2019au d\u00E9but de l\u2019\u00E9v\u00E9nement.
MESSAGE_EVENT_MISSING_SHORT_DESCRIPTION=L\u2019\u00E9v\u00E9nement ne peut pas \u00EAtre enregistr\u00E9. S\u2019il vous pla\u00EEt donner un nom court.
MESSAGE_EVENT_WRING_DATE_FORMAT=Vous avez besoin au d\u00E9but de l\u2019\u00E9v\u00E9nement dans le format jj.mm.aaaa sp\u00E9cifier.
MESSAGE_GENERIC_MISSING_DESCRIPTION=Vous devez entrer un indication.
MESSAGE_EVENTDOCTYPE_ASSIGNMENT_WRONG=L\u2019attribution d\u2019un type de documents \u00E0 un \u00E9v\u00E9nement est d\u00E9fectueux.
MESSAGE_EVENT_LOCATION_TITLE_EMPTY=Le lieu ne peut pas \u00EAtre enregistr\u00E9. D\u00E9cerner un titre s\u2019il vous pla\u00EEt.
MESSAGE_EVENT_LOCATION_MAX_REMARK_REACHED=Le contenu du champ \u00ABRemarque\u00BB ne peut pas d\u00E9passer 1000 caract\u00E8res.
MESSAGE_EMAIL_DRAFT_NAME_MISSING=Vous devez donner un nom de la mod\u00E8le de courrier \u00E9lectronique.
MESSAGE_EMAIL_DRAFT_SUBJECT_MISSING=Ils ont donn\u00E9 le mod\u00E8le e-mail sans sujet.
MESSAGE_EMAIL_DRAFT_TEXT_MISSING=Vous ne saisissez du texte dans le mod\u00E8le e-mail.
MESSAGE_EMAIL_LIST_NAME_EMPTY=euillez entrer un nom de distribution.
MESSAGE_TASK_TIME_WITHOUT_DATE=Entrez un temps sans une date correspondante n\u2019est pas autoris\u00E9e.
MESSAGE_TASK_END_DATE_NOT_FUTURE=La t\u00E2che ne peut pas \u00EAtre enregistr\u00E9e. La date de fin doit \u00EAtre \u00E0 l\u2019avenir.
MESSAGE_TASK_END_DATE_WITHOUT_BEGIN_DATE=La t\u00E2che ne peut pas \u00EAtre enregistr\u00E9e. Veuillez \u00E9galement indiquer une date de d\u00E9but, en plus de la date de fin.
MESSAGE_TASK_BEGIN_DATE_BEFORE_END_DATE=La t\u00E2che ne peut pas \u00EAtre enregistr\u00E9e. La date de d\u00E9but doit \u00EAtre avant la date de fin.
MESSAGE_TASK_NO_SHORTNAME=La t\u00E2che ne peut pas \u00EAtre enregistr\u00E9e. S\u2019il vous pla\u00EEt donner un nom court.
MESSAGE_TASK_MAX_REMARK_REACHED=La t\u00E2che ne peut pas \u00EAtre enregistr\u00E9e. Le champ description est autoris\u00E9 \u00E0 avoir plus de 1000 caract\u00E8res.
MESSAGE_TASK_EMAIL_WITHOUT_SENDER=L\u2019e-mail ne peuvent \u00EAtre transmis sans exp\u00E9diteur.
MESSAGE_TASK_EMAIL_WITHOUT_RECEIVER=L\u2019e-mail ne peuvent \u00EAtre transmis sans r\u00E9cepteur.
MESSAGE_TASK_EMAIL_WITHOUT_SUBJECT=L\u2019e-mail ne peuvent \u00EAtre transmis sans sujet.
MESSAGE_ORG_UNIT_NO_NAME=Vous devez entrer un nom
MESSAGE_PERSON_MAX_COMPANY_REACHED=Vous pouvez sp\u00E9cifier jusqu\u2019\u00E0 100 caract\u00E8res pour la soci\u00E9t\u00E9.
MESSAGE_PERSON_MAX_NAME_REACHED=Vous pouvez sp\u00E9cifier un maximum de 100 caract\u00E8res pour le nom du personnage principal.
MESSAGE_PERSON_MAX_LASTNAME_REACHED=Vous pouvez sp\u00E9cifier un maximum de 100 caract\u00E8res pour le pr\u00E9nom du personnage principal.
MESSAGE_PERSON_NO_MAIL=Vous devez sp\u00E9cifier une adresse e-mail.
MESSAGE_PERSON_NO_COMPANY_NAME=Vous devez sp\u00E9cifier un nom pour l\u2019entreprise / institution.
MESSAGE_PERSON_NO_NAME_LAST_NAME=Vous devez sp\u00E9cifier un pr\u00E9nom et un nom.
MESSAGE_PERSON_NO_NAME=Vous devez sp\u00E9cifier un pr\u00E9nom.
MESSAGE_PERSON_NO_LASTNAME=Vous devez sp\u00E9cifier un nom.
MESSAGE_PERSON_CATEGORY_NO_CONNECTION_PERSON_CATEGORY=Impossible d\u2019enregistrer la connexion entre la personne et la cat\u00E9gorie.
MESSAGE_DOCTYPE_MAX_CONNECTOR_REACHED=Le connecteur peut \u00EAtre jusqu\u2019\u00E0 50 caract\u00E8res de long.
MESSAGE_PROXY_NO_REPRESENTATIVE=Le champ \u00ABrepr\u00E9sentatif\u00BB est obligatoire.
MESSAGE_PROXY_NO_ROLE=Le champ \u00ABr\u00F4le\u00BB est obligatoire.
MESSAGE_PROXY_MISSING_BOTH=Les champs \u00ABr\u00F4le\u00BB et \u00ABrepr\u00E9sentatif\u00BB sont obligatoires.
MESSAGE_PROXY_REPRESENTATIVE_BEGIN_BEFORE_END=Le d\u00E9but de la repr\u00E9sentation doit \u00EAtre avant la fin.
MESSAGE_FUNCTION_MISSING_NAME=Vous devez donner un nom \u00E0 la fonction.
MESSAGE_USER_MISSING_ROLE=Vous devez taper un nom de r\u00F4le d\u2019utilisateur.
MESSAGE_ORGUNIT_BUSY=XXX TODO: While the client is still assigned users it cannot be deleted.

# EVENT LIST TEXTS
EVENT_LIST_WARNING_EVENTS_IN_FUTURE=Au moins un \u00E9v\u00E9nement marqu\u00E9 s\u2019ex\u00E9cute actuellement ou dans l\u2019avenir.
EVENT_LIST_WARNING_SELECTION_CHANGING=Si vous souhaitez personnaliser votre s\u00E9lection, vous annulez la suppression.
EVENT_LIST_DELETE_CONFIRMATION_MESSAGE=Veuillez supprimer tous les \u00E9v\u00E9nements s\u00E9lectionn\u00E9s? Cette action ne peut pas \u00EAtre annul\u00E9e.

# PERSON LIST TEXTS
PERSON_LIST_WARNING_NO_PERMISSION_TO_DELETE=Vous n\u2019\u00EAtes pas autoris\u00E9 \u00E0 supprimer des personnes.
PERSON_LIST_WARNING_ONLY_DELETE_ONE_PERSON=Vous pouvez supprimer qu\u2019une seule personne. S\u2019il vous pla\u00EEt s\u00E9lectionner qu\u2019une seule entr\u00E9e, ou contactez votre administrateur.
PERSON_LIST_QUESTION_DELETE_CONFIRMATION=Supprimer toutes les personnes s\u00E9l\u00E9ctionn\u00E9es?

# EVENT DETAIL SITE TEXTS
EVENT_DETAIL_ALREADY_EXISTS_ONE=Un \u00E9v\u00E9nement avec le nom \u00AB
EVENT_DETAIL_ALREADY_EXISTS_TWO=\u00BB d\u00E9j\u00E0 existe. Le nouvel \u00E9v\u00E9nement sauverait encore?

# CATEGORY TEXTS
CATEGORY_DETAIL_ALREADY_EXISTS=Une entr\u00E9e de donn\u00E9es ma\u00EEtre sous le nom d\u00E9j\u00E0 existe.

# CHANGELOG REPORTS TEXTS
CHANGELOG_NO_PROTOCOL_AVAILABLE=Il y a aucune donn\u00E9e de journaux est disponible.

# BROWSER TITLES
BROWSER_TITLE_REPORTS=Rapports

#NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GUEST_LIST_RESET_ALL_TO_MASTER_DATA=R\u00E9initialiser toutes les valeurs sur les donn\u00E9es de base
GUEST_LIST_EDIT_MASTER_DATA=Modifier les donn\u00E9es de base des personnes
GUEST=Invit\u00E9
GENERIC_OF=de

TOOLTIP_EDIT_HEADLINES=Vous pouvez toujours modifier les rubriques avant de l\u2019imprimer en cliquant sur le lien /u0022modifier/u0022. S\u2019il vous pla\u00EEt enregistrer cette avant l\u2019impression.
GENERIC_APPLY_TO_GUESTLIST=Prendre dans la liste des invit\u00E9s
GENERIC_APPLY_GUEST_TO_GUESTLIST=Prenez invit\u00E9 directement \u00E0 la liste des invit\u00E9s
GENERIC_APPLY=Reprendre
GENERIC_APPLY_PERSON_AS_HOST=Prenez personne directement en tant qu\u2019h\u00F4te
etikettfuraktuellepersonerzeugen=Produire \u00E9tiquette pour personne actuelle

aktuellepersonloschenundzurpersonenlistezuruckkehren=Supprimer la personne en cours et revenir \u00E0 la liste des personnes
freifeldvorschaufur=Champ libre aper\u00E7u
zudieserpersonwurdedasentsprechendevorschaufeldnochncihterzeugt=\u00C0 cette personne la case aper\u00E7u n\u2019a pas encore cr\u00E9\u00E9e.
siemussendierolleangebenunterdersieverawebnutzenmochten=Vous devez sp\u00E9cifier le r\u00F4le, dans lesquelles vous souhaitez utiliser VerA.web.
GENERIC_CHOOSE=Choisir
GENERIC_RESET=R\u00E9initialiser
siehabenkeineausreichendeberechtigungumdiegastelistezuentfernen=Vous n\u2019avez pas les autorisations n\u00E9cessaires pour supprimer les invit\u00E9s
wahlensiebittezunachsteinenodermehreregasteaus=S\u00E9lectionner les premiers h\u00F4tes\u200A\u2014\u200Aun ou plusieurs
bittebestatigensiedasloschendermarkiertengasteliste=Veuillez confirmer la suppression des invit\u00E9s marqu\u00E9!
GENERIC_NO_GUESTLIST_DELETED=Aucun invit\u00E9s ont \u00E9t\u00E9 supprim\u00E9es

EVENT_DOCTYPE_RESET_INFO=V\u00E9rifier si les types de documents sont d\u00E9j\u00E0 attribu\u00E9es \u00E0 cet \u00E9v\u00E9nement. Si tel est le cas, vous devrez recr\u00E9er les types de documents pour ce client. Pour ce faire, cliquez sur \u00ABR\u00E9initialiser les donn\u00E9es de base\u00BB

diesistuberdenmenupunktadministrationprogrammeinstellungenmoglich=Ceci est possible via l\u2019administration d\u2019\u00E9l\u00E9ment de menu \u2192 r\u00E9glages de programme

GENERIC_CHOSEN_GUESTLIST=Invit\u00E9s s\u00E9lectionn\u00E9s
exportierfahigegasteliste=Invit\u00E9s exportables
unvollstandigegasteliste=Invit\u00E9s incompl\u00E8tes

GUESTLIST_FILTER_EXPORT_INFO=Si vous avez frapp\u00E9 un filtrage dans la liste des invit\u00E9s, exporter seulement certaines invit\u00E9s

GUEST_CANNOT_BE_EXPORTED_1=Un invit\u00E9
GUEST_CANNOT_BE_EXPORTED_2=ne peut
GUEST_CANNOT_BE_EXPORTED_3=pas \u00EAtre
GUEST_CANNOT_BE_EXPORTED_4=export\u00E9
PERSON_MISSING_DOCTYPE_SPECIFIC_DATA=car aucun correspondant du document sp\u00E9cifique au type donn\u00E9es ont \u00E9t\u00E9 stock\u00E9es \u00E0 cette personne

GUESTS_CANNOT_BE_EXPORTED_1=Invit\u00E9s ne
GUESTS_CANNOT_BE_EXPORTED_2=peuvent pas
GUESTS_CANNOT_BE_EXPORTED_3=\u00EAtre
GUESTS_CANNOT_BE_EXPORTED_4=export\u00E9es
PERSONS_MISSING_DOCTYPE_SPECIFIC_DATA=car aucun correspondant du document sp\u00E9cifique au type donn\u00E9es ont \u00E9t\u00E9 stock\u00E9es \u00E0 cette personne
GENERIC_TO_EVENTDETAIL=D\u00E9tails administratifs
GENERIC_INSERT_CURRENT_MONTH=Ins\u00E9rer le mois en cours
GENERIC_SELECT_FUNCTION=Choisissez la fonction
diestammdatendiesesgasteswurdengeloschtsiekonnennurdatenimrahmendieserveranstaltungbearbeiten=Les donn\u00E9es de base de cet invit\u00E9 sont effac\u00E9es. Vous ne pouvez modifier les donn\u00E9es dans le cadre de cet \u00E9v\u00E9nement
DELETE_SELECTED_MANDATOR=Supprimer clients s\u00E9lectionn\u00E9s
PROMPT_APPLY_CATEGORY_RANK_FROM_MASTERDATA=Si le rang de la cat\u00E9gorie \u00E0 prendre?

# NEW MESSAGES ( TO BE CONVERTED LATER TO MESSAGE_...)
GENERIC_ASSIGN=Assigner
GENERIC_CANCEL=Annuler
GENERIC_CONNECTOR=Connecteur
GENERIC_VIEW_DOCUMENT_TYPE=Montrer le type du document
GENERIC_GENERATE_DOCUMENT_TYPE=g\u00E9n\u00E9rer un nouveau type de documents

# GUEST DETAIL TEXTS
GUEST_DETAIL_PARTNER=le partenaire
GUEST_DETAIL_PARTNER_GENITIV=les partenaire
GUEST_DETAIL_MAINPERSON=la personne principale

GUEST_DETAIL_DUP_SEAT_ERROR_ONE=Veuillez changer la place
GUEST_DETAIL_DUP_SEAT_ERROR_TWO=de
GUEST_DETAIL_DUP_SEAT_ERROR_THREE=vis \u00E0 vis la liste des invit\u00E9s. Cette personne se trouve actuellement
GUEST_DETAIL_DUP_SEAT_ERROR_FOUR=\u00E0 la place
GUEST_DETAIL_DUP_SEAT_ERROR_FIVE=. Les modifications ne sont pas sauvegard\u00E9es.

# GUEST TEXTS
GUEST_CALC_SERIALNO=Cet \u00E9v\u00E9nement est d\u00E9j\u00E0 fini dans le pass\u00E9. En tout cas, Voulez-vous recalculer le num\u00E9ro de s\u00E9rie?

# MAILING LIST TEXTS
MAILING_LIST_NO_ADDRESSES=D\u00E9signer un nouveau collaborateur n\u2019\u00E9tait pas possible \u00E0 cause de l\u2019absence de l\u2019adresse
MAILING_LIST_SELECTED_FILE=Fichier s\u00E9lectionn\u00E9
MAILING_LIST_ALREADY_SELECTED_FILE=Ce fichier a d\u00E9j\u00E0 \u00E9t\u00E9 s\u00E9lectionn\u00E9
MAILING_LIST_SELECTED_TOO_MANY=Trop de fichiers s\u00E9lectionn\u00E9s
MAILING_LIST_SELECTED_TOO_BIG=Fichier est trop gros
MAILING_LIST_SIZE_NOTICE=Fichier est trop gros; max. 1,6 Mo

# ORG UNIT LIST TEXTS
ORG_UNIT_NO_MANDANT_ID=Le Client \u00E0 ins\u00E9rer ne devrait pas avoir un num\u00E9ro d\u2019identit\u00E9
ORG_UNIT_MANDANT_ALREADY_EXISTS_ONE=Le Client \u00E0 ins\u00E9rer
ORG_UNIT_MANDANT_ALREADY_EXISTS_TWO=d\u00E9j\u00E0 existe.
ORG_UNIT_MANDANT_ID_COMPULSORY_ONE=Le Client \u00E0 modifier
ORG_UNIT_MANDANT_ID_COMPULSORY_TWO=devrait avoir un num\u00E9ro d\u2019identit\u00E9
ORG_UNIT_MANDANT_EXISTS_ONE=Un client dont le nom
ORG_UNIT_MANDANT_EXISTS_TWO=d\u00E9j\u00E0 existe.

# PERSON CATEGORIES TEXTS
PERSON_CATEGORIES_SELECT_WARNING=Pour ajouter une cat\u00E9gorie, veuillez choisir une. (vous n\u2019avez choisie qu\u2019un rang.)

# EXPORT FILE HEADERS
EXPORT_HEADER_DOCUMENT_TYPE=type_de_document
EXPORT_HEADER_FREETEXT_FIELD=champs_de_texte_libre
EXPORT_HEADER_PARTNER_FREETEXT_FIELD=Patenaire_champs_de_texte_libre
EXPORT_HEADER_INTERCONNECTS=Connecteur
EXPORT_HEADER_ADDRESS=Adresse
EXPORT_HEADER_CHARSET=Charset
EXPORT_HEADER_FUNCTION=fonction
EXPORT_HEADER_TITLE=Titre
EXPORT_HEADER_ACADEMIC_TITLE=Titre_acad\u00E9mique
EXPORT_HEADER_FIRSTNAME=Pr\u00E9nom
EXPORT_HEADER_LASTNAME=Nom de famille
EXPORT_HEADER_PARTNER_TITLE=Partenaire_titre
EXPORT_HEADER_PARTNER_ACADEMIC_TITLE=Partnaire_Titre_acad\u00E9mique
EXPORT_HEADER_PARTNER_FIRSTNAME=Partenaire_pr\u00E9nom
EXPORT_HEADER_PARTNER_LASTNAME=Partenaire_surnom
EXPORT_HEADER_POSTALCODE=Code_postal
EXPORT_HEADER_CITY=Ville
EXPORT_HEADER_STREET=Rue
EXPORT_HEADER_COUNTRY=Pays
EXPORT_HEADER_ADDITIONAL_ADDRESS_ONE=Adresse_extension_1
EXPORT_HEADER_ADDITIONAL_ADDRESS_TWO=Adresse_extension_2
EXPORT_HEADER_CITY_OF_BORN=Lieu_de_naissance
EXPORT_HEADER_TELEPHONE=T\u00E9l\u00E9phone
EXPORT_HEADER_FAX=Fax
EXPORT_HEADER_EMAIL=E-mail
EXPORT_HEADER_WWW=WWW
EXPORT_HEADER_MOBILE=Portable
EXPORT_HEADER_COMPANY=Entreprise
EXPORT_HEADER_POST_OFFICE_BOX_NUMBER=Num\u00E9ro_de_la_bo\u00EEte_\u00E0_lettre
EXPORT_HEADER_POST_OFFICE_BOX_PLZ=Code_postal
EXPORT_HEADER_WORK_AREA=Secteur_de_travail
EXPORT_HEADER_CATEGORY=Categorie
EXPORT_HEADER_CATEGORY_RANG=Categorie_rang
EXPORT_HEADER_RANG=Rang
EXPORT_HEADER_RESERVE=Reserve
EXPORT_HEADER_STATUS=Statut
EXPORT_HEADER_TABLE=Table
EXPORT_HEADER_SEAT=Place
EXPORT_HEADER_CURRENT_NUMBER=Num\u00E9ro_de_s\u00E9rie
EXPORT_HEADER_COLOUR=Couleur
EXPORT_HEADER_IN_COUNTRY=domestique
EXPORT_HEADER_LANGUAGES=Langues
EXPORT_HEADER_SEX=Sexe
EXPORT_HEADER_NATIONALITY=Nationalit\u00E9
EXPORT_HEADER_HINT_RESPONSIBLE=Conseil_h\u00F4te
EXPORT_HEADER_HINT_ORG_TEAM=Conseil_\u00E9quipe_org
EXPORT_HEADER_PARTNER_STATUS=Partenaire_statut
EXPORT_HEADER_PARTNER_TABLE=Partenaire_table
EXPORT_HEADER_PARTNER_SEAT=Partenaire_place
EXPORT_HEADER_PARTNER_CURRENT_NUMBER=Partenaire_num\u00E9ro_de_s\u00E9rie
EXPORT_HEADER_PARTNER_COLOUR=Partenaire_couleur
EXPORT_HEADER_PARTNER_IN_COUNTRY=domestique
EXPORT_HEADER_PARTNER_LANGUAGES=Partenaire_langues
EXPORT_HEADER_PARTNER_SEX=Partenaire_sexe
EXPORT_HEADER_PARTNER_NATIONALITY=Partenaire_nationalit\u00E9
EXPORT_HEADER_PARTNER_HINT_RESPONSIBLE=Partenaire_conseil_h\u00F4te
EXPORT_HEADER_PARTNER_HINT_ORG_TEAM=Partenaire_conseil_\u00E9quipe_org
EXPORT_HEADER_ACCEPT=Num\u00E9ro_acceptations
EXPORT_HEADER_DECLINE=Num\u00E9ro_declinaison
EXPORT_HEADER_OPEN=Num\u00E9ro_ouvert
EXPORT_HEADER_GUEST_IN_PLACE=Num\u00E9ro_d\u2019invit\u00E9s_sur_place
EXPORT_HEADER_GUEST_IN_RESERVE=Num\u00E9ro_d\u2019invit\u00E9s_en_reserve
EXPORT_HEADER_EVENT_NAME=Nom_de_l\u2019\u00E9v\u00E9nement
EXPORT_HEADER_EVENT_BEGIN=D\u00E9but_de_l\u2019\u00E9v\u00E9nements
EXPORT_HEADER_EVENT_END=Fin_de_l\u2019\u00E9v\u00E9nement
EXPORT_HEADER_EVENT_LOCATION=Lieu_de_l\u2019\u00E9v\u00E9nement
EXPORT_HEADER_OBSERVATION=Observation

# MAIN DATA (STAMMDATEN-WORKER) TEXTS
MAIN_DATA_WARN_ALREADY_EXISTS=Une donn\u00E9e de base avec ce nom existe d\u00E9j\u00E0.

# STATS (Statistik Worker)
STATS_COLUMN_EVENT_NAME=Nom de l\u2019\u00E9v\u00E9nement
STATS_COLUMN_DATE_BEGIN=D\u00E9but
STATS_COLUMN_INVITATION_TYPE=Type d\u2019invitation
STATS_COLUMN_INVITATION_STATUS=Statut
STATS_COLUMN_INVITATION_STATUS_PARTNER=Statut du partnenaire
STATS_COLUMN_YEAR=Ann\u00E9e
STATS_COLUMN_MONTH=Mois
STATS_COLUMN_EVENTS=\u00C9v\u00E9nement
STATS_NOT_INVITED=Pas invit\u00E9

# USER LIST TEXTS
USER_LIST_WARN_MANDANT=L\u2019utilisateur \u00E0 ins\u00E9rer est d\u00E9j\u00E0 associer au client %s.
USER_LIST_WARN_ALREADY_USER=L\u2019utilisateur \u00E0 ins\u00E9rer est d\u00E9j\u00E0 associer VerA.web.
USER_LIST_WARN_NO_ID=L\u2019utilisateur \u00E0 ins\u00E9rer ne devrait pas avoir un num\u00E9ro d\u2019identit\u00E9

# WORKAREA TEXTS
WORKAREA_NEED_MANDANT=Vous ne pouvez pas cr\u00E9er des espaces de travail, parce que vous n\u2019\u00EAtes pas assign\u00E9 \u00E0 des clients.
WORKAREA_ERROR_INCORRECT_NAME_ONE=La cr\u00E9ation du secteur du travail \u00AB
WORKAREA_ERROR_INCORRECT_NAME_TWO=\u00BB n\u2019est pas possible. Veuillez associer un client \u00E0 priori.

# VERIFY TEXTS
VERIFY_ERROR_ACCESS_TO_DB_UNABLE=L\u2019\u00E9tablissement de la connexion \u00E0 la base de donn\u00E9e n\u2019a pas \u00E9t\u00E9 possible.
VERIFY_ERROR_ACCESS_TO_DB_INTERRUPTED=La connexion \u00E0 la base de donn\u00E9e a \u00E9t\u00E9 interrompu.
VERIFY_ERROR_ACCESS_TO_DB_NOT_INTERRUPTED=\u00C9chec de l\u2019interruption de la connexion \u00E0 la base de donn\u00E9e.
VERIFY_ERROR_DB_NOT_ACCESSIBLE=\u00C9chec de la connexion \u00E0 la base de donn\u00E9e.
VERIFY_ERROR_DB_VERSION_NOT_DETERMINED=La d\u00E9termination de la version du sch\u00E9ma de la base de donn\u00E9e n\u2019\u00E9tait pas possible.
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_ONE=La version du sch\u00E9ma de la base de donn\u00E9e (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_TWO=) est diff\u00E9rente de la version de VerA.web (
VERIFY_ERROR_DB_VERSION_INCONSISTENCE_THREE=).
VERIFY_ERROR_DB_LC_CTYPE_NOT_WANTED=Votre configuration de la base de donn\u00E9e ne supporte pas let charset (LC_CTYPE=
VERIFY_ERROR_DB_LC_COLLATE_NOT_WANTED=La configuration de votre base de donn\u00E9e ne supporte pas les r\u00E8gles attendu pour la comparaison du texte (LC_COLLATE=
VERIFY_ERROR_XML=Une erreur est survenue, pendant la creation du document test-XML.(

#TO BE DELETED
inlandjageschlechtweiblich=In Country: Yes\u200A\u2014\u200ASex:Female
inlandjageschlechtmannlich=In Country: Yes\u200A\u2014\u200ASex:Male
inlandneingeschlechtweiblich=In Country: No\u200A\u2014\u200ASex:Female
inlandneingeschlechtmannlich=In Country: No\u200A\u2014\u200ASex:Male

# GENERIC DIALOG MESSAGES
GENERIC_PLEASE_WAIT_HEADER=Veuillez patienter...
GENERIC_PLEASE_WAIT_MESSAGE=Le processus pourrait prendre un peu de temps.

# WORK AREA (Bean) TEXTS
WORKAREA_ERROR_MISSING_NAME=L\u2019\u00E9space de travail ne doit pas \u00EAtre vide.

zurpersonensuche=Recherche des personnes
steuerdatei=le fichier de contr\u00F4le
dokumenttypauswahlen=Choisir le type du documents
EVENT_NO_DOCTYPES_ASSIGNED=Aucun type de documents a \u00E9t\u00E9 associ\u00E9 \u00E0 cet \u00E9v\u00E9nement

# DATE HELPER TEXTS
DATE_HELPER_INCORRECT_DATE= n\u2019est pas une date valide. Veuillez ins\u00E9rer und date du format JJ.MM.AAAA!

#WIP
GENERIC_SHOW_CURRENT_EVENTS=Montrer l\u2019\u00E9v\u00E9nement actuel
GENERIC_FURTHER_PROCEEDING=\u00C9tapes prochaines

LETTER_MAIN_PERSON=PP
LETTER_PARTNER=P
LETTER_RESERVE=R
LETTER_DELEGATION=D
LETTER_HOST=H

GENERIC_LASTNAME_WITH_SOFT_HYPHEN=Nom de famille
GENERIC_FIRSTNAME_WITH_SOFT_HYPHEN=Pr\u00E9nom
GENERIC_RELOAD=Recharger
GENERIC_LOAD_EXISTING_IMPORTPROCESS=Charger un proc\u00E9ssus d\u2019importation disponible
GENERIC_IMPORTID=Importation-id
GENERIC_YEAR=Ann\u00E9e
GENERIC_COUNT=Nombre
GENERIC_PARTICIPATION=Participation
GENERIC_NOT_ASSIGNED_TO_CATEGORY=Aucune cat\u00E9gorie attribu\u00E9
GENERIC_NOT_ASSIGNED_TO_WORKAREA=Aucun secteur de travail attribu\u00E9
GENERIC_NO_HOST_ASSIGNED=Aucun h\u00F4te attribu\u00E9
GENERIC_NO_GUEST_FOUND=Aucun invit\u00E9 trouv\u00E9

GENERIC_PHONE_NUMBER_SHORT=Num\u00E9ro de t\u00E9l\u00E9phone
GENERIC_FAX_NUMBER_SHORT=Num\u00E9ro du Fax

GENERIC_MONTH_YEAR=Mois/Ann\u00E9e
GENERIC_LOOK_AT=regarder
GENERIC_MOBILE_PHONE=Portable

PHONE_OFFICIAL=T\u00E9l\u00E9phone officiel
PHONE_PRIVATE=T\u00E9l\u00E9phone priv\u00E9
PHONE_MOBILE=T\u00E9l\u00E9phone portable

GENERIC_PARTNER_FREETEXTFIELD=Champs de texte libre du partenaire
GENERIC_VENUE=Lieu de l\u2019\u00E9v\u00E9nement

GENERIC_TOTAL=Total
OPTION_MARK_ADMINISTRATION_CATEGORY_1=Cat\u00E9gorie
OPTION_MARK_ADMINISTRATION_CATEGORY_2=Occasion
OPTION_MARK_ADMINISTRATION_CATEGORY_3=Corps diplomatique

GENERIC_IMPORTID_HYPHEN=Importation-id

GENERIC_SUBSTITUTED_BY=substitut\u00E9 par
GENERIC_NONE=Aucun
GENERIC_ADDRESS_BLOCK=Le block d\u2019adresse

GENERIC_CONTEXT_PLURAL=Le contexte

PERSON_DETAIL_DELETE_PERSON_HEADER=Veuillez confirmer l\u2019\u00E9limination de cette person!
PERSON_DETAIL_DELETE_PERSON_CANCEL_DELETION=Si vous voulez garder cetter personne, veuillez annuler l\u2019\u00E9limination.
PERSON_DETAIL_DELETE_PERSON_CONFIRM_DELETION_WARNING=Voulez vous \u00E9liminer cetter personne?

# PERSON HEADER TEXTS
PERSON_HEADER_NO_DOCTYPE_CONFIG=Aucun type de documents est configur\u00E9 pour \u00EAtre afficher.

#LAST ADDED
GENERIC_GENERATE_LOGIN_CREDENTIALS_FOR_ONLINE_REGISTRATION=G\u00E9nerer des donn\u00E9es de connexion pour l\u2019Enregistrement en Ligne
GENERIC_COPY_CURRENT_PERSON=Copier la personne actuelle
GENERIC_ASSIGN_CURRENT_PERSON_TO_EVENT=Associer la personne actuelle \u00E0 un \u00E9v\u00E9nement
GENERIC_PREVIOUS_PAGE=Page pr\u00E9c\u00E9dente
GENERIC_PREVIOUS_PERSON=Personne pr\u00E9c\u00E9dente
GENERIC_FIRST_PAGE=Premi\u00E8re page
GENERIC_FIRST_PERSON=Permi\u00E8re personne
GENERIC_LAST_PAGE=Derni\u00E8re page
GENERIC_LAST_PERSON=Derni\u00E8re personne
GENERIC_NEXT_PAGE=Page suivante
GENERIC_NEXT_PERSON=Personne suivante
GENERIC_INPUT_FIELD=Champs de saisie
GENERIC_SIMPLE_COMBOBOX=Zone de liste d\u00E9roulante simple
GENERIC_MULTIPLE_COMBOBOX=Zone de liste d\u00E9roulante multiple

# EVENT LOCATIONS (Veranstaltungsort)
HINT_DELETE_NOT_POSSIBLE_ONE=L\u2019\u00E9limination du lieu de l\u2019\u00E9v\u00E9nement \u00AB
HINT_DELETE_NOT_POSSIBLE_TWO=\u00BB n\u2019est pas possible, puisque ce dernier est en rapport avec, au moins, un autre \u00E9v\u00E9nement.
CONFIRMATION_CREATE_LOCATION_ONE=Voulez-vous supprimer le lieu de l\u2019\u00E9v\u00E9nement \u00AB
CONFIRMATION_CREATE_LOCATION_TWO=\u00BB?

INSERT_FUNCTION_FROM_MAIN_DATA=Ajouter une fonction des donn\u00E9es principales
INSERT_COMPANY_FROM_MAIN_DATA=Ajouter une entreprise des donn\u00E9es principales

HINT_GUEST_ALREADY_INVITED_SINGULAR=Une personne est d\u00E9j\u00E0 invit\u00E9 \u00E0 l\u2019\u00E9v\u00E9nement.
HINT_GUEST_ALREADY_INVITED_PLURAL=Des pesonnes sont d\u00E9j\u00E0 invit\u00E9 \u00E0 l\u2019\u00E9v\u00E9nement.

MESSAGE_REPLACED_PERSON_ONE=
MESSAGE_REPLACED_PERSON_TWO=personnes remplac\u00E9es.
MESSAGE_FOUND_PERSON_ONE=
MESSAGE_FOUND_PERSON_TWO=personnes trouv\u00E9es.

HINT_POPUP_CATEGORY_SELECTION_ONE=Vous avez choisi
HINT_POPUP_CATEGORY_SELECTION_TWO=personne(s). Le processus pourrait durer, selon le nombre des personnes choisis.

DELETE_DISTRIBUTOR=Voulez-vous supprimer le distributeur sel\u00E9ctionn\u00E9?
DELETE_DISTRIBUTORS=Voulez-vous supprimer les distributeurs sel\u00E9ctionn\u00E9s?
PLACEHOLDER_DATE_FORMAT=jj.mm.aaaa

DELETE_EVENT_TASKS_FIRST_LINE=Veuillez confirmer la suppression des t\u00E2ches s\u00E9lectionn\u00E9es!
DELETE_EVENT_TASKS_SECOND_LINE=Supprimer toutes les t\u00E2ches s\u00E9lectionn\u00E9es? Cette action ne peut pas \u00EAtre annul\u00E9e.

GM_NO_CHANGES=Vous avez apport\u00E9 aucune modification.
GM_CONFIRMATION_EMAIL_DISTRIBUTOR=Voulez-vous importer les addresses \u00E9l\u00E9ctroniques du distributeur?

CONTACT_PICTURE_UPLOAD=T\u00E9l\u00E9charger une photo
CONTACT_PICTURE_CHANGE=Changer la photo
CONTACT_PICTURE_WRONG_SIZE=Les dimensions de l\u2019image doivent \u00EAtre exactement 186x245 pixels.
PICTURE_SIZE=taille de l\u2019image
PIXELS=pixels

NO_CHANGES_WERE_MADE=Vous avez apport\u00E9 aucune modification.

NO_PARTNER_IN_MASTERDATA=Il n\u2019y a pas de partenaire dans le donn\u00E9e de base.

#GENERAL MESSAGE
GM_CATEGORY_MODIFY_S=Une cat\u00E9gorie a \u00E9t\u00E9 modifi\u00E9.
GM_CATEGORY_MODIFY_P=%s cat\u00E9gories ont \u00E9t\u00E9 modifi\u00E9.
GM_CATEGORY_MODIFY_N=Aucune cat\u00E9gorie a \u00E9t\u00E9 modifi\u00E9.
GM_CATEGORY_DELETE_S=Une cat\u00E9gorie a \u00E9t\u00E9 supprim\u00E9.
GM_CATEGORY_DELETE_P=%s cat\u00E9gories ont \u00E9t\u00E9 supprim\u00E9.
GM_CATEGORY_DELETE_N=Veuillez s\u00E9l\u00E9ctionner une ou plusieurs cat\u00E9gories.
GM_CATEGORY_INSERT_S=Une cat\u00E9gorie a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_CATEGORY_INSERT_P=%s cat\u00E9gories ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_CATEGORY_INSERT_N=Aucune cat\u00E9gorie a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_CLIENT_MODIFY_S=Un client a \u00E9t\u00E9 modifi\u00E9.
GM_CLIENT_MODIFY_P=%s clients ont \u00E9t\u00E9 modifi\u00E9.
GM_CLIENT_MODIFY_N=Aucun client a \u00E9t\u00E9 modifi\u00E9.
GM_CLIENT_DELETE_S=Un client a \u00E9t\u00E9 supprim\u00E9.
GM_CLIENT_DELETE_P=%s clients ont \u00E9t\u00E9 supprim\u00E9.
GM_CLIENT_DELETE_N=Aucun client a \u00E9t\u00E9 supprim\u00E9.
GM_CLIENT_INSERT_S=Un client a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_CLIENT_INSERT_P=%s clients ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_CLIENT_INSERT_N=Aucun client a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_COLOR_MODIFY_S=Une couleur a \u00E9t\u00E9 modifi\u00E9.
GM_COLOR_MODIFY_P=%s couleurs ont \u00E9t\u00E9 modifi\u00E9.
GM_COLOR_MODIFY_N=Aucune couleur a \u00E9t\u00E9 modifi\u00E9.
GM_COLOR_DELETE_S=Une couleur a \u00E9t\u00E9 supprim\u00E9.
GM_COLOR_DELETE_P=%s couleurs ont \u00E9t\u00E9 supprim\u00E9.
GM_COLOR_DELETE_N=Aucune couleur a \u00E9t\u00E9 supprim\u00E9.
GM_COLOR_INSERT_S=Une couleur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_COLOR_INSERT_P=%s couleurs ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_COLOR_INSERT_N=Aucune couleur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DELEGATION_FIELD_MODIFY_S=Un champ suppl\u00E9mentaire a \u00E9t\u00E9 modifi\u00E9.
GM_DELEGATION_FIELD_MODIFY_P=%s champs suppl\u00E9mentaires ont \u00E9t\u00E9 modifi\u00E9.
GM_DELEGATION_FIELD_MODIFY_N=Aucun champ suppl\u00E9mentaire a \u00E9t\u00E9 modifi\u00E9.
GM_DELEGATION_FIELD_DELETE_S=Un champ suppl\u00E9mentaire a \u00E9t\u00E9 supprim\u00E9.
GM_DELEGATION_FIELD_DELETE_P=%s champs suppl\u00E9mentaires ont \u00E9t\u00E9 supprim\u00E9.
GM_DELEGATION_FIELD_DELETE_N=Aucun champ suppl\u00E9mentaire a \u00E9t\u00E9 supprim\u00E9.
GM_DELEGATION_FIELD_INSERT_S=Un champ suppl\u00E9mentaire a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DELEGATION_FIELD_INSERT_P=%s champs suppl\u00E9mentaires ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DELEGATION_FIELD_INSERT_N=Aucun champ suppl\u00E9mentaire a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DISTRIBUTOR_MODIFY_S=Un distributeur a \u00E9t\u00E9 modifi\u00E9.
GM_DISTRIBUTOR_MODIFY_P=%s distributeurs ont \u00E9t\u00E9 modifi\u00E9.
GM_DISTRIBUTOR_MODIFY_N=Aucun distributeur a \u00E9t\u00E9 modifi\u00E9.
GM_DISTRIBUTOR_DELETE_S=Un distributeur a \u00E9t\u00E9 supprim\u00E9.
GM_DISTRIBUTOR_DELETE_P=%s distributeurs ont \u00E9t\u00E9 supprim\u00E9.
GM_DISTRIBUTOR_DELETE_N=Aucun distributeur a \u00E9t\u00E9 supprim\u00E9.
GM_DISTRIBUTOR_INSERT_S=Un distributeur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DISTRIBUTOR_INSERT_P=%s distributeurs ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DISTRIBUTOR_INSERT_N=Aucun distributeur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_DOCUMENT_TYPE_MODIFY_S=Un type de documents a \u00E9t\u00E9 modifi\u00E9.
GM_DOCUMENT_TYPE_MODIFY_P=%s types de documents ont \u00E9t\u00E9 modifi\u00E9.
GM_DOCUMENT_TYPE_MODIFY_N=Aucun type de documents a \u00E9t\u00E9 modifi\u00E9.
GM_DOCUMENT_TYPE_DELETE_S=Un type de documents a \u00E9t\u00E9 supprim\u00E9.
GM_DOCUMENT_TYPE_DELETE_P=%s types de documents ont \u00E9t\u00E9 supprim\u00E9.
GM_DOCUMENT_TYPE_DELETE_N=Veuillez s\u00E9l\u00E9ctionnez un ou plusieurs types de documents.
GM_DOCUMENT_TYPE_INSERT_S=Un type de documents a \u00E9t\u00E9 ajout\u00E9.
GM_DOCUMENT_TYPE_INSERT_P=%s types de documents ont \u00E9t\u00E9 ajout\u00E9.
GM_DOCUMENT_TYPE_INSERT_N=Aucun type de documents a \u00E9t\u00E9 ajout\u00E9.
GM_EMAIL_MODIFY_S=Un e-mail a \u00E9t\u00E9 modifi\u00E9.
GM_EMAIL_MODIFY_P=%s e-mails ont \u00E9t\u00E9 modifi\u00E9.
GM_EMAIL_MODIFY_N=Aucun e-mail a \u00E9t\u00E9 modifi\u00E9.
GM_EMAIL_DELETE_S=Un e-mail a \u00E9t\u00E9 supprim\u00E9.
GM_EMAIL_DELETE_P=%s e-mails ont \u00E9t\u00E9 supprim\u00E9.
GM_EMAIL_DELETE_N=Aucun e-mail a \u00E9t\u00E9 supprim\u00E9.
GM_EMAIL_INSERT_S=Un e-mail a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EMAIL_INSERT_P=%s e-mails ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EMAIL_INSERT_N=Aucun e-mail a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EVENT_MODIFY_S=Un \u00E9v\u00E9nement a \u00E9t\u00E9 modifi\u00E9.
GM_EVENT_MODIFY_P=%s \u00E9v\u00E9nements ont \u00E9t\u00E9 modifi\u00E9.
GM_EVENT_MODIFY_N=Aucun \u00E9v\u00E9nement a \u00E9t\u00E9 modifi\u00E9.
GM_EVENT_DELETE_S=Un \u00E9v\u00E9nement a \u00E9t\u00E9 supprim\u00E9.
GM_EVENT_DELETE_P=%s \u00E9v\u00E9nements ont \u00E9t\u00E9 supprim\u00E9.
GM_EVENT_DELETE_N=Aucun \u00E9v\u00E9nement a \u00E9t\u00E9 supprim\u00E9.
GM_EVENT_INSERT_S=Un \u00E9v\u00E9nement a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EVENT_INSERT_P=%s \u00E9v\u00E9nements ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EVENT_INSERT_N=Aucun \u00E9v\u00E9nement a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EVENT_LOCATION_MODIFY_S=Vous avez modifi\u00E9 un lieu de l\u2019\u00E9v\u00E9nement.
GM_EVENT_LOCATION_MODIFY_P=%s lieux des \u00E9v\u00E9nements ont \u00E9t\u00E9 modifi\u00E9.
GM_EVENT_LOCATION_MODIFY_N=Aucun lieu de l\u2019\u00E9v\u00E9nement a \u00E9t\u00E9 modifi\u00E9.
GM_EVENT_LOCATION_DELETE_S=Vous avez elimin\u00E9 un lieu de l\u2019\u00E9v\u00E9nement.
GM_EVENT_LOCATION_DELETE_P=Vous avez elimin\u00E9 %s lieux d\u2019\u00E9v\u00E9nements
GM_EVENT_LOCATION_DELETE_N=Aucun lieu de l\u2019\u00E9v\u00E9nement a \u00E9t\u00E9 elimin\u00E9.
GM_EVENT_LOCATION_INSERT_S=Vous avez cr\u00E9\u00E9 un lieu de l\u2019\u00E9v\u00E9nement.
GM_EVENT_LOCATION_INSERT_P=%s lieux des \u00E9v\u00E9nements ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_EVENT_LOCATION_INSERT_N=Le lieu ne peut pas \u00EAtre enregistr\u00E9. D\u00E9cerner un titre s\u2019il vous pla\u00EEt.
GM_GUEST_MODIFY_S=Un invit\u00E9 a \u00E9t\u00E9 modifi\u00E9.
GM_GUEST_MODIFY_P=%s invit\u00E9s ont \u00E9t\u00E9 modifi\u00E9.
GM_GUEST_MODIFY_N=Aucun invit\u00E9 a \u00E9t\u00E9 modifi\u00E9.
GM_GUEST_DELETE_S=Un invit\u00E9 a \u00E9t\u00E9 supprim\u00E9.
GM_GUEST_DELETE_P=%s invit\u00E9s ont \u00E9t\u00E9 supprim\u00E9.
GM_GUEST_DELETE_N=Aucun invit\u00E9 a \u00E9t\u00E9 supprim\u00E9.
GM_GUEST_INSERT_S=Un invit\u00E9 a \u00E9t\u00E9 ajout\u00E9.
GM_GUEST_INSERT_P=%s invit\u00E9s ont \u00E9t\u00E9 ajout\u00E9.
GM_GUEST_INSERT_N=Aucun invit\u00E9 a \u00E9t\u00E9 ajout\u00E9.
GM_MAIL_DRAFT_MODIFY_S=Un mod\u00E8le de courrier a \u00E9t\u00E9 modifi\u00E9.
GM_MAIL_DRAFT_MODIFY_P=%s mod\u00E8les de courrier ont \u00E9t\u00E9 modifi\u00E9.
GM_MAIL_DRAFT_MODIFY_N=Aucun mod\u00E8le de courrier a \u00E9t\u00E9 modifi\u00E9.
GM_MAIL_DRAFT_DELETE_S=Un mod\u00E8le de courrier a \u00E9t\u00E9 supprim\u00E9.
GM_MAIL_DRAFT_DELETE_P=%s mod\u00E8les de courrier ont \u00E9t\u00E9 supprim\u00E9.
GM_MAIL_DRAFT_DELETE_N=Aucun mod\u00E8le de courrier a \u00E9t\u00E9 supprim\u00E9.
GM_MAIL_DRAFT_INSERT_S=Un mod\u00E8le de courrier a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_MAIL_DRAFT_INSERT_P=%s mod\u00E8les de courrier ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_MAIL_DRAFT_INSERT_N=Aucun mod\u00E8le de courrier a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_OFFICIAL_TITLE_MODIFY_S=Un titre officiel a \u00E9t\u00E9 modifi\u00E9.
GM_OFFICIAL_TITLE_MODIFY_P=%s titres officiels ont \u00E9t\u00E9 modifi\u00E9.
GM_OFFICIAL_TITLE_MODIFY_N=Aucun titre officiel a \u00E9t\u00E9 modifi\u00E9.
GM_OFFICIAL_TITLE_DELETE_S=Un titre officiel a \u00E9t\u00E9 supprim\u00E9.
GM_OFFICIAL_TITLE_DELETE_P=%s titres officiels ont \u00E9t\u00E9 supprim\u00E9.
GM_OFFICIAL_TITLE_DELETE_N=Aucun titre officiel a \u00E9t\u00E9 supprim\u00E9.
GM_OFFICIAL_TITLE_INSERT_S=Un titre officiel a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_OFFICIAL_TITLE_INSERT_P=%s titres officiels ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_OFFICIAL_TITLE_INSERT_N=Aucun titre officiel a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_PERSON_MODIFY_S=Une personne a \u00E9t\u00E9 modifi\u00E9.
GM_PERSON_MODIFY_P=%s personnes ont \u00E9t\u00E9 modifi\u00E9.
GM_PERSON_MODIFY_N=Aucune personne a \u00E9t\u00E9 modifi\u00E9.
GM_PERSON_DELETE_S=Une personne a \u00E9t\u00E9 supprim\u00E9.
GM_PERSON_DELETE_P=%s personnes ont \u00E9t\u00E9 supprim\u00E9.
GM_PERSON_DELETE_N=Aucune personne a \u00E9t\u00E9 supprim\u00E9.
GM_PERSON_INSERT_S=Une personne a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_PERSON_INSERT_P=%s personnes ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_PERSON_INSERT_N=Aucune personne a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_REPRESENTATIVE_MODIFY_S=Un repr\u00E9sentant a \u00E9t\u00E9 modifi\u00E9.
GM_REPRESENTATIVE_MODIFY_P=%s repr\u00E9sentants ont \u00E9t\u00E9 modifi\u00E9.
GM_REPRESENTATIVE_MODIFY_N=Aucun repr\u00E9sentant a \u00E9t\u00E9 modifi\u00E9.
GM_REPRESENTATIVE_DELETE_S=Un repr\u00E9sentant a \u00E9t\u00E9 supprim\u00E9.
GM_REPRESENTATIVE_DELETE_P=%s repr\u00E9sentants ont \u00E9t\u00E9 supprim\u00E9.
GM_REPRESENTATIVE_DELETE_N=Aucun repr\u00E9sentant a \u00E9t\u00E9 supprim\u00E9.
GM_REPRESENTATIVE_INSERT_S=Un repr\u00E9sentant a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_REPRESENTATIVE_INSERT_P=%s repr\u00E9sentants ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_REPRESENTATIVE_INSERT_N=Aucun repr\u00E9sentant a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_SALUTATION_MODIFY_S=Une formule de politesse a \u00E9t\u00E9 modifi\u00E9.
GM_SALUTATION_MODIFY_P=%s formules de politesse ont \u00E9t\u00E9 modifi\u00E9.
GM_SALUTATION_MODIFY_N=Aucune formule de politesse a \u00E9t\u00E9 modifi\u00E9.
GM_SALUTATION_DELETE_S=Une formule de politesse a \u00E9t\u00E9 supprim\u00E9.
GM_SALUTATION_DELETE_P=%s formules de politesse ont \u00E9t\u00E9 supprim\u00E9.
GM_SALUTATION_DELETE_N=Aucune formule de politesse a \u00E9t\u00E9 supprim\u00E9.
GM_SALUTATION_INSERT_S=Une formule de politesse a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_SALUTATION_INSERT_P=%s formules de politesse ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_SALUTATION_INSERT_N=Aucune formule de politesse a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_TASK_MODIFY_S=Une t\u00E2che a \u00E9t\u00E9 modifi\u00E9.
GM_TASK_MODIFY_P=%s t\u00E2ches ont \u00E9t\u00E9 modifi\u00E9.
GM_TASK_MODIFY_N=Aucune t\u00E2che a \u00E9t\u00E9 modifi\u00E9.
GM_TASK_DELETE_S=Une t\u00E2che a \u00E9t\u00E9 supprim\u00E9.
GM_TASK_DELETE_P=%s t\u00E2ches ont \u00E9t\u00E9 supprim\u00E9.
GM_TASK_DELETE_N=Aucune t\u00E2che a \u00E9t\u00E9 supprim\u00E9.
GM_TASK_INSERT_S=Une t\u00E2che a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_TASK_INSERT_P=%s t\u00E2ches ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_TASK_INSERT_N=Aucune t\u00E2che a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_USER_MODIFY_S=Un utilisateur a \u00E9t\u00E9 modifi\u00E9.
GM_USER_MODIFY_P=%s utilisateurs ont \u00E9t\u00E9 modifi\u00E9.
GM_USER_MODIFY_N=Aucun utilisateur a \u00E9t\u00E9 modifi\u00E9.
GM_USER_DELETE_S=Un utilisateur a \u00E9t\u00E9 supprim\u00E9.
GM_USER_DELETE_P=%s utilisateurs ont \u00E9t\u00E9 supprim\u00E9.
GM_USER_DELETE_N=Aucun utilisateur a \u00E9t\u00E9 supprim\u00E9.
GM_USER_INSERT_S=Un utilisateur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_USER_INSERT_P=%s utilisateurs ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_USER_INSERT_N=Aucun utilisateur a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_WORKAREA_MODIFY_S=Une espace de travail a \u00E9t\u00E9 modifi\u00E9.
GM_WORKAREA_MODIFY_P=%s espaces de travail ont \u00E9t\u00E9 modifi\u00E9.
GM_WORKAREA_MODIFY_N=Aucune espace de travail a \u00E9t\u00E9 modifi\u00E9.
GM_WORKAREA_DELETE_S=Une espace de travail a \u00E9t\u00E9 supprim\u00E9.
GM_WORKAREA_DELETE_P=%s espaces de travail ont \u00E9t\u00E9 supprim\u00E9.
GM_WORKAREA_DELETE_N=Aucune espace de travail a \u00E9t\u00E9 supprim\u00E9.
GM_WORKAREA_INSERT_S=Une espace de travail a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_WORKAREA_INSERT_P=%s espaces de travail ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_WORKAREA_INSERT_N=Aucune espace de travail a \u00E9t\u00E9 cr\u00E9\u00E9.

GM_PDF_TEMPLATE_MODIFY_S=Un mod\u00E8le de PDF a \u00E9t\u00E9 modifi\u00E9.
GM_PDF_TEMPLATE_MODIFY_P=%s mod\u00E8les de PDF ont \u00E9t\u00E9 modifi\u00E9.
GM_PDF_TEMPLATE_MODIFY_N=Aucun mod\u00E8le de PDF a \u00E9t\u00E9 modifi\u00E9.
GM_PDF_TEMPLATE_DELETE_S=Un mod\u00E8le de PDF a \u00E9t\u00E9 supprim\u00E9.
GM_PDF_TEMPLATE_DELETE_P=%s mod\u00E8les de PDF ont \u00E9t\u00E9 supprim\u00E9.
GM_PDF_TEMPLATE_DELETE_N=Aucun mod\u00E8le de PDF a \u00E9t\u00E9 supprim\u00E9.
GM_PDF_TEMPLATE_INSERT_S=Un mod\u00E8le de PDF a \u00E9t\u00E9 cr\u00E9\u00E9.
GM_PDF_TEMPLATE_INSERT_P=%s mod\u00E8les de PDF ont \u00E9t\u00E9 cr\u00E9\u00E9.
GM_PDF_TEMPLATE_INSERT_N=Aucun mod\u00E8le de PDF a \u00E9t\u00E9 cr\u00E9\u00E9.

PDF_TEMPLATE_NOT_EMPTY_ERROR_MESSAGE=Vous devez donner un nom de mod\u00E8le
PDF_TEMPLATE_NO_FILE_ERROR_MESSAGE=Vous devez s\u00E9lectionner un fichier PDF.
PDF_TEMPLATE_LIST_NOT_LOAD=La liste des mod\u00E8les PDF ne pourra \u00EAtre charg\u00E9
PDF_GENERATE_BUTTON=G\u00E9n\u00E9rer des PDF
PDF_GENERATE_LABEL=Exporter des PDF

LOAD_MAILTEMPLATE_FAILED = Chargement email mod\u00E8le a \u00E9chou\u00E9
SELECT_MAILTEMPLATE = S\u2019il vous pla\u00EEt s\u00E9lectionner email mod\u00E8le

ADDRESS_ERROR = Votre e-mail a \u00E9t\u00E9 envoy\u00E9 au distributeur. Au moins un adresse e-mail de ce distributeur est \u00E9t\u00E9 incorrectement. Le distributeur n\u2019a pas pu \u00EAtre envoy\u00E9 vers ces adresses e-mail suivantes. S\u2019il vous pla\u00EEt v\u00E9rifier et le cas \u00E9ch\u00E9ant corriger les adresses e-mail suivantes:

LABELLING_MUST_NOT_BE_EMPTY:Le titre ne doit pas \u00EAtre vide

birthplace_a_e1=Lieu de naissance doit etre moins de 100 characteres.
birthplace_a_e2=Lieu de naissance doit etre moins de 100 characteres.
birthplace_a_e3=Lieu de naissance doit etre moins de 100 characteres.
city_a_e1=Ville doit etre moins de 300 characteres.
city_a_e2=Ville doit etre moins de 300 characteres.
city_a_e3=Ville doit etre moins de 300 characteres.
city_b_e1=Ville doit etre moins de 300 characteres.
city_b_e2=Ville doit etre moins de 300 characteres.
city_b_e3=Ville doit etre moins de 300 characteres.
city_c_e1=Ville doit etre moins de 300 characteres.
city_c_e2=Ville doit etre moins de 300 characteres.
city_c_e3=Ville doit etre moins de 300 characteres.
company_a_e1=Enterprise/Institution doit etre moins de 250 characteres.
company_a_e2=Enterprise/Institution doit etre moins de 250 characteres.
company_a_e3=Enterprise/Institution doit etre moins de 250 characteres.
company_b_e1=Enterprise/Institution doit etre moins de 250 characteres.
company_b_e2=Enterprise/Institution doit etre moins de 250 characteres.
company_b_e3=Enterprise/Institution doit etre moins de 250 characteres.
company_c_e1=Enterprise/Institution doit etre moins de 250 characteres.
company_c_e2=Enterprise/Institution doit etre moins de 250 characteres.
company_c_e3=Enterprise/Institution doit etre moins de 250 characteres.
country_a_e1=Pays doit etre moins de 100 characteres.
country_a_e2=Pays doit etre moins de 100 characteres.
country_a_e3=Pays doit etre moins de 100 characteres.
country_b_e1=Pays doit etre moins de 100 characteres.
country_b_e2=Pays doit etre moins de 100 characteres.
country_b_e3=Pays doit etre moins de 100 characteres.
country_c_e1=Pays doit etre moins de 100 characteres.
country_c_e2=Pays doit etre moins de 100 characteres.
country_c_e3=Pays doit etre moins de 100 characteres.
fax_a_e1=Fax doit etre moins de 100 characteres.
fax_a_e2=Fax doit etre moins de 100 characteres.
fax_a_e3=Fax doit etre moins de 100 characteres.
fax_b_e1=Fax doit etre moins de 100 characteres.
fax_b_e2=Fax doit etre moins de 100 characteres.
fax_b_e3=Fax doit etre moins de 100 characteres.
fax_c_e1=Fax doit etre moins de 100 characteres.
fax_c_e2=Fax doit etre moins de 100 characteres.
fax_c_e3=Fax doit etre moins de 100 characteres.
firstname_a_e1=Pr\u00E9nom doit etre moins de 100 characteres.
firstname_a_e2=Pr\u00E9nom doit etre moins de 100 characteres.
firstname_a_e3=Pr\u00E9nom doit etre moins de 100 characteres.
firstname_b_e1=Pr\u00E9nom doit etre moins de 100 characteres.
firstname_b_e2=Pr\u00E9nom doit etre moins de 100 characteres.
firstname_b_e3=Pr\u00E9nom doit etre moins de 100 characteres.
fon_a_e1=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_a_e2=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_a_e3=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_b_e1=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_b_e2=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_b_e3=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_c_e1=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_c_e2=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
fon_c_e3=T\u00E9l\u00E9phone doit etre moins de 100 characteres.
function_a_e1=Fonction doit etre moins de 250 characteres.
function_a_e2=Fonction doit etre moins de 250 characteres.
function_a_e3=Fonction doit etre moins de 250 characteres.
function_b_e1=Fonction doit etre moins de 250 characteres.
function_b_e2=Fonction doit etre moins de 250 characteres.
function_b_e3=Fonction doit etre moins de 250 characteres.
function_c_e1=Fonction doit etre moins de 250 characteres.
function_c_e2=Fonction doit etre moins de 250 characteres.
function_c_e3=Fonction doit etre moins de 250 characteres.
languages_a_e1=Langues doit etre moins de 250 characteres.
languages_b_e1=Langues doit etre moins de 250 characteres.
lastname_a_e1=Nom de famille doit etre moins de 100 characteres.
lastname_a_e2=Nom de famille doit etre moins de 100 characteres.
lastname_a_e3=Nom de famille doit etre moins de 100 characteres.
lastname_b_e1=Nom de famille doit etre moins de 100 characteres.
lastname_b_e2=Nom de famille doit etre moins de 100 characteres.
lastname_b_e3=Nom de famille doit etre moins de 100 characteres.
mail_a_e1=E-Mail doit etre moins de 250 characteres.
mail_a_e2=E-Mail doit etre moins de 250 characteres.
mail_a_e3=E-Mail doit etre moins de 250 characteres.
mail_b_e1=E-Mail doit etre moins de 250 characteres.
mail_b_e2=E-Mail doit etre moins de 250 characteres.
mail_b_e3=E-Mail doit etre moins de 250 characteres.
mail_c_e1=E-Mail doit etre moins de 250 characteres.
mail_c_e2=E-Mail doit etre moins de 250 characteres.
mail_c_e3=E-Mail doit etre moins de 250 characteres.
mobil_a_e1=Mobile doit etre moins de 100 characteres.
mobil_a_e2=Mobile doit etre moins de 100 characteres.
mobil_a_e3=Mobile doit etre moins de 100 characteres.
mobil_b_e1=Mobile doit etre moins de 100 characteres.
mobil_b_e2=Mobile doit etre moins de 100 characteres.
mobil_b_e3=Mobile doit etre moins de 100 characteres.
mobil_c_e1=Mobile doit etre moins de 100 characteres.
mobil_c_e2=Mobile doit etre moins de 100 characteres.
mobil_c_e3=Mobile doit etre moins de 100 characteres.
nationality_a_e1=Nationalit\u00E9 doit etre moins de 100 characteres.
nationality_b_e1=Nationalit\u00E9 doit etre moins de 100 characteres.
note_a_e1=Remarque doit etre moins de 2000 characteres.
note_b_e1=Remarque doit etre moins de 2000 characteres.
notehost_a_e1=Remarque \u00E0 l\u2019h\u00F4te doit etre moins de 2000 characteres.
notehost_b_e1=Remarque \u00E0 l\u2019h\u00F4te doit etre moins de 2000 characteres.
noteorga_a_e1=Remarque \u00E0 l\u2019organisation doit etre moins de 2000 characteres.
noteorga_b_e1=Remarque \u00E0 l\u2019organisation doit etre moins de 2000 characteres.
pobox_a_e1=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_a_e2=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_a_e3=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_b_e1=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_b_e2=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_b_e3=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_c_e1=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_c_e2=Bo\u00EEte postale doit etre moins de 50 characteres.
pobox_c_e3=Bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_a_e1=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_a_e2=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_a_e3=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_b_e1=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_b_e2=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_b_e3=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_c_e1=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_c_e2=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
poboxzipcode_c_e3=Code postale du bo\u00EEte postale doit etre moins de 50 characteres.
state_a_e1=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_a_e2=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_a_e3=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_b_e1=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_b_e2=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_b_e3=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_c_e1=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_c_e2=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
state_c_e3=\u00C9tat f\u00E9d\u00E9r\u00E9 doit etre moins de 100 characteres.
street_a_e1=Rue doit etre moins de 100 characteres.
street_a_e2=Rue doit etre moins de 100 characteres.
street_a_e3=Rue doit etre moins de 100 characteres.
street_b_e1=Rue doit etre moins de 100 characteres.
street_b_e2=Rue doit etre moins de 100 characteres.
street_b_e3=Rue doit etre moins de 100 characteres.
street_c_e1=Rue doit etre moins de 100 characteres.
street_c_e2=Rue doit etre moins de 100 characteres.
street_c_e3=Rue doit etre moins de 100 characteres.
suffix1_a_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_a_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_a_e3=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_b_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_b_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_b_e3=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_c_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_c_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix1_c_e3=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_a_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_a_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_a_e3=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_b_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_b_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_b_e3=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_c_e1=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_c_e2=Adresse_extension_1 doit etre moins de 100 characteres.
suffix2_c_e3=Adresse_extension_1 doit etre moins de 100 characteres.
title_a_e1=Niveau acad\u00E9mique doit etre moins de 250 characteres.
title_a_e2=Niveau acad\u00E9mique doit etre moins de 250 characteres.
title_a_e3=Niveau acad\u00E9mique doit etre moins de 250 characteres.
title_b_e1=Niveau acad\u00E9mique doit etre moins de 250 characteres.
title_b_e2=Niveau acad\u00E9mique doit etre moins de 250 characteres.
title_b_e3=Niveau acad\u00E9mique doit etre moins de 250 characteres.
url_a_e1=WWW doit etre moins de 250 characteres.
url_a_e2=WWW doit etre moins de 250 characteres.
url_a_e3=WWW doit etre moins de 250 characteres.
url_b_e1=WWW doit etre moins de 250 characteres.
url_b_e2=WWW doit etre moins de 250 characteres.
url_b_e3=WWW doit etre moins de 250 characteres.
url_c_e1=WWW doit etre moins de 250 characteres.
url_c_e2=WWW doit etre moins de 250 characteres.
url_c_e3=WWW doit etre moins de 250 characteres.
zipcode_a_e1=Code postale doit etre moins de 250 characteres.
zipcode_a_e2=Code postale doit etre moins de 250 characteres.
zipcode_a_e3=Code postale doit etre moins de 250 characteres.
zipcode_b_e1=Code postale doit etre moins de 250 characteres.
zipcode_b_e2=Code postale doit etre moins de 250 characteres.
zipcode_b_e3=Code postale doit etre moins de 250 characteres.
zipcode_c_e1=Code postale doit etre moins de 250 characteres.
zipcode_c_e2=Code postale doit etre moins de 250 characteres.
zipcode_c_e3=Code postale doit etre moins de 250 characteres.
internal_id=L\u2019identit\u00E9 interne doit \u00EAtre moins de 45 caract\u00E8res.
INTERNAL_ID=Identit\u00E9 interne

# ALTERNATIVE SALUTATIONS
SALUTATION_EDITABLE_TEXT=Ici vous pouvez cr\u00E9er un style alternatif pour ce mod\u00E8le de PDF
SALUTATION_TO_SALUTATION=volont\u00E9
SALUTATION_ERROR_LOAD=Erreur lors du chargement
SALUTATION_ERROR_EMPTY=Salutations alternatives ne doivent pas \u00EAtre vide
SALUTATION_ERROR_SAVE=Erreur lors de l\u2019enregistrement
SALUTATION_ERROR_DELETE=Erreur lors de la suppression
SALUTATION_ERROR_LENGTH=Salutations alternatives doit etre moins de 100 characteres
